---
title: "extract_Dem_climate_veg_data_for_map"
author: "Elizabeth Kleynhans"
date: '2022-09-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("R/functions/R_Postgres.R"))
library(data.table)
library(sf)
library(tidyverse)
library(rgeos)
library(mapview)
library(tmap)
library(rpostgis)
library(keyring)


```

#import FRT and change it to a raster for faster extraction

```{r}

createCastorDB <- function(sim) {
  message ('create castordb')
  #build the castordb - a realtional database that tracks the interactions between spatial and temporal objectives
  castordb <- dbConnect(RSQLite::SQLite(), ":memory:") #builds the db in memory; also resets any existing db! Can be set to store on disk
  #dbExecute(sim$castordb, "PRAGMA foreign_keys = ON;") #Turns the foreign key constraints on. 
  #dbExecute(castordb, "CREATE TABLE IF NOT EXISTS yields ( id integer PRIMARY KEY, yieldid integer, age integer, tvol numeric, dec_pcnt numeric, height numeric, qmd numeric default 0.0, basalarea numeric default 0.0, crownclosure numeric default 0.0, eca numeric);")
  #Note Zone table is created as a JOIN with zoneConstraints and zone
  dbExecute(castordb, "CREATE TABLE IF NOT EXISTS raster_info (name text, xmin numeric, xmax numeric, ymin numeric, ymax numeric, ncell integer, nrow integer, crs text);")
  #dbExecute(sim$castordb, "CREATE TABLE IF NOT EXISTS zone (zone_column text, reference_zone text)")
  #dbExecute(sim$castordb, "CREATE TABLE IF NOT EXISTS zoneConstraints ( id integer PRIMARY KEY, zoneid integer, reference_zone text, zone_column text, ndt integer, variable text, threshold numeric, type text, percentage numeric, denom text, multi_condition text, t_area numeric, start integer, stop integer);")
  dbExecute(castordb, "CREATE TABLE IF NOT EXISTS pixels_fire ( pixelid integer PRIMARY KEY,compartid character,frt numeric, dem numeric DEFAULT 0, slope numeric, aspect numeric, distinfrastructure numeric, springwind numeric, summerwind numeric, aspect_cardinal text, logit_P_lightning_coef_const numeric, logit_P_person_coef_const numeric, logit_P_escape_coef_const numeric, logit_P_spread_coef_const numeric);")
  return(invisible(sim))
  
  }

setTablesCastorDB <- function(sim) {
  message('...setting data tables')
  ###------------------------#
  #Set the compartment IDs----
  ###------------------------#
  
  boundaryInfo <- list("public.central_grp_aoi_072022","tsa_name","central_group", "wkb_geometry")
 
    #message(paste0('.....compartment ids: ', P(sim, "nameCompartmentRaster", "dataCastor")))
   ras<-terra::rast(RASTER_CLIP2(tmpRast = paste0('temp_', sample(1:10000, 1)), 
                          srcRaster= "rast.central_grp_aoi", 
                          clipper=boundaryInfo[[1]], 
                          geom= boundaryInfo[[4]], 
                          where_clause =  paste0 (boundaryInfo[[2]], " in (''", paste(boundaryInfo[[3]], sep = "' '", collapse= "'', ''") ,"'')"),
                          conn=NULL))
   
   
    pts <- data.table(terra::xyFromCell(ras,1:ncell(ras))) #Seems to be faster than rasterTopoints
    pts <- pts[, pixelid:= seq_len(.N)] # add in the pixelid which streams data in according to the cell number = pixelid
    
    pixels <- data.table(V1 = as.integer(ras[]))
    pixels[, pixelid := seq_len(.N)]
    
    #Set V1 to merge in the vat table values so that the column is character
    
      compart_vat <- data.table(getTableQuery(glue::glue("SELECT * FROM  vat.central_grp_aoi;")))
      pixels<- merge(pixels, compart_vat, by.x = "V1", by.y = "value", all.x = TRUE )
      pixels[, V1:= NULL]
      col_name<-data.table(colnames(compart_vat))[!V1 == "value"]
      setnames(pixels, col_name$V1 , "compartid")
      setorder(pixels, "pixelid")#sort the pixels table so that pixelid is in order.
  

    ras[]<-pixels$pixelid
    #sim$rasVelo<-velox::velox(sim$ras)
    
    #Add the raster_info
    ras.extent<-terra::ext(ras)
    #TODO: Hard coded for epsg 3005 need to convert to terra?
    dbExecute(castordb, glue::glue("INSERT INTO raster_info (name, xmin, xmax, ymin, ymax, ncell, nrow, crs) values ('ras', {ras.extent[1]}, {ras.extent[2]}, {ras.extent[3]}, {ras.extent[4]}, {ncell(ras)}, {nrow(ras)}, '3005');"))
    
  
  aoi<-terra::ext(ras) #need to check that each of the extents are the same
  
  dbGetQuery(castordb, "Select * from pixels_fire")
  
```

  

```{r}
#---------------------#
  #Get the FRT----
  #---------------------#

# frt<-getSpatialQuery("SELECT * FROM frt_canada")
# 
# #Create a provincial raster
# prov.rast <- raster::raster ( # standardized provincial raster with no data in it
#                               nrows = 15744, ncols = 17216, 
#                               xmn = 159587.5, xmx = 1881187.5, 
#                               ymn = 173787.5, ymx = 1748187.5, 
#                               crs = "+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs", 
#                               resolution = c(100, 100),                               
#                               vals = 0)
# 
# ras.frt <- fasterize::fasterize (frt, prov.rast, field = "Cluster")
# plot(ras.frt)
# 
# writeRaster(ras.frt, file=" C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\rast_frt_bc.tif", format="GTiff", overwrite=TRUE)
# 
# # run this in R:
# paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', 'C:/Work/caribou/castor_data/Fire/Fire_sim_data/data/rast_frt_bc.tif -t 100x100 rast.frt | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/castor')
# then copy the output thats between the " " from the above and paste it into the cmd and run that... should show Insert 0  1 lots of times.



ras.frt<-terra::rast(RASTER_CLIP2(tmpRast = paste0('temp_', sample(1:10000, 1)), 
                         srcRaster="rast.frt", 
                         clipper=boundaryInfo[[1]], 
                         geom= boundaryInfo[[4]], 
                         where_clause =  paste0 (boundaryInfo[[2]], " in (''", paste(boundaryInfo[[3]], sep = "' '", collapse= "'', ''") ,"'')"),
                         conn=NULL))
    if(aoi == terra::ext(ras.frt)){ # need to check that each of the extents are the same
      pixels<-cbind(pixels, data.table(frt= as.numeric(ras.frt[])))
      rm(ras.frt)
      gc()
    }else{
      stop(paste0("ERROR: extents are not the same check -"))
    }

  #---------------------#
  #Get the elevation----
  #---------------------#

ras.dem<-terra::rast(RASTER_CLIP2(tmpRast = paste0('temp_', sample(1:10000, 1)), 
                         srcRaster="rast.dem", 
                         clipper=boundaryInfo[[1]], 
                         geom= boundaryInfo[[4]], 
                         where_clause =  paste0 (boundaryInfo[[2]], " in (''", paste(boundaryInfo[[3]], sep = "' '", collapse= "'', ''") ,"'')"),
                         conn=NULL))

if(aoi == terra::ext(ras.dem)){#need to check that each of the extents are the same
      pixels <- cbind(pixels, data.table(dem = as.integer(ras.dem[]))) # add the ownership to the pixels table
      rm(ras.dem)
      gc()
    }else{
      stop(paste0("ERROR: extents are not the same check -"))
    }

# slope
ras.slope<-terra::rast(RASTER_CLIP2(tmpRast = paste0('temp_', sample(1:10000, 1)), 
                         srcRaster="rast.bc_ha_slope", 
                         clipper=boundaryInfo[[1]], 
                         geom= boundaryInfo[[4]], 
                         where_clause =  paste0 (boundaryInfo[[2]], " in (''", paste(boundaryInfo[[3]], sep = "' '", collapse= "'', ''") ,"'')"),
                         conn=NULL))
if(aoi == terra::ext(ras.slope)){#need to check that each of the extents are the same
      pixels <- cbind(pixels, data.table(slope = as.integer(ras.slope[]))) # add the ownership to the pixels table
      rm(ras.slope)
      gc()
    }else{
      stop(paste0("ERROR: extents are not the same check -"))
    }

#Aspect
# DEM_aspect <- raster("T:\\FOR\\VIC\\HTS\\ANA\\PROJECTS\\CASTOR\\Data\\dem\\all_bc\\aspect_ha_bc_3005.tif")
# # run this in R:
# paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', 'T:/FOR/VIC/HTS/ANA/PROJECTS/CASTOR/Data/dem/all_bc/aspect_ha_bc_3005.tif -t 100x100 rast.bc_ha_aspect | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/castor')
# # then copy the output thats between the " " from the above and paste it into the cmd and run that... should show Insert 0  1 lots of times.

# aspect
ras.aspect<-terra::rast(RASTER_CLIP2(tmpRast = paste0('temp_', sample(1:10000, 1)), 
                         srcRaster="rast.bc_ha_aspect", 
                         clipper=boundaryInfo[[1]], 
                         geom= boundaryInfo[[4]], 
                         where_clause =  paste0 (boundaryInfo[[2]], " in (''", paste(boundaryInfo[[3]], sep = "' '", collapse= "'', ''") ,"'')"),
                         conn=NULL))

if(aoi == terra::ext(ras.aspect)){#need to check that each of the extents are the same
      pixels <- cbind(pixels, data.table(aspect = as.integer(ras.aspect[]))) # add the ownership to the pixels table
      rm(ras.aspect)
      gc()
    }else{
      stop(paste0("ERROR: extents are not the same check -"))
    }


# dist infrastructure

# first calculate the minimum distance to infrastructure. Then save that raster and upload it to the database. Then use that.

# dist_rail<- raster("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\dist_rail.tif")
# dist_power<- raster("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\dist_power.tif")
# dist_oil<- raster("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\dist_oil.tif")
# dist_mines<- raster("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\dist_mines.tif")
# dist_urban<- raster("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\dist_urban.tif")
# 
#  inf.rast<- function(rast1, rast2) {
#   ifelse(rast1 < rast2, rast1, rast2)
#  }
#  
#  dist.inf <- overlay(dist_rail, dist_power, fun=inf.rast)
#  dist.inf <- overlay(dist.inf, dist_oil, fun=inf.rast)
#  dist.inf <- overlay(dist.inf, dist_mines, fun=inf.rast)
#  dist.inf <- overlay(dist.inf, dist_urban, fun=inf.rast)
# 
# plot(dist.inf)
# 
# writeRaster(dist.inf, file=" C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\rast_dist_infra.tif", format="GTiff", overwrite=TRUE)
# 
# # run this in R:
# paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', 'C:/Work/caribou/castor_data/Fire/Fire_sim_data/data/rast_dist_infra.tif -t 100x100 rast.dist_infrastructure | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/castor')
# 


ras.infra<-terra::rast(RASTER_CLIP2(tmpRast = paste0('temp_', sample(1:10000, 1)), 
                         srcRaster="rast.dist_infrastructure", 
                         clipper=boundaryInfo[[1]], 
                         geom= boundaryInfo[[4]], 
                         where_clause =  paste0 (boundaryInfo[[2]], " in (''", paste(boundaryInfo[[3]], sep = "' '", collapse= "'', ''") ,"'')"),
                         conn=NULL))

if(aoi == terra::ext(ras.infra)){#need to check that each of the extents are the same
      pixels <- cbind(pixels, data.table(distinfrastructure = as.integer(ras.infra[]))) # add the ownership to the pixels table
      rm(ras.infra)
      gc()
    }else{
      stop(paste0("ERROR: extents are not the same check -"))
    }

# Note the wind rasters have a different extent
# so I have to try to extract this data a different way
# summer_wind_raster<- raster("D:\\Fire\\fire_data\\raw_data\\GovCanadaWindFiles\\wind_summer_clipped_224.tif")
# summer_wind<-resample(summer_wind_raster, prov.rast, method = "bilinear")
# 
# writeRaster(summer_wind, file=" C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\rast_summer_wind.tif", format="GTiff", overwrite=TRUE)
# 
# # run this in R:
# paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', 'C:/Work/caribou/castor_data/Fire/Fire_sim_data/data/rast_summer_wind.tif -t 100x100 rast.summer_wind | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/castor')


ras.summer_wind<-terra::rast(RASTER_CLIP2(tmpRast = paste0('temp_', sample(1:10000, 1)), 
                         srcRaster="rast.summer_wind", 
                         clipper=boundaryInfo[[1]], 
                         geom= boundaryInfo[[4]], 
                         where_clause =  paste0 (boundaryInfo[[2]], " in (''", paste(boundaryInfo[[3]], sep = "' '", collapse= "'', ''") ,"'')"),
                         conn=NULL))

if(aoi == terra::ext(ras.summer_wind)){#need to check that each of the extents are the same
      pixels <- cbind(pixels, data.table(summerwind = as.integer(ras.summer_wind[]))) # add the ownership to the pixels table
      rm(ras.summer_wind)
      gc()
    }else{
      stop(paste0("ERROR: extents are not the same check -"))
    }

# spring_wind_raster<- raster("D:\\Fire\\fire_data\\raw_data\\GovCanadaWindFiles\\wind_spring_raster_224.tif")
# spring_wind<-resample(spring_wind_raster, prov.rast, method = "bilinear")
# 
# writeRaster(spring_wind, file=" C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\rast_spring_wind.tif", format="GTiff", overwrite=TRUE)
# 
# # run this in R:
# paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', 'C:/Work/caribou/castor_data/Fire/Fire_sim_data/data/rast_spring_wind.tif -t 100x100 rast.spring_wind | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/castor')


ras.spring_wind<-terra::rast(RASTER_CLIP2(tmpRast = paste0('temp_', sample(1:10000, 1)), 
                         srcRaster="rast.spring_wind", 
                         clipper=boundaryInfo[[1]], 
                         geom= boundaryInfo[[4]], 
                         where_clause =  paste0 (boundaryInfo[[2]], " in (''", paste(boundaryInfo[[3]], sep = "' '", collapse= "'', ''") ,"'')"),
                         conn=NULL))

if(aoi == terra::ext(ras.spring_wind)){#need to check that each of the extents are the same
      pixels <- cbind(pixels, data.table(springwind = as.integer(ras.spring_wind[]))) # add the ownership to the pixels table
      rm(ras.spring_wind)
      gc()
    }else{
      stop(paste0("ERROR: extents are not the same check -"))
    }

head(pixels)
```


```{r}
#Change Aspect to N,S,E,W
library(rvest)
library(tidyverse)

url <- 'http://snowfence.umn.edu/Components/winddirectionanddegreeswithouttable3.htm'
page <- read_html(url)
directions_raw <- page %>% html_node('td table') %>% html_table(header = TRUE)

directions <- directions_raw %>% 
    set_names(~tolower(sub(' Direction', '', .x))) %>% 
    slice(-1) %>% 
    separate(degree, c('degree_min', 'degree_max'), sep = '\\s+-\\s+', convert = TRUE)

directions

dat<-pixels

dat <- dat %>% 
    mutate(aspect_cardinal = cut(
        aspect, 
        breaks = c(0, directions$degree_max, 360), 
        labels = c(directions$cardinal, 'N')
    ))

dat$aspect_cardinal2<-0
dat$aspect_cardinal2[dat$aspect_cardinal=="N"]<-"N"
dat$aspect_cardinal2[dat$aspect_cardinal=="E"]<-"E"
dat$aspect_cardinal2[dat$aspect_cardinal=="S"]<-"S"
dat$aspect_cardinal2[dat$aspect_cardinal=="W"]<-"W"

dat$aspect_cardinal2[dat$aspect_cardinal=="NNE"]<-"N"
dat$aspect_cardinal2[dat$aspect_cardinal=="NNW"]<-"N"
dat$aspect_cardinal2[dat$aspect_cardinal=="NE" & dat$aspect<=45]<-"N"

dat$aspect_cardinal2[dat$aspect_cardinal=="NE" & dat$aspect>45]<-"E"
dat$aspect_cardinal2[dat$aspect_cardinal=="ENE"]<-"E"
dat$aspect_cardinal2[dat$aspect_cardinal=="ESE"]<-"E"
dat$aspect_cardinal2[dat$aspect_cardinal=="SE" & dat$aspect<=135]<-"E"

dat$aspect_cardinal2[dat$aspect_cardinal=="SE" & dat$aspect>135]<-"S"
dat$aspect_cardinal2[dat$aspect_cardinal=="SSE"]<-"S"
dat$aspect_cardinal2[dat$aspect_cardinal=="SSW"]<-"S"
dat$aspect_cardinal2[dat$aspect_cardinal=="SW" & dat$aspect<=225]<-"S"

dat$aspect_cardinal2[dat$aspect_cardinal=="SW" & dat$aspect>225]<-"W"
dat$aspect_cardinal2[dat$aspect_cardinal=="WSW"]<-"W"
dat$aspect_cardinal2[dat$aspect_cardinal=="WNW"]<-"W"
dat$aspect_cardinal2[dat$aspect_cardinal=="NW" & dat$aspect<=315]<-"W"
dat$aspect_cardinal2[dat$aspect_cardinal=="NW" & dat$aspect>315]<-"N"

table(dat$aspect_cardinal2)
dat[dat$aspect_cardinal2=="0",]
#dat<-dat %>% drop_na(aspect_cardinal)

names(dat)
# create dummy variables for aspect
dat$aspect_N <- ifelse(dat$aspect_cardinal2 == 'N', 1, 0)
dat$aspect_E <- ifelse(dat$aspect_cardinal2 == 'E', 1, 0)
dat$aspect_S <- ifelse(dat$aspect_cardinal2 == 'S', 1, 0)
dat$aspect_W <- ifelse(dat$aspect_cardinal2 == 'W', 1, 0)
```

### FRT 5
```{r}
frt5<- dat %>% filter(frt==5)

model_coef_table_lightning<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt5_lightning.csv")

model_coef_table_lightning

# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
logit_P_lightning_coef<- model_coef_table_lightning$intercept + 
  model_coef_table_lightning$coef_elevatn * frt5$dem

frt5$logit_P_lightning_coef<-logit_P_lightning_coef

####################################
# PErson ignitions

model_coef_table_person<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_FRT5_person.csv")
model_coef_table_person

logit_P_person_coef<- model_coef_table_person$intercept + 
  model_coef_table_person$coef_log_infr_dist*(log(frt5$distinfrastructure+1))

frt5$logit_P_person_coef<-logit_P_person_coef

##########################
# probability of escape

model_coef_table_escape<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt5_escape.csv")

model_coef_table_escape

logit_P_escape_coef<- model_coef_table_escape$intercept + 
  model_coef_table_escape$coef_elevation*frt5$dem + 
  model_coef_table_escape$coef_dist_infra*frt5$distinfrastructure
  
frt5$logit_P_escape_coef<-logit_P_escape_coef

##################################
# spread probabilities

model_coef_table_spread<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt5_spread.csv")

model_coef_table_spread

# there are some Na values for wind so Ill fill in those values with the average.
table(is.na(frt5$springwind))
frt5$springwind[is.na(frt5$springwind)] <- mean(frt5$springwind, na.rm = TRUE)
# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
logit_P_spread_coef<- model_coef_table_spread$intercept + 
  model_coef_table_spread$coef_elevation*frt5$dem +
  model_coef_table_spread$coef_aspect_N*frt5$aspect_N +
  model_coef_table_spread$coef_aspect_S*frt5$aspect_S +
  model_coef_table_spread$coef_aspect_W*frt5$aspect_W +
  model_coef_table_spread$coef_dist_infr*(log(frt5$distinfrastructure+1)) +
  model_coef_table_spread$coef_win_spg*frt5$springwind
  
frt5$logit_P_spread_coef<-logit_P_spread_coef

rm(model_coef_table, model_coef_table_escape, model_coef_table_lightning, model_coef_table_person, model_coef_table_spread)
gc()

```

## FRT 7
```{r}
frt7<- dat %>% filter(frt==7)

model_coef_table_lightning<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt7_lightning.csv")

model_coef_table_lightning

# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
logit_P_lightning_coef<- model_coef_table_lightning$intercept

frt7$logit_P_lightning_coef<-logit_P_lightning_coef

#####################
# Ignition Person
model_coef_table_person<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_FRT7_person.csv")

model_coef_table_person

logit_P_person_coef<- model_coef_table_person$intercept + 
  model_coef_table_person$coef_infr_dist*frt7$distinfrastructure

frt7$logit_P_person_coef<-logit_P_person_coef

###################
# escape
model_coef_table_escape<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_FRT7_escape.csv")

model_coef_table_escape

# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
logit_P_escape_coef<- model_coef_table_escape$intercept 

frt7$logit_P_escape_coef<-logit_P_escape_coef

######################
## spread
model_coef_table_spread<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt7_spread.csv")

model_coef_table_spread

logit_P_spread_coef<- model_coef_table_spread$intercept + 
  model_coef_table_spread$coef_slope*frt7$slope +
  model_coef_table_spread$coef_aspect_N*frt7$aspect_N +
  model_coef_table_spread$coef_aspect_S*frt7$aspect_S +
  model_coef_table_spread$coef_aspect_W*frt7$aspect_W +
  model_coef_table_spread$coef_dist_infr*frt7$distinfrastructure

frt7$logit_P_spread_coef<-logit_P_spread_coef

rm(model_coef_table, model_coef_table_escape, model_coef_table_lightning, model_coef_table_person, model_coef_table_spread)
gc()


```

## FRT9

```{r}
frt9<- dat %>% filter(frt==9)

model_coef_table_lightning<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt9_lightning.csv")
model_coef_table_lightning
# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
logit_P_lightning_coef<- model_coef_table_lightning$intercept + 
  model_coef_table_lightning$coef_elevatn*frt9$dem

frt9$logit_P_lightning_coef<-logit_P_lightning_coef
######################################3
# person caused ignitions

model_coef_table_person<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt9_person.csv")
model_coef_table_person

# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
logit_P_person_coef<- model_coef_table_person$intercept + 
  model_coef_table_person$coef_elevatn*frt9$dem  +
  model_coef_table_person$coef_infr_dist*frt9$distinfrastructure


frt9$logit_P_person_coef<-logit_P_person_coef

##################################
# escape
model_coef_table_escape<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt11_escape.csv")

model_coef_table_escape

# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
logit_P_escape_coef<- model_coef_table_escape$intercept +
  model_coef_table_escape$coef_dist_infra_m*frt9$distinfrastructure

frt9$logit_P_escape_coef<-logit_P_escape_coef

################################
# spread
model_coef_table_spread<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt9_spread.csv")

model_coef_table_spread

# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
logit_P_spread<- model_coef_table_spread$intercept +
  model_coef_table_spread$coef_elev*frt9$dem +
  model_coef_table_spread$coef_aspect_N*frt9$aspect_N +
  model_coef_table_spread$coef_aspect_S*frt9$aspect_S +
  model_coef_table_spread$coef_aspect_W*frt9$aspect_W +
  model_coef_table_spread$coef_dist_infr_m*frt9$distinfrastructure

logit_P_spread

frt9$logit_P_spread_coef<-logit_P_spread

rm(model_coef_table, model_coef_table_escape, model_coef_table_lightning, model_coef_table_person, model_coef_table_spread)
gc()

```

## FRT10
```{r}
frt10<- dat %>% filter(frt==10)

model_coef_table_lightning<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_FRT10_lightning.csv")

model_coef_table_lightning

logit_P_lightning_coef<- model_coef_table_lightning$intercept + 
  model_coef_table_lightning$coef_elevatn*frt10$dem

frt10$logit_P_lightning_coef<-logit_P_lightning_coef

########################################
# Person

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_FRT10_person.csv")
model_coef_table

logit_P_person_coef<- model_coef_table$intercept
frt10$logit_P_person_coef<-logit_P_person_coef

#################################
# escape
model_coef_table_escape<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt10_escape.csv")

model_coef_table_escape

logit_P_escape<- model_coef_table_escape$intercept + 
  model_coef_table_escape$coef_elevation*frt10$dem +
  model_coef_table_escape$coef_log_infr_dist*log(frt10$distinfrastructure +1)

frt10$logit_P_escape_coef<-logit_P_escape

###########################
# Spread

model_coef_table_spread<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt10_spread.csv")

model_coef_table_spread

# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
logit_P_spread<- model_coef_table_spread$intercept +
  model_coef_table_spread$coef_elevation*frt10$dem +
  model_coef_table_spread$coef_slope*frt10$slope +
  model_coef_table_spread$coef_aspect_N*frt10$aspect_N +
  model_coef_table_spread$coef_aspect_S*frt10$aspect_S +
  model_coef_table_spread$coef_aspect_W*frt10$aspect_W +
  model_coef_table_spread$coef_dist_infr*frt10$distinfrastructure

frt10$logit_P_spread_coef<-logit_P_spread

# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
rm(model_coef_table, model_coef_table_escape, model_coef_table_lightning, model_coef_table_person, model_coef_table_spread, prob_ignition_escape, prob_ignition_lightning, prob_ignition_person, prob_ignition_spread, logit_P_escape, logit_P_lightning, logit_P_person, logit_P_spread)
gc()

```


## FRT 11 

```{r}
frt11<- dat %>% filter(frt==11)

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_FRT11_lightning.csv")
model_coef_table

logit_P_lightning_coef<- model_coef_table$intercept

frt11$logit_P_lightning_coef<-logit_P_lightning_coef

##########################
#Person
model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt11_person.csv")
model_coef_table

logit_P_person_coef<- model_coef_table$intercept +
  model_coef_table$coef_log_infr_dist_m*log(frt11$distinfrastructure+1) 

frt11$logit_P_person_coef<-logit_P_person_coef


################################
# Escape

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt11_escape.csv")

model_coef_table

logit_P_escape_coef<- model_coef_table$intercept + 
  model_coef_table$coef_dist_infra_m*frt11$distinfrastructure

frt11$logit_P_escape_coef<-logit_P_escape_coef

##########################
# Spread

table(is.na(frt11$summerwind))
frt11$summerwind[is.na(frt11$summerwind)] <- mean(frt11$summerwind, na.rm = TRUE)

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt11_spread.csv")

model_coef_table

# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
logit_P_spread<- model_coef_table$intercept + 
  model_coef_table$coef_slope*frt11$slope +
  model_coef_table$coef_aspect_N*frt11$aspect_N +
  model_coef_table$coef_aspect_S*frt11$aspect_S +
  model_coef_table$coef_aspect_W*frt11$aspect_W +
  model_coef_table$coef_dist_infr*frt11$distinfrastructure +
  model_coef_table$coef_wind_summer*frt11$summerwind

frt11$logit_P_spread_coef<-logit_P_spread

```

## FRT 12

```{r}
frt12<- dat %>% filter(frt==12)

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_FRT12_lightning.csv")
model_coef_table

logit_P_lightning_coef<- model_coef_table$intercept + 
  model_coef_table$coef_elevatn*frt12$dem

frt12$logit_P_lightning_coef<-logit_P_lightning_coef

##########################
# Person

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_FRT12_person.csv")
model_coef_table

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

logit_P_person_coef<- model_coef_table$intercept + 
  model_coef_table$coef_elevatn*frt12$dem +
  model_coef_table$coef_log_inf_dist*log(frt12$distinfrastructure+1)
  
frt12$logit_P_person_coef<-logit_P_person_coef

##################################
#escape
model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt12_escape.csv")

model_coef_table

logit_P_escape_coef<- model_coef_table$intercept +
  model_coef_table$coef_win_sum*frt12$summerwind + 
  model_coef_table$coef_dist_infr_m*frt12$distinfrastructure

frt12$logit_P_escape_coef<-logit_P_escape_coef

########################
# Spread

table(is.na(frt12$summerwind))
frt12$summerwind[is.na(frt12$summerwind)] <- mean(frt12$summerwind, na.rm = TRUE)

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt12_spread.csv")

model_coef_table

# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
logit_P_spread<- model_coef_table$intercept +
  model_coef_table$coef_elevation*frt12$dem +
  model_coef_table$coef_slope*frt12$slope +
  model_coef_table$coef_log_dist_infra*log(frt12$distinfrastructure+1) +
  model_coef_table$coef_wind_summer*frt12$summerwind

logit_P_spread
frt12$logit_P_spread_coef<-logit_P_spread


```

## FRT13
```{r}
frt13<- dat %>% filter(frt==13)

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_FRT13_lightning.csv")
model_coef_table

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

logit_P_lightning_coef<- model_coef_table$intercept + 
  model_coef_table$coef_elevatn*frt13$dem

frt13$logit_P_lightning_coef<-logit_P_lightning_coef

#############################
# person

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_FRT13_person.csv")
model_coef_table

logit_P_person_coef<- model_coef_table$intercept + 
  model_coef_table$coef_elevatn*frt13$dem + 
  model_coef_table$coef_log_inf_dist*log(frt13$distinfrastructure+1)

frt13$logit_P_person_coef<-logit_P_person_coef

################################
#escape

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt13_escape.csv")
model_coef_table

logit_P_escape_coef<- model_coef_table$intercept + 
  model_coef_table$coef_slope*frt13$slope +
  model_coef_table$coef_win_sum*frt13$summerwind +
  model_coef_table$coef_infr_m*frt13$distinfrastructure

frt13$logit_P_escape_coef<-logit_P_escape_coef

##########################
#spread

frt13$summerwind[is.na(frt13$summerwind)] <- mean(frt13$summerwind, na.rm = TRUE)

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt13_spread.csv")

model_coef_table

# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
logit_P_spread<- model_coef_table$intercept + 
  model_coef_table$coef_elevation*frt13$dem +
  model_coef_table$coef_aspect_N*frt13$aspect_N +
  model_coef_table$coef_aspect_S*frt13$aspect_S +
  model_coef_table$coef_aspect_W*frt13$aspect_W +
  model_coef_table$coef_log_dist_infra*log(frt13$distinfrastructure+1) +
  model_coef_table$coef_wind_summer*frt13$summerwind

logit_P_spread
frt13$logit_P_spread_coef<-logit_P_spread

```

#FRT 14
```{r}
frt14<- dat %>% filter(frt==14)

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_FRT14_lightning.csv")
model_coef_table

logit_P_lightning_coef<- model_coef_table$intercept
frt14$logit_P_lightning_coef<-logit_P_lightning_coef

############################
# person

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_FRT14_person.csv")
model_coef_table

logit_P_person_coef<- model_coef_table$intercept + 
  model_coef_table$coef_log_inf_dist*log(frt14$distinfrastructure+1)

frt14$logit_P_person_coef<-logit_P_person_coef

##############################
#escape  

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt14_escape.csv")
model_coef_table

logit_P_escape_coef<- model_coef_table$intercept + 
  model_coef_table$coef_elev*frt14$dem +
  model_coef_table$coef_slope*frt14$slope +
  model_coef_table$coef_win_sum*frt14$summerwind +
  model_coef_table$coef_dist_infr_m*frt14$distinfrastructure
  
frt14$logit_P_escape_coef<-logit_P_escape_coef

################################
#spread

frt14$summerwind[is.na(frt14$summerwind)] <- mean(frt14$summerwind, na.rm = TRUE)

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt14_spread.csv")

model_coef_table

# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
logit_P_spread<- model_coef_table$intercept + 
  model_coef_table$coef_elevation*frt14$dem +
  model_coef_table$coef_slope*frt14$slope +
  model_coef_table$coef_aspect_N*frt14$aspect_N +
  model_coef_table$coef_aspect_S*frt14$aspect_S +
  model_coef_table$coef_aspect_W*frt14$aspect_W +
  model_coef_table$coef_log_dist_infra*log(frt14$distinfrastructure+1) +
  model_coef_table$coef_wind_summer*frt14$summerwind

logit_P_spread
frt14$logit_P_spread_coef<-logit_P_spread

```

## FRT15
```{r}
frt15<- dat %>% filter(frt==15)

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_FRT15_lightning.csv")
model_coef_table

logit_P_lightning_coef<- model_coef_table$intercept + 
  model_coef_table$coef_elevatn*frt15$dem

frt15$logit_P_lightning_coef<-logit_P_lightning_coef

################################
# Person

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_FRT15_person.csv")
model_coef_table

logit_P_person_coef<- model_coef_table$intercept + 
  model_coef_table$coef_infr_dist*frt15$distinfrastructure 

frt15$logit_P_person_coef<-logit_P_person_coef

################################
# escape

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt15_escape.csv")
model_coef_table

logit_P_escape_coef<- model_coef_table$intercept + 
  model_coef_table$coef_slope*frt15$slope +
  model_coef_table$coef_log_infr_ds*log(frt15$distinfrastructure+1)

frt15$logit_P_escape_coef<-logit_P_escape_coef

#################################
# spread
frt15$summerwind[is.na(frt15$summerwind)] <- mean(frt15$summerwind, na.rm = TRUE)

model_coef_table<-read.csv("C:\\Work\\caribou\\castor\\R\\fire_sim\\Analysis_results\\BC\\Coefficient_tables\\top_mod_table_frt15_spread.csv")
model_coef_table

# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
logit_P_spread<- model_coef_table$intercept + 
  model_coef_table$coef_slope*frt15$slope +
  model_coef_table$coef_aspect_N*frt15$aspect_N +
  model_coef_table$coef_aspect_S*frt15$aspect_S +
  model_coef_table$coef_aspect_W*frt15$aspect_W +
  model_coef_table$coef_log_dist_infra*log(frt15$distinfrastructure+1) +
  model_coef_table$coef_wind_summer*frt15$summerwind

logit_P_spread
frt15$logit_P_spread_coef<-logit_P_spread


rm(model_coef_table, model_coef_table_escape, model_coef_table_lightning, model_coef_table_person, model_coef_table_spread, prob_ignition_escape, prob_ignition_lightning, prob_ignition_person, prob_ignition_spread, logit_P_escape, logit_P_lightning, logit_P_person, logit_P_spread)
gc()

table(is.na(frt15$prob_ignition_spread))

```

# now join all the frt's back together. 
```{r}
frt_all<-rbind(rbind(rbind(rbind(rbind(rbind(rbind(rbind(frt5, frt7), frt9), frt10), frt11), frt12), frt13), frt14), frt15)

dim(frt_all)
table(frt_all$frt)
table(pixels$frt)

table(is.na(frt_all$logit_P_lightning_coef ))
table(is.na(frt_all$logit_P_person_coef))
table(is.na(frt_all$logit_P_escape_coef ))
table(is.na(frt_all$logit_P_spread_coef))

frt_const<-frt_all %>% dplyr::select(pixelid, frt,
                                     dem:springwind, logit_P_lightning_coef:logit_P_spread_coef) %>%
            rename(logit_P_lightning_coef_const =logit_P_lightning_coef,
                   logit_P_person_coef_const=logit_P_person_coef, 
                   logit_P_escape_coef_const=logit_P_escape_coef,
                   logit_P_spread_coef_const=logit_P_spread_coef)


table(frt_all$frt)

names(frt_const)

const_coef_data<- left_join(pixels, frt_const)
table(const_coef_data$frt)

```

```{r}
 

# save data to postgres 
dbBegin(castordb)
    rs<-dbSendQuery(castordb, "INSERT INTO pixels_fire (pixelid, compartid, frt, dem, slope, aspect, distinfrastructure, springwind, summerwind, logit_P_lightning_coef_const, logit_P_person_coef_const, logit_P_escape_coef_const, logit_P_spread_coef_const) 
                      values (:pixelid, :compartid, :frt, :dem, :slope, :aspect, :distinfrastructure, :springwind, :summerwind, :logit_P_lightning_coef_const, :logit_P_person_coef_const, :logit_P_escape_coef_const, :logit_P_spread_coef_const)", const_coef_data)
    dbClearResult(rs)
    dbCommit(castordb)

```


```{r}
#**************FOREST INVENTORY - VEGETATION VARIABLES*******************#
  #----------------------------#
  #----Set forest attributes----
  #----------------------------#

# nameForestInventoryRaster = "rast.vri2020_id", 
# nameForestInventoryKey = "feature_id", 
# nameForestInventoryTable = "veg_comp_2020_adj",
# nameForestInventoryAge = "proj_age_1",  
# nameForestInventoryHeight = "proj_height_1",
# nameForestInventoryCrownClosure = "crown_closure",                             
# nameForestInventoryTreed = "bclcs_level_2",
# nameForestInventoryBasalArea = "basal_area",
# nameForestInventoryQMD = "quad_diam_125",
# nameForestInventorySiteIndex = "site_index"


#boundaryInfo <- list("public.forest_tenure","objectid","something", "geom") 
# ras.fid<- terra::rast(RASTER_CLIP2(tmpRast = paste0('temp_', sample(1:10000, 1)), 
#                                    srcRaster= "rast.vri2020_id", 
#                                    clipper="public.forest_tenure", 
#                                    geom= "geom",
#                                    where_clause = "objectid > 0",
#                                    conn=NULL))
ras.fid<- raster("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\vri2020_id.tif")

plot(ras.fid)

if(aoi == terra::ext(ras.fid)){ #need to check that each of the extents are the same
      inv_id<-data.table(fid = as.integer(ras.fid[]))
      inv_id[, pixelid:= seq_len(.N)]
      inv_id[, fid:= as.integer(fid)] #make sure the fid is an integer for merging later on
      rm(ras.fid)
      gc()
    }else{
      stop(paste0("ERROR: extents are not the same check -", P(sim, "nameForestInventoryRaster", "dataCastor")))
    }

forest_attributes<-c("bclcs_level_2","proj_age_1","proj_height_1", "crown_closure", "pct_dead")
                                   
fids<-unique(inv_id[!(is.na(fid)), fid])

for (i in 1:length(forest_attributes)) { 
  
print(forest_attributes[i])
  
attrib_inv<-data.table(getTableQuery(paste0("SELECT feature_id as fid, ", paste(forest_attributes[i], collapse = ","), " FROM veg_comp_2020_adj WHERE feature_id IN (", paste(fids, collapse = ","),");" )))

inv<-merge(x=inv_id, y=attrib_inv, by.x = "fid", by.y = "fid", all.x = TRUE) 

#Merge to pixels using the pixelid
pixels<-merge(x = pixels, y =inv, by.x = "pixelid", by.y = "pixelid", all.x = TRUE)
pixels<-pixels[, fid:=NULL] # remove the fid key
rm(inv, attrib_inv)
gc()     
}

write.csv(pixels, "D://Fire//fire_data//raw_data//pixels.csv")

# collect some more info from vri
forest_attributes<-c("bclcs_level_2","proj_age_1","proj_height_1", "crown_closure", "stand_percentage_dead")
                                   
fids<-unique(inv_id[!(is.na(fid)), fid])

for (i in 1:length(forest_attributes)) { 
  
print(forest_attributes[i])
  
attrib_inv<-data.table(getTableQuery(paste0("SELECT feature_id as fid, ", paste(forest_attributes[i], collapse = ","), " FROM veg_comp_2020_adj WHERE feature_id IN (", paste(fids, collapse = ","),");" )))

inv<-merge(x=inv_id, y=attrib_inv, by.x = "fid", by.y = "fid", all.x = TRUE) 

#Merge to pixels using the pixelid
pixels<-merge(x = pixels, y =inv, by.x = "pixelid", by.y = "pixelid", all.x = TRUE)
pixels<-pixels[, fid:=NULL] # remove the fid key

rm(inv, attrib_inv)

gc()     
}

head(pixels)
        

'inventory_standard_cd'
'non_productive_cd'
'coast_interior_cd',
'bclcs_level_1',
'bclcs_level_2',
'bclcs_level_3',
'bclcs_level_5',
'non_veg_cover_type_1'
'land_cover_class_cd_1'
'bec_zone_code',
'bec_subzone',
'earliest_nonlogging_dist_type',
'earliest_nonlogging_dist_date',
'stand_percentage_dead',
'harvest_date',
'crown_closure',
'vri_live_stems_per_ha',
'vri_dead_stems_per_ha',
'species_cd_1',
'species_pct_1',
'species_cd_2',
'species_pct_2',
'species_cd_3',
'species_pct_3',
'species_cd_4',
'species_pct_4',
'species_cd_5',
'species_pct_5',
'species_cd_6',
'species_pct_6',
'proj_age_1',
'proj_height_1',

forest_attributes_castordb<-sapply(c("Treed","Age","Height", "CrownClosure", "SiteIndex", "QMD", "BasalArea"), function(x){
        if(!(P(sim, paste0("nameForestInventory", x), "dataCastor") == '99999')){
          return(paste0(P(sim, paste0("nameForestInventory", x), "dataCastor"), " as ", tolower(x)))
        }else{
          message(paste0("WARNING: Missing parameter nameForestInventory", x, " ---Defaulting to NA"))
        }
      })

      
      forest_attributes_castordb<-sapply(c("bclcs_level_2","proj_age_1","proj_height_1", "crown_closure", "stand_percentage_dead"), function(x){
          return(paste0(paste0("nameForestInventory", x), " as ", tolower(x)))
        }else{
          message(paste0("WARNING: Missing parameter nameForestInventory", x, " ---Defaulting to NA"))
        }
      })
      
      forest_attributes_castordb<-Filter(Negate(is.null), forest_attributes_castordb) #remove any nulls
      
          
      if(length(forest_attributes_castordb) > 0){
        print(paste0("getting inventory attributes: ", paste(forest_attributes_castordb, collapse = ",")))
        fids<-unique(inv_id[!(is.na(fid)), fid])
        attrib_inv<-data.table(getTableQuery(paste0("SELECT " , P(sim, "nameForestInventoryKey", "dataCastor"), " as fid, ", paste(forest_attributes_castordb, collapse = ","), " FROM ",
                                                    P(sim, "nameForestInventoryTable","dataCastor"), " WHERE ", P(sim, "nameForestInventoryKey", "dataCastor") ," IN (",
                                                    paste(fids, collapse = ","),");" )))
        
        print("...merging with fid") #Merge this with the raster using fid which gives you the primary key -- pixelid
        inv<-merge(x=inv_id, y=attrib_inv, by.x = "fid", by.y = "fid", all.x = TRUE) 
        
        #Merge to pixels using the pixelid
        pixels<-merge(x = pixels, y =inv, by.x = "pixelid", by.y = "pixelid", all.x = TRUE)
        pixels<-pixels[, fid:=NULL] # remove the fid key
        
        #Change the VRI bclcs_level_2 which is the TREED parameter to a binary.
        pixels<-pixels[!treed == 'T', treed:=0][treed == 'T', treed:=1]
        
        if(!is.null(multiVars1)){
          for(var in multiVars1){
            if(is.character(pixels[, eval(parse(text =var))])){
              dbExecute(sim$castordb, glue::glue("ALTER TABLE pixels ADD COLUMN {var} text;"))
            }else{
              dbExecute(sim$castordb, glue::glue("ALTER TABLE pixels ADD COLUMN {var} numeric;"))
            }
          }
        }
        rm(inv, attrib_inv,inv_id, fids)
      }else{
        stop("No forest attributes from the inventory specified")
      }
    } else { 
      stop(paste0('nameForestInventoryTable = ', P(sim, "nameForestInventoryTable","dataCastor")))
    }  
  } else{
    multiVars<-''
    multiVars2<-''
    multiVars1<-NULL
  }
```
