---
title: "fisherHabitatLoader"
author: ""
date: "26 October 2022"
output:
  html_document:
    keep_md: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE, results = "hold") ## TODO: use 'eval = TRUE'

```

## Overview
This is a .RMD to test the functionality of the fisherHabtiatLoader in the Williams Lake TSA. 


```{r module_usage}
library (SpaDES.core)
library (data.table)
library (terra)
library (keyring)
library (tidyverse)
library (here)
source (paste0(here::here(), "/R/functions/R_Postgres.R"))

moduleDir <- file.path (paste0 (here::here (), "/R/SpaDES-modules"))
inputDir <- file.path (paste0 (here::here (), "/R/scenarios/test_flex2/inputs")) %>% reproducible::checkPath (create = TRUE)
outputDir <- file.path (paste0 (here::here (), "/R/scenarios/test_flex2/outputs")) %>% reproducible::checkPath (create = TRUE)
cacheDir <- file.path (paste0 (here::here (), "/R/scenarios/test_flex2"))

times <- list (start = 0, end = 40)

parameters <- list(
  dataLoaderCLUS = list(dbName='clus',
                         save_clusdb = FALSE, # Set to TRUE first time running the analysis
                         sqlite_dbname = "fisherABM_test", 
                         nameBoundaryFile = "tsa_aac_bounds",
                         useCLUSdb = paste0(here::here(), "/R/scenarios/test_flex2/fisherABM_test_clusdb.sqlite"),
                         nameBoundaryColumn = "tsa_name", 
                         nameBoundary = c ("Williams_Lake_TSA"), 
                         nameBoundaryGeom = 'wkb_geometry',
                         nameCompartmentRaster = "rast.tsa_aac_boundary",
                         nameCompartmentTable = "vat.tsa_aac_bounds_vat",
                         nameMaskHarvestLandbaseRaster ='rast.thlb_2020', 
                         nameZoneRasters=c("rast.zone_cond_beo", 
                                           "rast.zone_cond_vqo", 
                                           "rast.zone_wha_2021", 
                                           "rast.zone_uwr_2021",  
                                           "rast.zone_cond_nharv", 
                                           "rast.zone_cond_fsw", 
                                           "rast.zone_cond_cw"
                              ),
                         nameZoneTable="zone.constraints", 
                         nameYieldsRaster = "rast.ycid_vdyp_2020",
                         nameYieldTable ="yc_vdyp_2020",
                         nameYieldsCurrentRaster = "rast.ycid_tipsy_current_2020",
                         nameYieldCurrentTable = "tipsy_current_prov_2020",
                         nameYieldsTransitionRaster = "rast.ycid_tipsy_prov_2020", 
                         nameYieldTransitionTable = "tipsy_prov_2020", 
                         nameForestInventoryRaster = "rast.vri2020_id", 
                         nameForestInventoryKey = "feature_id",                     
                         nameForestInventoryTable = "veg_comp_lyr_r1_poly2020",
                         nameForestInventoryAge = "proj_age_1",  
                         nameForestInventoryHeight = "proj_height_1",
                         nameForestInventoryCrownClosure = "crown_closure",
                         nameForestInventoryTreed = "bclcs_level_2",
                         nameForestInventorySiteIndex = "site_index",
                         nameForestInventoryBasalArea= "basal_area",
                         nameForestInventoryQMD = "quad_diam_125"
                    ),
  blockingCLUS = list(blockMethod ='pre', 
                      patchZone = 'rast.zone_cond_beo',
                      patchVariation = 6,
                      nameCutblockRaster ="rast.cns_cut_bl",
                      useLandingsArea = FALSE, 
                      useSpreadProbRas = FALSE),
  forestryCLUS = list(harvestBlockPriority = "age DESC", # "dist, age DESC, vol DESC"
                      #harvestZonePriority = "age DESC",
                      #harvestZonePriorityInterval = 1,
                      adjacencyConstraint = 0),
  growingStockCLUS = list (periodLength = 5),
  roadCLUS = list(roadMethod = 'mst', # pre mst
                  nameCostSurfaceRas = 'rast.rd_cost_surface', 
                  nameRoads =  'rast.ce_road_2019'),
  fisherHabitatLoader = list (),
  uploaderCLUS = list(aoiName = 'test_fisher_habitat_loader', 
                      dbInfo  = list(keyring::key_get("vmdbhost", keyring="postgreSQL"), 
                                     keyring::key_get("vmdbuser", keyring="postgreSQL"), 
                                     keyring::key_get("vmdbpass", keyring="postgreSQL"),  
                                     keyring::key_get("vmdbname", keyring="postgreSQL"))
  )
)


scenario = data.table (name = "test_fisher_habitat",
                       description = "Testing fisher habitat loader on Williams Lake TSA.")

harvestFlow <- rbindlist(list(data.table(compartment = "Williams_Lake_TSA",
                                     partition = ' vol > 150 ', 
                                     period = rep( seq (from = 1,
                                                      to = 40, 
                                                      by = 1),
                                                1), 
                                     flow = 12500000, #2,500,000m3/year 
                                     partition_type = 'live') 
                        ))

patchSizeDist<- data.table(ndt= c(1,1,1,1,1,1,
                                  2,2,2,2,2,2,
                                  3,3,3,3,3,3,
                                  4,4,4,4,4,4,
                                  5,5,5,5,5,5), 
                           sizeClass = c(40,80,120,160,200,240), 
                           freq = c(0.3,0.3,0.1,0.1,0.1, 0.1,
                                    0.3,0.3,0.1,0.1,0.1, 0.1,
                                    0.2, 0.3, 0.125, 0.125, 0.125, 0.125,
                                    0.1,0.02,0.02,0.02,0.02,0.8,
                                    0.3,0.3,0.1,0.1,0.1, 0.1))

modules <- list ("fisherHabitatLoader",
                 "growingStockCLUS",
                 "blockingCLUS", 
                 "forestryCLUS", 
                 "roadCLUS",
                 "uploaderCLUS",
                 "dataLoaderCLUS")



objects <- list (scenario = scenario,
                 harvestFlow = harvestFlow, 
                 patchSizeDist = patchSizeDist)

inputs <- list ()

outputs <- data.frame (objectName = c("harvestReport",
                                      "growingStockReport"))

paths <- list(cachePath = cacheDir,
              modulePath = moduleDir,
              inputPath = inputDir,
              outputPath = outputDir)

mySim <- simInit(times = times, 
                 params = parameters, 
                 modules = modules,
                 objects = objects,
                 paths = paths)

mySimOut <- spades(mySim)
```

