---
title: "Untitled"
author: "Elizabeth Kleynhans"
date: "2024-02-06"
output: html_document
---

Some pre-processing of the vri
####GET BEC
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


message("create fuel types table")
  
  message("getting BEC information")
  
  ras.bec<- terra::rast(RASTER_CLIP2(tmpRast = paste0('temp_', sample(1:10000, 1)), 
                                     srcRaster= P(mySim, "nameBecRast", "fireCastor"), 
                                     clipper=mySim$boundaryInfo[1] , 
                                     geom= mySim$boundaryInfo[4] , 
                                     where_clause =  paste0(mySim$boundaryInfo[2] , " in (''", paste(mySim$boundaryInfo[[3]], sep = "' '", collapse= "'', ''") ,"'')"),
                                     conn=NULL))
  
  if(terra::ext(mySim$ras) == terra::ext(ras.bec)){ #need to check that each of the extents are the same
    bec_id<-data.table(idkey = as.integer(ras.bec[]))
    bec_id[, pixelid := seq_len(.N)][, idkey := as.integer(idkey)]
    rm(ras.bec)
    gc()
  }else{
    stop(paste0("ERROR: extents are not the same check -", P(mySim, "nameBecRast", "fireCastor")))
  }
  
  bec_id_key<-unique(bec_id[!(is.na(idkey)), idkey])
  bec_key<-data.table(getTableQuery(paste0("SELECT idkey, zone, subzone FROM ",P(mySim, "nameBecTable","fireCastor"), " WHERE idkey IN (", paste(bec_id_key, collapse = ","),");")))
  
  bec<-merge(x=bec_id, y=bec_key, by.x = "idkey", by.y = "idkey", all.x = TRUE) 
  bec<-bec[, idkey:=NULL] # remove the fid key
```

#### GET VRI DATA
```{r setup, include=FALSE}
#**************FOREST INVENTORY - VEGETATION VARIABLES*******************#
  #----------------------------#
  #----Set forest attributes----
  #----------------------------#
  if(!P(mySim, "nameForestInventoryRaster","fireCastor") == '99999'){
    message("clipping inventory key")
    ras.fid<- terra::rast(RASTER_CLIP2(tmpRast = paste0('temp_', sample(1:10000, 1)), 
                                       srcRaster= P(mySim, "nameForestInventoryRaster", "fireCastor"), 
                                       clipper=mySim$boundaryInfo[[1]], 
                                       geom= mySim$boundaryInfo[[4]], 
                                       where_clause =  paste0 (mySim$boundaryInfo[[2]], " in (''", paste(mySim$boundaryInfo[[3]], sep = "' '", collapse= "'', ''") ,"'')"),
                                       conn=NULL))
    if(terra::ext(mySim$ras) == terra::ext(ras.fid)){ #need to check that each of the extents are the same
      inv_id<-data.table(fid = as.integer(ras.fid[]))
      inv_id[, pixelid:= seq_len(.N)]
      inv_id[, fid:= as.integer(fid)] #make sure the fid is an integer for merging later on
      rm(ras.fid)
      gc()
    }else{
      stop(paste0("ERROR: extents are not the same check -", P(mySim, "nameForestInventoryRaster", "fireCastor")))
    }
    
    
    if(!P(mySim, "nameForestInventoryTable2","fireCastor") == '99999'){ #Get the forest inventory variables 
      
      fuel_attributes_castordb<-sapply(c('bclcs_level_1', 'bclcs_level_2', 'bclcs_level_3', 'bclcs_level_4',  'bclcs_level_5', 'inventory_standard_cd', 'non_productive_cd', 'coast_interior_cd',  'land_cover_class_cd_1', 'earliest_nonlogging_dist_type', 'earliest_nonlogging_dist_date','vri_live_stems_per_ha', 'vri_dead_stems_per_ha','species_cd_1','species_pct_1','species_cd_2', 'species_pct_2', 'species_cd_3', 'species_pct_3','species_cd_4','species_pct_4', 'species_cd_5', 'species_pct_5', 'species_cd_6', 'species_pct_6'), function(x){
        if(!(P(mySim, paste0("nameForestInventory", x), "fireCastor") == '99999')){
          return(paste0(P(mySim, paste0("nameForestInventory", x), "fireCastor"), " as ", tolower(x)))
        }else{
          message(paste0("WARNING: Missing parameter nameForestInventory", x, " ---Defaulting to NA"))
        }
      })
      
      fuel_attributes_castordb<-Filter(Negate(is.null), fuel_attributes_castordb) #remove any nulls
      
      if(length(fuel_attributes_castordb) > 0){
        print(paste0("getting inventory attributes to create fuel types: ", paste(fuel_attributes_castordb, collapse = ",")))
        fids<-unique(inv_id[!(is.na(fid)), fid])
        attrib_inv<-data.table(getTableQuery(paste0("SELECT " , P(mySim, "nameForestInventoryKey", "fireCastor"), " as fid, ", paste(fuel_attributes_castordb, collapse = ","), " FROM ",P(mySim, "nameForestInventoryTable2","fireCastor"), " WHERE ", P(mySim, "nameForestInventoryKey", "fireCastor") ," IN (",
                                                    paste(fids, collapse = ","),");" )))
        
        
        message("...merging with fid") #Merge this with the raster using fid which gives you the primary key -- pixelid
        inv<-merge(x=inv_id, y=attrib_inv, by.x = "fid", by.y = "fid", all.x = TRUE) 
        inv<-inv[, fid:=NULL] # remove the fid key
        
        inv<-merge(x=inv, y=bec, by.x="pixelid", by.y="pixelid", all.x=TRUE)
        
        inv[, earliest_nonlogging_dist_date := substr(earliest_nonlogging_dist_date,1,4)]
        inv[, earliest_nonlogging_dist_date := as.integer(earliest_nonlogging_dist_date)]
```

#### Estimate % conifer

```{r setup, include=FALSE}
message("calculating % conifer and dominant conifer species")
        
        conifer<-c("C","CW","Y","YC","F","FD","FDC","FDI","B","BB","BA","BG","BL","H","HM","HW","HXM","J","JR","JS","P","PJ","PF","PL","PR","PLI","PXJ","PY","PLC","PW","PA","S","SB","SE","SS","SW","SX","SXW","SXL","SXS","T","TW","X", "XC","XH", "ZC")
        
        inv[, pct1:=0][species_cd_1 %in% conifer, pct1:=species_pct_1]
        inv[, pct2:=0][species_cd_2 %in% conifer, pct2:=species_pct_2]
        inv[, pct3:=0][species_cd_3 %in% conifer, pct3:=species_pct_3]
        inv[, pct4:=0][species_cd_4 %in% conifer, pct4:=species_pct_4]
        inv[, pct5:=0][species_cd_5 %in% conifer, pct5:=species_pct_5]
        inv[, pct6:=0][species_cd_6 %in% conifer, pct6:=species_pct_6]
        
        # create dominant conifer column and populate
        inv[, dominant_conifer:="none"]
        inv[species_cd_1 %in% conifer, dominant_conifer:=species_cd_1]
        inv[!(species_cd_1 %in% conifer) & species_cd_2 %in% conifer, dominant_conifer:=species_cd_2]
        inv[!(species_cd_1 %in% conifer) & !(species_cd_2 %in% conifer) & species_cd_3 %in% conifer, dominant_conifer:=species_cd_3]
        inv[!(species_cd_1 %in% conifer) & !(species_cd_2 %in% conifer) & !(species_cd_3 %in% conifer) & species_cd_4 %in% conifer, dominant_conifer:=species_cd_4]
        inv[!(species_cd_1 %in% conifer) & !(species_cd_2 %in% conifer) & !(species_cd_3 %in% conifer) & !(species_cd_4 %in% conifer) & species_cd_5 %in% conifer, dominant_conifer:=species_cd_5]
        inv[!(species_cd_1 %in% conifer) & !(species_cd_2 %in% conifer) & !(species_cd_3 %in% conifer) & !(species_cd_4 %in% conifer) & !(species_cd_5 %in% conifer) & species_cd_6 %in% conifer, dominant_conifer:=species_cd_6]
        
        #determing total percent cover of conifer species
        inv[,conifer_pct_cover_total:=pct1+pct2+pct3+pct4+pct5+pct6]
        
        mySim$inv[!is.na(bclcs_level_1)]
        

```

# Get kyles veg data
```{r}
  
  ## extract data from BEC instead of pulling it off the vri. I think it will be better!
message("getting vegetation data")

# if (nrow(sim$inv)<1){
#   sim$inv<-data.table(dbGetQuery(sim$castordb, "SELECT * FROM fueltype"))
# }

  veg_attributes<- data.table(dbGetQuery(mySim$castordb, "SELECT pixelid, crownclosure, age, vol, height, dec_pcnt, blockid FROM pixels"))
  
  veg2<-merge(mySim$inv, veg_attributes, by.x="pixelid", by.y = "pixelid", all.x=TRUE)
  
  rm(veg_attributes)
  gc()

  #### CHECK if years_since_nonlogging_dist needs to be updated after a fire####
  

  veg2[, years_since_nonlogging_dist:=NA_integer_]
  veg2[, years_since_nonlogging_dist:=2020 - earliest_nonlogging_dist_date]
 
```


# Now create the decision tree



```{r}

 conifer<-c("C","CW","Y","YC","F","FD","FDC","FDI","B","BB","BA","BG","BL","H","HM","HW","HXM","J","JR","JS","P","PJ","PF","PL","PR","PLI","PXJ","PY","PLC","PW","PA","S","SB","SE","SS","SW","SX","SXW","SXL","SXS","T","TW","X", "XC","XH", "ZC")
  
  wet<-c("mc", "mcp", "mh", "mk", "mkp", "mks", "mm", "mmp", "mmw", "ms", "mv", "mvp", "mw", "mwp", "mww", "vc", "vcp", "vcw", "vh", "vk", "vks", "vm", "wc", "wcp", "wcw", "wh", "whp", "wk", "wm", "wmp", "wmu", "ws", "wv", "wvp", "ww")
  
  burn<-c("B","BE", "BG", "BR", "BW", "NB")

#### General definitions ####
veg2[bclcs_level_2=="W" | bclcs_level_5 %in% c("GL","LA", "RE", "RI", "OC"), fwveg := "W"]
veg2[(conifer_pct_cover_total>=75 & crownclosure>=10) | (bclcs_level_4 == "TC" & is.na(species_pct_1)), fwveg:="TC"]
veg2[(conifer_pct_cover_total<=25 & crownclosure>=10) | (bclcs_level_4 == "TB" & is.na(species_pct_1)), fwveg:="TB"]
veg2[(conifer_pct_cover_total %between% c(26,74) & crownclosure>=10) | (bclcs_level_4 == "TM" & is.na(species_pct_1)), fwveg:="TM"]
veg2[crownclosure<10, fwveg:="O"]
veg2[crownclosure<5 & bclcs_level_5 %in% c("PN", "BR","TA", "BL", "MZ", "LB", "RS", "LS", "RM", "BE", "RZ", "MU", "CB", "MN", "GP","TZ","RN", "UR", "AP", "MI","RE") | (is.na(crownclosure) & is.na(bclcs_level_5) bclcs_level_1 =="N"), fwveg:="N"]

#### recently burned #### 
veg2[earliest_nonlogging_dist_type %in% "burn" & years_since_nonlogging_dist  < 2, fwveg:="N"]

veg2[earliest_nonlogging_dist_type %in% "burn" & years_since_nonlogging_dist %between% c(2,3), fwveg:="TB"]

veg2[earliest_nonlogging_dist_type %in% "burn" & years_since_nonlogging_dist %between% c(2,3) & conifer_pct_cover_total>=75 & crownclosure>60 , fwveg:="N"]

veg2[earliest_nonlogging_dist_type %in% "burn" & years_since_nonlogging_dist %between% c(2,3) & crownclosure<5, fwveg:="N"]

veg2[earliest_nonlogging_dist_type %in% "burn" & years_since_nonlogging_dist %between% c(4,6), fwveg:="TB"]

veg2[earliest_nonlogging_dist_type %in% "burn" & years_since_nonlogging_dist %between% c(4,6) & crownclosure %between% c(5,9), fwveg:="O"]

veg2[earliest_nonlogging_dist_type %in% "burn" & years_since_nonlogging_dist %between% c(7,10), fwveg:="O"]

veg2[earliest_nonlogging_dist_type %in% "burn" & years_since_nonlogging_dist %between% c(7,10) & conifer_pct_cover_total %between% c(25, 75) & crownclosure>10, fwveg:="TB"]

veg2[earliest_nonlogging_dist_type %in% "burn" & years_since_nonlogging_dist %between% c(7,10) & conifer_pct_cover_total>=75 & crownclosure>60, fwveg:="TC"]

##### Recently Logged #####
veg2[blockid>0 & age <=7 & (years_since_nonlogging_dist > 7 | is.na(years_since_nonlogging_dist)), fwveg:="S"]

veg2[bclcs_level_1=="N" & blockid>0 & (age %between% c(7,24)) & (years_since_nonlogging_dist > age | is.na(years_since_nonlogging_dist)), fwveg:="O"]

  veg2[bclcs_level_1=="N" & blockid>0 & (age %between% c(7,24)) & zone %in% c("CWH","MH","ICH") & (years_since_nonlogging_dist > age | is.na(years_since_nonlogging_dist)), fwveg:="TB"]
       
  # harvest date > 25 & bclcs_level_1 =="N"
  veg2[bclcs_level_1=="N" & blockid>0 & age>=25 & zone %in% c("CMA","IMA"), fwveg:="N"]
  veg2[bclcs_level_1=="N" & blockid>0 & age>=25 & zone== c("BAFA", "MH"), fwveg:= "TB"]
  veg2[bclcs_level_1=="N" & blockid>0 & age>=25 & zone %in% c("CWH", "SWB"), fwveg:="TM"]
  veg2[bclcs_level_1=="N" & blockid>0 & age>=25 & zone =="CWH" & subzone %in% wet, fwveg:="TC"]
  veg2[bclcs_level_1=="N" & blockid>0 & age>=25 & zone %in% c("BWBS","SBS","SBPS", "MS", "IDF", "ESSF", "CDF","ICH"), fwveg:="TC"]
  veg2[bclcs_level_1=="N" & blockid>0 & age>=25 & zone %in% c("PP","BG"), fwveg:="O"]
  
  # some more specific difinitions with slash
  
veg2[bclcs_level_1=="V" & bclcs_level_2=="T" & species_pct_1> 79 & species_cd_1 == "PY" & (crownclosure %between% c(10, 25)) & blockid>0 & age<=10, fwveg:="S"]

   veg2[bclcs_level_1=="V" & bclcs_level_2=="T" & species_pct_1>= 80 & species_cd_1 == "PY" & bclcs_level_5 %in% c("DE","OP") & blockid>0 & age<=10, fwveg:="S"]
   
   veg2[bclcs_level_1=="V" & bclcs_level_2=="T" & species_pct_1> 79 & species_cd_1 %in% c("SB", "SW", "SE") & blockid>0 & age<=10 & (years_since_nonlogging_dist > 10 | is.na(years_since_nonlogging_dist)), fwveg:="S"]


   #### mountain pine beetle attack####
# veg2[earliest_nonlogging_dist_type=="IBM" & years_since_nonlogging_dist <=5 & dec_pcnt >50, fwveg:="M-3"]
# veg2[earliest_nonlogging_dist_type=="IBM" & years_since_nonlogging_dist <=5 & dec_pcnt %between% c(25,50), fwveg:="C-2"]
# veg2[earliest_nonlogging_dist_type=="IBM" & years_since_nonlogging_dist <=5 & dec_pcnt < 25, fwveg:="C-3"]
# 
# veg2[earliest_nonlogging_dist_type=="IBM" & years_since_nonlogging_dist > 5 & dec_pcnt >50, fwveg:="C-2"]
# veg2[earliest_nonlogging_dist_type=="IBM" & years_since_nonlogging_dist > 5 & dec_pcnt<51, fwveg:="C-3"]



```



