---
title: "openJDK_Install"
author: "Kyle"
date: "26/05/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Purpose

OpenJDK is needed for developing and running Java Applications. You already have Java on your computer -since 2 billion applications use java. In the blockingCLUS model, the graph-based image segementation algorithum is coded in Java in order to leverage the iterator methods for arrayList data strutures. At the time I could not find an efficient comparable data structure found in R, but maybe this will change.

##  Download the OpenJDK Software

* Go to: https://jdk.java.net/14/

You will see a section that looks something like:
Builds
Linux / x64	tar.gz (sha256)	198665889
macOS / x64	tar.gz (sha256)	193293652
Windows / x64	zip (sha256)	198729845

* Download the Windows 64 bit zip. The Download will likely be stored in your Downloads folder.

## Extract to C:\Program Files\Java

* Create a file in C:\Program Files\ called Java

* Go back to your Downloads folder. Right click on the openjdk folder (openjdk-14.0.1_windows-x64_bin.zip). Click 7-zip --> Extract files... 

* The 7-zip user form will prompt you. Set Extract to: C:\Program Files\Java

## Set Environmental Variables

* In the Windows search bar (near the Windows Start symbol) type environmental and select 'Edit the systems environmental variables'

* Under the Advanced Tab --> click Environmental Variables

* Under the Systems variables (bottom section) --> click New

* Set the variable name to JAVA_HOME 

* Set the variable value to C:\Program Files\Java\jdk-14.0.1\bin. Click ok

* Back in Environmental Variables -- the bottom section that says System Variables-- Double Click on Path. Click New. Paste in C:\Program Files\Java\jdk-14.0.1\bin.

* Move the C:\Program Files\Java\jdk-14.0.1\bin path to the top via the Move up button

## Check

* Open up command prompt (cmd) type: java --version. Hit Enter. You should see:
openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)




