---
title: "Comparing_Data_Distributions"
author: "Cora Skaien"
date: "26/03/2022"
output: html_document
---
<!--
Copyright 2021 Province of British Columbia

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(data.table)
library(sf)
library(tidyverse)
library(rgeos)
library(cleangeo)
library(dplyr)
library(tidyr)
library(ggplot2)
library(rgdal)
library(sp)
library(keyring)
library(DBI)
library(rgeos)
library(car)
library(rje)
library(caret)
library(pROC)
library(visreg)
library(gtools)
```

Unsure about below anymore
```{r setup, include=FALSE}
source(here::here("R/functions/R_Postgres.R")) #maybe this is the problem after my update?
```

Determine distribution of data by environmental variables. This will need to be repeated for when data sets combined, but peak here.

First, we will need to bring in the data and then append the same data we have for the rest of the data.
```{r}
#Bring in ALL Clayton Huckleberry Data
Huckleberry_Clayton_ALL<-st_read(dsn="C:\\cora\\Hucklberry\\Grizzly Bear stuff\\berries\\data\\Clayton_huckleberry_SpeciesPresent.shp", stringsAsFactors = T)

```

```{r}
DEM_slope <- raster("T:\\FOR\\VIC\\HTS\\ANA\\PROJECTS\\CLUS\\Data\\dem\\all_bc\\slope_ha_bc_3005.tif")
crs(DEM_slope) 

DEM_aspect <- raster("T:\\FOR\\VIC\\HTS\\ANA\\PROJECTS\\CLUS\\Data\\dem\\all_bc\\aspect_ha_bc_3005.tif")
crs(DEM_aspect)

#Elevation
DEM_elevation <- raster("T:\\FOR\\VIC\\HTS\\ANA\\PROJECTS\\CLUS\\Data\\dem\\all_bc\\dem_ha_bc.tif")
crs(DEM_elevation)
crs(Huckleberry_Clayton_ALL) #Same!

#Stack rasters
rasStack = stack(DEM_slope, DEM_aspect, DEM_elevation)
crs(rasStack) #3005
head(rasStack)
str(rasStack)
extent(rasStack)
```


```{r}
Huckleberry_Clayton_ALL$coords_x1<-st_coordinates(Huckleberry_Clayton_ALL)
head(Huckleberry_Clayton_ALL)
crs(Huckleberry_Clayton_ALL)

pointCoordinates<-data.frame(Huckleberry_Clayton_ALL$coords.x1, Huckleberry_Clayton_ALL$coords.x2)
head(pointCoordinates)

DEM_huck_ALL=raster::extract(rasStack, pointCoordinates)
head(DEM_huck_ALL)

#Append
Huckleberry_Clayton_ALL<-cbind(Huckleberry_Clayton_ALL, DEM_huck_ALL)
head(Huckleberry_Clayton_ALL)
```

Compare distirbutions between all data and cutblock locations.

```{r}
hist(Huckleberry_Clayton_ALL$dem_ha_bc, xlim=c(500,2500))
mean(Huckleberry_Clayton_ALL$dem_ha_bc) #1639.47
min(Huckleberry_Clayton_ALL$dem_ha_bc) #440
max(Huckleberry_Clayton_ALL$dem_ha_bc) #2303

cutblock_plots_openings_productivity_huck_df<-read.csv(file="C:\\cora\\Hucklberry\\Grizzly Bear stuff\\berries\\data\\Clayton_cutblocks_DEM_Huckleberry_B.csv")

hist(cutblock_plots_openings_productivity_huck_df$dem_ha_bc, xlim=c(500,2500))
mean(cutblock_plots_openings_productivity_huck_df$dem_ha_bc) #1587.69
```


