---
title: "Huckleberry_Model_Ideas"
author: "Cora Skaien"
date: "17/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!--
Copyright 2021 Province of British Columbia

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
-->

#Overview
The goal of this project is to be able to assess whether we can model the abundance and productivity of huckleberry and soopalilie (buffaloberry) patches and relate this to grizzly bear foraging quality habitat. Some work has been done looking at associations between forest cutblock age and the abundance of both huckleberries and soopalilie, and some preliminary analyses have been performed to assess the correlations between variables.

Currently, we have data provided by Dr. Clayton Lamb on the abundance of huckleberry plants and berries, along with accompanying data on climate, soils, DEM, etc. We should look into the possibility of acquiring additional data that may be comparable that may cover more areas of BC. It has been suggested that we can model canopy closure from models that Kyle has. We can (and should) include climate, but the main questions of interest are stand characteristics (e.g., crown closure, basal area). There will also be some static variables such as topography.

We likely should split the analyses into different BEC zones, and only include those that have huckleberry or soopalilie. Maybe this does not matter, but when projecting forward, only BEC zones that contain these species should be mapped. 

#Notes:
1. Ideally predict across province, but only in BEC Zones with huckleberry potential. BEC zone or subzone: Could also include provenance of planted stand (species). Ensure using only BEC zones that could contain huckleberries. Planting dataset sparse.

2. Cutblock size info? I have coordinates and I may be able to match these to online databases. https://catalogue.data.gov.bc.ca/dataset/harvested-areas-of-bc-consolidated-cutblocks- Note: retention patch sizes may not be adequately captured here. Note: many cutblock sizes only capture that year's cutblock and not adjacent ones. May also wish to consider size:edge ratio. Consider area-to-perimeter ratio. Likely less important for actual berry production (although shading effects could influence), and more important for grizzly bear selection of foraging sites.

3. Cutblock treatment: RESULTS file on bc gov page may have info on treatments and silviculture. (scarification, planting density, timing of harvest - winter vs summer)

4. Data projection is ESPG 3005.

5. Generate ifelse statement to determine if fire after logging or not. Tyler has done something similar.

6. In VegModData, what is the difference between 0 and NA? 0s are when this species was looked for and not found; NA indicates that it was not explicitly sought.

7.  Other data available? Data from Chandler and Hamilton have much lower stand age results than Tyler's preliminary analyses. Garth has already sent some from another student.

8. Subset so only use plots that have been logged before.

9. Due to hierarchical nature, could use negative binomial hurdle models.

10. Current data set too small to look at different types of mechanical treatment, but this is likely important.


#Questions I have and notes:
  1. Phenology and distribution and abundance? And energetics! Perhaps: P/A, percent cover focus. Then phenology and energetics. Energetics priority before phenology for our aims. Negative binomial (counts and P/A --> model occurrence and then count for it; regression models--> zero inflated models--> look into! Talk to Peter)
  2. If extent BC, how to create a raster for soil pH across the province to be able to include it in the predictive model. Or even over a smaller area. May need to create 2 models, one with and one without?
  3. Is there any way to use the phenology data to extrapolate to a Julian Date for ripened fruit?
  4.How do we get CMI?
  5. How do we get percent area burned?
  6. Best month allocation for season? I am using MAM spring, JJA summer, etc.
  
#Key variables to acquire and/or investigate:
1. Canopy closure/cover -- could consider applying 50% canopy rule but investigate without first (Can acquire, I believe, from VRI or other means; otherwise here https://landcover.usgs.gov/glc/TreeCoverDescriptionAndDownloads.php)
   Note: LandSatCC_2010 likely the canopy cover as of 2010.
2. Cut block harvesting techniques and Silviculture (I believe I can get this from RESULTS files) - include seasonality.
3. Whether cutblock planted after or not (I suspect this will be confounded with age since this became common practice after 1990s)
4. Cut block size (can get this data from cutblock layer)
5. ClimateBC data (already in dataset: Annual heat Moisture (AHM) Index, Climate Moisture Index (CMI), EMT, EXT, MAT, MCMT, MSP)--> winter snow seems REALLY important for huckleberry; summer metrics more important for buffaloberry
6. land cover type (MODIS in the dataset - categorical)
7. Solar heat load (acquire from DEM info?) - otherwise use slope, elevation, aspect. Can be calculated from DEM in ArcGIS. I see note of this in metadata but do not see in data file.
8. Soil pH?? But how to scale up when we likely do not have a province wide soil pH layer? (Or do we??? Need to figure out how to use this and see if useful: https://www.env.gov.bc.ca/esd/distdata/ecosystems/Soil_Data/SOIL_DATA_FGDB/) Data has this, but for projecting, need layer.
9. Soil properties (sandiness, course materials, etc.) - Do we have this across BC? Maybe this is what link above can give us. Data has this, but for projecting, we need layer. Clayton did extensive processing to create these layers and has kindly shared them. Unfortunately, the shared layers only cover SE BC and thus not the extent of the entire data.
10. Consider area-to-perimeter ratio.

Clayton's climate models found best predictors:(1) percent of area burned, (2) percent sand, (3) average winter temperature, (4) precipitation as snow, (5) canopy cover, (6) average pH, (7) slope and (8) solar heat load

**Assess whether linear or non-linear for each. Canopy cover should be quadratic - upside down u-shaped with long tail.

#See some initial exploration of the data here by Tyler Muhly:
https://github.com/bcgov/FAIB_wildlife/blob/main/berry_model.Rmd

#See important layers here:
1. RESULTS: showing forest regeneration following harvest. https://catalogue.data.gov.bc.ca/dataset/results-forest-cover-inventory
https://catalogue.data.gov.bc.ca/dataset/results-openings-attribute-only
https://catalogue.data.gov.bc.ca/dataset/results-planting
https://catalogue.data.gov.bc.ca/dataset/results-activity-treatment-units
https://catalogue.data.gov.bc.ca/dataset/results-forest-cover-silviculture
https://catalogue.data.gov.bc.ca/dataset/results-forest-cover-species-attribute-only
https://catalogue.data.gov.bc.ca/dataset/results-openings-slope-aspect-and-elevation
https://catalogue.data.gov.bc.ca/dataset/results-openings-svw




########### Literature Review ###############

##Chandler, J. and Hamilton, E. 2021. Response of Vaccinium membranaceum to logging, prescribed burning, wildfire, and tree cover in the ESSF, ICH and SBS zones in central and norther BC. Technical report.
 
Key findings:
   - ESSF > cover than SBS and ICH (over 30% cover only found in ESSF zone).
   - cover peaked 18 years after burn, and at 12 years in unburned plots (all harvested I think); with >30% reached in unburned plots after 3 years but not in burned plots until year 12
   - No data for unburned plots age 15-28 years.
   - 70% of ESSF plots with >40% cover were burned
   - percent cover seems to be much higher in unburned plots, but decreases after 12 years. Burned plots have a steady increase over time, peaking at 18 years at a lower level than the peak for unburned plots.

##Colton, C. P., Coops, N. C., and Burton, C. 2021. Grizzly Bwar (Ursus arctos) responses to forest harvesting: A review of underlying mechanisms and management recommendations. Forest Ecology and Management 497: 119471.
  
This paper aimed to assess the use of harvested forest stands (< 40 years old) by grizzly bears. Many studies report use of these harvested forest stands, and some suggest a preference for them. Many elements influenced the response of grizzlies to these stands including: natural forest openings, cut block design, silviculture techniques, age since harvest, grizzly bear food availability, human activity and grizzly bear sex and age.

Coastal vs interior grizzly bears have different feeding patterns. On the coast, grizzlies predominately feed on salmon; in the interior, they predominately feed on berries and occur in burned and alpine and subalpine meadows. On the coast, bears also will eat berries, but to a lesser proportion; in interior BC, they feed on vegetative material in mature forests, sedge meadows, south facing avalanche slopes, and alpine and subalpine meadows before relocating to riparian areas for salmon in mid-summer to autumn.

Many changes to harvesting and silviculture practices from the 1950s to now, with two-pass forest harvesting, variable retention and large clearcuts (>800 ha) occurring most often today. Tree planting in harvested plots was not common until the 1990s.

Forest succession after clear cutting stages (4):
1. Stand initiation or Early Seral Forest Stage: species vigourously re-occupying space with abundant resources and low competition. Often provides a spring food source of grasses, forbs and roots and summer-autumn food sources of roots, herbs, amd berries for grizzly bears. The reduced canopy cover (<30%) in particular increases the abundance of huckleberries.
2. Canopy closure and Stem Exclusion: high mortality of understory and sub-dominant plants
3. Understory re-initiation: mature trees die, forming canopy gaps for mixed-age forest. Very little food source for bears.
4. Mature forest: provide ungulate prey, denning habitat, resting habitat, and some marginal foraging opportunities.

Grizzly bear density is positively related to non-forested areas.

'Selection' reflects an animal choosing to use a habitat, and 'preference' reflects the likelihood of an animal choosing to use a habitat if offered on an equal basis with other habitats.

Stratified by season: spring (hypophagia), summer (early hyperphagia) and autumn (hyperphagia). We may wish to assess seasonality like this too.
Researchers found evidence for cut block use all seasons, selection most consistent in summer and then autumn, with spring highly variable. Dominant ecological factor was the abundance of berries from shrubs (as well as roots, ants and other forage.
Avoidance was associated with accelerated re-growth (including post-harvest mechanical site prep, planting, seeding and herbicides), poor forage in cut blocks (from accelerated re-growth or salvage logging) and human presence.

Extremely variable results from different studies for grizzly bear preference, selection, avoidance and neutral for cutblocks across all seasons. Grizzly bears prefer natural openings, but will select clearcuts when natural openings are sparse, especially if human access is reduced. Grizzly bears prefer larger cutblocks to smaller ones, but are more often found near the forest edges. Forestry practices that maximize heterogeneity, security and cover, while considering human impacts (roads) are optimal. 

Silviculture: artificially accelerated cutblock re-growth can reduce grizzly bear forage. Scarification often damages shrub roots and reduces forage regrowth, resulting in grizzly bears not selecting these sites. Planting of trees can artificially enhance the speed of canopy closure which negatively impacts berry-producing shrubs. Herbicides accelerate forest regrowth and canopy closure, negatively impacting berry-producing shrubs. Pro-active thinning can lead to an increase in shrub biomass in regenerating forests.

Age since harvest: cut blocks in early seral forest stage preferred by bears. In some areas, this is 10-30 years after cutblock (and 20-40 years in others, with 19-20 optimal usage age), with lower usage before and after.

Riparian buffer zones had increased grizzly usage in Marine West Coast Forest (salmon abundant). Interior ecoregions, vegetative forage in cut blocks dominant driver of grizzly bear selection. Huckleberry fruit main driver (but also other berry-producing shrubs), which increase with reduced canopy cover.

Female grizzlies are more likely to use cutblocks, and males more likely to use natural openings (likely result of male dominance). 

Many of the above points are summarized well in Table 3 of paper.


##Prevey, J.S., Parker, L.E., Harringtn, C.A., Lamb, C.T. and Proctor, M.F. 2020. Climate change shifts in habitat suitability and phenology of huckleberry (Vaccinium membranaceum). Agricultural and Forest Meteorology, 280: 107803. 
In this paper, the authors predicted timing of flowering and fruit ripening for huckleberry for the current bioclimatic niche, and for future climate model projections under 2 different scenarios. Under these future projections, suitable habitat for huckleberry was predicted to shrink 5-40% across NW USA by the end of the 21st century (greatest reduction at lowest elevations), but increase of 5-60% at higher elevations and latitudes, and it was predicted that: (1) flowering would advance 23-50 days (mean 35 days), and (2) fruiting would advance 24-52 days (mean 36 days).

Study area extended from California to BC and east to Montana and Alberta.

Data: federal agencies, academic research projects, citizen science data, other publicly-available sources. Removed points located east of 96 ' W longitude (outside species range). Used 1-km grids for climate, using contemporary climate data and a downscaled global climate model.

Used presence-only maximum entropy models (do not have absence data). Extensive details provided on page 4 of paper. For phenology, calculated 'therma sums' (also known as growing-degree days).

See Table 2 for tested climatic variables and top variables, including Annual heat Moisture (AHM) Index, Climate Moisture Index (CMI), EMT, EXT, MAT, MCMT, MSP. Common theme with other papers: huckleberry is limited by winter temperatures, and habitat suitability likely to increase at higher elevations.

Earlier flowering = increased chance frost damage = decreased berry production. Phenology models did not account for timing of snowmelt, photoperiod, cold temperatures over winter, which may influence their phenology.

##Roberts, D.R., Neilsen, S.E., and Stenhouse, G.B. 2014. Idiosyncratic responses of grizzly bear habitat to climate change based on projected food resource changes. Ecological Applications 24(5): 1144-1154.
These authors project habitat changes for 17 species considered to be key grizzly bear food resources. They observed a general trend towards uphill migration for berry producing shrubs that grizzly bears feed on, which may result in increased vulnerability to bear populations at lower elevations and increased human-wildlife conflict.

Metrics often used to assess grizzly bear suitable habitat: land cover type, forest crown closure, slope, aspect, elevation, metrics for road density and urbanization. Metrics used here: climate variables, topography variables, forest crown closure. Nine metrics used: mean annual T, average winter T, average summer T, winter precip, summer precip, annual heat moisture, summer heat moisture, number frost free days, number degree days above 5'C. Topography: compound topographic index, topographic heat load index, general slope/aspect topographic radiation aspect (TRASP) index.

Future predictions: 300 m x 300 m resolution. Predicted climate and crown closure into the future. Areas of agricultural use, surface water, and high alpine rock and ice were removed from the species habitat projections.

Found huckleberry projected to increase by 84-112% by 2080. Most species predicted to maintain 94-100% of current habitat by 2080, but some predicted to lose much habitat. All species showed increase in elevation predicted, with one scenario predicting a median decrease of 203 m for huckleberry.

Huckleberry among the least affected species for elevational shifts. It's habitat range is predicted to remain stable with some additional increase in elevation for new habitat (but less increase than other species)- they mostly saw complete maintenance of present day range for huckleberry.

##Lamb, C.T., Mowat, G., McLellan, B.N., Nielsen, S.E., and Boutin, S. 2017. Forbidden fruit: human settlement and abundant fruit create an ecological trap for an apex omnivore.Journal of Animal Ecology, 86:55-65.
In this paper, the authors assess habitat suitability, human-influence, grizzly bear occurrence and grizzly bear mortality. They find that the valley within their study region, which was high in both berry resources and human density, was more attractive to bears than surrounding areas, despite 17% lower apparent survival in this same region. Despite lower fitness, the detected a net flow of bears into the ET (ecological trap), which contributed to a study-wide population decline.

In their study region, black huckleberry tends to ripen between AUgust 1 and September 15th, and buffalo berry tends to ripen between July 1 and August 15th.

The researchers created occurrence models for both fruiting shrub species (huckleberry and bufalloberry) using multivariate logistic regression (P/A) and occurrence records from 1779 vegetation plots (20 x 20 m) conducted within the study area, using climate, soil, topographic and fire variables. Data was separated into training (85%) and validation (15%) datasets. 

The best huckleberry model included: (1) percent of area burned, (2) percent sand, (3) average winter temperature, (4) precipitation as snow, (5) canopy cover, (6) average pH, (7) slope and (8) solar heat load. "The best buffaloberry model was similar to that found for huckleberry, but the summer climate better explained occurrence for this species. Huckleberry occurrence decreased with latitude, while buffaloberry was more evenly distributed (Fig. S1). Huckleberry and buffaloberry showed very little spatial overlap with <6% of berry occurrence cells containing both species."

Data acquisition: 
1. SOIL - Soil data was obtained from the BC Ministry of Environment (http://www.env.gov.bc.ca/esd/distdata/ecosystems/Soil_Data/SOIL_DATA_FGDB , more info in Lacelle 1990).
2. CLIMATE - Climate BC.
3. FIRE - Spatial information on forest fires was acquired from the Wildfire Management Branch of BC (data from 1920-2014) (https://apps.gov.bc.ca/pub/ geometadata/metadataDetail.do?from=search&edit=true&showall=showall&recordSet=ISO19115&recordUID=57060) and used to calculate time since last fire for each plot, and produce a time since last fire surface.  
4. CANOPY COVER - The authors gathered information on canopy cover from the Vegetation Resource Information data from the BC government and missing data was filled with cover information from industry partners.  
5. TOPOGRAPHY - The authors calculated global radiation, compound topographic index (CTI) and slope using a digital elevation model and ArcMap 10.1.

A note on canopy cover: "Canopy cover has been identified as an important driver of berry presence and production for both of these species (Minore 1984; Hamer 1996; Nielsen et al. 2004; Pengelly and Hamer 2014).  Of the studies we examined, nearly all berry production occurred at 50% canopy cover or less. Therefore, we applied a canopy cover rule where occurred sites with less than 50% canopy cover were considered to have fruit producing shrubs, while occurred sites with greater than 50% canopy cover were considered to have negligible fruit."

Peak fruiting- The authors collected Brix readings for huckleberry (Vaccinium membranaceum) and buffaloberry (Sheperdia canadiensis) from early July to early September 2014.BRIX is the sugar content of berries. One complication of using Brix values as measure of ripeness involves the general increase in brix values through the year, even when berries are post ripe.  As a result, we used the subjective ripeness information we collected to determine the range of brix values we could consider the berries as ripe for each species.  In general, the subjective rating for berries followed as such:
1.	Green
   a.	Green
   b.	Hard
   c.	Generally small
   d.	Little to no liquid to be extracted
2.	Mid Ripe 
   a.	Starting to change color
   b.	Becoming softer
   c.	mid size
   d.	Liquid can be extracted
3.	Ripe
   a.	Fully colored
   b.	Soft
   c.	Full size
   d.	Lots of liquid
4.	Post Ripe
   a.	Still fully colored, and full size, but,
   b.	Beginning to dessicate, signs of wrinkling
   c.	Liquid becoming scarce

##Proctor, M., Lamb, C.T., and MacHutchon, G. 2017. The grizzly dance between berries and bullets: relationships among bottom-up food resources and top-down mortality risk on grizzly bear populations in southeast British Columbia. Trans-border Grizzly Bear Project. Kaslo, BC, Canada.
In this report, the authors aim to create a huckleberry patch model that was more predictive than a generalized huckleberry occurrence model, and to assess the influences of bottom up and top-down processes.

The authors found that huckleberry patches were consistently the most influential predictor of habitat selection, density and fitness for grizzly bears. Mortality was best predicted by road density. Thus, both bottom up and top down impacts found.

The authors found that the top five predictors in the best huckleberry patch model were, in decreasing importance: 1) canopy cover, 2) coarse fragments in soil, 3) slope, 4) precipitation as snow in winter and, 5) average solar radiation. Overall, areas of low canopy cover, low angle slope, few coarse fragments in soil, north and east aspects, as well as high winter snow load produce huckleberry patches important to grizzly bears.

The authors also found that 74% of huckleberry patches were not in cut blocks. The ~26% of huckleberry patches that were in cut blocks occurred where the proportion of focal area in cut blocks was only 18%. Mean cut block age with huckleberry patches was ~40 yrs vs ~25 years for cut blocks without patches. They also found that planted cut blocks were less likely to have huckleberry patches. Slash burning didn’t increase the probability of a cut block yielding a huckleberry patch, it was slightly reduced. Fires (not slash burns) were ~3x more likely to yield a huckleberry patch than a cutblock. 

Huckleberry patches were more prevalent in the Englemann Spruce Sub-alpine Fir (ESSF) zone and in the wet mild subzones wm3, wm4, and wmw. Site series that favor huckleberry patches were 103 subxeric (dry), and to a lesser degree 101. Old forests (80-250 years old) and early seral stage dominated by shrubs dominated the structural stages with huckleberry patches.

Environmental variables hypothesized to limit the occurrence of huckleberry (Table 1) include soil pH (Barney 1999; Barney et al. 2006), soil texture (Habitat Management Branch Province of BC 2000; Barney et al. 2006), climate (Holden et al. 2012), forest fires (Nielsen and Nielsen 2010), canopy cover (Minore 1984) and topography (Roberts et al. 2014). For the huckleberry occurrence model, precipitation as snow dominated the variables for influence in our top huckleberry model followed by mean annual precipitation, canopy cover, maximum summer temperature and elevation in order of influence. For the huckleberry patches important to grizzly bear model, the top five predictors were, in decreasing importance: 1) canopy cover, 2) coarse fragments in soil, 3) slope, 4) precipitation as snow in winter, and 5) average annual radiation (Fig. 9). Areas of low canopy cover, low angle slope, few coarse fragments in soil, north and east aspects, as well as high winter snowload produce huckleberry patches important to grizzly bears. In other studies, growing-degree days across April to June and July temperature range explained 70% of the inter-annual variability in huckleberry productivity. 

Used Boosted Regression Trees (BRT) instead of standard GLMs. "BRT’s were well suited to our application as this method could handle the complex, nonlinear relationships we expected to find with these data, and BRT’s are known to provide greater predictive performance than GLM’s (Elith et al. 2006). In addition, compared to GLM’s, BRT’s do not face the same issues when fitting models with multicollinearity between predictors because trees are fit with recursive partitioning algorithms instead of matrix inversions (Shirley et al.2013). To fit the BRT we used the ‘gbm’ package (Ridgeway 2015) in Program R (R Core Team 2016). Another advantage of BRT’s is that a priori model definitions are not required. Instead BRT’s fit the meaningful ecological variables included to the data, and those variables that predict poorly do not affect results as these variables contribute very little to the model predictions. However, these variables that contribute little to model predictions can be removed from the model using a k-fold cross-validation and iteratively removing variables until an optimum is achieved."

Spatial projections of huckleberry models: Used a cut off from logistic regression values, wherein below that value represented an absense, and above a presence. The final value used for the cut-off was 0.48. Additional restrictions: if present, but canopy cover> 50%, thyen berry production set to 0.

Tested model fit with ROC AUC scores. Training data was 60% of total data and validation data was 40%. AUC > 0.7 considered a good fit.

Authors also explored how harvest cutblock techniques influenced huckleberry production, including  type of cutting, (i.e., clear cut, selective cut), planting, slash burning, time since disturbance, fire disturbed (not slash burned), shrub cover, herb cover, and canopy cover. They found that 74% of the patches were not in cutblocks, likely because they preferred elevations of 1500-2100 m which is above the operable harvesting elevation of 1800 m. Huckleberries were 3x more likely to occur in non-harvested sites that recently burned than in sites that did not recently burn. "While canopy cover <30% was the most predictive variable in huckleberry patches that grizzly bears use, there was no difference between cut blocks with or without huckleberry patches in mean canopy cover levels (p = 0.30). This suggests that while canopy cover is an important predictor of a huckleberry patch that grizzly bears use, opening the canopy does not necessarily result in a huckleberry patch. Twenty-six percent of areas predicted to have huckleberry patches important to grizzly bears were in a cut block, suggesting that timber harvest can contribute to the regional availability of huckleberry patches for grizzly bears. cut blocks that were planted post timber harvest were 80% less likely to yield a huckleberry patch. We suspect that planting hastens the return to canopy closure that is not conducive to a productive huckleberry patch. Slash burning post timber harvest did not appear to influence whether or not a cut block contained a huckleberry patch; slash burned cut blocks were slightly less likely to have a patch. There was no difference in % shrub cover between sites with and without huckleberry patches (p = 0.27) but herb cover was significantly less in sites with huckleberry patches (p < 0.001)." Results suggest that it may take 20-29 years before huckleberries return in logged sites compared to those not logged (Figure 29). They suggest that canopy cover <30% post-harvesting key for huckleberries for 40-50 years.

Some difficulties were experienced when trying to incorporate BEC zone and subzones, but ESSF seemed to be dominant BEC zone with huckleberries overall.

The authors recommend "that the timber industry test for huckleberry patch genesis in the areas we have identified as good future potential for huckleberry patches when the canopy is opened up (Figs. 21 & 30). [Their] map of important huckleberry patches should be incorporated into current logging planning cycles (or other land uses in the backcountry) to insure that road building and harvest plans be designed to not destroy or provide permanent access to important patches." They also suggest managing access to huckleberry patches and considering decommisioning and blocking off roads to retain high production patches of huckleberry for grizzly bears.


##Kearney, S.P., Coops, N.C., Stenhouse, G.B., Nielsen, S.E., Hermosilla, T., White, J.C., and Wulder, M.A. 2019. Grizzly bear selection of recently harvested forests is dependent on forest recovery rate and landscape composition. Forest Ecology and Management 440: 117459.
Overview of results: Grizzly bears were three times more likely to select for recently harvested sites if natural disturbance sites were sparse (compared to undisturbed sites). When natural disturbances were abundant, then neutral selection harvested vs natural. Selection for harvested sites decreased sharply 15-20 years after harvest. They were also more likely to use the logged areas in summer and fall when natural disturbances were few; but less likely in spring and fall and more likely in summer when natural disturbances were abundant.

Previous studies have found or suggested that grizzly bears predominately utilize early-seral forests regenerating after disturbance (natural, logging) because of their association with increased bear food resources. Homogeneous undisturbed forest habitats have been shown to contain fewer bear food (e.g., berries), and subsequent avoidance by grizzly bears. With suppression of wildfire and increased harvesting (often with planting), harvesting has become the predominant disturbance in interior mountain regions of North America. 

Many studies have shown contrasting results: avoidance, neutral and selection for harvested sites by grizzly bears, but most neglect to consider nearby natural disturbance availability. Here, the authors used spectral analysis from Landsat satellite time series since 1984 (33 years) plus telemetry data (415,000 locations of 160 individual grizzly bears).

Favourable vegetation metrics and greenness values fell after 15-20 years in harvested plots, which coincided with reduced use by grizzly bears. In burned areas, vegetation metrics remained below preferred range for 5-10 years, but then generally remained within in (something missing here to complete thought...).

These authors cite literature that demonstrate that several berry species (such as huckleberry) have been negatively associated with cutblocks, except at forest edge, But these shrubs often thrive where fires have occurred. The authors suggest that high use in the summer can coincide with forb and grass consumption. In respect to time, cutblocks shown to be favoured on short-term (<20 years), but areas affected by wildfire more so in medium term (10-30 years). Nielsen et al 2004 found: prob use highest for cutblocks ages 20-40 during hypophagia and greater than 35 years in hyperphagia. Canopy closure happens more quickly in harvested areas than those affected by fires, likely in part from planting (partially because forest regeneration after harvest is mandated by law in Canada).

This paper talks about the effects of mechanical disturbance (i.e., scarification), but also the impacts of herbicide application. Mechanical disturbance and high canopy closure are negatively associated with roots, berries and ungulates - food sources important during hypophagia and hyperphagia; suggesting that clearcuts may favour sources good during mesophagia.

Authors suggest that no one has investigated impacts of silvilculture management practices on grizzly bear food abundance and habitat selection. Authors recommend that controlled burns could be conducted away from forestry roads to make more favourable for bears. They also suggest avoiding salvage logging and subsequent replanting after low-intensity fires, and to reduce or delay regeneration efforts after harvesting.


##Hertel et al. 2016. Bears and berries: species-specific selective foraging on a patchily distributed food resource in a human-altered landscape. Behav Ecol Sociobiol 70:831–842.
During the peak berry season in August and September, these authors sampled berry occurrence, abundance, and sugar content, a proxy for quality, at locations selected by bears for foraging and at random locations in the landscape. Many berries were found to influence grizzly bear selection. Forestry practices had a large effect on berry occurrence and abundance, and brown bears responded by foraging most selectively in mature forests and on clearcuts. Particular selection for clearcuts in the fall in this region with few natural openings in mature forests (i.e., during hyperphagia) in Sweden.

Methods of use: "[Authors] analyzed the number of ripe bilberries, lingonberries, and crowberries at a given site separately. Because our berry count data were zero-inflated and overdispersed, we modeled berry occurrence and abundance separately with negative binomial hurdle models (Zeileis et al. 2008). Hurdle models treat the data in two separate ways. First, a binomial model identifies which factors affect the occurrence of berries at a given site (value 1 for all plots with 1 or more ripe berries) compared to plots with no berry occurrence (i.e., plots with zero berries). Second, a zero-truncated negative binomial model identifies which factors influence the abundance of berries, once they are present in a plot (value of berry count for all plots with 1 or more counts) (Ridout et al. 1998; Potts and Elith 2006). The underlying assumption of these models is that zero observations are true negatives (e.g., not due to sampling or observer error). We used the glmmADMB package (Fournier et al. 2012; Skaug et al. 2013) to fit the zero-truncated part of the mixed-effects hurdle model and the lme4 package (Bates et al. 2014) to fit the binomial part. We based model selection on a stepwise backward model selection, removing nonsignificant covariates or interactions one at a time and comparing full and reduced models with likelihood ratio tests (LRs)."

Sugar methods: "We determined the sugar content in the juice of a random subsample of five ripe berries. Total soluble solids (TSS), which is the combination of sucrose, fructose, glucose, were measured in %Brix (percentage of sugar in an aqueous solution; 1 %Brix≌1 g sucrose in 100 g sucrose water solution)." Results: "Sugar content decreased with increasing NDVI, elevation, and as the season progressed. Post hoc multiple comparisons of means showed that berries on clearcuts contained more sugar than berries in mature forests."


##Nielsen, S.E., Boyce, M.S., and Stenhouse, G.B. 2004. Grizzly bears and forestry: I. Selection of clearcuts by grizzly bears in west-central Alberta, Canada. Forest Ecology and Management, 199: 51-65.
These authors found, using telemetry data, that grizzly bears used cutblocks as available during hypophagia and late hyperphagia,  and selected clearcuts more than expected during early hyperphagia. Grizzly bear's avoided centres of clearcuts and selected those with greater perimeter-to-edge ratios. They also used them more often during crepuscular/nocturnal periods. During hypophagia, selected for intermediate aged clearcuts (~30 years); during late hyperphagia, selected recent and old clearcuts. They also found some effects by difference in site prep.

High quality grizzly habitat: roadless areas, with mosaic of early seral-staged forests and natural openings in proximity to secure forest beds for day beds and hiding cover. Suppression of fires is a major threat, and widespread succession without further disturbance has led to grizzly bear population declines. At time of this publication, most prior studies had shown widespread avoidance of clearcuts. These authors indicate that in most prior studies, however, natural clearcuts were not limiting.

Clearcut metrics included: clearcut year, size, site prep/scarification method and silviculture (see Table 4). Also assessed elevation, distance to clearcut edge, area-to-perimeter ratio, soil wetness from compound topographic index (CTI), solar radiation (see Table 2).

Found: grizzly bears selected clearcuts based on availability during hypophagia and late hyperphagia, but selected for clearcuts more often during early hyperphagia. During hypophagia, selected intermediate aged (~30 years) clearcuts, and selected for areas of low solar radiation. For scarification, some types of mechanical prep were selected for, and others selected against. Early hyperphagia: areas with higher solar radiation selected. Late hyperphagia: preferred clearcuts with irregular shape that were young or old (up to 46 years); negative relationship with distance to edge wherein they used space closer to edges; mechanial treatments has some positive and other negative correlations; no influence of silviculture techniques. Grizzly bears most often used clearcuts during crepuscular/nocturnal periods as opposed to diurnal.

##Nielsen, S.E., Munro, R.H.M., Bainbridge, E.L., Stenhouse, G.B., and Boyce, M.S. 2004. Grizzly Bears and Forestry II. Distribution of grizzly bear foods in clearcuts of west-central Alberta, canada. Forest Ecology and Management 199: 67-82.
These authors assessed the impacts of clearcuts on 13 grizzly bear foods in Alberta, making comparisons between clearcuts and adjacent forested site. Mechanical scarification negatively impacted S. canadensis (buffalo berry), but not huckleberry. Age of clearcut and canopy cover were strongly correlated with most foods. Patterns of fruit occurrence were related to canopy cover. Plant occurrence lower in clearcuts than forests for huckleberry, with no difference for buffalo berry. Fruit occurrence was greater in clearcuts than forest for huckleberry, but not so for other species like buffalo berry. 

Key factors investigated: scarification, canopy cover, clearcut age and terrain characteristics. Separated scarified into yes/no (0/1). Used elevation, CTI (soil wetness metric the Compound Topographic Index), the slope-aspect index (SAI = sin(aspect +225) x (slope/45) - note, max slope was 45 degrees here).

Separated data into 85% testing set and 15% validation set, and used logistic regression models to model occurrence of 13 foods. Tested for colinerariy with Pearson's correlation tests. All factors r >= |0.6| and individual VIF scores >10 assumed colinear and not included in same model structure together. Here, they found that age and canopy cover were colinear (r = 0.66) and were not included together. Assessed model accuracy and merit using AIC, AUC and PCC (Percent Correctly Assigned with cut-off values as 0/1, and >70% being reasonably predictive).

Fruit distribution was assessed with a conditional model, using only those sites where the plant species was present and logistic regression (lacked fruit production during fruiting period vs had fruits). Fruit productivity modelled two ways: (1) conditional where plant occurred, and (2) all sites regardless. 

Modelling distribution plants: buffalo berry had good fit; huckleberry models did not.
Modelling distribution fruits: huckleberry at intermediate canopy cover (34%), and buffalo berry at low canopy cover (0%). Fruit production similar in clearcuts and forest for species of interest. For SAI, huckleberry and buffalo berry appear at opposite ends of the distribution. Indicate that previous work shows buffalo berry more common in early seral or open forests.

##McClelland, C.J.R., Coops, N.C., Kearney, S.P., Burton, A.C., Nielsen, S.E., and Stenhouse, G.B. 2020. Variations in grizzly bear habitat selection in relation to the daily and seasonal availability of annual plant-food resources. Ecological Informatics, 58: 101116. 
In this paper, authors assessed seasonal availability of plant food-species at 30 m resolution and compared with grizzly bear GPS collar data. grizzly bears selected areas where key food sources were available. In dry spring conditions, they selected for root species and occurred earlier than in wet spring years. In wet summers, selection for forb species prolonged. In dry fall, selection for berry species longest.

Early season precipitation in other studies has shown later fruiting in berry-producing shrubs because pollinators were deterred in early season. Phenology has shifted to being several days earlier since 2000 to now - in boreal, 0.23-0.28 days per year advancement 2000 to 2014; in Western Canada, advancement of 0.78 days/year from 2000 to 2018. Both bears and berries are shifting earlier in phenology - buffaloberry is shifting earlier in Alberta for example. Authors predict selection for roots and berries in dry years, and for forbs in wet years. Developed SDMs for 8 food sources and couple with GPS collar data.

Methods: very interesting! Use MODIS and Landsat EVI data and fuse them through Dynamic Time Warping to produce daily 30 m EVI products (Daily Remote Inference of VEgetation - DRIVE). DRIVE is a new approach to estimate phenology curves which can be split to determine phases of green up and senescence. From this, extracted Start of Availability (SOA) and End of Availability (EOA). Availability layers used in GLMMs with logistic regression. Climate variables acquired from ClimateNA, and created a distance to road metric using Alberta road data. Land cover classified (e.g., bryoids, broadleaf, coniferous, herbs, mixed wood, shrubland). Topographic variables: slope, aspect, elevation, insolation, Topographic Position Index (TPI), Topographic Wetness Index (TWI). Distance to forest edge. Use Maximum Entropy models (MAXENT) - requires presence only data. Used bootstraping to randomly sample training and validation datasets 100 times for each species. Used AUC values to assess: 0.5-0.75 indicate poor model performance (although many other authors 0.7 as cutoff), 0.7-0.9 good performance, 0.9+ high performance.

They suggest that mean annual precipitation is the key variable dictating timing of plant foods for grizzly bears.

##McClelland, C.J.R., Denny, C.K., Larsen, T.A., Stenhouse, G.B., Nielsen, S.E. 2021. Landscape estimates of carrying capacity for grizzly bears using nutritional energy supply for management and conservation planning. Journal of Nature Conservation, 62: 126018.
These authors estimated carrying capacity for grizzlies given abundance of vegetation (roots, fruits, herbs), insects (ants), and ungulates. They also converted data into digestable kilocalories and compared models that predicted bear densities at carrying capacity for all 5 categories together, and for just fruit and meat model. Both models resulted in similar results, suggesting that roots, herbs and insects are less limiting. Estimates can be applied to known densities, and this is further correlated with road densities to assess top-down mortality factors that may limit grizzly bear populations.

Excellent data available. Sites in Alberta, and they have a 16-year dataset of 4663 plots wherein distribution (P/A) and abundance (percent cover or count) was recorded for 19 food species, and standardized by area. Environmental variables: climate, terrain and land cover; forest structure, forest composition, land cover, terrain, soil composition/moisture, wildfire and forest harvest history, and climate variables.

Modelled data with stepwise regression on a logistic regression model. To model plant abundance, they used logit-transformed percent cover data (to bound between 0 and 1). Modelled non-transformed fruit and ant density using negative binomial regression, and included abundance as a fixed effect factor because fruit abundance should scale by plant abundance. The used 10-fold cross validation and assessed AUC.

Kilocalorie estimates: created rasters by food group. Determined fruit and ant biomass from model coefficients and dried weight measurements. GLMMs developed for estimates and values also estimated from Lopez-Alfaro et al. 2015. 

Herbs and fruit accounted for the majority of digestible kilocalories.

Here, they were able to estimate carrying capacity for bears using just fruit and meat layers, which would be cool to do if we have for sufficient berry producing species and meat species (e.g., moose, caribou, deer). We could then predict carrying capacity across a changing landscape. Roads, however, keep populations below carrying capacity - so distance to roads also need to be incorporated.

##Souliere, C.M., Coogan, S.C.P., Stenhouse, G.B., and Nielsen, S.E. 2020. Harvested forests as a surrogate to wildfires in relation to grizzly bear food-supply in west-central Alberta. Forest Ecology and Management, 456: 117685.
The authors in this paper highlight that grizzly bears prefer early seral vegetation, which can occur after forest fires and clearcutting. They explore whether harvested areas can actually act as sufficient surrogates to wildfires for grizzly bears in terms of food supply in west-central Alberta (where stand-replacing fires are uncommon). Their findings suggest that harvested plots can act as surrogates for wildfires, with access for humans by roads being a complication that needs to be considered. They found that forb production was best in very young (~5 years) harvested stands, and that berry productivity and digestible energy was highest in the young age class (~20 years).

Other studies have found that grizzly bear body size and condition is positively correlated with forestry disturbance and food resource abundance. They assessed 33 plots (within mature, harvested and burned plots of 5 and 20 years disturbance) for plant and ant occurrence within 50 x 20 m belt transects. They then estimated the abundance of 13 berry-producing shrubs and 4 forb species in a 50m x 2 m belt transect. They also recorded sweetvetch and ungulate pellet occurrence but sample size was too low to analyze. They estimated fruit energy from fruit count and approximating fruit mass from the literature. They present an equation for estimating digestible energy using these metrics.

Comparing Odds ratios, huckleberry was equally likely in post-burn and post-harvest stands for very young stands (~5 years), failed to converge at young stands (~20 years) and more common in post-harvest stands in 80 year old stands. For buffaloberry, failed to converge ~5 years, coefficient 0.4 showing slightly more in harvested stand at 20 years, and more common in post-fire stands at 80 years. Top ranked models for huckleberry and buffaloberry includes disturbance age. Buffaloberry peaked at mid-levels for canopy cover, whereas most other species peaked at lower canopy cover. Fruit per hectare was highest in harvested plots of ~20 years. Fruit digestibility was also highest at ~20 year aged stands for both post-harvest and post-fire plots (with no difference between these 2 conditions). Total digestible energy (forbs, ants and fruit) was highest in post-fire stands aged 5-20 years. Has be hypotheized by previous papers that scarification can reduce huckleberry in <25 year old stands because of damage to rhizomes (Martin 1983).

##Stewart, B.P., Nelson, T.A., Wulder, M.A., Nielsen, S.E., and Stenhouse, G. 2012. Impact of disturbance characteristics and age on grizzly bear habitat selection. Applied Geography, 34: 614-625.
These authors used a four-decade remotely sensed disturbance history and telemetry data for 22 adult grizzly bears from 2005-2009 in Canadian Rockies. They found that male bears tended to select for disturbed sites that were 30-40 years old more frequently than younger stands, whereas females showed equal selection for all ages of disturbed sites except those <10 years. Females selected for disturbances summer/fall > spring. Male bears showed other seasons > fall.  Both sexes selected for larger disturbances at all ages.

##Holden, Z.A., Kasworm, W.F., Servheen, C., Hahn, B., Dobrowski, S. 2012. Sensitivity of berry productivity to climatic variation in the Cabinet-Yaak Grizzly Bear Recovery Zone, Northwest United States, 1989-2010. Wildlife Society Bulletin, DOI: 10.1002/wsb.128.
These authors investigated annual berry productivity in huckleberry and serviceberry from 1989 to 2010, looking at temperature, precipitation and snow indices. They found that huckleberry production was highest during cool springs, with high diurnal July temperature ranges. April-June growing degree days and July temp range explained 70% of interannual variation. 

Intro: Huckleberries make up to 10% grizzly diet in their region. Serviceberry valuable food for ungulates, especially the bark from it in the winter. Beavers and snowshoe hares also consume. Huckleberry requires high levels of sunlight to produce berries, and respond favourably to disturbance and open-stand characteristics. Regional climatic variation key in predicting huckleberry production.

Variables: snow-free date, number of snow-free days, maximum snow-water equivalent (SWE) and monthly and seasonal cumulative precipitation. Monthly mean and cumulative minimum and maximum temperatures, seasonal temperature metrics, and growing-degree days above 18 C and 5 C (GDD1 and GDD5) were calculated using daily minimum and maximum temperatures for each station. For huckleberry, best explanatory variables were growing degree days above 5'C and July temperature range. Suggest that solar radiation important, as it relates to photosynthesis capabilities.

They suggest that warmer spring temperatures could lead to lower huckleberry production. They also suggest that early snowmelt can result in decreased plant-available summer moisture, and this might be the link we have observed between PAS and production.

##Krebs, C.J., Boonstra, R., Cowcill, K., and Kenney, A.J. 2009. Climatic determinants of berry crops in the boreal forest of the southwestern Yukon. Botany, 87: 401-408.
Assessed multiple berry species, including huckleberry (40 cm x 40 cm quadrat) and buffaloberry (2 tagged twigs) over 12 years. Most common predictors were the rainfall and temperature from t-1 and t-2 timeframes! suggest that both years prior need to be good years to get a bumper crop (test interaction between two years). Flowering primordia are set in year t-1.

Included minimum temperature from May 15-30 to account for possible bud damage.

July rainfall was most powerful estimate for buffaloberry (of year t-1) for berry counts. Huckleberry: best models had rainfall in May ot t, t-1 and t-2. "Moreover, aggregated climatic variables like mean summer temperature or total summer rainfall were of little use in predicting future berry crops, and monthly averages were needed, a reflection of the lack of
correlation among summer weather measures".

*Get measures for spring frost and growing degree days (May)

##Krebs, C.J., Cowcill, K., Boonstra, R., and Kenney, A.J., 2010. Do changes in berry crops drive population fluctuations in small rodents in the southwestern Yukon? Journal of Mammalogy, 91(2): 500-509.
This paper looks at how the abundance of 6 different shrub and herb species, mushrooms and white spruce seeds impact the survival of 3 rodent species. They found that the production of these crops in year t influenced rodent densities in years t+1.

##Spencer, M., Willsey, T., Berg, K., and Anderson, J. 2020. A literature review for the western science state of knowledge for huckleberries.
"Black huckleberry populations are under pressure in the Kootenay region due to many factors, particularly fire suppression, backcountry road construction, commercial forestry, recreational and commercial berry harvesting and climate change." --> brings up a question of whether we want to include a metric of human access, like logging road densities. But I think it is better to keep that out of this model for now.

Objective: "To summarize the environmental conditions that may influence huckleberry patch productivity (including elevation, slope/aspect, canopy cover, forestry practices, fire regime, harvest, climate change)"

BEC Zones: ESSF** (best), ICH (next best), MS and IDF in Kootenays.

"Abundance is also associated with areas of moderate to high snowfall as deep snowpacks insulate plants from extreme cold and desiccation by heavy winter frosts (Haeussler and Coates, 1986; Proctor et al., 2017)."

"Similar to other Vaccinium species, black huckleberry favours moist, well-drained, and acidic soil that is high in organic matter and low in calcium and available nutrients (Barney et al., 2006)."

"Black huckleberry is tolerant of a range of soil textures, from loamy sands to clay loams, but is most productive in soils with low bulk densities and high water-holding capacity (Barney et al., 2006). Compacted, heavy-textured, and poorly-draining soils are associated with poor survival and productivity, due to restricted growth of roots and rhizomes. A soil pH of 5.5 is optimal for black huckleberry productivity (Minore and Dubrasich, 1978)." 

"Huckleberry is considered an indicator of nitrogen-poor sites (Cocksedge et al., 2009), but will grow within a broad range of soil nutrient profiles (Barney et al., 2006)."

"Black huckleberry abundance increases with both elevation (to 1,200 m) and continentality in B.C. (Cocksedge et al., 2009)." 400-800 m elevation on coast; generally absent below 1200 m (drier) regions of interior. Most likely 1500-2000 in Kootenays.

"Black huckleberry establishes well on moderately steep slopes (25-40%) (Martin, 1979; 1980)."

"Black huckleberry is a dominant understory species in all stages of forest succession and can be found in both shaded old-growth forests and in cleared areas with full sun exposure (Anzinger, 2002). Canopy cover <30% has been identified as the most important factor associated with huckleberry patches important to grizzly bears (Proctor et al., 2017), and MacHutchon (2017) determined that an open canopy is likely more important to patch development and berry production than forest structural stage."

"Huckleberry produces extensive rhizome networks and reproduction primarily occurs vegetatively from adventitious shoots on its rhizomes and root crowns (Simonin, 2000). Vigorous rhizomatous regeneration occurs following disturbances such as fire or logging, allowing huckleberry to dominate early seral shrub communities (Martin, 1979; Anzinger, 2002). 20% canopy closure has been reported as ideal for berry production (Keefer, 2011), with a decline in productivity observed at >30% canopy cover (Martin, 1979; 1980)."

"Huckleberry roots may penetrate as deep as 1 m below the soil surface, but rhizomes are typically present in top 8-30 cm of the soil profile (Minore, 1975). Low intensity fires that do not destroy organic soil horizons leave rhizome networks intact, and vigorous sprouting of rhizomes occurs following light surface fires (Minore, 1975; Mah, 2000). Under optimal conditions, emerging shoots have been observed in as few as 15 days following a burn (Martin, 1979)." Fire also helps inhibit dense forest canopy. "In the East Kootenay region, the most productive contemporary sites are those with a history of logging and broadcasting burning (Hobby and Keefer, 2010)."

"Huckleberry patch regeneration in cut-blocks depends on the presence of several cumulative site characteristics (soil, ecological, climate, and topographic conditions), combined with an open canopy (Proctor et al., 2017). Martin (1980) found that the primary factors determining fruit production in clearcuts were canopy cover, site aspect and silvicultural post-timber treatment practices... On xeric aspects, canopy removal may decrease productivity due to moisture stress (Martin, 1979). Proctor et al. (2017) found that planted cut blocks were less likely to support huckleberry patches, likely due to increased canopy cover. Post-timber mechanical site preparation is destructive to huckleberry rhizomes and has been associated with significant reductions in the cover and productivity of regenerating patches (Martin, 1980; Keefer, 2011)."

"For instance, increased tree cover provides refuge for black bears, which may have negative impacts on grizzly bear population dynamics due to increased competition for huckleberries (Mowat, G., Large Carnivore Specialist, Wildlife and Habitat Branch, B.C. Ministry of FLNRORD, pers. comm., April 2020)."

"Other management recommendations to preserve huckleberry patches include minimizing disturbance to the forest floor by logging on winter snowpacks, limiting road density and restricting access to areas supporting productive huckleberry patches, implementing selective logging and prescribed burns to maintain and regenerate existing patches, and limiting fire suppression in remote areas (Proctor et al., 2017)."

Climate: "In the northwestern U.S., the range of huckleberry is expected to shrink by 5-40% by the end of the century, whereas habitat at altitudes > 3,050 m and boreal ecosystems in northern B.C. are expected to increase by 5-60%. In addition to predicted range shifts, phenology models predict that flowering and fruiting may occur 11-52 days earlier by the end of the 21st century (Prevéy et al., 2020)... the risk of late frost events may not change despite warmer spring temperatures (Richardson et al., 2018). Holden et al. (2012) found a negative correlation between monthly spring (April-June) temperatures and huckleberry productivity, which can likely be attributed to a combination of frost damage to early-flowering plants and a declining snowpack leading to summer moisture deficits."

"Forest management practices: The response of black huckleberry to forest management practices is variable and appears to be highly dependent on site-specific characteristics (Kerns et al., 2004; Keefer, 2011; Proctor et al., 2017). The extent to which timber harvest can mimic natural disturbance regimes and facilitate the generation of productive huckleberry patches requires more research (Proctor et al., 2017). Commercial forest practices such as mechanical site preparation and post-logging planting can negatively impact huckleberry patches (Martin, 1980; Keefer, 2011), and it is not yet clear if the ecological requirements for productive huckleberry patches can be balanced with a profitable timer industry (Proctor et al., 2017). Experimentation with post-timber site-preparation techniques (e.g. brushing, mechanical site preparation, broadcast burning) and re-planting intervals will be useful in addressing this knowledge gap."

"Proctor et al. (2017) developed a model associating geophysical, ecological, soil, climate, and topographical variables with huckleberry patches known to be used by bears. Their huckleberry patch model found that the most important predictors for patches utilized by grizzly bears were low canopy cover, low coarse fragment content in soil, low slope angle, high winter snowpack, and a cool (north–east) aspect (Proctor et al., 2017). In addition, they found that cut blocks were a poor predictor for huckleberry patches, as was slash burning, whereas fires other than slash burning increased the probability of huckleberry patch establishment."

Holden et al. (2012): "Low spring temperatures and high diurnal ranges in July were found to be important predictors of huckleberry production, whereas precipitation and snowpack were found to be less important for productivity in this region."

Prevey et al. 2020: "Briefly, habitat in lower elevation regions of the current range of huckleberry patches are predicted to shrink, whereas habitat suitability is expected to increase at higher elevations and northern latitudes. This shift in range is expected to be accompanied by an average advancement of flowering and fruiting time of approximately 35 days."

"Soil characteristics, elevation, slope, and aspect greatly influence black huckleberry growth and productivity. Black huckleberry is most productive in soils with low bulk densities and high water-holding capacities, and in the Kootenay region huckleberry abundance is highest in areas of neutral to acid bedrock. Black huckleberry establishes well on moderately steep slopes (25-40%) and its abundance generally increases with elevation up to 1,200 m."

##Martin, P. 1980. Factors influencing globe huckleberry fruit production in Northwestern Montana. Int. Conf. Bear Res. and Management 5: 159-165. 
This author investigated the impacts of wildfires, harvesting techniques and physical and vegetation site characteristics on huckleberry production, an important food source for grizzly bears. They found that timber stands that were not disturbed in the last 60 years had low production. The most productive sites were those that experienced wildfire 25-60 years ago, or clearcut and broadcast burned 8-15 years ago. Scarification on any aspects reduced huckleberry production. Fruit production was not related to the percent cover or height of the huckleberry plants.

**When looking at berry production, include physical plant characteristics as covariates.

"Scarification apparently destroyed the rhizomes of the huckleberry shrubs and thus prevented vegetative propagation. Since seedling propagation of huckleberries is extremely rare in western Montana (P. Stickney, For. Sci. Lab., Missoula, Mont., pers. comm.), widespread rhizome destruction reduces the percent cover of huckleberry plants."

Plots burned after harvest were productive earlier than those burned in wildfire. "Perhaps the fire was less intense, and the depth of rhizome destruction less extensive."

When berry density increased, so did berry volume. Canopy cover cut-off for drop in berry production was 30%. Fruit production was low on both steep and gentle slopes, but with a minimal relationship overall. 

##Anderson, N.J. 1994. Grizzly bear food production on clearcuts within the western and northwestern Yellowstone ecosystem. Thesis, University of Montana.
Anderson found some opposite patterns in Yellowstone as other researchers have found more locally. Namely, he observed that huckleberries were more abundant in undisturbed forest patches than in clearcuts, and that shrub density increased with successional age. Likely different canopy and forest characteristics.

##Notes from Vacc mem Lit review_Mar_31_21
Martin (1980) found that the primary factors determining fruit production in clearcuts were canopy cover, site aspect and silvicultural post-timber treatment practices. 

Proctor et al. (2017) found that planted cut blocks were less likely to support huckleberry patches, likely due to increased canopy cover. 

Additionally, berries produced in shaded areas are reported as being less sweet than those grown in open sun, which further discourages foraging by bears (Mowat et al., 2017).

Post-timber mechanical site preparation is destructive to huckleberry rhizomes and has been associated with significant reductions in the cover and productivity of regenerating patches (Martin, 1980; Keefer, 2011).

In contrast, huckleberry in patches on mesic aspects that are broadcast-burned after timber harvesting can return to post-disturbance cover and productivity within 8-15 years (Martin 1980). 

Other management recommendations to preserve huckleberry patches include minimizing disturbance to the forest floor by logging on winter snowpacks, limiting road density and restricting access to areas supporting productive huckleberry patches, implementing selective logging and prescribed burns to maintain and regenerate existing patches, and limiting fire suppression in remote areas (Proctor et al., 2017).

Burton 1998: Fruit production in Vaccinium was higher at any light levels greater than 60% relative irradiance. The size and sugar content of Vaccinium berries bore no relationship to light intensity...   These results suggest that partial cutting would be better than clear-cut logging for promoting the highest populations of these shrub species... completely open (clear-cut) conditions are not likely detrimental to growth and berry production. Peak productivity was noted in a plot receiving 75% global irradiance, while the best fitting parabolic function predicts maximum performance at approximately 90% irradiance. We also found that fruit density and productivity in Vaccinium were more sensitive to soil moisture conditions than to canopy conditions 

##Keefer, M., Cocksedge, W., Munro, R., Meuleman, J., and MacPherson, N. 2010. What about the berries? Managing for understory species. The Centre for Livelihoods and Ecology.
There is a lack of policy around managing non-timber forest products (NTFPs). Some First Nations and logging companies have made their own informal policies. There is a need for more guidance. "With lack of provincial regulations on these species, there is great concern over the maintenance and protection of both the species and their habitat."

"Forest understory species contribute to biological diversity and long-term ecosystem productivity (Alaback and Herman 1988; Halpern and Spies 1995), are well correlated with mammalian and avian abundance (Carey 1995; Carey and Johnson 1995; Morrison 1982), and are important for wildlife, contributing browse, berries, and cover (Willams et al. 1980; Bunnell and Hamilton 1983; Campbell and Johnson 1983; Kasworm et al. 1984; Noyce and Coy 1990; Tirmenstein 1990 a & b; McLellan and Hovey 1995; Riddell 2005). These plant species can also contribute to fuel reduction treatments and in ecosystem restoration (Monsen et al. 2004)."

"High density planting or mechanical scarification may decrease the abundance and quality of some species, particularly in the short-term (Haeussler et al. 2002; Minore 1984). Such disturbances can also propagate invasive plants that may impede the re-establishment of valuable plants. Other silvicultural practices, such as broadcast burns (depending on timing and intensity), spacing, and pruning may enhance berry habitat for some species (Kerns et al. 2002; Johnson 1999; Halpern and Spies 1995; Minore 1975; Burton 1998)."

"Increasing extremes such as late frosts and drought can result in decreased berry production in habitats that would otherwise have provided abundant crops."

"Low intensity fires (Turner 1991) which could also assist with issues of fuel loading. Highly analogous treatments have been occurring in the East Kootenay through the Ministry of Forests and Range Ecosystem Restoration Program. The program is using prescribed fire to enhance wild plants in their natural ecosystems."

"Competition with timber growth has led to practices of enhancing timber production at the expense of (i.e. the removal of) understory species. Although the goal was not to reduce berry production per se, inevitably that would happen when the vegetation management program was effective. Simply increasing the awareness of important NTFP species, and including these within management considerations, may decrease the negative effects due to timber management practices."

"Silviculture regimes, such as clearcuts, partial cuts, shelterwoods, patch clearcut, single-tree selection, etc., can be carried out in conjunction with NTFP stand management regimes. The question to forest managers is the implication to growth and yield and to stand establishment. How the two growth and yield metrics (timber and NTFP) interact is still in the early stages of research, especially considering the substantial suite of variables, including the broad number of species identified as cultural or NTFP use and the lack of substantial autecological information on many of these species (Clason et al. 2008; Haeussler et al. 2002)."

"For example, if a woodlot manager wished to commercially thin a 50 year old coastal Douglas-fir stand down to 60% of the original basal area in order to realize the interim economic value from thinning, increase mean log diameter, and increase sunlight penetration to enhance salal foliage production for commercial harvest, then the manager could use available growth and yield models, such as TIPSY (Table Interpolation Program for Stand Yields) and VDYP (Variable Density Yield Prediction system) to estimate the effects on the value of the timber."

##Pigeon, K.E., Cardinal, E., Stenhouse, G.B., and Cote, S.D. 2016. Staying cool in a changing landscape: the influence of maximum daily temperature on grizzyl bear habitat selection. Oecologia, DOI 10.1007/s00442-016-3630-5.
In this paper, the authors investigated the influences of ambient temperature on grizzly bear behaviour, and associated conditions with cutblocks vs. mature forest. They found that "cutblocks aged 0–20 years provided an abundance of forage but were on average 6 °C warmer than mature conifer stands and 21- to 40-year-old cutblocks. When ambient temperatures increased, the relative change (odds ratio) in the probability of selection for 0- to 20-year-old cutblocks decreased during the hottest part of the day and increased during cooler periods, especially for males. Concurrently, the probability of selection for 21- to 40-year-old cutblocks increased on warmer days."

##Pigeon, K.E., Stenhouse, G., and Cote, S.D. 2016: Drivers of hibernation: linking food and weather to denning behaviour of grizzyl bears. Behavioural Ecology and Sociobiology, 70: 1745-1754.
These authors assessed timing if grizzly bear den entry and exit according to sex, reproductive status, berry abundance and weather variables. They found that den entry was linked to food availability (39%), with delayed entry if there were abundant berries in the fall, and den exit was dictated by weather, with warmer springs (26%) and less snow (winter precip; 21%) resulting in earlier exit. Den exit dates also were explained by sex (22%) and reproductive status (14%). This combination may result in shorter denning periods if warmer temperatures result in longer growing seasons. The spring temperature is likely linked to temperature within den that stimulates early exit. "Climate-induced changes in the hibernation behaviour of bears may further increase human-bear interactions because bears and humans could be simultaneously active on the landscape for longer periods associated with unseasonably warm springs or autumns expected with future climate conditions."

##Chandeler, J.R., Haeussler, S., Hamilton, E.H., Feller, M., Bradfield, G., and Simard, S.w. 2017. Twenty years of ecosystem response after clearcutting and slashburning in conifer forests of central British Columbia, Canada. PLOS One, 12(2): e0172667.doi:10.1371/journal.pone.0172667
These authors recorded vascular plant cover repeatedly after treatment (clearcut logging, prescribed burning and reforestation) between 1981 and 2008 in 16 permanent research installations in three biogeoclimatic zones: Engelmann Spruce-Subalpine Fir, Interior Cedar-Hemlock and Sub-Boreal Spruce. They grouped plant species from 181 recorded species into functional groups (plant functional types) to evaluate plant community response to disturbance. 

Knowledge gap: "prescribed burning (specifically slashburning) has been widely used after timber harvest as a means of reducing fire hazard, costs of site preparation, and competing vegetation [29±31], and there has been recent impetus to expand this practice [32]. While ecosystem models have been developed to predict the effect of harvesting and/or fire on long-term tree biomass production [33] and stand development [34, 35], few studies have examined long-term response of understory plant communities after clearcutting and slashburning in BC [8, 9]."

Methodology: All sites clearcut 1981-1987, with logging performed in the winter to help protect understory and soil. Within 3 years of logging, all sites were slash-burned in the fall, and then planted with P. glauca x engelmannii, P. contorta var. latifolia and/or A. lasiocarpa seedlings. Recorded percent cover and height of each vascular plant. Vegetation was re-sampled, generally 1, 2, 3, 5, 10, and 20 years following slashburning for most sites.

Determining Plant Functional Types: Plant attributes used in the cluster analysis included physical properties (plant height, plant duration, leaf duration, Nfixation), seed properties (seed quantity, seed dispersal, seed longevity, seed size), root properties (depth of rooting, vigour of sprouting, rate of lateral spread, dominant mycorrhizal guild).

Findings: Twenty years post-treatment, species diversity increased in all zones and plant abundance was greatest in the Interior Cedar-Hemlock. Cover of understory plant functional types associated with mature conifer forests increased in all zones, (I personally need clarification on this statement). Overall, loss of compositional or functional diversity following harvest and site remediation was not detected, suggesting that montane and subalpine forests in British Columbia are resilient to this treatment. For all zones combined, richness increased from 79 species in year 1 to 132 species 20 years after clearcutting and slashburning. Five years post-burn, all three zones developed into open meadows with fireweed (Epilobium angustifolium) as the dominant species with a mixture of V. sitchensis in the ESSF; R. parviflorus and G. dryopteris in the ICH; and R. parviflorus and red raspberry (Rubus idaeus) in the SBS. The early dominance of E. angustifolium after clearcut and/or fire is consistent with previous studies [10, 13, 38±40, 72]; however, in all three zones, E. angustifolium began to decline after year 5 and was no longer the dominant species (mean % cover < 20%) by year 20.

"The vegetation community in the open young forests in the ESSF seemed to resemble that supported prior to burning [46] with V. membranaceumÐM. ferrugineaÐV. sitchensis dominated understory (Fig 4A). Similarly, in the ICH and the SBS, forbs with limited lateral spread (C. canadensis and L. borealis), rapid lateral spread (G. dryopteris), and budbank and seedbank (R. parviflorus) regeneration strategies [73] appeared to return [47, 49±52]. However, even by year 20, residual V. membranaceum (in the ICH and SBS) and two forbs with limited lateral spread (R. pedatus in the ICH and C. uniflora in the SBS) did not reestablish as significant components of the understory community."

May wish to check sources pertaining to this statement if look at climate over time on huckleberry: "There is considerable interest in assessing the resilience of forests to management strategies and natural disturbance in the face of changing climates and evolving management practices [1-3]."

##Duguid, M.C.D., and Ashton, M.S., 2013. A meta-analysis of the effect of forest management for timber and understory plant species diversity in temperate forests. Forest Ecology and Management 303: 81-90.
These authors performed a meta-analysis to investigate the impacts of timber harvesting on understory species diversity. They found: "Across a pool of 96 studies, we find no effect on understory plant species richness from managing forests for timber. When intensive regeneration harvests (e.g. clearcut, shelterwood) are separated from less intensive regeneration harvests (e.g. single tree and group selection systems) and thinnings, selection harvests show a positive effect on species richness. Intensive regeneration harvests and thinning treatments had no effect on species richness. We examined the role of stand development following regeneration treatments, and found no detectable effects on species richness for even-aged stands within the first 50 years after clearcut and shelterwood timber harvests. Stands in later successional stages, however, had lower species richness than un-logged stands. All these findings together suggest that silvicultural activities focused toward timber management are not inconsistent with conservation of understory plant diversity."... BUT... "it should be noted that our analysis makes no distinction in classifying the nature of diversity, especially between colonizing early-successional species that peak after 1–10 years and then disappear, and late successional, often more site specific and shade tolerant species, that may persist post harvest but often disappear or retract in their range and abundance. Further studies are needed to tease out differences in diversity in relation to successional stage and affects of forest management."

In this paper, the definition of understory varied from "all vascular plants <1 m, to herbaceous species only".

##Abella, S.R., and Springer, J.D. 2015. Effects of tree cutting and fire on understory vegetation in mixed conifer forests. Forest Ecology and Management 335: 281-299.
"[These authors] undertook a systematic review of published studies evaluating effects of tree cutting and fire on understory vegetation in western North American mixed conifer forests. Used 41 studies from 50 articles (in seven states in the USA and British Columbia in Canada). Total understory plant abundance (cover, biomass, or density) commonly declined in the short term within 4 years after treatment. This may result from damage to plants during tree cutting operations or fire, heavy loadings of slash, little change or even expansion of tree canopies after low-intensity treatments, herbivory, or drought. In contrast, all 7 studies measuring understories longer than 5 years since treatment reported increases in understory metrics. Treatments in these long-term studies also persistently decreased tree canopy cover... Cutting and prescribed fire applied together resulted in the greatest invasion of non-native plants, but non-native cover was minimal compared to native cover... prescribed fire and tree cutting consistently increased disturbance-promoted native species in the short term and total understory abundance in the long term."

This paper provides an excellent historical literature review of the consequences of fire suppression and land management in NW North America over the last 2909 years (is this the right number? Seems oddly specific), what it has done to forests. "Overall conclusions from these, and other studies in mixed conifer forests (e.g., Kaufmann et al., 1998; Gruell, 2001; Taylor, 2004), indicate that: (i) understory plant cover has generally decreased during the past 100 years, likely linked with increased tree density and supported by negative relationships between tree abundance and understory vegetation (Larson and Wolters, 1983); (ii) grazing, fire exclusion, different climatic conditions (from the 1800s to today), and other factors (e.g., air pollution) have likely interacted to change composition or abundance of understory plants in ways not well understood; and (iii) it is difficult to ascertain specific past reference conditions for these understories, suggesting opportunity for developing reference information based on how contemporary vegetation responds to disturbance to help guide future forest management efforts."  "Many mixed-conifer forests sustained fires at least as frequent (often <10-year return intervals) as those in P. ponderosa forests, but longer return intervals (including longer than 50 years) could occur in moister forest or where topography limited fire spread, and during climatic periods unfavorable to fire spread. Mixed-severity fire regimes, consisting mostly of low intensity surface fire punctuated by more severe surface fire or patches of crown fire (Fulé et al., 2003), have been broadly reported in mixed conifer forests from Mexico (Minnich et al., 2000) through the U.S. to Canada (Heyerdahl et al., 2012)."

In many studies, the threshold seems to be 40% for when understory cover reduces dramatically (at >40% cover). "While specific quantities vary among regions and likely with soil properties within regions, <40–50% tree canopy cover is apparently a threshold above which understory production is minimal." "A doubling of tree basal area from 11.5 m2 ha1 to 23 m2 ha1 also approximately halved understory biomass in the White Mountains of Arizona (Thill et al., 1983)... Similarly, reductions in basal area down to <20 m2 ha1, and commonly 8–15 m2 ha1, are apparently approximate thresholds for understory abundance (Thill et al.,
1983; Battles et al., 2001; Lochhead and Comeau, 2012)."

"Residual slash following tree cutting may play a major, but poorly understood, role in post-treatment understory dynamics. Slash can decrease understory vegetation by burying plants (Metlen et al., 2004), or through other mechanisms such as immobilization of soil nutrients in carbon-enriched soil (Perry et al., 2010)." "Among studies examining slash handling methods, Mason et al. (2009) found that piling slash correlated with lower site-level understory biomass than did scattering slash. Two studies found that burning slash (either scattered, Steele and Beaufait (1969), or chipped slash, Walker et al. (2012)) reduced plant cover more than simply leaving the scattered or chipped slash, but the authors also suggest that relocating slash is often impractical given location and access." Many studies have found that understory abundance was greatest when lash was removed from site. "In Arizona P. ponderosa (Korb et al., 2004) and Colorado Pinus contorta (lodgepole pine) forest (Fornwalt and Rhoades, 2011), burning piled slash sterilized soil and essentially eliminated plant cover in areas that had been underneath piles. Collectively, these observations suggest that slash (and associated slash treatments) can temper understory response to tree cutting and may be related to reductions in understory vegetation reported in some short-term studies of this review."

"Depending on how and when (e.g., summer versus over snow cover) tree cutting operations are implemented, soil disturbance can be substantial. Young et al. (1967) reported that 39% of the ground was disturbed in some way by a sanitation cut, and 62% was disturbed on steep slopes when thinning trees using heavy machinery (Cram et al., 2007). Machinery, as well as felling trees by hand coupled with slash treatments, can damage or kill aboveground plant parts or disturb root systems belowground (Page-Dumroese et al., 1991). Similarly, fire can damage or kill plants, especially if they are a primary fuel (Kauffman and Martin, 1990)."

"Overall conclusions from these studies suggest that soil seed banks in mixed conifer forests are usually not large (typically 61000 seeds m2 for the upper 5 cm of mineral soil), but they can be species-rich (30 to >80 species) and contain native perennials and shorter-lived species often associated with disturbance (Strickler and Edgerton, 1976; Kramer and Johnson, 1987; Stark et al., 2006; Abella and Springer, 2012)."

"Two of the most important factors in understory dynamics after tree cutting and fire in mixed conifer forests were time since treatment and specific operational aspects of treatments (e.g., whether cutting and fire were applied together, and amount of forest overstory removed). Understory measures often declined for the first few years after treatment, but subsequently increased if forest overstories had been reduced to well below 40–50% canopy cover."

##Page, H.N., E.W. Bork, and R.F. Newman. 2005. Understorey responses to mechanical restoration and drought within montane forests of British Columbia. BC Journal of Ecosystems and Management 6(1):8–21.
These authors investigated overstorey and understorey charactertistics in East Kootenays of IDF and PP forests. "Pre-thinning data consistently indicated that understorey shrub and herb abundance were positively associated with light intensity and inversely with tree density (i.e., ingrowth) at both locations. Immediately after thinning, greater reductions in tree density or increases in understorey light were generally associated with greater reductions in understorey species richness, diversity, and shrub and herb cover; however, the presence of drought conditions complicated this effect. Overall, the results indicate that while the effects of ingrowth appear detrimental to understorey vegetation, the disturbance caused by mechanical thinning, particularly when accompanied by drought, can reduce the abundance of many important understorey characteristics in the short term."

This article also has a good brief fire history background in the introduction.

"Prescribed burning has been studied extensively, but less attention has been paid to the effect of the thinning necessary to restore more natural stand structure before fire reintroduction (Smith and Arno 1999)."

Methods: "systematic grid of 22-m diameter timber cruise plots was established. Only plots identified as in the IDFdm2 or PPdh2 biogeoclimatic zone, and with slopes of less than 5%, were selected for monitoring. Slopes greater than 5% were excluded to remove strong moisture gradients as a confounding factor in the interpretation of ingrowth" Monitored over 3 years. "In the first phase of restoration, commercial logging companies thinned and (or) slashed forest stands at the two sites from near full crown closure to between 20% and 70% closure (Powell et al. 1999). The IDF and PP sites were treated in June 1999 and in June– July 2000, respectively. Thinning consisted of cutting and removing any commercially valuable intermediate sized timber (i.e., subdominant trees); slashing involved cutting undesired tree species and low quality, diseased, and juvenile stems (< 20 years old) within all macroplots at both sites (Powell et al. 1999). Slashed material was left on site. Large-diameter (i.e., veteran) trees and snags were retained. Tree density, diameter at breast height, and height of codominant trees were determined in each macroplot using standard variable plot (prism) methods (Husch et al. 1982). Post-thinning overstorey values were obtained by subtracting the density, basal area, and volume of trees removed from each macroplot from pre-thinning stand estimates. Canopy cover (%) of all understorey vascular plant species was estimated in 0.1-m2 microquadrats positioned every metre (n = 20) along the two outermost transects. The density of common native bunchgrasses, including rough fescue (Festuca campestris), Idaho fescue (Festuca idahoensis), bluebunch wheatgrass, Richardson’s needlegrass (Stipa richardsonii), needleand- thread grass (Stipa comata), and stiff needlegrass (Stipa occidentalis var. pubescens), was assessed in two 10-m2 (1 × 10 m) belted subplots established along each outside transect. The density of shrubs was assessed similarly in two 20-m2 (2 × 10 m) belted subplots, also centred on the outside transects. Above-ground current annual understorey biomass was estimated by sampling four 0.5-m2 (0.5 × 1 m) previously unsampled mesoquadrats systematically located on the centre transect of each macroplot. The amount of understorey light was measured 30 cm above-ground over each 0.1-m2 microquadrat using a LI-COR®LAI-2000 Plant Canopy Analyzer."

Results: "At the IDF site, shrubs such as saskatoon and bunchgrasses appear to have been directly damaged by logging and tree removal. Shrubs may be particularly susceptible to mechanical thinning because they maintain above-ground perennial biomass, which may account for several studies indicating shrub biomass yield does not respond favourably to thinning within xeric ecosystems; however, the absence of a negative relationship between thinning intensity and saskatoon density 2 years after treatment suggests this important shrub species may be recovering. In the short term, the loss of total herb, pinegrass, and bryophyte cover represents lost biodiversity; these species are important ecosystem components responsible for protecting soils and meeting other land use needs (e.g., wildlife habitat and livestock grazing). Moreover, these results suggest that the detrimental impact of physical site disturbance should be evaluated against the potential benefit to plants and the plant community by increased resources such as light. Another consideration when using thinning as a restoration tool is that opening the overstorey may favour early successional species or invasive weeds."

"Overall, these results indicate that some caution and flexibility should be maintained when applying thinning treatments. For example, to minimize impacts on the understorey and ensure recovery of the plant community, it may be better to conduct restoration activities on frozen soils and (or) protective snow cover. Winter harvesting is known to reduce compaction of forest soils (Maynard and MacIsaac 1998; Krzic et al. 2005). Practitioners should also recognize that at least two full growing seasons (longer under drought conditions) will be needed to significantly increase understorey cover and biomass. Finally, continued monitoring is advised to fully assess the long-term impacts of commercial thinning and other management activities on understorey recovery and ecosystem restoration."


############### February 3 Thoughts ##################
 ##From Tyler:
 Goal: Define (fit a quantitative model if possible) the relationship between berry cover/abundance and harvested forest stand characteristics (and silvicultural practices) that can be used to assess the influence of forest harvest on berry production at large scales (e.g., timber supply area).

Objectives:
-	Develop model of the relationship between forest stand characteristics (e.g., canopy closure) and berry cover/abundance in cutblocks
-	Develop model of the relationship between silviculture practices (e.g., planting, burn, mechanical) and berry cover/abundance in cutblocks
Other Thoughts:
-	For timber supply modeling, I think we still need a spatial map/model of berry distribution
o	For landscape simulation purposes, to tell us where berries are likely to occur and respond to forest harvest
o	Also useful for understanding potential change in berry distribution under climate change, and how that might interact with forestry
o	Can we use Clayton’s model?
	Not ground validated
	Uses canopy closure, so could be circular; remove these stand level effects? 
o	If not, could use something coarser like BEC zone, subzone?
-	Canopy closure seems to be a key variable 
o	estimated from landcover data? Is this updated annually and aligned with timing of berry plots? Is there an estimate from plot data? 
-	Data on silviculture incomplete? Is there enough to look at planting densities, planted/not planted?
-	Could use TASS model to ‘fill in the blanks’ on stand characteristic data
o	If we know silviculture inputs to cutblocks (e.g., planting densities), we can simulate the stand and estimate stand characteristics, e.g., canopy closure, light levels, at the time when the berry plot was taken; use these estimates to fit the model
o	Note: limited to single spp., pine or spruce stands
-	Developing a wildfire model may be a secondary goal, if time allows; aligns with fire modeling work


## See subsequent correspondance and document for work plans from Garth Mowat and other team members.

