---
title: "Fire models - Brief Literature Review"
author: "Elizabeth Kleynhans and Cora Skaien"
date: "26/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

- here are some ideas and lit. review about how to go about developing a 'fire model' for caribou recovery

## Possible Approaches

### FAIB - TSA 16 Fire Modeling Methodology

They model it in STSM with a four step process. 

1.) Examine the fire regime in study area by getting spatial files of historic fire perimeters and BC wildfire Provincial Strategic Threat Analysis (PSTA) dataset which determines threat of fires to different areas. THey then calculate how much of the area was burned since fire data is available and from this determine how long it would take for an equivalent area of the forested portion of the TSA to burn (referred to as rotation period). The inverse of the rotation period (1/rotation period) is the expected annual rate of disturbance or in other words the proportion of the total forested area burned per year.

2.) Establish a theoretical simulated distribution. Using the fire perimeter data they fit a distribution to a log transformation of the data e.g. using fitdistrplus in R and test whether the determined distribution is a good fit.

3.) Parametrize the timber supply model. They parameterized the SELES model with parameters such as 20% of the burned forest being destroyed, the rest is then available for harvest for the next 5 years after which the amount of available timber is set to 0%. Where a fire initially ignites is dependent on the PSTA wildfire threat analysis layer with areas with higher hazard having a greater probability of ignition and the subsequent fire patch size is determined from the lognormal distribution. Also fire preferentially spreads to higher hazard areas.

4.) the model is then run and the distributions are reviewd. They also examine scenarios where fire frequency is increased so that it doubles over a 100 year period to examine the impacts of that.

### Marchal et. al. (2020) Turning down the heat: Vegetation feedbacks limit fire regime responses to global warming. Ecosystems 23: 204-216.

These authors simulate annual fire activity from 2011 to 2099 in hard wood, mixed wood and coniferous forests in Quebec.  They used a spatial resolution of 1ha and temporal resolution of 1 year. For the study area they classified vegetation into 5 different fuel types: Hardwoods (HW), conifers (CN), disturbed (D), open (O), and open water (WT). Areas that were less than 15 years since disturbance were classified as disturbed, areas with >50% basal area of hard wood  or conifer were classified as HW or C and everything else was labeled O.They then simulated vegetation dynamics as fuel-type trajectories and assumed that fires were stand replacing. After a fire they tested various scenarios of vegetation trajectories on future fires. The scenarios are 
1.) there is no change in category. After a fire HW areas stay HW, cN areas stay CN and open areas stay open.
2.) there is a 15 year lag. In the first 15 years after fire the area is classified as disturbed then after 15 years it goes back to what it was before the disturbance.
3.) There is a vegetation trajectory of mixedwood forests going to CN forests after 81 years. Other forest types stay as is after a disturbance.
4.) As scenario 3 except that the first 15 years after disturbance are classified as disturbed then the vegetation trajectories kick in i.e. after 81 years mixed wood forests go to coniferous.

They simulated fire by breaking down the process of burning into three processes: ignition, escape and spread which were each modelled separately as functions of fire weather and vegetation. 

They simulated spread across the landscape using the spread function in SpaDES package, which immulates bond percolation where fire spreads from a burning cell to an unburned neighbouring cell according to some probability. This probability depends on fire size distributional parameters (predicted from fuels and weather). They tested their fire spread model by simulating fire spread of known fires between the years 2000 - 2010 using known vegetation and fire weather data to parameterize the model over time and also simulated out into the future.

Ignition: they developed predictive statistical models of annual fire frequency as a function of fire weather and fuel type. Fire weather was represented as the month drought code (Van Wagner 1987).

Escape: they used logistic regression to predict sensitivity to  fire weather and vegetation conditions. They then estimated the probability that a fire would be at least 1ha in size (escape) and derived an equation for this. 

### Lakes TSA Discussion paper 2019
Seems like they did not include fire in the future forecasts. Rather they obtained layers of historical fires (fire perimeter) and burn severities (to classify injury to trees i.e. amount of timber that is still harvestable) and adjusted the available timber volumes from those. 

### Marchal J, Cumming SG, McIntire EJB (2017) Exploiting poisson additivity to predict fire frequency from maps of fire weather and land cover in boreal forests of Quebec, Canada. Ecography 40: 200-209.

Here they statistically predict the probability that a fire will start in a 10 x 10km pixel as a result of lightning or humans. The first thing they do is determine vegetation categories for each pixel and calculate the proportion of these vegetation categories in each pixel. Vegetation categories are: coniferous (<50% of basal area deciduous), hardwood (>50% of basal area is deciduous), disturbed (disturbed within past 15 years), and open or open water. 
They then obtained fire counts and determined the cause to classify then as lighting or human.
They also obtained weather data: max monthly temp, monthly precipitation, and they estimated monthly drought code (MDC) using the equation in Begeron et. al. (2010) (Will climate change drive 21st century burn rates in Canadian boreal forest outside of its natural variability: collating global climate model experiments with sedimentary charcoal data. Int J. Wildland Fire 19: 1127-1139).

Then they performed negative binomial regressions (because of overdispersion in the count data) looking at the relationship between each of the weather variables and lighting or human caused weather. They tried various combinations of weather including each month alone, and combinations of months together. Overall they found that July monthly drought code was the best predictor of fires using AICc. 

Then they examined the relationship between fire ignition and fire weather (MDC) and vegetation type/land cover by testing each term individually, and with the interaction between them. They also examined fire weather with varying slopes for vegetation, fire weather with varying slopes and intercepts, and some fancy pants models where they allowed break points i.e. changes in slope because a visual examination of fire weather and vegetation suggested there might be break points. 

Overall they found that for lighting caused fires models with varying intercepts and slopes and break points was best. Although if you examine the results the model with just varying intercepts and slopes and no breakpoints was not far behind. 

For human caused fires they also included road densities within the pixel as a model term. Here they found the best model was a model that allowed varying intercepts and slopes according to vegetation type and included the interaction between fire weather and road density. Models with breakpoints were not better in this case. Again they used AICc to determine the top candidate model. 

### Approaches

### Approach to making fire model

## 1.) Following methods outlined in Marchal et al. 2017. Ecography calculate the probability of ignition according to vegetation type and fire weather.

To do this I need to get the following layers: 
1.) history of fire ignitions in BC both lighting and human caused. I need to split these ignitions up because models for human caused versus lighting caused fires are probably a little different
2.) get a vegetation layer particularly forestry layer that has information about the kinds of trees i.e. deciduous versus coniferous. Also get disturbance information (Kyle's cutblocks layer) for the same years as we have fire ignition data.
3.) get weather data: monthly means of daily mean temp, monthly means of average daily temp, monthly means of daily max temp, monthly precipitation.
4.) estimate monthly drought code following Bergeron et al (2010) Int. J. Wildland Fire 19: 1127-1139
using the following equations. I'm a bit confused but I think they must assume that MDC is 0 in March and then calculate the April value from that. Not sure this is right but maybe its close enough?

Evapotranspiration = # days in month * (0.36 (monthly mean of daily max Temp) + day length adjustment factor)

DC_half (Drought Code for first half of month = MDC_0 (MDC value from previous month) + 0.25 Evapotranspiration

MDC for second half of month after rainfall for that month happens  is calculated as follows:

Q_mr (moisture equivalent after rain) =  [3.937*(0.83 * rainfall (in mm))]/800*     exp(- MDC_0/400)

MDC_m (Drying over second half of month) = DC_half + 0.25Evapotranspiration


## Rothermel Fire Spread Model

Vacchiano et al. (2015) An Implementation of the Rothermel Fire Spread Model in the R Programming Language. Fire Technology

This paper outlines a R package that estimates the rate of a fires spread [ros()] by implementing the Rothermel Equation. Essentially this equation is a physics based equation and calculates rate of spread as heat source divided by heat sink. It takes into account fuel characteristics such as fuel load i.e. amount of fuel per ha, surface area to volume ratio of fuel, fuel moisture contents,  how much moisture is needed in the fuel for fire extinction, how much heat different fuels give out, slope and wind characteristics. These values feed in to calculating the rate of spread.

I could use this equation with these fuel characteristics and topography and use it to give the fire a probability of spread to the next cell or to define how the fire is spreading.

Also see Andrews PL (2018) The Rothermel Surface Fire Spread Model and Associated Developments: A Comprehensive Explanation. USDA - General Technical Report RMRS-GTR-371




##Additional thoughts, considerations and literature review added by Cora Skaien from here onwards
1. Liz captures most of my initial thoughts above (lightning versus human caused fires may need to be modelled separate, projecting climate and vegetation change into the future for the models)
2. How to best combine human and lightening predicted fire data once complete? Additive effects in some areas that may have medium to high probabilities for both.
   # See STSM2020_p5_AdvancedComponents file for section 1.5 for parameter table for how to incorporate mutiple influences (0/1)
3. Do we have data on where thunderstorms are most likely to occur (e.g., specific mountain ranges and how weather patterns interact with them)? Lightning strike data --> Tyler thinks this might already be incorporated.
4. recently burned areas less like to burn again: create probability map for areas where prescribed burns occurred. Could use data where prescribed burns occurred over last 20+ years and data where natural forest fires occurred and create probability map using each pixel, considering occurrence and intensity of wildfires (if any) after prescribed burns. Compare to control pixels randomly selected but with similar environmental variables to areas that were selected for prescribed burn. Perhaps fuel reductions are already accounted for in recent aerial photos that will be used, however. NOTE: some studies show that with changing climate, the return interval is reducing and that fuel regeneration is not super predictable by time.
5. Current models being run assume all fires and stand replacing. Consider lower intensity fires as well for relevant BEC zones? Find any sources or data that indicate fire severity.
6. Some models in Marchal et al. 2020 are already available in SPaDES. Check these out and see if any are relevant and useful?
7. We need to determine how to best model how our forest composition changes after disturbance given different forest types compared to Quebec. Often we have deciduous pop up I believe still in the interior --> is this true for all BEC zones?
8. Is there any data on rates of conversion of wetlands to forest? Much of the open water part is exclusively open water, so maybe this is not a concern, but wetlands are likely ot burn less unless converted I assume.
9. Consider (semi-)natural fire breaks, such as roads, when considering spread. Logging roads vs paved roads as fire breaks? Look into. This will be important for the spread model. Also could be important to consider habitat fragmentation (VRI data may assit).
10. Can we incorporate spread from one BEC type to another?
11. Interesting ideas and resources a bit tangential maybe in this webinar, talking about forest succession after a fire, using LANDSAT to determine fire severity, and fuel breaks (https://www.youtube.com/watch?v=FS7yz1JKdTs)
12. Slope and Aspect likely important. Slope important for spread, and aspect important for ignition?
- "Because of the local, up-slope winds, wildfires usually burn up-slope. The steeper the slope, the more rapidly the fire will burn up-slope (and more intensely). The reason is because of both greater radiant heat and greater convective heat." "Aspect is the direction that a slope faces.  The direction a slope faces determines how much radiated heat it will receive from the sun.  Slopes facing south to southwest will receive the most solar radiation.  As a result, this slope is warmer than slopes facing a northerly direction.  The warmer slope results in lower relative humidity, higher temperatures and rapid loss of moisture.  The fuel will tend to be dryer flashy-type that ignites and burns readily.  The period that fires will ignite and burn will also be longer on south-facing slopes." http://www.auburn.edu/academic/forestry_wildlife/fire/topos_effect.htm
- "In northern aspects solar radiation was lower and fuels had less water limitation to growth which, combined with steeper slopes, produced more extreme severity. In topographic fires there was more extreme severity in northern aspects with steeper slopes and in areas with more water availability and high crown biomass" (Lecina-Diaz et al. 2014) 
13. Spread days: as outlined in Wang et al. 2017, there can be no non-spread days while a fire is active, but there can be neglible spread days. Using MODIS, is it possible to create a frequency distribution of spread rates per day per fire and correlate to climate variables that are most important in ignition, escape and spread? Check out Parks 2014 and Wang et al. 2014 for more details on RSD, PSD and using MODIS for spread days.
- since we are not estimating daily spread or only annual burned area, the actual spread rate may not be important for current models.
14. If Colin Mahony can add fire weather data to ClimateBC over the coming years, it would be so wonderful to create a new model using those data and comparing it to this model. Can take most recent year's fires as test and see which model predicts best, and assess areas of greatest difference in future predictions between the models for each 20 year period. End of Discussion in Wang et al. 2017, they do a brief comparison to a model that used monthly climate variables (Boulanger et al. 2014) to compare to their models. Doing this more explicitly with our models would be really useful!

################# LITERATURE REVIEW ###################

##Notes on Pariesen et al. 2019. Applications of simulation-based burn probability modelling: a review
This paper provides a good historical overview of Burn probability Models (BP) and its uses. This paper aims to: (1) describe the inputs and outputs of BP models; (2) provide an overview of applications of these models; (3) demonstrate common applications through case studies; and (4) develop a comprehensive list of published studies using the BP method.

The paper emphasizes the need to first create baseline outputs, which are not necessarily simplistic. But this initial model offers a departure point for alternate scenarios, and can provide a reference state to assess change.

Examples of inputs: 
   - fuels (e.g., land cover, flammable biomass, unburnable areas)
   - topography
   - spatio-temporal patterns of ignition
   - fire weather
   
Suggested considerations include:
   - classifying areas into fuel types (e.g., BEC zone)
   - different causes (human vs. lightning)
   - If fires will burn for days, incorporate realistic day to day variability in weather, or drawing sequential fire-conductive conditions from historical data
   - can account for topographic relief on wind speed and wind direction (e.g., WindNinja grids)
   
This paper also discusses the importance of model calibration: generally via heuristic and iterative manner by adjusting inputs and assessing outputs through comparison of actual and simulated fires.

Four key types of outputs: (1) ignition points; (2) associated fire perimeter; (3) BP maps; (4) fire behaviour maps.

Three key purposes of BP models: (1) direct examination; (2) neighbourhood processes; (3) hazard and risk. Direct examination is often a direct comparison, with fire maps side by side for different scenarios, or a 'difference' map that represents differences between two scenarios. Neighbourhood processes tell us where fires arecoming from relaive to an area of concern, and can also assess "source-sink" ratio to describe each pixel's propensity for producing or receiving a fire -- potential applications for between regions such as BEC zones too. Fire hazard combined fire probability and a quantitative assessment of fire behaviour; wildland fire risk is a product of fire likelihood and potential impacts of wildfire (positive and negative). This can apply to estimating expected financial losses, ecological habitat change and carbon emissions. 

An element not included in any models in Canada is long distance spotting events, and they suggest that making fuel breaks partially flammable can help partially account for this short-fall.


##Summary of Considerations for modelling burn probability across landscapes with steep environmental gradients: an example from the Columbia Mountains, Canada by Parisien et al. 2012.
In this paper, the authors create a Burn Probability (BP) model for the area around Revelstoke BC, taking into account topography and windspeed. Many elements have been touched on previously, such as modeling separately by fuel type (BEC zone) and by ignition type, with human and lightning caused fires modeled separately and incorporating road density into the human-caused fire model. Some other key elements they performed that warrant consideration by us include:
   1.Fire duration - really important to know fire duration. Can create frequency distributions for duration for each BEC zone. Can also model spread based off of this. Really important for escape and spread.
   2. Topography - really important to include for fire behaviour (DEM). More important for spread than ignition IMO.
   3. Wind direction and speed - can be modelled with WindNinja based on DEM. Really important for escape and spread.
   4. Fire Spread Rate - used satellited-detected hot spots from 1994-2010 and fancy stats to estimate how big the fire was each day and then estimate spread rate. Could do a simpler model where take fire size and divide by number of burn days and predict a constant rate of spread. If can get daily spread, and correlate to daily fire weather, would be even better. However, future predictions will mostly be climate, so creating a distribution of spread rates from ClimateBC data and average spread rate probably sufficient.
   5. Could assess if seasonality of fires is important by BEC zone
   6. Solar radiation from aspect and slope - this can be really important to the probability of ignition
   7. The importance of non-linearity of variables and using quadratic, or other, transformations.
   8. Fragmented areas - probability of spread was lower in fragmented areas. Account for in spread.
   9. Test spread rates against historical data because often over-predicted from model and may need a correcting factor.
   10. Also discuss the need to account for fire suppression activities.
   
   
##Notes from Wang et al. 2016 "Future burn probability in south-central British Columbia"
"A spread day represents a day when a non-negligible area is burned by the fire and is usually associated with the presence of fire-conducive weather (Parisien et al. 2005; Podur and Wotton 2011; Wang et al. 2014). We determined the number of spread days in the observed period from a historical database of daily fire progressions derived from Moderate-Resolution Imaging Spectroradiometer (MODIS) fire detections from 2000 to 2009 using the method described in Parks (2014). To differentiate spread and non-spread days, we used a threshold based on a calculated rate of spread of$1m min 1 (? foemat issues now) based on 4 h of burning (per day) and assuming circular growth, as described in Parisien et al. (2013). Frequency distributions of the number of spread days were produced for each fire zone; they are largely responsible for the size variation of simulated fires. As such, we made some adjustments to the spread day distributions for the simulated fire sizes to match the observed ones. The distributions were also smoothed to reduce noise."
   - maximum 7 spread days
   
##Wang, X., Parisien, M-A., Taylor, S.W., Candau, J-N., Stralberg, D., Marshall, G.A., Little, J.M., and Flannigan, M.D. 2017. Projected changes in daily fire spread across Canada over the next century. Environmental Research Letters, 12: 025005.
Highlights that by estimating by monthly, annual or decadal climate patterns, we miss out on the relevant day-to-day fire spread. These authors used CMIP5, MODIS, historical weather observations and national fire database of Canada to estimate the potential changes in the number of active burning days of wildfire and relating spread days to daily fire-conducive weather. Their results suggest that the number of fire spread days could increase 2-3 times in Eastern Canada and a 50% increase in Western Canada.

Some variables they suggest to be important: the number of fire-conducive weather days per month, number of rain-free days. Differentiate between potential spread days (when fire weather is conducive to spread) and realized spread days (when fire actually spreading). They also highlight that there can be no days when a fire is not spreading, as it would be extinguished, but that there are negligible spread days that are characterized by surface fire type behaviour with head fire rates typically <0.3 km/hr.They outline required conditions really in introduction and highlight that extreme fire weather might not result in realized spread days due to (a) lack of flammable biomass, (b) geographic impediment to spread, (c) successful fire suppression, (d) or lack of ignitions. Therefore, realized spread days (RSD) < potential spread days (PSD). This paper actually estimated the number of potential spread days (PSD) and realized spread days (RSD) using a correction factor: they highlight their 8-step process for calculating baseline and future PSD and RSD.

Used Parks (2014) methodology using MODIS. Used Wang et al. (2014) to determine spread vs. non-spread days. They emphasize the importance of a good link function between PSD and RSD to get the correct correction factors.

When comparing their results to one that used monthly climate variables (Boulanger et al. 2014), Wang et al. found that patterns of annual area burned were almost the inverse between the 2 studies!  Differences may be a result of temporal data resolution, or may be differences in GCMS (Global Climate Models) used and other variables.

Authors emphasize the confounding effects of fire suppression efforts both before and during fires, and that we must assumethese efforts remain constant moving into the future, but this may not be the case.

Cora's thoughts: If we were to get estimates of PSD from future ClimateBC info, we would potentially need to alter results by some scaling factor to account for if too high (some other papers did this scaling using Climate data).


##Wang, X., Parisien, M-A., Flannigan, M D., Parks, S.A., Anderson, K.R., Little, J.M., and Taylor, S.W. 2014. The potential and realized spread of wildifes across Canada. Global Change Biology, 20: 2518-2530.
Fires can burn for weeks or months, but not all of the burn days are 'spread' days. Most sread occurs on a small proportion of actual burn days (e.g., 1-15) and may not necessarily be consecutive days during the active burn period. In this paper, they outline how to determine potential spread days (PSD) and realized spread days (RSD). They found substantial variability between PSD and RSD. PSD and RSD greater in Western than Eastern Canada. PSd has a decreasing pattern from South to North, but no such pattern with RSD. RSD:PSD ratio considering higher in Northern Canada, and they attribute this to (1) more coniferous veg (more flammable), (2) lesser human impacts (less fragmentation), (3) sufficient fire ignitions and (4) intense droughts (also (5) longer daylight hours during fire season). Here, the authors create simple linear relationships between PSD and RSD for each fire zone that create a simple correction factor. These data can be used to estimate RSD from weather-based data in regions where fire databases are poor.

In temperate and boreal forests, large fires (1-10000 km square) are infrequent but account for most of the area burned. They may burn for weeks to months and rain-free periods largely dictate how long they can burn, but also contingent on number of fire conducive days for spread. Conducive spread days = hot, dry and windy. 

Data: Assign fire zones across Canada by 'homogenous' fire zones created by Boulanger et al. 2012. Used weather stations across Canada to calculate Fire Weather Index (FWI): temperature, relative humidity, wind speed and 24 hour precipitation to calculate three fuel moisture codes and three fire-weather indices. PSD defined as when FWI > 19 (although Wang et al. 2017 used 20). Defined rain free period by Duff Moisture Code (DMC), wherein the DMC was used when FWI > 20. DMC good predictor of fire spread potential in boreal forests and provides a numerical rating of moisture content of organic layer 1-6 cm in forest floor. Table 1 has variables used: Mean T, mean ppt, seasonal severity rating (derived from weather stations), ratio of conifer:other tree spp., percent non-fuel (e.g., rock, urban, irrigated agriculture, open water), mean human footprint index, Mean annual area burned. Used MODIS to estimate spread following Parks 2014, and MODIS fire detection dayswere interpolated using the 'weighted by mean and distance' (WMD) method. Uses 30 m x 30 m resolution and equation presented in paper. Using 5 closest MODIS detection points was found to be more accurate than using other methods, such as nearest neighbour. MODIS has 2 types of fire detections:(1) actively burning fire front and (2) smoldering combustion after flaming front passed through. They limited their analysis to fires > 200 ha. Numerous equations presented toi compare and transform the frequency distributions, and then use these in a linear regression model.

Spread days are defined as days when fire spread exceed 240 m (rate of at least 1 m/minute assuming 4 hour burn period each day and circular growth). They indicate this should not be indicative of actual fire progression, but instead just to simply estimate spread and non-spread days.

Also assessed the association between RSD/PSD with each of the environmental variables in Table 1 to get an idea of correlates and contributors. Remember: PSD = Number of days where FWI >20, and RSD: actual value from MODIS hot spot analysis. Main correlates to PSD are seasonal severity rating (r=0.60) and surface-area ratio (r=0.61), a measure of topographic roughness. Realized spread correlates strongest were: mean total precip (r = -0.70) and mean annual area burned (r = 0.72). RSD:PSD strongest: mean temp (r = -0.75), mean human footprint index (r =-0.75) (but these 2 co-vary).  Degree to which potential fire spread is realized is correlated with: proportion of coniferous cover (r = 0.60).

Discrepancy between PSD and RSD seem to be due to bottom-up (nonclimatic; vegetation and topography) variables as opposed to top-down (climate).

Smoke and cloud cover can obscure MODIS images and can be lost data. Previous studies have demonstrated that longer droughts (potential burn periods) during fire season are likely to produce larger and more severe fires.

key: need daily fire weather metrics, but then can estimate potential spread days from that and scale to an estimate for realized spread days. Potential useful for future applications of Colin Mahony gets fire weather variables into ClimateBC/ClimateWNA.

##Parks. S.A. 2014. Mapping day-of-burning with coarse-resolution satellite fire-detection data. International Journal of Wildfire, 23: 215-223.
MODIS data is at 1 km-square resolution, so data needs to be downscaled if want an area that is less. This paper presents a method for doing exactly this. The methods in this paper will be particularly important for future models if daily fire weather variables are available.

This paper presents multiple ways (Day 2) to estimate Day of Burning (DOB) for fires of a certain size threshold. MODIS has a 1 km resolution, so some of our 1 ha fires may or may not show up here and this may limit our spread day estimates? DOB was estimated for each pixel within each fire perimeter using several interpolation techniques (Table 2), with code from Parks available with no restrictions. Three step process: (1) All MODIS fire detection data overlapping and within 1 km of final fire perimeter were selected for use in interpolation, and they removed fires <100 ha; (2) estimate DOB for each pixel within each fure perimeter using all 10 interpolation methods in Table 2; (3) reassigned all spatially contiguous interpolated DOB regions that were <=25 ha to DOB values of the nearest regions larger than 25 ha. Parks was able to make a pixel at resolution of 30 m x 30 m, so hopefully it is easy to make interpolation to 100 m x 100 m.

If a fire detection was noted before 12 noon, it was assigned the day before for start date. Of the 10 methods, similar but subtley different results were created. When compared to known data, the weighted by meand and distance (WMD) did best. However, the 6 top performing methods were all similar (IDW, IDW.sq, IDW.half, WMD.sq and AD with WMD).

These methods increase accuracy compared to using sigmoidal growth function as a function of fire duration and final size (which is our other option). Some limitations: ground proofing data hard to come by; smoke, canopy cover and clouds can obscure detections; individual pixels in fast moving or low intensity fires may go undetected. 

The authors suggest that these methods may be inappropriate for small fires <500 ha in size. The average size for our lightning caused fires is 262 ha and for person caused fires is 26 ha... so we may encounter some problems!

Looking at maps (Figure 4), we can see where fires started and ended, which can give us guidance to direction fires travelled. Could we make a raster with this information? It would be very coarse, but hopefully we could correlate it to topography?

##Flannigan, M.D., Logan, K.A., Amiro, B.D., Skinner, W.R., and Stocks, B.J. 2005. Future area burned in Canada. Climate Change 71:1-16.
Authors here investigated how weather, fire weather index and area burned relate to each other. They found that temperature and fuel moisture were the best variables to relate to historical monthly area burned with 36-64% of variance explained depending on ecozone. Their results predict significant increases in burned area by end of century by 74-118%, but they do not account for changes in vegetation, ignitions, fire season length and human activity.

They highlight four factors that influence fire activity: weather/climate, fuels, ignition agents and humans. They suggest that in Canada, climate/weather is the most significant factor influencing fires. It determined fuel moisture, influences lightning ignitions and contributes to fire growth through wind action. Many factors influence in addition though, including but not limited to: extent of forest, topography, habitat fragmentation, fuel characteristics, season, latitude, fire suppression policies, fire site accessibility, etc.

The data used included start date, location, cause and final size of fire. Log-transformed are burned (size) data. Use weather stations and Environment Canada to get temperature, RH, wind speed and 24-hour precipitation at noon to calculate the Fire Weather Index (FWI). They used a thin-plate cubic-spline technique (Falnnigan and Wooton 1989) between weather stations to interpolate. There was a discrepency between reported precipitation and actual measured precip, so they used a correction factor.

GCMs can come as monthly anomaly data (in which if the value is 5 degrees, then you add 5 degrees to the baseline value), or you can use daily data directly. The daily approach allows daily precip to change, whereas the monthly approach constrains you to historical data, and daily precip is very important for fire behaviour. Most fire spread occurs during a few days that coincide with severe fire weather. They found that larger spatial units (ecozones) had better results than finer spatial units (ecogroups). Authors emphasize the need to include changing fuel type in future studies. They found that the length of the fire season was predicted to increase by 20% or 30 days by the end of the century. But they indicate also that they did not account for habitat fragmentation from agriculture, urban development and trasnporation corridors which should decrease the extent burned. 

Authors emphasize tyhat using daily weather was more accurate than monthly climate averages.

##Beverly, J.L., and McLoughlin, N. 2019. Burn probability simulation and subsequent wildland fire activity in Alberta, Canada - Implications for risk assessment and strategic planning. Forest Ecology and Management 451: 117490.
Burn probability maps use Monte Carlo methods to create repeated simulations of fire ignition and spread across a study area landscape to identify locations that burn more frequently than others. These authors compared burn probability maps to actual burned area 5 years after creation. Depending on burn probability maps, results were variable from fires occurring where models least predicted them, to reasonable accuracy. Quantile classification was better at predicting actual burned area than Jenks natural breaks, equal interval and defined interval.

Burn probability (BP): assessed as the number of times a location burned in relation to the number of independent trials or model iterations. Displayed as a heat map. Monte Carlo simulations creating these heat maps have been used to generate 'hot spots' and 'cold spots' in Spain, Korea, US, Canada and Greece. Authors emphasize that model results are dependent on the historical time period and choice of study area, and how ignitions, spread and fire size are modelled.

Often burn probability maps are created to compare against mitigation alternatives and different climate scenarios. I would REALLY like to include fire mitigation into the probability for each (ignition, escape and spread) down the road and see if there is any difference. 

In the second last paragraph of introductions, the authors address the importance of map classification methods, number of bins (classes), and colour selection in map interpretation and designation of 'hot spots'. Natural breaks (Jenks) vs other breaks, few vs many bins/classes. Within their study regions, they account for both total area and total burnable area(total area minus water and non-fuel land cover types). Burn probability mapping is typically displayed with classes as opposed to stretched continuous display: easier for land managers to interpret. A very large number of bins approximate a continuous map.

Here, they used Burn-P3 with Prometheus, which utilizes DEM, landcover type,and and fire weather. Number and sizes simulated are constrained by user-defined fire regime and fire environment attributes input into the model. Program is calibrated with real data. They used 28-54 years of fire data for calibration. Defined escaped fires as > 4 ha for most regions, except one region where it was defined as >10 ha. They calculate the proportion of fires > 4 and 10 ha respectively. This may be useful for us to do too.

Proportions of burn probability values within burned areas were compared with null model proportions with chi square tests. Distributions of burn probability values in burned and unburned areas compared with Wilcoxin rank sum test. They found often that areas that burned subsequently were in areas that had a low probability of burning in the models, and that burn probabilities mapped with high spatial precision performed poorly. 

Threshold choice also important. Some use 50th percentile threshold, others higher value. Here, using the 50th percentile, resulting in half the study area being predicted to occur in a high probability of being burned zone. Here, quantile classification performed best, with 3 breaks. These authors caution using Burn-P3 results in fire management decisions.

#Commentary on "Burn probability simulation and subsequent wildland fire activity in Alberta, Canada - Implications for risk assessment and strategic planning" by Parisien et al.
This commentary is in response to the prior paper assessed above in which Parisen et al. assess the methods and conclusions from Beverly and McLoughlin (2019). Parisien et al. feel that Beverly and McLoughlin are sending an erroneous message that BP modeling is inaccurate and not useful. The three outlined issues they make for the original paper are (1) inappropriate method for assessing accuracy, (2) misinterpretation of BP outputs and (3) data quality issues. 

Issue #1: Background --> BP models iterate over many model runs and measures a conditional or annluaized probability for each location. Results can be used to (1) determine strategic placement of fuel treatments, (2) assess risk transmission to urban interface and (3) inform conservation of criticial habitat. Parisien et al. suggest that Beverley and McLoughlin's assumption that model performance is contingent on observations of burned areas coincident with high BP. This has 3 conceptual flaws: (1) Burn-P3 outputs represent "fire sinks", where over many iterations, fires occurred here often, but in reality, fires occur across multiple burn probability areas; (2) ideally, burned areas (unit of hectares) need to be compared with burned areas, and probabilities (units related to time, i.e., per year) compared with probabilities; instead, the authors compare proportional burned area within subjectively determined classified bins of probabilities. They go on to say that the confidence interval for areas burned is so large as to encompass all regions within a short time frame. (3) Stochatsic nature of wildfires: wildfires can occur in areas of low BP due to chance alone. 

Issue #2: Parisien et al. suggest that managers do not expect BP models to be accurate (questionable??). They also suggest that the absolute value of BP is not what is important, but rather than change in BP over time. And this is what is needed for fire mitigation planning. They suggest that BP modeling is useful for predicting long term fuel management programs but are not useful for predicting where fires will occur in any given year. Parisien et al. suggest that it is nearly impossible to predict ignitions and escaoe, but that knowledge of where the landscape is inherently more flammable is useful for whoever is living and working in fire-prone areas. BP models also tell us that very large wildfires tend to cobverge where there are large tracts of high-flammability vegetation in spite of relatively few ignitions, and that fire refugia often exist in areas of low BP where vegetation is naturally fragmented or isolated (e.g., lee side of lakes). Lastly, they suggest that BP modeling is not only useful for creating BP maps, but also for assessing "firesheds", which involves mapping all potential ignitions that may reach a feature of interest. 

Issue #3: Models are highly sensitive to the quality of the data, and it has been emphasized that a thorough "data critique" should be performed before any BP modeling occurs. Important factors: (1) number and spatio-temporal patterns of ignition; (2) accuracy of mapped fuels; (3) care to which ignition frequency and fire size distribution are calibrated (Parisien et al. 2010). If your model predicts fires on several orders of magnitude greater than the input data, something is likely wrong with the calibration, especially if you assume consistent conditions and not future conditions. Updating fuels after disturbance is essential, yet challenging. Parisien et al. also caution against the assumption that area has no fuel for a set period of time after a fire, as some areas recover quickly. 

Conclusion: comparing BP maps to burned areas is problematic. BP models still useful for landscape level planning. Not useful for estimating fires in any particular year.

Cora's thoughts: Issue #3 makes sense to me, as fires are stochastic. The first two issues did not conseptually make sense to me.

#Reponse to commentary on "Burn probability simulation and subsequent wildland fire activity in Alberta, Canada - Implications for risk assessment and strategic planning" by Pariesen et al., by Beverly and McLoughlin.
This commentary is in response to the Parisien et al. response on the original paper. The authors reiterate their research question, and directly quote a Parisien et al. 2013 paper in which it was suggested that "the results of BP maps should be directly compared to fires in subsequent years to assess their accuracy". B and M emphasize that they did not devalue the use of BP models, but instead suggsted to exercise cxaution. In this response, they make a very compelling case for justification of the methods they used, which were directly suggested by Parisien et al. in a prior paper of theirs, and debunk many of the issues presented in the initial response piece.

Cora's feelings: I seem to better understand the logic and arguments of Beverly and McLoughlin, but perhaps I am not understanding Parisien et al.s points?

##D'Este, M., Ganga, A., Elia, M., Lovreglio, R., Giannico, V., Spano, G., Colangelo, G., Lafortezza, R., and Sanesi, G. 2020. Modeling fire ignition probability and frequency using Hurdle models: a cross-regional study in Southern Europe. Ecological processes, 9:54.
Goal of paper: (1) assess fire ignition occurrence in terms of probability and frequency; (2) compare main drivers affecting fire occurrence; (3) produce fire probability and frequency maps for each region (Spain and Italy). Used Negative Binomial Hurdle Models. Results: inverse correlation between fire and distance to infrastructure. Land cover type also important, with forest, agriculture and grassland most affected by fires.Although climate, topography and landscape important, anthropogenic factors were more important in these regions. 

This paper cites many papers that have previously used logistic regression, geographically weighted logistic regression, and machine learning techniques, with counts of fires also using Poisson and negative binomial regression (paragraph 2 of introduction). Here, they use hurdle models which work better with non-normal distributions (e.g., many 0s for no ignition, and relatively only a few 1s for where ignitions occur). Poisson Hurdle models can be used for fire size.

Variables investigated: Temp (mean, max), dry days, elevation, slope, population density, distances to roads, urban area distance, land cover (%, 8 classes). Data was assessed via P/A fire and the number of ignitions per cell (1 km square grid).

Hurdle models shape count data with a preponderance of 0s. In the hurdle part, logistic regression is used for P/A (1/0) of fires, then the negative binomial regression is a function of probability for the count part of the data. Negative Binomial Hurdle is recommended when the observed outcome has an average lower than the variance. Here, they used the hurdle() function from the R 'pscl' package. Requires have fire ignition point frequency by cell. Data was split into training (70%) and validation data, using AUC for logistic regression and Pearson correlation coefficient and root mean square error (RMSE) for the count part.

Elevation was negatively correlated with fire ignitions in 2/3 regions, but positive in the third. Most other studies have found a negative coreelation, but what fuel is at higher elevations in different regions may reverse the relationship. Negative relationship found with distance to roads and to infrastructur - this was due to arson and negligence. Population density had limited predictive power.  

Thought to ponder: take number of fires per month from 2002-2020 and correlate with variables to get predictions for number of fires by climate, etc? If need to bound how many fires may occur. May wish to use Hurdle Models for the ignition portion of the models! Then add escape, size and spread to the next steps subsequent to this. HOWEVER: Because we are not taking EVERY cell and assessing fire or not, we may be under-representing zeros, and Hurdle Models may not be the best solution... ponder...

##Flannigan, M.D., Krawchuk, M.A., de Groot, W.J., Wotton, B.M., and Gowman, L.M. 2009. Implications of changing climate for global wildland fires. International Journal of Wildland Fire 18: 483-507.
The authors of this paper review the current understanding of wildfire predictions for the future. They indicate that "To date, research suggests a general increase in area burned and fire occurrence but there is a lot of spatial variability, with some areas of no change or even decreases in area burned and occurrence." Fire season length is increasing in temperate and boreal forests and predicted to continue this trend. They suggest that models need to all account for weather/climate, vegetation, people and other disturbances.

The first paragraph of this paper offers a great historical perspective: fire size 1960-2000 ranged from 273 to 567 Mha (average: 383 Mha), with estimates 2000-2005 closer to 608 Mha/year, predominately in grasslands and Savannahs of Africa and Australia (but also South Asia and South America), and then forested regions. These authors suggest that long-term fire data show a gradual global monotonic increase in wildfire since the last glacial maximum 21,000 years ago (although I have heard contrary insights from fire experts, or they may have been talking more on the scale of 100,000s of years). There is greater percent area burned in the southern hemisphere compared to the northern hemisphere.

Forest fires contribute to carbon balance through immediate release of CO2, CH4 and CO, and slow release afterwards as decay releases more CO2 into the atmosphere. The impact varies among biomes, however. Primary driver for carbon balance in boreal forest. "For fires to spread, there needs to be fuel continuity; some suggest that at least 30% of the landscape needs to have fuel for a fire to spread (Hargrove et al. 2000)." "...understorey shrubs in a forest can act as ladder fuels that carry a surface fire up into tree crowns and generate a much more intense fire." "Cary et al. (2006) found that weather and climate best explained model area burned estimated from landscape fire models compared with variation in terrain and fuel pattern. Carcaillet et al. (2001) found that climate was the key process triggering fire over the eastern boreal forest during the Holocene. Prasad et al. (2008) found that mean annual temperature and average precipitation of the warmest quarter of the year were among the variables that best explained fire occurrence in southern India." Lots of good additional sources and comments on influence of climate on probability of fire.

In regards to future fires, they highlight the importance of weather (climate and wind), fuels and changing vegetation. Humans are the unknown factor. "The FWI (Fire Weather Index) in Canada is expected to increase, but with significant regional variation (Bergeron and Flannigan 1995; Amiro et al. 2001)." 

Area burned (spread) influenced by: size sample area, time, topography, habitat fragmentation, fuel characteristics, season, latitude, fire suppression, fire site accessibility, ignitions, climate-weather and simultaneous fires.

In Canada: "Area burned was projected to increase by as much as 5.7 times the present values, but for many sites, the historical area burned (1600s to near present) was higher than estimated future fire activity."

Ignitions: "The direct effect of climate change on fire occurrence will be through fire weather, as it affects the moisture content and sustained ignition of fuel." "In a study of wildfire in the western USA, Westerling et al. (2006) found that fire season length had increased by over 2 months over the 1980s, using data from 1970 to 2003, and attribute the earlier start of the fire season to earlier snowmelt from higher spring and summer temperatures. In a case study in the province of Ontario, Canada, analysis of the date of initial fire activity showed progressively earlier starts to the fire season over the last two decades (R. McAlpine, pers. comm.)."

Authors also address fire intensity and severity. "It was suggested by Stocks (1993) that under climate change, a disproportionate number of fires may escape initial attack, resulting in very significant increases in area burned. The reasoning behind this hypothesis was that there tends to be a very narrow range in the transition between the overall suppression systems success or failure."

##Mann, M.E., Rahmstorf, S., Kornhuber, K., Steinman, B.A., Miller, S.K., and Coumou, D. 2017. Influence of anthropogenic climate change on planetary wave resonance and extreme weather events. Nature Scientific Reports 7: 45242.
Not directly applicable to models, but applicable to greater rationale for models (not that any new rationale is needed). Abstract (terms were new to me, so summarizing accuratelt was difficult): "Persistent episodes of extreme weather in the Northern Hemisphere summer have been shown to be associated with the presence of high-amplitude quasi-stationary atmospheric Rossby waves within a particular wavelength range (zonal wavenumber 68). The underlying mechanistic relationship involves the phenomenon of quasi-resonant amplification (QRA) of synoptic-scale waves with that wavenumber range becoming trapped within an effective mid-latitude atmospheric waveguide. Recent work suggests an increase in recent decades in the occurrence of QRA-favorable conditions and associated extreme weather, possibly linked to amplified Arctic warming and thus a climate change influence. Here, we isolate a specific fingerprint in the zonal mean surface temperature profile that is associated with QRA-favorable conditions. State-of-the-art (CMIP5) historical climate model simulations subject to anthropogenic forcing display an increase in the projection of this fingerprint that is mirrored in multiple observational surface temperature datasets. Both the models and observations suggest this signal has only recently emerged from the background noise of natural variability."

#Wotton, B.M., Flannigan, M.D., and Marshall, G.A. 2017. Potential climate change impacts in fire intensity and key wildfire suppresion thresholds in Canada. Environmental Research Letters, 12: 095003.
Justification for this study comes from the consensus that future climate will in general make the environment more conducive to fire. Here, the authors use General Circulation Models and carbon emission pathways to generate future fire environment scenarios. They specifically assess how potential for crown fire occurrence and active growth of fire changes with changing climate. Overall, they find that the proportion of days in fire seasons with the potential for unmanageable fire will increase, nearly doubling in some regions.

Borel forest is the focus. They outline literature assessing climate change. For example, Flannigan et al. 2016 suggest that the increased rainfall precicted is more than offset by the estimated increase in evapotranspiration from fuels, resulting in drier fuel overall. They also suggest the issue with fires not accounting for the increase in lightning activity. Early models suggested that a moderate increase in ignitions can lead to a disproportional increase in escaped fires. They suggest that part of the increase in escaped fires estimated is a result og future fireline intensity exceeding thresholds beyond which suppresion resources could be effective.

Data used: entire forested region of Canada. Used fuel data from 16 Canadian Forest Fire Behaviour Prediction (FBP) system from the Canadian Forest Service, at 250 m x 250 m resolution. Data was summarized into 40 km x 40 km grid cells across Canada. Weather: used FWI System to get daily outputs from three GCMs to resconstruct daily fire weather. Future climate scenarios based on differing levels of end of century radiative forcing (RCP2.6, 4.5 and 8.5). Baseline time: 1971-2000. Future periods: 2021-2040, 2041-2060, 2061-2080, 2081-2099. Fire behaviour: Canadian FBP System used as primary source of fire behaviour predictions, and estimated changes in headfire intensity between current and future time periods. Analysis: for future, used both absolute values and percent change. They define a Spread Event Day Probability (SEP).

Results: Temperature increased in short and long term, with greatest increase in RCP8.5. For precipitation, there are areas of increase and others of decrease. They found little change in wind speeds and thus did not report this metric. Fire Fuel Moisture Code (FFMC) and Duff Moisture Code (DMC) generally predict drier conditions. They predict increased fireline intensity and fire rate of spread into the future. Crown Fraction Burned (CFB) above the 0.1 threshold shown to increase by 3-40% across the different scenarios for near future, and 30-140% for far future. Mean number of actual days a fire could spread increased 6-20% for near future and 30-92% for distant future. Increases in the average number of days per fire season increased 2-55% in near future and 28-195% in distant future scenarios.

Increased frequency of crown fire in the boreal forests of primary concern since this will lead to increased unmanageable fire --> also leads to increased carbon emissions. Despite increased predictions, this may not result in increased area burned if fire suppression techniques can help prevent.

##Halofsky, J.E., Peterson, D.L., and Harvey, B.L. 2020. Changing wildfire, changing forests: the effects if climate change on fire regimes and vegetation in the Pacific Northwest, USA. Fire Ecology, 16:4.
Large and severe fires are associated with hot and dry conditions, and it is predicted that climate will become more hot and more dry. Predict longer fire seasons, likely increasing frequency and extent of fires. They predict that interactions with drought and insect damage likely to be main drivers for ecosystem change. Hotter, drier sites may be at particular risk of regeneration failures, in part from high reburn possibility. Such results can help managers allocate resources to where to implement fuel treatments, or fire breaks in ecosystems where fuel treatments tend to be less effective (e.g., wetter, high elevation sites and coastal forests). 

Year with relatively warm and dry conditions have lead to greater area burned; decreasing fuel moisture in combination with these conditions result in large areas of dry fuels that are more likely to ignite. In some areas, fire resistant trees have been heavily logged. 

This paper is a synthesis paper that utilizes: (1) long-term paleoecological studies; (2) medium-term (decades to centuries) fire history studies; (3) near-term (years to decades) studies on trends in vegetation and fire associated with recent climate change; (4) forward-looking studies using modelling to predict future fire and vegetation change; and (5) recent synthesis focused on potential climate change effects. 

##Davis, K. T., Dobrowski, S. Z., Higuera, P.E., Holden, Z.A., Veblen, T.T., Rother, M.T., Parks, S.A., Sala, A. and Maneta, M.P. 2019. Wildifes and climate change push low-elevation forests across a critical threshold for tree regeneration. PNAS 116(13): 6193-6198.
Climate change is increasing fire activity and has potential to accelerate climate-induced shifts in vegetation communities. Via: (1) killing adult trees that would otherwise survive climate shifts (2) making areas no longer suitable for seedling establishment and survival. Here, the authors investigate relationship between annual climate and post-fire regeneration of Douglas Fir and Ponderosa Pine. They found a non-linear response for recruitment, but instead thresholds based on vapor pressure deficit, soil moisture and max surface temperature. They found that three thresholds had been crossed over the prior 20 years, making conditions increasingly unsuitable for regeneration. These results were exacerbated by high fire severity and low seed availability. They conclude that there will likely be an ecosystem transition in low-elevation PP and DF ecosystems.

The intro focuses on how we do not always see gradual changes, but how we instead sometimes see abrupt changes once thresholds are exceeded. Additionally, some systems may oscillate between two states before a transition occurs. Sometimes these abrupt ecosystem transitions can result in non-forested states. Used boosted regression trees. 

##Tepley, A.J., Thomann, E., Veblen, T.T., Perry, G.L.W., Holz, A., Paritis, J., Kitzberger, T., and Anderson-Teixeira, K.J. 2017. Influences of fire-vegetation feedbacks and post-fire recovery rates on forest landscape vulnerability to altered fire regimes. Journal of Ecology, 106: 1925-1940.
With ongoing climate change, forests face the risk of conversion to non-forest vegetation through alteration of fire regimes and post-fire recovery dynamics. Here, the authors develop a mathematical model to understand fire-vegetation feedbacks and forest recovery time with altered fire regimes. Some possibilities: when early-seral forests < fire-prone than older forests --> negative feedbacks limit forest loss; conversely, with more flammable early-seral forests resulted in positive feedback loops and produced a tipping point that resulted in extensive forest loss. Additionally, this conversion to non-forest habitat was faster than forest re-expansion rates.

Fire modifies vegetation composition and structure via effects on fuel amount and type, fuel connectivity, and canopy-mediated influences on micro-climate and fuel moisture (MacDermott et al. 2017; Ray et al. 2005). Example where expect positive feedback loop: fire burns trees and converts to shrub dominated landscape that dries more readily. Example negative feedback: Borel or alpine environment changes to deciduous based forest that burns less readily. Invasive plant species could promote either pattern, depending on their flammability and interactions with other plants in the area. High severity fires can hinder seedling establishment or growth, or can deplete seed sources. 

These models focused only on high severity fires that cause complete or nearly complete above-ground mortality of trees. 

##Alizadeh, M.R., Abatzoglou, J.T., Luce, C.H., Adamowski, J.F., Farid, A. and Sadegh, M. 2021. Warming enabled upslope advance in western US forest fires. PNAS, 118(22): e2009717118.
These authors found that from 1984 to 2017 that the elevation of fires has increased by 252 m (median), making elevations > 2500 m more often burned. They conclude that this change is concurrent with climate change and may have dramatic effects given historic fire return intervals that were once much longer (one to multiple centuries). Also, the rate of increase in number of fires is occurring disproportionately more at higher elevations than at lower elevations. Paleoecological records show increased occurrence of high elevation fires during warm epochs during the Holocene. This paper outlines a lot of good background to the issues that climate change presents for future fires: longer snow-free periods, less fire-season precipitation, increased evapotranspiration, increased convective storms and lightning strikes. Part of the importance of this work is that the ecosystems they studied the increase in fire frequency and range is an ecosystem that is not usually disturbed by anthropogenic sources/causes (land use change, for example), and thus are more likely a direct result of climate change. Some of the impacts of increased elevation of fires include: biodiversity loss, vegetation conversion, change in snowpack, landscape transformation. Other consequences: can remove standing trees which help anchor snow, resulting in increased snowpack and avalanche activity; reduce sediment retention, which can expose bedrock and change river morphology and floodplain extent. Stream temperatures in burned areas can be 2-3 times greater than in non-fire affected regions, which can cause extinction of some endemic species.  

   

########### Additional resources related to Timber Supply from Kelly ###############

##Fall, Andrew. SELES Spatial Timber Supply Model (STSM): Parameterizing landscape-scape natural disturbance. January 2019.
Variation in fire result of: (1) forest types; (2) climate; (3) geography and (4) access. Key here is to define the disturbance agent, the area, and specific parameters. Agents include: fire, insects, windthrow, slides, flooding and drought.The agent must affect stands or larger scale, is significant enough to affect timber supply, sufficient knowledge available to develop parameters. Must determine zones for each agent based on where it can or cannot occur, and where the agent has different characteristics due to climate, tree species or other factors.  BEC zones or NDTs offer a great zone division for fires. Natural Analysis Unitd (AUs) may have multiple disturbance agent within, or only one. It is key that credible parameters can be derived for each disturbance agent. In STSM, must define: (1) rotation (i.e., number of years it takes to disturb an area equal to the whole area); (2) rotation coefficient of variation (variability in annual disturbance); (3) proportion of immediate loss (the percentage made directly unmerchantable by the agent immediately); (4) shelf life (number of years merchantable dead volume is available for salvage); (5) stand preference (influence of stand age and volume on probability that agent will impact cell); (6) patch size distribution (target size of each disturbance patch).

Wildfire parameters defined: summarize for a given study area, the number of fires, mean fire size, area burned per year and rotation by BEC variant and province wide. Rotation years can also be seen in the Biodiversity Handbook.

##Fall, Andrew. SELES Spatial Timber Supply Model (STSM): Assessing potential effects of climate change on natural disturbance and timber supply. January 2019.
Here, authors used ClimateBC Projections at 400 m x 400 m resolution under different CGM scenarios to estimate changes in landscape-scale fire disturbance. The overall results suggest that future changes to natural disturbance caused by climate change can have significant near-term effects on timber supply.

Used historic normal, RCP 4.5 and RCP 8.5. Also had data on disturbance agents for Mountain Pine Beetle, Spruce bark beetle and Spruce 2-year Budworm, using results from previous TSR reports and general information on the species. Scenarios assessed included base management, no salvage and salvage as a priority. They set loss of merchantable timber to 10% after fire. Fire size was summarized (mean) by BEC zone. Shelf life set at 10 years for all fire zones. Ignition set as random. Fire size set as negative exponential based on distribution historic fire size. Using past data on fire size (ha), beetle spread, etc., variables were input into the model to match. They created a variable called "sumFireWeather" that takes the number of days with >10'C for each of 2025, 2055 and 2085, and used this variable to estimate the change in fire rotation.

The final figure needs some time for me to understand, but it seems that all scenarios see an appreciable drop in harvest levels after 2020, with RCP85 causing the greatest drops, and not salvaging in 4.5 and 8.5 causing the most severe of drops. The best scenario was salvaging with no change in carbon conditions.

Cora: it would be very interesting to compare results from such an analysis as above to the model outputs we create from this module being developed.


##Tranche Analysis- Kelly Izzard
"Uncertainties associated with landscape-scale natural disturbance and potential effects from climate change, as well as management response (e.g., salvage), lead to uncertainty related to the degree of reliance on natural disturbance assumptions in timber supply projections. To address these uncertainties, timber supply analysis in support of the timber supply review process can be viewed as risk assessment." Perfomed structured sensitivity analysis.

Define risk classes:
"	Geographic areas (e.g., high productivity, low elevation forests with good road access vs. lower productivity, high elevation forests that requires heli- access or expensive road constructions)
	Forest type (e.g., cedar vs. hemlock that have different market values; old growth vs. second growth)
	Regeneration assumptions (e.g., unmanaged natural regeneration vs. heavily managed regeneration with thinning, genetic improvements and fertilization)
	Natural disturbance (e.g., assumptions of low vs. high recovery of salvage)
	Climate change (e.g., historic wildfire levels vs. increased wildfire, climate refugia)"

"Under the RCP8.5 scenario the frequency of fire and area burnt increase approximately five-fold over (450% increase) in the first 100 years relative to the base case, with on average 84% of the disturbance occurring in the non-contributing portion of the TSA (the THLB makes up approximately 28% of the forest estate). Area burnt in the THLB increases from an average 1000 ha/year to 2800 ha/years or approximately a three-fold increase."

"The increased loss from increased fire has the effect that short-term harvest can technically increase (subject to modest-size steps as harvest potential declines) without exacerbating the low point of the timber supply flow. This is in part because logging timber that has a high chance of burning in the future may have little impact on future timber supply. However, this is somewhat a technical anomaly in the sense that it this is due to how timber supply is assessed as a maximization process. The tranche approach help contextualize potential short-term opportunity to cut timber that may be at risk due to climate change in terms of expectations of worsening potential declines as the system adjusts to new natural disturbance regimes."

"A key message from this analysis is that even modest climate change (RCP 4.5) has the potential for significant disruption to timber supply based on more optimistic assumptions (e.g., projecting historic fire). While the parameters derived for this analysis could certainly be refined and improved, it seems reasonable to expect increased fires due to a combination of increased fire season length, increased change of fires crowning and increased fire intensity (decreased suppression potential). Combined, this suggests that there can be an expectation of a protracted time period of adjustment, and increased timber production from salvage (which may interact with the economic aspects of the geographic risk analysis). 

That said, the analysis also indicates that there is a window of a couple of decades over which the timber supply in the fire risk scenarios with salvage are similar. This represents a planning opportunity to refine understanding of how climate change may affect this landscape and improve anticipation of appropriate strategic forest management response."

##Whitman, E., Batllori, E., Parisien, M-A., Miller, C., Coop, J.D., Krawchuk, M.A., Chong, G.W., and Haire, S.L. 2015. The climate space of fire regimes in north-western North America. Journal of Biogeography 42: 1736-1749.
These authors characterize fire-regime components along climate gradients and a gradient of human influence. They used a multivariate framework to collapse 12 climatic variables into two major climate gradients and binned them into 73 discrete climate domains, and examined variation in fire-regime components (frequency, size, severity, seasonality and cause) across climate domains. Results: A primary climate gradient of temperature and summer precipitation and a secondary gradient of continentality and winter precipitation in the study area were identified. Conclusions: Wildfire activity is highest where thermal and moisture gradients converge to promote fuel production, flammability and ignitions.

"Fire frequency in an area affects plant communities, for instance, by disrupting tree growth cycles and the availability of seeds, whereas fire size influences landscape patchiness and the regeneration of local vegetation communities. Fire seasonality may constrain vegetation recovery and influences fire intensity and burn severity (Zedler, 1995; Stocks et al., 2002), which is a measure of ecosystem change and fuel consumption that may determine post-fire vegetation dynamics (McHugh & Kolb, 2003; Parks et al., 2014)." ... "Globally, fire frequency
varies reliably along gradients of productivity and fuel availability in drier regions, and gradients of temperature in wetter, biomass-rich areas (Krawchuk & Moritz, 2011; Pausas & Ribeiro, 2013)." ... "Humans influence fire regimes via ignition, suppression and other land-use practices that alter fuel availability, type and continuity. Such influences can entirely decouple natural environmental controls of fire regimes (Syphard et al., 2007; McWethy et al., 2013)."

"The goal of this study is to increase understanding of the spatial pattern of fire-regime components and their relationships to one another and to human influence in a broad climatic context. To meet this goal we examine fire regimes within a quantitative framework, integrating both human and climatic gradients. We: (1) collapse climatic variables into two climate gradients that define the climate space of the study area using a multivariate technique; (2) position fire-regime components of a spatial database of large fires along these climate gradients and a gradient of anthropogenic influence; and (3) explore relationships among fire regime components and their drivers."

Great background for coverage area, incluidng max and min of mean temp and precip, and description of vegetation. "Wildfires occur less frequently at high elevations and in temperate and coastal rain forests."

Downsacled data: "The DEM was resampled to a continuous 2-km resolution raster with an Albers equal-area conic projection... Climate WNA (Wang et al., 2012) to downscale climate data from the PRISM Climate Group for the 19812010 climate normals period (Daly et al., 2002)."

Fire size limitation: "The resulting database was limited to fires larger than 385 ha that burned during the 19842011 time period, reflecting the timeline and processing methods of the MTBS, and includes both wildfires and prescribed burns"

"Canada does not have an equivalent national initiative to characterize burn severity, we consulted MTBS staff and replicated methods for image processing and dNBR (difference normalized burn ratio) calculation for Canadian fires. This analysis used multispectral imagery from the Landsat 5 and 7 satellite sensors retrieved from the USGS Global Visualization Viewer website (US Geological Survey, 2014) and computed in the R package landsat, version 1.0.8 (Goslee, 2011; R Core Team, 2013)."

"The human influence in the study area was represented by the Wildlife Conservation Society Global Human Footprint Index version 2, 2005 (HFI; Sanderson et al., 2002). The HFI is a synthesis of nine datasets representing population density, land transformation, accessibility and electrical power infrastructure."

"To characterize climatic variation of the study area the 12 climate variables (Table 1) were collapsed into two orthogonal components using principal components analysis (PCA)." Retained first 2 axes, explained 76% variation together.

"The primary climate gradient in the study area was a latitudinal gradient of temperature and summer precipitation, as indicated by the PCA factor loadings, with temperature increasing to the south and summer precipitation increasing to the north. The secondary gradient was longitudinal, following continentality and winter precipitation, with continental and winter-dry climates increasing eastward." Did not include fuel/vegetation type because argued that climate inherently captures vegetation differences.

"Fire size, burn severity and frequency of fires (proportion burned per year) were interrelated (Figs 5 & 6). Fire size increased as a function of increasing burn severity (deviance explained; DE = 53.4%, P = 0.003), and the frequency and size of fires significantly explained one another (DE = 47.3%, P = 0.003; DE = 46.5%, P = 0.001)." ... "with lightning-caused ignitions increasing through the summer and declining into the fall (DE = 18.8%, P < 0.001)."

"Fire size was not significantly predicted by either gradient alone, but the multivariable model with fire size as a function of both RC1 and RC2 was significant (DE = 78.8%, P < 0.001; Table 2). Fire frequency increased with increasing temperature and summer dryness (DE = 19.9%, P = 0.015), while burn severity increased until moderate conditions on the RC1 gradient were reached and then declined with increasing temperature and summer dryness (DE = 61.1%, P < 0.001). Increasing continentality and winter precipitation had a negative relationship with burn severity (DE = 20.6%, P = 0.026)."

"Fire frequency (proportion of area burned per year) and size were highest at the core of the climate space of fire, supporting the idea that fires primarily occur in an environmental middle ground where favourable climatic conditions for fuels, ignitions and conditions conducive to burning overlap, whereas fire is limited at extremes of precipitation and temperature in the climate space"

"During the time period examined, fires were uncommon in relatively dry, warm environments where fuel production is limited (e.g. Wyoming sagebrush steppe) and rare in maritime and winter-wet climates (e.g. the BC coast), with very high levels of moisture and precipitation that limit fire spread (Meyn et al., 2010)."

"Burn severity and fire size are related to fuel availability and the conditions that allow fires to burn, both of which vary with climate (Littell et al., 2009; Bradstock et al., 2010; Abatzoglou & Kolden, 2013)."

"Shifts in vegetation communities as a result of climate change may be strongly mediated by disturbances such as fire (e.g. by opening areas for colonization by invading species; Schneider et al., 2009). These potential changes may be more apparent where fire-regime component characteristics are on the edge of their climate envelope, as future climate change may push these characteristics beyond their current bounds."

"Large fires tend to have heterogeneous levels of burn severity and may contain larger, continuous areas of severely burned stands (related to higher values of dNBR), whereas smaller fires may be dominated by one level of burn severity (Turner et al., 1994; Birch et al., 2014)."

"Fire regimes can have strong influences on vegetation composition and structure; for example the relationship between frequent, low-severity surface fire regimes in open stands of western ponderosa pine (Veblen et al., 2000), the infrequent, high-severity stand-replacing crown fires that characterize more densely-stocked subalpine forests (e.g. Yellowstone National Park; Turner et al., 2003), or the infrequent surface fires that create mosaics of burned and unburned areas in sagebrush ecosystems (Baker, 2006). Variation in burn severity and fire size leads to different successional trajectories for vegetation recovery (Turner et al., 1997; Johnstone & Chapin, 2006), and plant productivity - the production of fuel  is dependent on site characteristics and climate."

"...with low burn severity where human-caused ignitions dominated. This may be as a result of where and when fires burn: human-caused fires (both prescribed and accidental ignitions) often occur in the spring under less favourable conditions for high severity, whereas lightning fires may ignite in remote areas where they become large and burn under a range of conditions (Stocks et al., 2002)."

##Dillon, K.D., Holden, Z.A., Morgan, P., Crimmins, M.A., Heyerdahl, E.K., and Luce, C.H. 2011. Both topography and climate affected forest and woodland burn severity in two regions of the western US, 1984 to 2006. Ecosphere, 12: https://doi.org/10.1890/ES11-00271.1
"Severe fires kill and consume large amounts of above- and belowground biomass and affect soils, resulting in long-lasting consequences for vegetation, aquatic ecosystem productivity and diversity, and other ecosystem properties... Together, topography, climate, and weather explained severe fire occurrence with classification accuracies ranging from 68% to 84%. Topographic variables were relatively more important predictors of severe fire occurrence than either climate or weather variables."

"...but much less is known about the degree of ecological change (i.e., burn severity) caused by wildfires (Lentile et al. 2006, Lentile et al. 2007, Keane et al. 2008, Keeley 2009)."

"The primary factors typically thought to control fire intensity and duration are topography, weather, and fuels (Pyne et al. 1996). Many have argued that accumulation of fuels from fire suppression during the past century is influencing the occurrence of high severity fire today (Keane et al. 2002), while others have argued that weather is the primary driver of fire behavior (Bessie and Johnson 1995)."

"The effects of topography on fire behavior (ignition, spread, intensity) have been the subject of much research (Pyne et al. 1996), and some studies have focused on burn severity relative to topography (e.g., Kushla and Ripple 1997, Broncano and Retana 2004, Holden et al. 2009). Topography affects energy and water balances that control vegetation development, and therefore the accumulation of biomass that fuels fires when it is sufficiently dry. Furthermore, elevation, aspect, latitude, longitude, topographic position, and surrounding topographic context all influence microclimatic conditions (temperature, precipitation, direct solar radiation, wind exposure, etc.) that influence the moisture content of fuel. Physical properties of fires such as combustion rate, fuel consumption, total heat, and soil heating in turn cause changes to vegetation and soils that form the basis for describing or estimating burn severity (Pyne et al. 1996, Keane et al. 2010)."

"First, drier conditions generally increase the net energy released from fuel during burning. In New Mexico, for example, area burned severely was correlated with the duration of rain-free periods in the spring preceding the fire (Holden et al. 2007). Second, more fuel, including logs, duff, and tree crowns, is likely to be consumed if fuels are dry than if they are not (Pyne et al. 1996), and significant consumption of crown fuels can lead to severe fire effects. Third, Pierce and Meyer (2008) hypothesized that multidecadal climate influenced the occurrence of large, severe fires in past millennia."

"Bigler et al. (2005) hypothesized that the local effects of fuels and topography decline with increasingly severe fire weather, particularly across short elevation gradients."

"Calculated from pre- and post-fire Landsat TM and ETM imagery, dNBR and RdNBR both use light reflected from earth in near-infrared (Landsat band 4) and mid-infrared (Landsat band 7) wavelengths to capture fireinduced changes in vegetation cover and soil characteristics. While dNBR provides a measure of absolute change, RdNBR is adjusted to account for pre-fire conditions at each pixel. As such, RdNBR provides a more consistent measure of burn severity than dNBR when evaluating severity across broad regions and diverse vegetation (Miller et al. 2009a, Norton et al. 2009), including sites with low preburn biomass... We define burn severity, therefore, as the degree of change one year post-fire relative to pre-fire conditions (Lentile et al. 2006) as measured by RdNBR."

Determine severity "ensure that post-fire imagery was taken six to 18 months post-fire and that pre- and post-fire images were taken in the same season (+/-60 days). By using satellite imagery from approximately one year post-fire, we inherently included some delayed effects of fire such as plant mortality and resprouting, which can be influenced by factors other than fire (Keeley 2009). Management actions such as salvage logging, reseeding, and planting can also occur during the first year after fire, potentially influencing RdNBR values."

"Using methods similar to Miller and Thode (2007), we used a non-linear equation to regress RdNBR against CBI (R2  0.69) and calculate a threshold for severely burned equivalent to CBI values above 2.25 (RdNBR  695; Fig. 3). Field-measured CBI values of 2.25 represent the midpoint between moderate and high severity for rating factors such as surface fuel consumption, soil heating, plant mortality, and alteration of foliage at different heights above the soil surface (Key and Benson 2006)."

Topography included: elevation, "slope and aspect, slope position and curvature, and topographic complexity. Our indices of slope and aspect were percent slope, heat load index (McCune and Keon 2002, Eq. 3), solar radiation aspect index (Roberts and Cooper 1989), and an index combining slope and cosine-transformed aspect (Stage 1976). Indices of slope position and curvature were hierarchical slope position (Murphy et al. 2010), compound topographic index (Moore et al. 1993), and a topographic position index (Weiss 2001) that we calculated at three spatial scales (annular neighborhoods with 150 m, 300 m, and 2,000 m outer radii ). Indices of topographic complexity, also calculated at three spatial scales (circular neighborhoods with 90 m, 450 m, and 810 m radii ), were Martonnes modified dissection coefficient (Evans 1972) and elevation relief ratio (Pike and Wilson 1971). Prior to modeling, we eliminated variables that were highly correlated with others (Spearmans rho . 0.75). From our 16 candidate topographic predictor variables, we retained between 12 and 14 variables in each ecoregion (Appendix A)."

Climate variables: normalized monthly temperature and precipitation, soil moisture, and fire weather. "To capture the departure from average conditions at each fire location, we took the monthly values for the year of fire and the previous year, and normalized them by subtracting the 56-year mean for that month and location and dividing by the standard deviation."

"For the 10-day period starting on the detection date of each fire, we determined the maximum and mean values of the Fosberg fire weather index (FFWI; Fosberg 1978) and wind speed, and the number of days with FFWI above the 90th percentile and wind speed above 20 miles per hour."

Used Random Forest models. Good discussion included regarding the pros of such approaches. They also described how to run multiple runs and exract the "variable importance", and then classify them from least to most important from the mean of al the Random Forests. Used three measures of accuracy, averaged across the cross-validated replicates of the optimal models: overall percentage correctly classified (PCC), kappa, and area under the receiver operating characteristic curve (AUC). They assumed that AUC values of 0.7, 0.8, and 0.9 indicate fair, good, or excellent accuracy, respectively (Swets 1988). "To evaluate the influence of specific variables on burn severity, we generated partial dependence plots from our optimal Random Forest models. These plots display the relationship between individual predictors and the likelihood of high severity fire, showing how different values of each predictor affect the response while holding other variables constant at their average (Cutler et al. 2007)."

Results: "Across all ecoregions, topography had the most influence on the probability of a location having high burn severity, but climate before and during the fire also contributed significantly... Topography variables always scored better than climate variables... For all models, the top five topographic variables always included elevation in the first or second rank followed by the macroscale topographic position index (2000 m), often in second rank. Pixel-scale slope and aspect variables were also included in the top five variables in all models, indicating an important influence of finer-scale topography as well. Climate variables were included in all of the best models, and always included conditions both before and during fires. However, two fire weather variables (wind speed and FFWI) were rarely important. Antecedent temperature and precipitation variables were included in the best models for all ecoregions. Severe fires more common at high elevations in other years, but low elevations in big years. Regardless of year, severe fire is generally more likely at sites with low to moderate heat load (generally northwest through southeast aspects)."

Discussion: "Previous studies have found high burn severity more on north-facing slopes than south-facing slopes in Southwest and Rocky Mountain ecosystems (Bigler et al. 2005, Holden et al. 2009: Fig. 3), and we generally found the highest probability of severe fire on sites with cooler aspects as well. The relatively cool and wet environment of upper elevations and northerly aspects can result in more total biomass available to burn than in more open forests and woodlands at lower elevations and warmer aspects. Although the cooler and wetter sites burn less often, when they do burn they are more likely to experience crown fires, resulting in a higher degree of change.... when all slope aspects are available to burn during the summer droughts characteristic of the Mediterranean climate there, it is likely that the drier conditions found on warmer aspects can lead to an increased probability of severe fire on those sites. Likely, the type of coarsescale weather and climate variables we analyzed condition fuels and make them available for burning (i.e., relatively wet conditions that lead to an abundance of fine fuels or relatively warm and dry conditions that decrease fuel moistures). Some of the topographic variables in our analysis may act as indirect proxies for more direct, physically-based variables that would better capture interactions among topography, climate, and weather and their effects on fire behavior and burn severity. For example, the topographic dissection indices used here have been related to the location of snow drifts, as well as patterns of nocturnal air temperatures (e.g., cold air drainage) and relative humidity in the northern Rockies (Holden et al. 2011)."

"Our ability to predict whether a pixel burned severely was consistently lower during years of widespread fire, or framed another way, fire burned more indiscriminately in big years. In relatively cool, wet fire seasons for example, north-facing slopes at high elevation are unlikely to burn due to delayed snowmelt timing, low solar insolation, low vapor pressure deficit, and low surface air temperatures (Holden and Jolly 2011). Thus, until climatic and moisture conditions become conducive to fire spread on a large enough portion of the landscape, as occurs in big years, terrain can impose spatial constraints on fire spread and intensity, limiting the influence of short term weather and climate factors."

Potential limitations: "It is possible that the consistently higher performance of topographic variables in the Random Forest models is an artifact of the difference in spatial scale. Topographic variables were at the same spatial resolution (30-m) as the fire data, while the climatic variables were coarser. Also, by not including maps of actual vegetation type, structure, and fuels we ignore many landscape factors (e.g., previous fires, thinning, timber harvest, and insect-induced tree mortality) that would likely influence satellite-inferred burn severity. Finally, many of these fires represent those that escaped initial suppression efforts. Thousands more were successfully stopped before reaching mapable size."

"Moving forward, studies such as ours that include information on pre-fire fuels and vegetation, as well as finer-scale climate and weather, will be important. Analyses for particular vegetation types and/or elevation ranges may also be useful, as both recent trends and drivers of burn severity may differ among ecosystems (Miller et al. 2009b), just as drivers of fire occurrence differ with vegetation type (Littell et al. 2009)."

##Spittlehouse, D.L., and Dymond, C.C. 2022. Interaction of elevation and climate change on fire weather risk. Canadian Journal of Forest Research, 52: 237-249.
