---
title: "Getting Started with CLUS"
author: "Tyler Muhly"
date: "03/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Introduction
Here we document how to get started using the caribou and land use simulator (CLUS) model. This provides the basic instructions for implementing and running a scenario on CLUS.

Fundamentally, the CLUS model is a forest harvest simulator with the ability to flexibly "constrain" areas of the landscape to simulate alternative forest management regimes. These alternative regimes constitute specified areas ('zones') with defined forest targets (e.g., percentage area of a certain forest age). Thus, it can be used to test how alternative forest management zones influence the spatial distribution and rate (i.e., annual volume cut) of forest harvest. However, CLUS also includes various modules that provide caribou-specific indicators. Thus, the CLUS model can also be used to estimate the influence of alternative forest management regimes on caribou. Below we provide instructions for implementing a forest harvest scenario in CLUS. We provide the basic structure of the model, including data and parameter inputs needed to run the model.

## Model "Software" and Framework
CLUS is primarily built using [R programming language](https://www.r-project.org/), with a dash of JAVA in the module to create harvest blocks. An advantage of using R is that it is supported by many users that are actively creating 'packages' to do various analytical functions. There is a strong library of statistical packages, but also a diversity of data management and visualization packages. Working in R therefore provides a lot of flexibility. R packages are also typically well documented, so it is usually straighforward to learn how to use and apply the functions in a given package. 

The CLUS model proper is implemented using the [SpaDES package](https://spades.predictiveecology.org/). SpaDES provides a structure for implementing discrete-event, spatial simulation models, not unlike what a SELES model does. Importantly, SpaDES provides functions to manage 'events' in a model. Events are scheduled within 'modules' that represent independent processes within a model. Modules, and events within them, are scheduled and then actioned using SpaDES functions. 

All the programming code needed to run CLUS is available on [GitHub](https://github.com/bcgov/clus), an internet repository for developing software code. It is provided under the [Apache 2.0 software license](https://github.com/bcgov/clus/blob/master/LICENSE). To run the software on a local computer, you will need to [clone the repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository) code to that computer. We assume that you have an understanding of how to use program R, and R interfaces like [RStudio](https://rstudio.com/), and thus we do not go into detail on those here. 

The CLUS GitHub folder structure is complex, as it contains a lot of analysis code that are peripheral to running the CLUS model. However, much of this code can be ignored, unless you are interested in understading some of the more detailed analyses completed to parameterize the CLUS model. The key code for running the CLUS model is located in the R->SpaDES-modules, R->Params and R->functions folders.

The R->functions folder contains a script and instructions for setting up password protection with the keyring function ("keyring_init.Rmd"). It also contains a script called "R_Postgres.R" with custom R functions for querying and manipulating data in the PostgreSQL database. These functions refer to some additonal custom SQL functions created within the PostgreSQL database (these must be loaded into whichever PostgreSQL database you are using). For example, there are functions for clipping raster data to a polygon. These functions are referred to within the CLUS modules, and therefore it is important to preserve and maintain these functions within the folder structure.  

The R->Params folder contains various .Rmd scripts for creating data and parameters needed to run the CLUS model. Many of these were used to create forest harvest constraints across the province. The "proposed_uwr_init.Rmd", "prov_manage_objs.Rmd", "uwr_cond_harvest.Rmd" and "wha_cond_harvest.Rmd" are scripts used to identify the location (rasters) and type of forest harvest constraints (table) to apply to those locations for each specified management area. These include 'typical' constraints used in timber supply models to support timber supply reviews. The "prov_manage_objs.Rmd" develops constraints related to biodiversity emphasis options (BEO), fisheries sensitive watershed areas (FWs), visual quality objectives (VQOs), old growth management areas (OGMAs), parks and protected areas and community watersheds across British Columbia. The "uwr_cond_harvest.Rmd" and "wha_cond_harvest.Rmd" files develop constraints around government action regulation (GAR) orders, including unglate winter ranges (UWRs) and wildlife habitat areas (WHAs), respectively. Forest harvest constraints in some of these GAR order area are complex, and are subject to interpretation (see [UWR](http://www.env.gov.bc.ca/wld/frpa/uwr/approved_uwr.html) and [WHA](http://www.env.gov.bc.ca/cgi-bin/apps/faw/wharesult.cgi?search=show_approved) orders), but these can be reviewed  and modified as requried using the script. There are also scripts for defining proposed areas and forestryconstraints, for example, within caribou herd ranges ("caribou_herd_raster.Rmd") and critical habitat areas ("criticalHabitatRaster.Rmd"). Other scripts can be used to identify areas of interest ("areaofinterestRaster.Rmd") for summarizing volume and area of forest harvested, and forest harvest unit areas ("study_area_boundaries.Rmd"), e.g., timber supply areas.

The R->SpaDES-modules folder contains the bulk of the scripts that run the model functions. Each folder within the directory contains a "module" of the model. Detailed information on the modules are provided in .rmd files within each module folder, and these modules will be desribed in more detail below.

## Data Framework
At a minimum, CLUS needs an SQLite database to function. This databases houses the data needed to run the forestry modules (e.g. forest inventory characteristics, yield curves and zone constaints). This database is created by running the "dataLoaderCLUS" module, hwoever, previously created databases can be used to run scenarios, i.e., it's not necessary to run the "dataLoaderCLUS" module each time you want to run a scenario or set of scenarios. 

If you do not have an SQLite database then you will need to run the "dataLoaderCLUS" module (needs to be run to create described in more detail below). This module requires connecting to a a [PostgreSQL database](https://www.postgresql.org/). We use PostgreSQL because it is an open source (i.e., free), relational database with high performance capabilities (e.g., it can be used to store and query large datasets efficiently and quickly), and it is widely used in the Forest Analysis and Inventory Branch (FAIB). Here we do not go into detail on how to use PostgreSQL, but working knowledge of the database will faciliate your abiltiy to use CLUS (although, we note that you could program an interface that connects the model to any preferred database). 

The "dataLoaderCLUS" module connects to a PostgreSQL database using the ["DBI" package](https://cran.r-project.org/web/packages/DBI/index.html). We have the model configured to connect to a PostgreSQL database on a network computer, with passwords protected using the ["keyring" package](https://cran.r-project.org/web/packages/keyring/index.html). These configurations can be modified to connect the CLUS model to any local or network PostgreSQL database, or you can request permission to use our database. Either way, the PostgreSQL houses the 'core' data needed to run the CLUS model, i.e., source datasets for the model, which typically cover the extent of British Columbia, and are updated relatively infrequently (annually or less). 

## SpaDES Modules
### dataLoaderCLUS
The "dataLoaderCLUS" module compiles data on forest inventory and stand yields, the timber harvest land base, identifies harvest blocks and builds roads to those blocks, and defines management zones and their contraints for the area of interest (i.e., the landscape where you want to simulate forestry activity and caribou indicators). The area of interest could be any portion of British Columbia, but is typically a forest management unit, like a timber supply area or tree farm licence area. The dataLoaderCLUS module takes these data from a PostgreSQL database and compiles it into a SQL Lite database for the area of interest.

Many of the data in the PostgreSQL database are defined as "parameters", within the R->Params folder. To run the "dataLoaderCLUS", you need to have created the following spatial files within the PostgreSQL database that yuo will be connecting to (parameter names as they are named in the "dataLoaderCLUS" module are indicated in parentheses):
- the analysis unit boundaries file, e.g., timber supply areas (nameBoundaryFile) 
- the column/field in the analysis unit boundary file that contains the names of each unique area of interest  (nameBoundaryColumn)
- the name of the area of interest, as defined in the column (nameBoundary)
- the geometry type in the analysis unit boundary file (nameBoundaryGeom)
- the rasterized version of the analysis unit boundaries (nameCompartmentRaster)
- the value attribute table (VAT) that links the integer values in the analysis unit raster to the name of the area of interest (nameCompartmentTable)
- the raster of the timber harvest land base (nameMaskHarvestLandbaseRaster)
- the rasters of each zone where a forest harvest constraint will be applied, including all zones in the 'business-as-usual' or alternative forest managment scenarios (nameZoneRasters)
- the table where the constraints for each raster zone are defined (nameZoneTable)
- a raster with a unique integer id for each unique 'natural' forest stand yield curve, i.e., Variable Density Yield Projection (VDYP), corresponding to the raster pixel where that curve applies (nameYieldsRaster)
- the Variable Density Yield Projection yield table, which can be linked to each stand by the unique integer id (nameYieldTable)
- a raster with a unique integer id for each unique 'managed' forest stand yield curve, i.e., Table Interpolation Program for Stand Yields curve, which can be linked to each stand by the unique id (Variable Density Yield Projection)
- the able Interpolation Program for Stand Yields table, which can be linked to each stand by the unique integer id (nameYieldTransitionTable)
- the forest inventory raster, with a unique integer id for each forest stand in the inventory (nameForestInventoryRaster)
- the inventory data table in the Postgres database (nameForestInventoryTable)
- the column/field in the the forest inventory data that defines each unique forest stand (nameForestInventoryKey), that can be linked to the raster integer id
- the column/field in the the forest inventory data that defines the age of each unique forest stand (nameForestInventoryAge)
- the column/field in the the forest inventory data that defines the height of each unique forest stand (nameForestInventoryHeight)
- the column/field in the the forest inventory data that defines the crown closure of each unique forest stand (nameForestInventoryCrownClosure)
- the column/field in the the forest inventory data that defines the site index of each unique forest stand (nameForestInventorySiteIndex)

Each raster that is created in the Postgres database conforms to the provincial standard 1 ha raster grid. This facilitates the spatial joining of data from different sources.

The SQLite database includes four tables, called "pixels", "yields", "zone" and "zoneConstraint". The "pixels" table includes (but is not limited) to columns with the unique integer for each pixel in the area of interest, and the potential forest cutblock id, yield curve id's, THLB, stand age, volume, height, crown closure and site index assigned to that pixel, and columns for each relevant zone that identifies which zones the pixel occurs within.    

### Params
Much of the data required by the dataLoaderCLUS can be created and populated into a Postgres database using .Rmd files in the "Params" folder of CLUS (clus/R/Params).

The "criticalHabitatRaster.Rmd" creates rasters of critical habitat areas for caribou, and to define 'constraints' to apply to those areas. It takes polygonal critical habitat data, assigns an integer to each unique herd and type of critical habitat and creates a raster for each unique type. It also allows you to create a 'constraint' table that allows you to identify a forest harvest constaint to each unique raster zonis. The table includes the zone ID integer, the name of the zone, the "variable" to be constrained (i.e., age, height, crown closure, or whatever data is in, or can be created from the 'pixels' table in the SQLite database), the type of constraint (i.e., 'nh' = no harvest, 'ge' = greater than or equal to, or 'le' = less than or equal to), the threshold of the constraint (i.e., the value at which the variable will be constrained), and the "percentage" of the zone that must meet the constraint threshold. For example, if you want to apply a minimum 40% of an zone to be age 40 or more, then for that zone, variable = 'age', type = 'ge' and percentage = '40'.  

Similarly, the "parntershipAgreementRaster.Rmd" 






Here we develop rasters that specify the location of areas of interest for estimating volume by area as outptus from CLUS. Can be used to estimate the contribution of a spatially defined area to annual harvested volume. 







The following not in the SQL lite

The "areaofinterstRaster.Rmd" can be used to create rasters and associated VAT's of areas of interest 


"caribou_herd_raster.Rmd" can be used to to create rasters and associated VAT's for caribou herd areas. These get used in  






- criticalHabitatRaster: where set critical habitat and herd boudanries for cariobu and set constraints for those areas





discuss how can use CLUS scneario tool to create a zone cosnraitn area, and process to get that into SQLite dbase






#### Zone constraints
- zone contraints are specific parameters that relate spatial areas ('zones') to a specific constraint on forestry (or in the future, any land use activity)
- 'standard' appraoch is to at a minimum include zone constraints simialr to what is include in timebr suppyl review models, including:
  - ungulate winter ranges (UWRs)
    - uwr_cond_harvest, rast.zone_cond_uwr
  - wildlife habtiat areas (WHAs)
    - wha_cond_harvest, rast.zone_cond_wha
  - biodiversity emphasis options (BEOs)
    - prov_managae_objs, rast.zone_cond_beo
  - Fisheries Sensitive watersheds (FSWs)
    - prov_managae_objs, rast.zone_cond_fsw
  - Equivalent Clearcut Areas (ECAs)
    - prov_managae_objs, rast.zone_cond_cw
  - visual quality objectives (VQOs)
    - prov_managae_objs, rast.zone_cond_vqo"
  - old growth management areas (OGMAs) - legal - no harvesting
    - prov_managae_objs, rast.zone_nharv
  - Parks and Protected Areas (parks)
    - prov_managae_objs, rast.zone_nharv
    
- additonal zone cotnraints for a particualr sceanrio can be added here, for example, for cariobu:
  - contraints on criticla habtiat 
    - criticalHabitatRaster
  - constaints within herd boudanries 
    - criticalHabtiatRaster
  - Section 11 Partnership Agreement areas
    - partnershipAgreementRaster
    
- the .rmd creates a raster, but also a table that correpsonds to teh raster id
- a table gest created for each zone constaint, and these get aggregated in teh postgres database into the "zone_constraints" table (a 'parent' table in postgres to all the constraint tables)


#### Growth and Yeild Models
- data from TIPSY and VDYP growth adn yeild models gets brought into the model to estimate future paramters of 'managed' and 'natural origin' stands, respecitvely
- volume and height data from TIPSY  data is created via the tipsy_curves.rmd
  - creates a raster of teh inventory stands ids that correpsond to teh tipsy curves
  - volume (tipsy_prov) and height (tipsy_ht_prov) tables created in postgres
- these data come from provincial estimates created by Dave Waddell from FAIB

- data from VDYP comes from provincial estimates created by Wenli Xu from FAIB
  - height, basal area and volume output table is created (vdyp_output)
  - creates a raster to link to appropriate stands in teh forest inventory
  
- linkage between VDYP and TIPSY is made where????


#### Forest Inventory
  - uses [VRI](https://catalogue.data.gov.bc.ca/dataset/vri-2019-forest-vegetation-composite-rank-1-layer-r1-) 
  - input is the spatial invenotry polygon data
    - need to also know the name of the projected age, projected height, site index and crown closure columns for instantiating the inventory and setting constraints 
  - raster of stand id's (rast.vri2018_id) where is this raster created????
  
#### Caribou Habitat Model
- if going to use the cariobu habtait model (resource selection function (RSF)), then need to define which [designatble unit the caribou herds are a part of](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.2323))


### Modules
- in dataLoaderCLUS rmd, need to specify the modules you want to be able to run from the database
  - also need to set the parameters of these modules
  - blockingCLUS set to blockMethod = 'pre' to use the pre-blocking algorithm.....
  - roadCLUS, set roadMethod to 'pre' to create the road netowrk based on landings to the blocks; need to defien a costs surface raster for creatign roads, and teh name of the  raster of teh exsitign roads (rast.crds_all)

### Running Scenarios (forestryCLUS)
- to run sceanrios, satrt with teh forestryCLUS module
  - this module estalshises forest harvest queue and harvest objectives from which forestry activity 
  is simulated

#### Time Intervals
- specify in times 
  - start = 0
  - end = number of intervals, e.g., if using a 5 year interval and want to sim over a 200 year period, end = 40

  
#### harvestPriority
- The harvest queue is established using the 'harvestPriority' parameter
  - the paramter is an SQL query for how to prioritize stand characteristics 
  - it queires the pixels table (i.e., you can prirotize based on any values in teh pixels table)
  - for example 'dist, age DESC, vol DESC' says to priortize based on:
      - 'dist', i.e., distance to disturbed pixel (closest first), then
      - 'age DESC', i.e., descending age (oldest first), then
      - 'vol DESC', i.e., descending volume (highest volume first)
- also need to set the adjacency height constraint (adjacencyConstraint)

#### growingStockCLUS
- you  set the time interval between simulating forest stand characteristics within the growingStockCLUS parameters 
  - growingStockCLUS = list (periodLength = 5); here we simulate teh parameters every 5 years   

#### scenario 
- there is a parameter ('scenario') to name the scenario and provide a brief description of it
  - this can be used to track scenarios and will be uploaded to the server with the app for interfacing with results  
  - for BAU scenario, may need to do several 'test' runs to identify the appropriate harvest flow
  - keep all scenarios and variations in aprametrs as you run them (comment them out) so there is a record

#### harvestFlow
- harvestFlow parameter is where the annual cut level is set
  - will likely need to do multiple test runs to identify an appropriate BAU sceanrio
  - can use AAC dtermination or base-case models form last TSR for analysis unti workign in, but as our model may output differ then these, will likely nee dto test and adjust different leveles.
  - goal for BAU is to get a susitaned flow over 200 year period 
  - creates a list of data.tables where you can set the harvest level by TSA or TFL and for specific time periods 
  - can also set a 'partition' to identify other criteria for allocatign harvest
    - for example, a minimum volume havest criteria of 110m^3^/ha (' vol > 110 ')
  - remeber that if simualting with time intervals >1 year to multiply annual harvest flwo target by the interval

#### patchSizeDist
  - establsihes the size of cutblocks to be harvested adn the frequency to haveset them by natural disturabcen type (ndt), as defined in the Forest Practices Code [Biodiversity Guidebook](https://www.for.gov.bc.ca/hfd/library/documents/bib19715.pdf); NDT's are associated with biogeolcimatic units
  
#### Outputs
- define where table ouputs get uploaded (via 'uploaderCLUS')
- currently we upload to a postgres on a VM server; 
  -  define the area of interest name that (aoiName); this sets the name of the schema wehre tables get uploaded to postgres

- decalre in outputs(mySim) which 'reports', i.e., tables to save and uplaod to the vritual machine
  - "harvestReport" = reports inforamtion on harvest volume and area harvested, age of harvested stand, by time interval and comaprtment
  - "growingStockReport" = reports on growing stock (forest stand ????) by time interval adn compartment
  - "tableSurvival" = 
  - "disturbanceReport"
  - "volumebyareaReport" = reports volume harvested by the model within a specified area 
    - the 'specified area(s)' can be defined using the Params -> areaofinterestRaster.Rmd
        - this create a raster and vat table for the area(s) of interest based 
    - does nto need to be implemented as part of teh sql lite db; can be included after the fact, because it referes to       the data in the CLUS db
    - then, need to identify the report in the parameter list, modules list and outputs within the forestryCLUS.Rmd    
      (can see 'forestryCLUS_tfl48_volumebyarea_example.Rmd' for an example)
      
  

    
    
    
    