---
title: "Summary_Figures_Quesnel"
author: "Elizabeth Kleynhans"
date: "2024-11-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(ggplot2)
library(RSQLite)
library(terra)
library(raster)
require (dplyr)
library(bcdata)
source (here::here("R/functions/R_Postgres.R"))
```


Create map of Quesnel and plot the historical fires on it.
```{r Quesnel_map, echo=FALSE, fig.cap = "**Figure 1.** Map of Boundary TSA with the locations of actual fires caused by lightning in 2023"}

study_area<-getSpatialQuery("SELECT tsnmbrdscr, wkb_geometry FROM public.tsa where tsnmbrdscr in ('Quesnel_TSA')")

study_area<-st_transform (study_area, 3005)

# get latest data off BCGW
perimeters<-try(
  bcdc_query_geodata("WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL_FIRE_POLYS_SP") %>%
    filter(FIRE_YEAR > 2000) %>%
    collect()
)
perimeters<-st_transform (perimeters, 3005)
perimeters<-perimeters %>% filter( FIRE_SIZE_HECTARES > 1 & FIRE_CAUSE == "Lightning")
perim_subset <- perimeters[study_area, ]
#hist(perim_subset$FIRE_SIZE_HECTARES)
perim_subset_total<-data.table(perim_subset)
perim_subset_total<-perim_subset_total[, sum(FIRE_SIZE_HECTARES), by = FIRE_YEAR]
perim_subset_total$FIRE_YEAR<-as.numeric(perim_subset_total$FIRE_YEAR)

ggplot(data=perim_subset_total) +
  geom_point(aes(x=FIRE_YEAR, y=V1)) +
  geom_line(aes(x=FIRE_YEAR, y=V1)) +
  ylab("Area burned (ha)") + xlab("Year")


ignitions<- try(
  bcdc_query_geodata("WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL_INCIDENTS_SP") %>%
    filter(FIRE_YEAR > 2000) %>%
    collect()
)

ignit<-st_transform (ignitions, 3005)
ignit<-ignit %>% filter( FIRE_CAUSE == "Lightning")

# get study area
ignit_subset <- ignit[study_area, ]
ignit_subset_total<-data.table(ignit_subset)
ignit_subset_total<-ignit_subset_total[, sum(CURRENT_SIZE), by = FIRE_YEAR]


#hist(ignit_subset$CURRENT_SIZE)
perim_subset$FIRE_YEAR<-as.factor(perim_subset$FIRE_YEAR)
perim_subset<-perim_subset %>% filter(FIRE_SIZE_HECTARES>1)

perim_subset_summary<-perim_subset %>% group_by("FIRE_YEAR") %>% count(FIRE_YEAR)

ggplot() +
  geom_sf(data=study_area) + 
  #geom_sf(data=ignit) +
  geom_sf(data = perim_subset, aes(colour =FIRE_YEAR,fill=FIRE_YEAR, alpha = 0.5),show.legend = "point", size = 4) +
  theme(legend.key = element_rect(fill = "white"))
  

```

Get the data from each of the reps for each of the runs
```{r setup, include=FALSE}
#The following two runs are runs with harvest
base_rs_01<-rbindlist(lapply(c('01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16','17', '29','30'), function(i){
  report<-readRDS(paste0("D:/Fire/Quesnel_fire/outputs_harvest/r2/rep",i,"/perFireReport_37.rds"))
  report$rep<-i
  report
}))

base_rs_02<-rbindlist(lapply(c('01', '02', '03', '31', '32', '33', '34', '35', '36', '37', '38', '40'), function(i){
  report<-readRDS(paste0("D:/Fire/Quesnel_fire/outputs_harvest/r1/rep",i,"/perFireReport_37.rds"))
  report$rep<-i
  report
}))

# Get the no harvest runs
base_ns_01<-rbindlist(lapply(c('01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15'), function(i){
  report<-readRDS(paste0("D:/Fire/Quesnel_fire/outputs_no_harvest/r2/rep",i,"/perFireReport_37.rds"))
  report$rep<-i
  report
}))

base_ns_02<-rbindlist(lapply(c('01', '02', '03', '04', '05', '06', '07', '08','09', '10', '11', '12', '13', '14', '15','16','17', '18', '19', '20'), function(i){
  report<-readRDS(paste0("D:/Fire/Quesnel_fire/outputs_no_harvest/r1/rep",i,"/perFireReport_37.rds"))
  report$rep<-i
  report
}))
```

Now summarize the data by time period and rep
```{r setup, include=FALSE}

base_summary_01<-base_rs_01[, sum(fire_perimeter_size), by = c("timeperiod","rep")]
base_summary_01$scenario = 'harvest'
base_summary_01$run = 'r2'
base_summary_01<-base_summary_01[timeperiod<38,]
base_summary_01[,timeperiod:=timeperiod+2023]
base_summary_summary_01<-base_summary_01[, mean(V1), by = "timeperiod"]
base_summary_summary_01<-base_summary_summary_01 %>% rename(FIRE_YEAR=timeperiod)
base_rs_01

base_summary_02<-base_rs_02[, sum(fire_perimeter_size), by = c("timeperiod","rep")]
base_summary_02$scenario = 'harvest'
base_summary_02$run = 'r1'
base_summary_02<-base_summary_02[timeperiod<38,]
base_summary_02[,timeperiod:=timeperiod+2023]
base_summary_summary_02<-base_summary_02[, mean(V1), by = "timeperiod"]
base_summary_summary_02<-base_summary_summary_02 %>% rename(FIRE_YEAR=timeperiod)

# plot actual fire sizes on the same graph as the fire sizes predicte and do it separately for each run
fire_1<-ggplot() +
  geom_line(data=base_summary_01, aes(x=timeperiod, y=V1, group=rep),colour="grey") +
  #geom_line(data=base_summary_02, aes(x=timeperiod, y=log(V1+1), group=rep),colour="skyblue") +
  geom_line(data=base_summary_summary_01, aes(x=FIRE_YEAR, y=V1), col="black", linewidth=1) +
  #geom_line(data=base_summary_summary_02, aes(x=FIRE_YEAR, y=log(V1+1)), col="blue", linewidth=1.25) +
  #geom_line(data=perim_subset_total[FIRE_YEAR>2014, ], aes(x=FIRE_YEAR, y=V1), col="red", linewidth=1) +
  #xlim(2015, 2060) +
  #ylim(0, 100000)
  ylab("Area burned (ha)") + xlab("Year")

fire2<-ggplot() +
  #geom_line(data=base_summary_01, aes(x=timeperiod, y=V1, group=rep),colour="grey") +
  geom_line(data=base_summary_02, aes(x=timeperiod, y=V1, group=rep),colour="skyblue") +
  #geom_line(data=base_summary_summary_01, aes(x=FIRE_YEAR, y=V1), col="black", linewidth=1) +
  geom_line(data=base_summary_summary_02, aes(x=period, y=V1), col="blue", linewidth=1.25) +
  #geom_line(data=perim_subset_total, aes(x=FIRE_YEAR, y=V1), col="red", linewidth=1) +
  #geom_point(data=perim_subset_total, aes(x=FIRE_YEAR, y=V1), col="red")+
  #xlim(2008, 2060) +
  ylim(0, 450000) +
  ylab("Log area burned (ha)") + xlab("Year")


# plot the two harvest runs on a log scale so we can see the ups and downs better
fire_plot1<-ggplot() +
  geom_line(data=base_summary_01, aes(x=timeperiod, y=log(V1+1), group=rep),colour="grey") +
  geom_line(data=base_summary_02, aes(x=timeperiod, y=log(V1+1), group=rep),colour="skyblue") +
  geom_line(data=base_summary_summary_01, aes(x=FIRE_YEAR, y=log(V1+1)), col="black", linewidth=1) +
  geom_line(data=base_summary_summary_02, aes(x=FIRE_YEAR, y=log(V1+1)), col="blue", linewidth=1) +
  geom_line(data=perim_subset_total, aes(x=FIRE_YEAR, y=log(V1+1)), col="red", linewidth=1) +
  xlim(2001, 2060) +
  ylab("Log area burned (ha)") + xlab("Year")
```

Now look at the difference between harvest and no harvest

```{r setup, include=FALSE}
base_nh_summary_01<-base_ns_01[, sum(fire_perimeter_size), by = c("timeperiod","rep")]
base_nh_summary_01$scenario = 'no_harvest'
base_nh_summary_01$run = 'r2'
base_nh_summary_01[,timeperiod:=timeperiod+2023]
base_nh_summary_summary_01<-base_nh_summary_01[, mean(V1), by = "timeperiod"]
base_nh_summary_summary_01<-base_nh_summary_summary_01 %>% rename(FIRE_YEAR=timeperiod)

dat<-rbind(base_summary_01, base_nh_summary_01)
dat$log_area_burned<-log(dat$V1)

dat_10000<-dat[V1>4999, ]

ggplot(data=dat_10000, aes(x=scenario, y=V1))+ 
  geom_violin() +
  #geom_boxplot(width=0.1) +
  geom_dotplot(binaxis='y', stackdir='center', dotsize=0.3)+
  ylab("Area burned (ha)")

#Try look at Coefficient of variaiton

dat_harvest<-dat[scenario=="harvest", ]
sd(dat_harvest$V1)/mean(dat_harvest$V1)

dat_harvestno<-dat[scenario=="no_harvest", ]
sd(dat_harvestno$V1)/mean(dat_harvestno$V1)
##############################################

## second run 
base_nh_summary_02<-base_ns_02[, sum(fire_perimeter_size), by = c("timeperiod","rep")]
base_nh_summary_02$scenario = 'no_harvest'
base_nh_summary_02$run = 'r1'
base_nh_summary_02[,timeperiod:=timeperiod+2023]
base_nh_summary_summary_02<-base_nh_summary_01[, mean(V1), by = "timeperiod"]
base_nh_summary_summary_02<-base_nh_summary_summary_02 %>% rename(FIRE_YEAR=timeperiod)

dat2<-rbind(base_summary_02, base_nh_summary_02)

dat_10000<-dat2[V1>10000, ]

ggplot(data=dat_10000, aes(x=scenario, y=V1))+ 
  geom_violin() +
  #geom_boxplot(width=0.1) +
  geom_dotplot(binaxis='y', stackdir='center', dotsize=0.3)+
  ylab("Area burned (ha)")

#Try look at Coefficient of variaiton

dat_harvest<-dat2[scenario=="harvest", ]
sd(dat_harvest$V1)/mean(dat_harvest$V1)

dat_harvestno<-dat2[scenario=="no_harvest", ]
sd(dat_harvestno$V1)/mean(dat_harvestno$V1)
##############################################



ggplot() +
  geom_line(data=base_summary_02, aes(x=timeperiod, y=V1, group=rep),colour="grey") +
  geom_line(data=base_nh_summary_02, aes(x=timeperiod, y=(V1), group=rep),colour="lightblue") +
  geom_line(data=base_summary_summary_02, aes(x=period, y=V1), col="black", linewidth=1) +
  geom_line(data=base_nh_summary_summary_02, aes(x=FIRE_YEAR, y=V1), col="blue", linewidth=1.25) + ylim(0, 100000)
  geom_line(data=perim_subset_total, aes(x=FIRE_YEAR, y=V1), col="red", linewidth=1) +
  geom_point(data=perim_subset_total, aes(x=FIRE_YEAR, y=V1), col="red")+
  xlim(2008, 2060) +
  #ylim(0, 100000)
  ylab("Log area burned (ha)") + xlab("Year")


  
  

```

Now add climate variable to see how it correlates
```{r}
sqlite <- dbDriver("SQLite")

castordb <- dbConnect(sqlite, paste0 (here::here (),"/quesnel_fire_long_castordb.sqlite"))

climatedat1<-dbGetQuery(castordb, "SELECT * from climate_CanESM5_ssp245")
climatedat1<-data.table(climatedat1)
climatedat1<-climatedat1[run %in% c("r1i1p1f1","r2i1p1f1")]

climatedat1<-climatedat1[, cmi_min:= do.call(pmin, .SD),.SDcols=c("cmi_05", "cmi_06","cmi_07","cmi_08") ]
  climatedat1<-climatedat1[, `:=`(PPT_sm = rowSums(.SD, na.rm=T)), .SDcols=c("ppt_05", "ppt_06","ppt_07","ppt_08")]
  climatedat1<-climatedat1[, TEMP_MAX:= do.call(pmax, .SD),.SDcols=c("tmax_05","tmax_06","tmax_07","tmax_08") ]
  climatedat1<-climatedat1[, Tdelta07 := tmax_07-tmin_07]
  climatedat1<-climatedat1[period<2061,]

  
  climatedat1_summary<-climatedat1[, mean(PPT_sm), by = c("run","period")]
  
  
  climatedat1_summary$Tmaxzscore<-(climatedat1_summary$V1-mean(climatedat1_summary$V1))/sd(climatedat1_summary$V1)


# get z-zcore for fire
  base_summary_summary_02$fire_size_zscore<-(base_summary_summary_02$V1-mean(base_summary_summary_02$V1))/sd(base_summary_summary_02$V1)
  
  base_summary_summary_02<-base_summary_summary_02 %>% rename(period=FIRE_YEAR)
# plot relationship with cmi
  climatedat1_summary<-climatedat1[, mean(cmi3yr), by = c("run","period")]
r1_cmi<-ggplot(data=climatedat1_summary[run=="r1i1p1f1"& period>2022, ]) +
  geom_line(aes(x=period, y=V1), colour="blue", linewidth=1.) + 
  ylab("cmi3yr")

r2_cmi<-ggplot(data=climatedat1_summary[run=="r2i1p1f1"& period>2022, ]) +
  geom_line(aes(x=period, y=V1), colour="black", linewidth=1.) + 
  ylab("cmi3yr")


# plot relationship with TempMax
climatedat1_summary<-climatedat1[, mean(TEMP_MAX), by = c("run","period")]
r1_tmax<-ggplot(data=climatedat1_summary[run=="r1i1p1f1"& period>2022, ]) +
  geom_line(aes(x=period, y=V1), colour="blue", linewidth=1.) + 
  ylab("Temp_max")

r2_tmax<-ggplot(data=climatedat1_summary[run=="r2i1p1f1"& period>2022, ]) +
  geom_line(aes(x=period, y=V1), colour="black", linewidth=1.) + 
  ylab("Temp_max")


library(cowplot)
plot_grid(r1_cmi, r1_tmax, fire2,nrow=3, rel_heights = c(0.8, 0.8, 2))
plot_grid(r2_cmi, r2_tmax, fire_1,nrow=3, rel_heights = c(0.8, 0.8, 2))

plot_grid(r2, fire_1,nrow=2, rel_heights = c(0.8, 2))





ggplot(data=clggplot(data=clggplot(data=climatedat1_summary) +
  #geom_line(data=climatedat1, aes(x=period, y=TEMP_MAX, group=pixelid_climate, group=run), linewidth = 0.1) +
  geom_line(aes(x=period, y=V1, colour=run), linewidth=1.) +
  scale_color_manual(values=c("blue", "black")) + 
  ylab("Maximum summer temperature")
  


canesm<-climatedat1[,c("gcm", "run", "cmi", "cmi3yr", "tmax_04", "tmax_05", "tmax_06", "tmax_07", "tmax_08", "ppt_04", "ppt_05", "ppt_06","ppt_07", "ppt_08")]
canesm<- canesm[run %in% c("r1i1p1f1", "r2i1p1f1"),]

```

Create figure about number of ignitions
```{r}
base_rs_01<-rbindlist(lapply(c('01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16','17', '29','30'), function(i){
  report<-readRDS(paste0("D:/Fire/Quesnel_fire/outputs_harvest/r2/rep",i,"/fireReport_37.rds"))
  report$rep<-i
  report
}))

base_rs_02<-rbindlist(lapply(c('01', '02', '03', '31', '32', '33', '34', '35', '36', '37', '38', '40'), function(i){
  report<-readRDS(paste0("D:/Fire/Quesnel_fire/outputs_harvest/r1/rep",i,"/fireReport_37.rds"))
  report$rep<-i
  report
}))

base_rs_01$scenario = 'harvest'
base_rs_01$run = 'r2'
base_rs_01<-base_rs_01[timeperiod<38,]
base_rs_01[,timeperiod:=timeperiod+2023]
base_summary_summary_01<-base_rs_01[, mean(numberstarts), by = "timeperiod"]
base_summary_summary_01<-base_summary_summary_01 %>% rename(FIRE_YEAR=timeperiod)

base_rs_02$scenario = 'harvest'
base_rs_02$run = 'r1'
base_rs_02<-base_rs_02[timeperiod<38,]
base_rs_02[,timeperiod:=timeperiod+2023]
base_summary_summary_02<-base_rs_02[, mean(numberstarts), by = "timeperiod"]
base_summary_summary_02<-base_summary_summary_02 %>% rename(FIRE_YEAR=timeperiod)

fire_plot1<-ggplot() +
  geom_line(data=base_rs_01, aes(x=timeperiod, y=numberstarts, group=rep),colour="grey") +
  geom_line(data=base_rs_02, aes(x=timeperiod, y=numberstarts, group=rep),colour="skyblue") +
  geom_line(data=base_summary_summary_01, aes(x=FIRE_YEAR, y=V1), col="black", linewidth=1) +
  geom_line(data=base_summary_summary_02, aes(x=FIRE_YEAR, y=V1), col="blue", linewidth=1) +
  geom_line(data=perim_subset_summary, aes(x=FIRE_YEAR, y=n), col="red", linewidth=1) +
  xlim(2001, 2060) +
  ylab("Number of fires") + xlab("Year")

```


