<!--
Copyright 2020 Province of British Columbia
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.-->

---
title: "Database creation for Comparison Analysis Between STSM and Castor"
author: "Tyler Muhly"
date: "20 March 2023"
output: pdf_document
---

# Overview




# Usage
Set parameters for creating the database in the code chunk below.

```{r module_usage}
library (SpaDES)
library (SpaDES.tools)
library (data.table)
library (keyring)

source (here::here("R/functions/R_Postgres.R"))

Sys.setenv(JAVA_HOME = 'C:\\Program Files\\Java\\jdk-14.0.1') #throws an error if pointing to different version of java (i.e., 32 vs 64 bit)

moduleDir <- file.path (paste0 (here::here (), "/R/SpaDES-modules"))
inputDir <- file.path (paste0 (here::here (), "/R/scenarios/comparison_stsm/inputs")) %>% reproducible::checkPath (create = TRUE)
outputDir <- file.path (paste0 (here::here (), "/R/scenarios/comparison_stsm/outputs")) %>% reproducible::checkPath (create = TRUE)
cacheDir <- file.path (paste0 (here::here (), "/R/scenarios/comparison_stsm"))

times <- list(start = 0, end = 0)

parameters <-  list (
        .progress = list (type = NA, interval = NA),
        .globals = list (),
        dataCastor = list(dbName = 'castor',
                          saveCastorDB = TRUE,
                          sqlite_dbname = "stsm_compare_blocks_roads", 
                          nameBoundaryFile = "castor_stsm_compare.bounds_tsa99", 
                          nameBoundaryColumn = "tsa_name", 
                          nameBoundary = "tsa99", 
                          nameBoundaryGeom = 'wkb_geometry',
                          nameCompartmentRaster = "castor_stsm_compare.rast_bounds_tsa99", 
                          nameCompartmentTable = "castor_stsm_compare.vat_bounds_tsa99", 
                          nameMaskHarvestLandbaseRaster = 'castor_stsm_compare.rast_thlb', 
                          
                          nameZoneRasters = c ("rast.zone_cond_beo",
                                               "castor_stsm_compare.rast_zone_test"),
                          nameZoneTable = "castor_stsm_compare.constraints", 
                          
                          nameYieldsRaster = "castor_stsm_compare.rast_ycid_vdyp", 
                          nameYieldTable = "castor_stsm_compare.vdyp", 
                          nameYieldsTransitionRaster = "castor_stsm_compare.rast_ycid_tipsy", 
                          nameYieldTransitionTable = "castor_stsm_compare.tipsy", 
                          nameForestInventoryRaster = "castor_stsm_compare.rast_vri_id", 
                          nameForestInventoryKey = "vri_fid", 
                          nameForestInventoryTable = "castor_stsm_compare.vri",
                          nameForestInventoryAge = "proj_age_1",  
                          nameForestInventoryHeight = "proj_ht_1",
                          nameForestInventoryCrownClosure = "cr_closure",                             
                          nameForestInventoryTreed = "bclcs_lv_2",
                          nameForestInventorySiteIndex = "site_index"
                          ),
        blockingCastor = list(blockMethod='pre',
                              patchZone = 'rast.zone_cond_beo',
                              patchVariation = 6,
                              nameCutblockRaster = "rast.cns_cut_bl",
                              useLandingsArea = FALSE),
        roadCastor = list (roadMethod = 'pre',
                           nameCostSurfaceRas = 'castor_stsm_compare.rast_road_cost_adj',
                           nameRoads =  'castor_stsm_compare.rast_roads'
                           ),
        uploadCastor = list(aoiName = 'stsm_compare',
                              dbInfo  = list(keyring::key_get("vmdbhost", keyring="postgreSQL"),
                                             keyring::key_get("vmdbuser", keyring="postgreSQL"),
                                             keyring::key_get("vmdbpass", keyring="postgreSQL"), 
                                             keyring::key_get("vmdbname", keyring="postgreSQL")))
        )

scenario = data.table (name = "load_data_blocks_roads", description = "dataCastor with blocking and roading")


patchSizeDist<- data.table(ndt= c(1,1,1,1,1,1,
                                  2,2,2,2,2,2,
                                  3,3,3,3,3,3,
                                  4,4,4,4,4,4,
                                  5,5,5,5,5,5), 
                           sizeClass = c(40,80,120,160,200,240), 
                           freq = c(0.3,0.3,0.1,0.1,0.1, 0.1,
                                    0.3,0.3,0.1,0.1,0.1, 0.1,
                                    0.2, 0.3, 0.125, 0.125, 0.125, 0.125,
                                    0.1,0.02,0.02,0.02,0.02,0.8,
                                    0.3,0.3,0.1,0.1,0.1, 0.1))
modules <- list("dataCastor", 
                "blockingCastor", 
                "roadCastor", 
                "uploadCastor")

objects <- list(patchSizeDist=patchSizeDist, 
                #rsf_model_coeff=rsf_model_coeff , 
                scenario = scenario)

paths <- list(cachePath = cacheDir,
              modulePath = moduleDir,
              inputPath = inputDir,
              outputPath = outputDir)

inputs <- list()
outputs <- list()

mySim <- simInit(times = times, 
                 params = parameters, 
                 modules = modules,
                 objects = objects,
                 paths = paths)

# outputs to keep; these are tables that get used in the uploader
outputs(mySim) <- data.frame (objectName = c("harvestReport",
                                             "growingStockReport"
                                             ))

system.time({
mysimout<-spades(mySim)
})

```

## Update Stands in THLB with NUll age to age = 0

```{r}
db <- dbConnect(RSQLite::SQLite(), dbname = paste0(here::here(), "/R/scenarios/comparison_stsm/stsm_compare_blocks_roads_castordb.sqlite"))

dbExecute (db, "UPDATE pixels SET age = 249 WHERE age > 249;") 

dbDisconnect(db)
```

