<!---
# Copyright 2018 Province of British Columbia
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

#=============================================================================
--->

---
title: "CLUS - roads"
output:
 html_document: default
---

<div style="margin-bottom:100px;">
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Introduction

Roads are an important consequence from land use operations that impact future economic opportunities and wildlife habitat. Using an annual harvest of 200 000 ha with 3 % of the harvest area in roads, a road right of way of 20 m, roughly 3 000 km of roads get built per year. This equates to travelling between Vancouver and Golden 4.2 times. How are these roads planned and designed? 

Short term planning has been the historical approach to road development. Largely because it is an enormous task to manually project road networks (e.g., depending on the computer, it may take up to ½ day for an individual timber supply area). Especially if this process is done manually. Further, we rarely have a long term view on the life cycle of each road segment. This includes how much volume will be hauled over the roads which make it hard to determine the best decision regarding deactivation and reactivation. Lastly there are limited tools available to assess strategic questions such as how yarding distance and road design parameters affect the total length and cost of the network, area of land lost to roads and the amount to caribou habitat sensitive to future road networks.

Our interest is in the automated process of projecting roads, the speed in preforming this process and the realism of assumptions. While optimal road construction strategies including activation and deactivation have been developed (Murray 1998; Anderson et al. 2006), optimizing very large landbases is problematic in terms of speed in execution, generating the estimates needed to parameterize the formulation and the level of integration with other modelling approaches like simulation. Research has shown there are trade-offs between optimized routing and the time to solve the problem (Dean 1997; Picard et al. 2006).

Simulation models offer an alternative approach to optimization that links nicely to strategic models looking to assess land uses across very large landscapes involving multiple regions and timber supply areas. These models employ heuristic algorithms for road design which may not be optimal but rather close to it. Thus, many assumptions are needed to parameterize road simulations and these need careful consideration. The following anlaysis looks at the various road simulation assumptions used by Forest Analysis and Inventory Branch (FAIB). In particular, road simulations assume landings (determined by a harvest scheduler) will be connected to an existing road network. These include: a "as the crow flies" method where the road has no costs associated with direction; a "least cost distance" which builds upon the "crow flies" method by incorporating costs and obstacles (a.k.a., "as the wolf runs"); and a MST (Minimum Spanning Tree) with Least-Cost Paths as used in StTSM-SELES (Spatial (Tim) Timber Supply Model in Spatially Explicit Landscape Event Simulator).  


##Problem Defintion

###Road Spacing and Multiple Target Access

All of the current road simulators used in FAIB have a similar problem in the forest management context– design a future road network that connects harvesting locations or landings to an existing road network under the objective of minimizing cost. This problem can be defined under two approachs: i) a road spacing problem (RSP) where every point is potentially a target, the problem is then to find a network as densely as possible, with a stopping rule that infers the maximum total cost that can be achieved. or ii) a multiple target access problem (MTAP) which considers _m_ point-shaped targets (i.e., landings of cutblocks) that have to be connected to an existing road network (the source). The first approach provides a long term view of road development that would help inform road saturation and activation or deactivation decisions. If the harvest locations are known, this approach can also be implemented at single time step often in the simulations intitalization or start up period through pre-solving. Examples of pre-solving the road network can be found in jfssam (Dave Waddell's Model) or through SELES-roading. Conversely, a second approach can be taken which simulates roads dynamically. The difference between these two approaches concerns the amount of information given to the model with the first approach assuming perfect information of harvest locations across the simulation time horizon which would result in a lower cost (ie., road density). The second approach assumes limited information concerning harvest locations (i.e., a single period of locations) and thus has a higher cost. This lack of information may be more realistic with the temporal scale of imformation used in road planning and thus, is of interest to assess the economic and ecological impacts of land uses. 

A common assumption when simulating paths between landings  and an existing road network concerns the objective of minimizing cost. In the simplest case, the minimum cost will be the straight line path between the existing road network and landing. However, a more realistic cost may include various impedance attributes like slope, habitat, length of roads, time, risk to fire or other barriers. Some expamples of a cost surface include: [Tobler's hiking function](https://en.wikipedia.org/wiki/Tobler%27s_hiking_function), expert opinion from operational researchers or an empircally derived function relating various topogrphical and biophyiscal variables. No matter what the attributes of cost surface may be, an estimate of cost is required for each pixel and thus, the cost of a road segment is the sum of the costs associated to the pixels that form the segment. The total costs for a road segment form the edges of a graph with the vertices or nodes representing source, posible locations to build the road to target locations. For a raster data-structre, nodes are located on a square grid and spatially neighbouring nodes are connected by edges (or arcs).Adding addtional impedance attributes will increase the complexity of the path which will result in an increased cost of the network (i.e., greater road density). Further, the path of a landing to the existing road netwowrk assumes each road is planned independant of other landing locations. This may create parrallel roads/paths that may seem redundant. To over come this effects a more centrailized approach to road planning is needed.

To include the effect of other landings on the road network a decision is assumed to determine which landing will connect to other landings versus the existing road network. This decision can be approximated with a minimum spanning tree problem which uses the paths between each landing to an existing road and each landing to another landing as nodes in a graph. A more detail description of the least cost paths and minimuim spanning trees follows.

###Least-Cost Path

Decomposing the MTAP we find a similar smaller problem, connecting a single target point to a source point which is also called a least cost path or shortest path. To solve this problem [Dijkstra’s algorithm](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm) is often implemented (see [ArcGIS Network Analyst](http://help.arcgis.com/en/arcgisdesktop/10.0/pdf/network-analyst-tutorial.pdf) or [QGIS Network anlaysis library](https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/network_analysis.html). In this algorithm, every node is visited and thus solving the graph provides information on the least cost path for every target-source combination. This works by first initializing the graph by setting all the points to ‘unvisited’ and storing this as a set (called unvisited set). The values of the points are set to infinity except for the origin or source point which is set to zero. A series of iteration then determine the path. In the first iteration the current node is the source point. From the current node consider all the neighbours and calculate the cost from the current node to each of the neighbour nodes. This cost includes the cost from the current node (in the first iteration this will be 0). Store these nodes in priory queue so that the smallest distance is first. Thus, the first node will be the least cost. In the next iteration. find all the nieghbours For this first node and calculate the cost to go from the source point to these neighbouring nodes (this is taken from the edge). Store the least cost at this node and remove from unvisted set. The next interation then begins by finding all the neighbouring nodes until the target has been reached. A complete graphical example can be found [here](http://optlab-server.sce.carleton.ca/POAnimations2007/DijkstrasAlgo.html). Note Djikstra's algorihutm  has limtations with negative costs and solving time and thus, various modifications of this algorithum have been proposed (eg., [A*](https://en.wikipedia.org/wiki/A*_search_algorithm), [Johnson's Algorithm](https://en.wikipedia.org/wiki/Johnson%27s_algorithm))

###Minimum Spanning Tree
A minimum spanning tree (MST) connects all nodes in a graph with out any loops or cycles. In the forestry context, the nodes of the MST are cutblock locations and existing road networks and the edges are routes solved using a Least-Cost Path algorthium (eg., [Dijkstra’s algorithm](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm)). To solve the MST, [Kruskal's algorithm](https://en.wikipedia.org/wiki/Kruskal%27s_algorithm) is often used , however, this algrotihum is 'greedy' (finds a locally optimal choice using a problem solving heuristic with the intent of finding a global optimum) and thus various alternatives exist  (see [Prim's algorithm](https://en.wikipedia.org/wiki/Prim%27s_algorithm)). [Kruskal's algorithm](https://en.wikipedia.org/wiki/Kruskal%27s_algorithm) begins by sorting graph edges with respect to their weights (these are the total cost of the least cost path). Then, add edges to the MST by starting with the edges with the smallest weight and going until the edge of the largest weight. Lastly, only add edges that do not form a loop or cycle. A complete graphical example can be found [here](http://optlab-server.sce.carleton.ca/POAnimations2007/MinSpanTree.html). 

##Objectives
Various approaches to simulating road development in BC were compared for purposes of identifying their differences and evaluating trade-offs. To provide this comparison, the approaches were first contrasted based on their conceptual and structural assumptions. Using these assumptions, versions of the  approaches were then developed in the R programming language within the [SpaDES](https://cran.r-project.org/web/packages/SpaDES/index.html) package to support a consistent comparison between accuracy and speed of execution. The following describes the approaches and provides a comparison of the simulated outcomes.

##Description of Approaches

All of the methods are dependent on two considerations: i) the road building cost and ii) the view of road branching. First, road building cost is given as a surface constructed from many spatial layers including hydrology, slope, altitude, topography etc. However, the cost can also deal with transportation cost, destruction risk or negative impacts to the environment or wildlife habitat. Second, a degraded version of the MTAP is considered by forcing the only possible branching points of the road network to be targets. However, solutions to these problems increase the time and complexity of the algorithm which severely limits the number of possible scenarios that can be run. For the remainder of this analysis, the degraded version of the MTAP is considered becuase all of the proposed approaches make this assumption.

### The 'Snapping' Approach 
This approach simply snaps a landing (i.e., cutblock location) to the nearest existing road segment. Since the snapping is done for each landing it is also called an independent path with reduction method. First the existing road network is closest road point is determined using gdistance


### Least Cost Paths Approach 
This approach builds upon the snapping approach by first assuming a path for each landing to the existing road network and second including the cost of barriers and impedance attributes. This approach requires a cost surface that is more complicated than the snapping approach and thus requires greater computational time. 

### MST-Least Cost Paths Approach 
This approach builds upon the least cost paths approach by determining if landings should be connected to one another before being connected to the exiting road network. Least cost distances are estimated both between landings and landings with the existing road network. These distances are then used as nodes for solving a minim spanning tree problem. Least cost paths are then constructed following the solution to the MST. This approach allows for greater branching in simulated roads which would reduce the cost relative to the least cost paths approach. However, the computational time would increase over the least cost paths approach given the extra step of solving the MST. 

#Comparison

To compare the three approaches: i) a schedule of historical harvest locations or landings was queried (starting from 1980 to 2018) from the consoldated cutblocks polygon spatial file; ii) these landings were then selected within a study area representing a caribou boundary; iii) each of the three approachs were simulated; iv) an analysis on the resulting simulated roads was then compared to the current (2018) state of road development.

Selecting the landings involved the following query. Note the ST_Exteriorring function being used - this function was chosen over centroid because a centroid would only by applicable to a spatial contiguous cutblock. For cutblocks that are not spatially contiguous the selection of a randomly selected exterior point would resemble an actual location of a landing. This could be further improved by querying further on the selection of exterior points that were closest to the centroid or an existing road network or other.

```{sql eval=FALSE}
Create TAble cutseq as
  SELECT a.areaha, a.harvestyr, ST_X(a.point) as X , ST_Y(a.point) as Y, point 
  FROM (SELECT areaha, harvestyr, ST_PointN(ST_Exteriorring(wkb_geometry) , 1) as point
  FROM cns_cut_bl_polygon) a 

```

Once the landing locations have been queried. The landings that intersected with caribou herd boundaries were selected.

```{sql eval=FALSE}

SELECT harvestyr, x, y from cutseq, 
(Select  P(sim)$nameBoundaryGeom FROM  P(sim)$nameBoundaryFile 
WHERE P(sim)$nameBoundaryColumn =  P(sim)$nameBoundary) as h
WHERE h.P(sim)$nameBoundaryGeom && cutseq.point 
AND ST_Contains(h.P(sim)$nameBoundaryGeom, cutseq.point
ORDER BY harvestyr;
```




#References
Anderson, A. E. and J. Nelson. 2004. Projecting vector based road networks with a shortest path algorithm. Can. J. For. Res., 34(7):1444–1457.[Cross-ref](http://www.nrcresearchpress.com/doi/abs/10.1139/x04-030#.WyFgGu4vxEY)

Dean, D. J. Finding optimal routes for networks of harvest site access roads using GIS-based techniques. Can. J. For. Res., 27:11–22, 1997.[Cross-ref](http://www.nrcresearchpress.com/doi/abs/10.1139/x96-144#.WyFgPu4vxEY)

Murray, A. T. 1998.Route planning for harvest site access. Can. J. For. Res., 28(7):1084–1087.[Cross-ref](http://www.nrcresearchpress.com/doi/abs/10.1139/x98-122#.WyFgWu4vxEY)

Picard, N., Gazull, L. and Freycon, V. 2006. Finding optimal routes for harvesting tree access. International Journal of Forest Engineering. 17(2): 35-50.[Cross-ref](https://journals.lib.unb.ca/index.php/ijfe/article/view/5695/6700)

