---
title: "inla_baysian_coregional"
author: "Kyle Lochhead"
date: "2024-09-26"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("R/functions/R_Postgres.R"))
library(data.table)
library(sf)
library(tidyverse)
library(glmmTMB)
library(DHARMa)
library(sdmTMB)
library(INLA)
```

## Data
```{r}
data.person<-readRDS("data_person_occurence_10k.rds")
data.person<-data.person[, count_person:= count]
data.lightning<-readRDS("data_lightning_occurence_10k.rds")
data.all<-merge(data.lightning, data.person[,c("pixelid", "FIRE_YEAR", "count_person")], by.x = c("pixelid", "FIRE_YEAR"), by.y = c("pixelid", "FIRE_YEAR"))
occ.model.data<-data.all[!is.na(CMI3yr),][,dCMI3yr:=CMI-(CMI3yr/3)][, coast:=0][frt==15, coast:=1][,flammable:=con + mix + dec + young + veg][flammable >0, ][, year:= as.factor(FIRE_YEAR)][!is.na(fire_centre),]

occ.model.data<-occ.model.data[, avgCMIProv:=sum(CMI)/.N, by = c("FIRE_YEAR")][,dry:=0][avgCMIProv < -0.47, dry :=1][,year:=as.integer(year)][, pcon:=(con/flammable)*100][, pdec:=(dec/flammable)*100][, pyoung:=(young/flammable)*100][, pmix:=(mix/flammable)*100][, proad:=scale(road/flammable)][,lroad:=log(road+1)]

# Determine threshold
threshold<-occ.model.data[, .(count = sum(count), avgCMIProv = min(avgCMIProv) ), by = FIRE_YEAR]
#saveRDS(threshold, "avgCMIProv10k.rds")

#Set the trainingset
occ.model.data.train<-occ.model.data[FIRE_YEAR < 2018, ]
occ.model.data.train$frt<-as.factor(occ.model.data.train$frt)
occ.model.data.train<-cbind(occ.model.data.train, model.matrix( ~ 0 + frt, data=occ.model.data.train ))


locations<-cbind(occ.model.data.train$x, occ.model.data.train$y)
mesh<-inla.mesh.2d(locations, max.edge = c(100,800), cutoff = 15)
plot(mesh)
points(locations, col = "red", pch = 2)
nv <- mesh$n
```
#Person caused
```{r}
A_Matrix<-inla.spde.make.A(mesh, loc = locations)
fire.spde = inla.spde2.pcmatern(mesh = mesh, prior.range = c(400, 0.5), prior.sigma = c(.5, .5)) 

#Transforms
occ.model.data.train$log_flammable<-log(occ.model.data.train$flammable)
p1 <- as.formula(paste0("y ~ -1 + Intercept + lroad + frt5 + frt7 + frt9 + frt10 + frt11 + frt12 + frt13 + frt14 + frt15 +  offset(log_flammable) + f(spatial1, model = fire.spde)"))

s.index <- inla.spde.make.index(name = "spatial1",                                n.spde = fire.spde$n.spde,                                n.group = 1,  n.repl = 1)

StackFire <- inla.stack(data = list(y = occ.model.data.train$count_person),A = list(A_Matrix,1),              effects = list(s.index, list(Intercept = 1, lroad=occ.model.data.train$lroad ,frt5 = occ.model.data.train$frt5, frt7 = occ.model.data.train$frt7, frt9 = occ.model.data.train$frt9, frt10 = occ.model.data.train$frt10, frt11 = occ.model.data.train$frt11, frt12 = occ.model.data.train$frt12, frt13 = occ.model.data.train$frt13, frt14 = occ.model.data.train$frt14, frt15 = occ.model.data.train$frt15, log_flammable = log(occ.model.data.train$flammable))))

PER1 <- inla(p1, 
            family = "nbinomial",
            data = inla.stack.data(StackFire, spde=fire.spde),
            control.family=list(list(link="log")),
            control.compute = list(dic = TRUE),
            control.predictor = list(A = inla.stack.A(StackFire), compute=TRUE , link =1),
            control.fixed = list(mean=list(Intercept = -15, lroad = 0.448, frt5 = -2.3, frt7 = 0.24, frt9 =-1.4, frt10 = -2.5, frt11 =-1.16, frt12 =-0.8, frt13 = -1.47, frt14 = 0.336, frt15 =-1.15, default=0)),
            control.inla = list(int.strategy = "eb")
)


```

#lightning caused
```{r}
#Fit in INLA
A_Matrix<-inla.spde.make.A(mesh, loc = locations)

fire.spde = inla.spde2.pcmatern(mesh = mesh, prior.range = c(400, 0.5), prior.sigma = c(.5, .5)) 

#Transforms
occ.model.data.train$log_flammable<-log(occ.model.data.train$flammable)

f1 <- as.formula(paste0("y ~ -1 + Intercept + CMI_MIN + dCMI3yr + avgCMIProv + log_con + log_dec + frt5 + frt7 + frt9 + frt10 + frt11 + frt12 + frt13 + frt14 + frt15 +  offset(log_flammable)"))

f2 <- as.formula(paste0("y ~ -1 + Intercept + CMI_MIN + dCMI3yr + avgCMIProv + log_con + log_dec + frt5 + frt7 + frt9 + frt10 + frt11 + frt12 + frt13 + frt14 + frt15 +  offset(log_flammable)  + f(spatial1, model = fire.spde)"))

s.index <- inla.spde.make.index(name = "spatial1",                                n.spde = fire.spde$n.spde,                                n.group = 1,  n.repl = 1)

StackFire <- inla.stack(data = list(y = occ.model.data.train$count),A = list(A_Matrix,1),              effects = list(s.index, list(Intercept = 1, CMI_MIN = occ.model.data.train$CMI_MIN, dCMI3yr = occ.model.data.train$dCMI3yr,avgCMIProv =occ.model.data.train$avgCMIProv,  log_con =log(occ.model.data.train$con + 1), log_dec =log(occ.model.data.train$dec + 1) ,frt5 = occ.model.data.train$frt5, frt7 = occ.model.data.train$frt7, frt9 = occ.model.data.train$frt9, frt10 = occ.model.data.train$frt10, frt11 = occ.model.data.train$frt11, frt12 = occ.model.data.train$frt12, frt13 = occ.model.data.train$frt13, frt14 = occ.model.data.train$frt14, frt15 = occ.model.data.train$frt15, log_flammable = log(occ.model.data.train$flammable))))


IM1 <- inla(f1, 
            family = "nbinomial",
            data = inla.stack.data(StackFire, spde=fire.spde),
            control.family=list(list(link="log")),
            control.compute = list(dic = TRUE),
            control.predictor = list(A = inla.stack.A(StackFire), compute=TRUE , link =1),
            control.fixed = list(mean=list(default=0)),
            control.inla = list(int.strategy = "eb")
)

IM2 <- inla(f2, 
            family = "nbinomial", verbose = TRUE,
            data = inla.stack.data(StackFire, spde=fire.spde),
            control.family=list(list(link="log")),
            control.compute = list(dic = TRUE),
            control.predictor = list(A = inla.stack.A(StackFire), compute=TRUE , link =1),
            control.fixed = list(mean=list(Intercept=-15, CMI_MIN=-0.1, dCMI3yr = -0.3, avgCMIProv = -0.2, log_con = 0.5, log_dec = 0, frt5 = -1, frt7 = -2.5, frt9 =-2.8, frt10 = -2.3, frt11 =-2.1, frt12 =-1.8, frt13 = -1.8, frt14 = -1.5, frt15 =-3.5, default=0)),
            control.inla = list(int.strategy = "eb")
)
```

##Joint
```{r}
#Fit in INLA
A.m<-inla.spde.make.A(mesh, loc = locations)

fire.spde = inla.spde2.pcmatern(mesh = mesh, prior.range = c(400, 0.5), prior.sigma = c(.5, .5)) 

s.index.lig <- 
  inla.spde.make.index(name = "spatial.field.lig", n.spde = fire.spde$n.spde)

#s.index.per<- inla.spde.make.index(name = "spatial.field.per", n.spde = fire.spde$n.spde)

#Y
y1 <- occ.model.data.train$count; names(y1) <- "y.1"
#y2 <- occ.model.data.train$count_person; names(y2) <- "y.2"

stk.lightning<- inla.stack(
data = list(y = y1),
A = list(A.m, 1),
effects = list(spatial.field.lig =  s.index.lig,
data.frame(Intercept.lightning = 1,log_flammable = log(occ.model.data.train$flammable))),
tag = "Lightning")

stk.person <- inla.stack(
data = list(y = cbind(NA, as.vector(y2))),
A = list(A.m, A.m, 1),
effects = list(
spatial.field.per = s.index.per, base.copy.person = 1:nv,
data.frame(Intercept.person = 1, log_flammable = log(occ.model.data.train$flammable))),
tag = "Person")

A.pr <- inla.spde.make.A(mesh = mesh, loc = locations)
# Prepare the data for the prediction
ypred <- matrix(NA, nrow = nrow(occ.model.data.train), ncol = 1)

stk.lightning.pr <- inla.stack(
data = list(y = ypred),
A = list(A.pr, 1),
effects = list(spatial.field.lig = s.index.lig ,
data.frame(Intercept.lightning = 1,log_flammable = log(occ.model.data.train$flammable))),
tag = "Lightning.pred")

stk.person.pr <- inla.stack(
data = list(y = ypred),
A = list(A.pr, A.pr, 1),
effects = list(
spatial.field.per = s.index.per, base.copy.person = 1:nv,
data.frame(Intercept.person = 1, log_flammable = log(occ.model.data.train$flammable))),
tag = "Person.pred")

# Stack for the shared effect
stk.shared <- inla.stack(
data = list(y = ypred),
A = list(A.pr),
effects = list(spatial.field.lig =  s.index.lig ),
tag = "Shared")

stk.person.spec <- inla.stack(
data = list(y = ypred),
A = list(A.pr),
effects = list(spatial.field.per =  s.index.per),
tag = "Person.spec")

# Put all the stacks together
#join.stack <- inla.stack(stk.lightning, stk.person,stk.lightning.pr, stk.person.pr,stk.shared, stk.person.spec)
join.stack <- inla.stack(stk.lightning, stk.lightning.pr)

#form <- y ~ -1 + Intercept.lightning + Intercept.person + offset(log_flammable) + f(spatial.field.lig, model = fire.spde) +f(spatial.field.per, model = fire.spde) +f(base.copy.person, copy = "spatial.field.lig", fixed = TRUE)

form <- y ~ -1 + Intercept.lightning + offset(log_flammable) + f(spatial.field.lig, model = fire.spde)
#Fit
fire.res <- inla(formula = form, verbose = TRUE,
data = inla.stack.data(join.stack, spde = fire.spde),
family = rep("nbinomial", 1),
control.predictor = list(A = inla.stack.A(join.stack), link =1, compute = TRUE, precision = 1e6),
control.compute = list(dic = TRUE, waic = TRUE, cpo = TRUE, mlik = TRUE, po = TRUE), control.fixed = list(mean=list(Intercept.lightning=-5, Intercept.person =-5, default=0)),
            control.inla = list(int.strategy = "eb"))


```

#Diagonistics