---
title: "forestryCLUS"
author: ""
date: "08 April 2019"
output: pdf_document
---

<!--
Copyright 2018 Province of British Columbia
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.-->

# Overview

This module provides the logic for simulating forestry decisions on the landscape. These decisions currently involve spatializing the harvest flow objectives which include: where, when and how much to harvest. These factors help determine policies related to harvest flows, opening size, seral distrubitions, road densitites, preservation areas, silvicultural systems, etc. More sophistication to these decisions would involve looking at the costs and benefits beyond the time period, this requires optimization or improved heuristics -- which may be considered in the future. The general overview of forestryCLUS follows.

At each time step, harvest units (pixels or blocks) are ranked according to a priority (e.g., oldest first), this constructs a queue. This queue of harvest units are then subject ot various constraints meant to meet objectives for the study area. Harvest units are harvested until either a constraint is binding, the queue is exhausted or the harvest flow is met. Next, the age of the forest is advanced to the next time period and the process is repeated. 

During the simulation various reports and information surrounding each pixel can be saved/recorded or used in a summary. Note these outputs are considered expected future outcomes given the inputs developed by the anlayst.For a historical selection of harvesting activities see [cutblockSeqPrepCLUS](https://github.com/bcgov/clus/tree/master/R/SpaDES-modules/cutblockSeqPrepCLUS). Both  cutblockSeqPrepCLUS and forestryCLUS build a list of landing locations through simulation time. One is historical while the other is future.

# Usage
This module could be a parent module. It can rely on: 
1. dataloadCLUS (set up the db) 
2. blockingCLUS (preforms the pixel aggregation into harvest units)
3. (Optionally) roadCLUS (preforms the access to the harvest units)


```{r module_usage}
library(SpaDES.core)
source("C:/Users/KLOCHHEA/clus/R/functions/R_Postgres.R")

moduleDir <- file.path("C:/Users/KLOCHHEA/clus/R/SpaDES-modules")
inputDir <- file.path("C:/Users/KLOCHHEA/clus/R") %>% reproducible::checkPath(create = TRUE)
outputDir <- file.path("C:/Users/KLOCHHEA/clus/R")
cacheDir <- file.path("C:/Users/KLOCHHEA/clus/R")
times <- list(start = 0, end = 15)
parameters <- list(
  .progress = list(type = NA, interval = NA),
  .globals = list(),
  dataLoaderCLUS = list( 
                         #Database connection
                         dbName='clus',
                         save_clusdb = FALSE,
                         #Study Area
                         nameBoundaryFile="study_area_compart",
                         nameBoundaryColumn="tsb_number",
                         nameBoundary=c("08B", "08C"), 
                         nameBoundaryGeom='wkb_geometry',
                         nameCompartmentRaster = "rast.forest_tenure",
                         #Zones
                         nameMaskHarvestLandbaseRaster='rast.bc_thlb2018',
                         nameZoneRasters=c("rast.zone_beo", "rast.zone_vqo"),
                         nameZoneTable ="zone_constraints",
                         #VRI info
                         #nameAgeRaster= "rast.vri2017_projage1",
                         #nameHeightRaster= "rast.vri2017_projheight1",
                         #nameCrownClosureRaster = "rast.vri2017_crownclosure",
                         #Yield info
                         #nameYieldIDRaster ="rast.yieldid",
                         nameYieldTable ="yield_ex"
                      ),
forestryCLUS = list( harvestPriority = "age DESC, vol DESC, crowncover DESC")
                )
modules <- list("dataLoaderCLUS", "growingStockCLUS", "forestryCLUS")
harvestFlow<- data.table(compartment = c('08B','08B','08B','08C','08C','08C'),
                                   partition = 'age > 50',
                                   Year = rep(seq(from = 2018, to=2020, by = 
                                                    1),2), 
                                   Flow = c(1000, 1001, 1004, 1100, 1011, 1024))
objects <- list(harvestFlow = harvestFlow 
                )
paths <- list(
  cachePath = cacheDir,
  modulePath = moduleDir,
  inputPath = inputDir,
  outputPath = outputDir
)

mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects, paths = paths)

system.time({
mysimout<-spades(mySim)
})

```

# Events
1. SELECT compartments FROM compartments WHERE target > 0
2. FOR compartment in compartments
       SELECT pixelid FROM pixels WHERE compartment = compartment 
       AND thlb > 0 AND constraint = 0 ORDER BY priotity
3. Queue pixelids || select blockids

# Data dependencies

## Input data

A SQLite db is required (output from dataloaderCLUS). A harvestFlow data.table object that includes the forest management unit (i.e., compartment, aka - 'supply block'), the partition from which the harvest flow applies (e.x., All dead pine); the yeay from which the flow applies and the amount of volume.

## Output data

A list of landings || blocks from when they are harvested.

# Links to other modules

dataloaderCLUS is required.

