---
title: "forestryCLUS_tutorial.RmD"
author: "Tyler Muhly"
date: "23 April 2021"
output:
  html_document: 
    keep_md: yes
---

<!--
Copyright 2020 Province of British Columbia
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.-->

# Overview
This module is designed to spatially simulate forestry activity on a landscape. It is a 'tutorial' version of the module, designed to simplify the process for new model users. The module is used to specify harvest flow and specifications (e.g., zonal constraints, adjacency rules, etc.) for the area of interest. The data to run the simulator are specified and created in a previous step, using the *dataLoaderCLUS* module. The general overview of forestryCLUS follows:

At each time step, harvest units (pixels or blocks) are ranked according to a priority of forest stand (e.g., oldest first) or zone characteristics, which constructs a harvest 'queue'. This queue of harvest units are then subject to various constraints meant to meet objectives for the study area. The harvest units are 'harvested' (i.e., converted to a 'new' stand, and the volume from the stand is tallied) until either a constraint is binding, the queue is exhausted or the harvest flow target is met. Next, the age of the forest is advanced to the next time period and the process is repeated. 

During the simulation, various reports and information surrounding each pixel can be saved/recorded or summarized. Note these outputs are considered expected future outcomes given the inputs developed by the analyst. 

Here you can specify an overview of the simulation analyses completed using this particular .Rmd file.

## Revelstoke TSA 
In this tutorial we use the the [Revelstoke timber supply area (TSA)](https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/timber-supply-review-and-allowable-annual-cut/allowable-annual-cut-timber-supply-areas/revelstoke-tsa) as an example. The Revelstoke TSA 
is located in south-eastern British Columbia, and encompasses approximately 527,000 hectares of land. On July 28, 2011, the allowable annual cut was set at 225,000 cubic metres. The TSA is somewhat unique in that it has a steep elevational gradient. It is characterized by lakes and rivers surrounded by relatively steep valleys up to the peaks of the Selkirk mountains. Thus forest harvest is constrained by topography.

## Scenarios
The following scenarios were run:

1. business-as-usual (BAU) sustained yield: approximates the existing forest harvest constraints and behaviours; establishes the current 'baseline' or benchmark to evaluate the potential impact of 'new' actions

2. New proposed management area: adds a hypothetical management area with a constraint of: minimum 90% of the area greater than or equal to 80 years old.

## Key Parameters 
Below are some of the key parameters used in the simulations.

### Zone Constraints
Baseline zone constraints (used in all simulations):
* biodiversity emphasis options: rast.zone_cond_beo
* visual quality objectives: rast.zone_cond_vqo
* wildlife habitat areas: rast.zone_cond_wha
* ungulate winter ranges: rast.zone_cond_uwr
* fisheries sensitive watersheds: rast.zone_cond_fsw
* old growth management areas and parks and protected areas: rast.zone_cond_nharv
* community watersheds: rast.zone_cond_cw

Zone constraints included in hypothetical management area scenario only:
* hypothetical management area: rast.raster_test

### Harvest Priority Queue
Oldest first, which was similar to what was used in teh timber supply review analysis.
* harvestPriority = 'age DESC'

### Harvest Simulation Duration and Target Volume
Here we simulate forest harvest over a 200 year period at 5 year intervals. First we simulate a long-term sustained yield harvest flow, where the harvest target remains flat and does not decline during the 200 year period (i.e., non-declining even flow). The allowable annual cut (AAC) for the harvest unit was 225,000m^3^/year, so first we simulated a flow of 200,000m^3^/year, and incrementally adjusted until we found the long-term sustained yield at 210,000m^3^/year (i.e., 1,050,000m^3^/5-year)

### Minimum Harvest Criteria
Here we used a minimum harvest volume of 150m^3^/ha as criteria for whether a forest stand would be harvested. 

In the previous timber supply review analysis a minimum harvest age was used, and was determined by calculating the age at which 95% of the stands achieved maximum mean annual increment (MAI). That age was not provided in the report. 

### Stand Adjacency
Here we used an adjacency constraint of 3m. 

In the previous timber supply review analysis, adjacency has handled by allowing 25% of the THLB in each landscape unit to be less than 13 years old.






```{r module_usage}
library (SpaDES.core)
library (data.table)
source (paste0(here::here(), "/R/functions/R_Postgres.R"))

moduleDir <- file.path(paste0(here::here(), "/R/SpaDES-modules"))
inputDir <- file.path(paste0(here::here(), "/R/SpaDES-modules/forestryCLUS/inputs")) %>% reproducible::checkPath(create = TRUE)
outputDir <- file.path(paste0(here::here(), "/R/SpaDES-modules/forestryCLUS/outputs"))
cacheDir <- file.path(paste0(here::here(), "/R/SpaDES-modules/forestryCLUS"))

times <- list(start = 0, end = 40) # 5 year interval; 200 years = 40 intervals
parameters <- list(
  .progress = list(type = NA, interval = NA),
  .globals = list(),
  dataLoaderCLUS = list (  dbName='clus',
                           save_clusdb = TRUE,
                           useCLUSdb = paste0(here::here(), "/R/SpaDES-modules/dataLoaderCLUS/Revelstoke_TSA_clusdb.sqlite"),
                           nameBoundaryFile = "tsa_aac_bounds",
                           nameBoundaryColumn = "tsa_name",
                           nameBoundary = "Revelstoke_TSA",
                           nameBoundaryGeom = 'wkb_geometry',
                           nameCompartmentRaster = "rast.tsa_aac_boundary",
                           nameCompartmentTable = "tsa_aac_bounds_vat",
                           nameMaskHarvestLandbaseRaster = 'rast.bc_thlb2018',
                           nameZoneRasters = c("rast.zone_cond_beo", 
                                             "rast.zone_cond_vqo", 
                                             "rast.zone_cond_wha", 
                                             "rast.zone_cond_uwr",
                                             "rast.zone_cond_fsw", 
                                             "rast.zone_cond_nharv", 
                                             "rast.zone_cond_cw"
                                             # "rast.raster_test"
                                               ),
                           nameZoneTable = "zone.constraints",
                           # nameZonePriorityRaster = "rast.zone_cond_beo",
                           nameYieldsRaster = "rast.ycid_vdyp",
                           nameYieldTable = "yc_vdyp",
                           nameYieldsTransitionRaster = "rast.tipsy2018_id",
                           nameYieldTransitionTable = "yc_tipsy",
                           nameForestInventoryRaster = "rast.vri2019_id",
                           nameForestInventoryKey = "feature_id",
                           nameForestInventoryTable = "veg_comp_lyr_r1_poly2019",
                           nameForestInventoryAge = "proj_age_1",
                           nameForestInventoryHeight = "proj_height_1",
                           nameForestInventoryTreed = "bclcs_level_2",
                           nameForestInventoryCrownClosure = "crown_closure",
                           nameForestInventoryTreed = "bclcs_level_2",
                           nameForestInventorySiteIndex = "site_index"),
  blockingCLUS = list(blockMethod ='pre', 
                      patchZone = 'rast.zone_cond_beo',
                      patchVariation = 6,
                      nameCutblockRaster ="rast.cns_cut_bl",
                      useLandingsArea = FALSE, 
                      useSpreadProbRas = FALSE),
  forestryCLUS = list(harvestBlockPriority = "age DESC", 
                      #harvestZonePriority = "age DESC",
                      #harvestZonePriorityInterval = 1,
                      reportHarvestConstraints = TRUE,
                      adjacencyConstraint = 3),
  growingStockCLUS = list (periodLength = 5),
  roadCLUS = list(roadMethod = 'pre', 
                  nameCostSurfaceRas = 'rast.rd_cost_surface', 
                  nameRoads =  'rast.crds_all'),
  uploaderCLUS = list(aoiName = 'tutorial', 
                      dbInfo  = list(keyring::key_get("vmdbhost", keyring="postgreSQL"), 
                                     keyring::key_get("vmdbuser", keyring="postgreSQL"), 
                                     keyring::key_get("vmdbpass", keyring="postgreSQL"),  
                                     keyring::key_get("vmdbname", keyring="postgreSQL"))
                  )
)

modules <- list("dataLoaderCLUS", 
                "growingStockCLUS", 
                "blockingCLUS", 
                "forestryCLUS", 
                "roadCLUS",  
                "uploaderCLUS"
                )


### SCENARIOS ###
scenario = data.table (name = "revelstoke_bau", 
                       description = "Business-as-usual case; sustainable flow = 210,000m^3^/year. Adjacency = 3m. Oldest first. 150m3/ha minimum volume.")



harvestFlow <- rbindlist(list(data.table(compartment ="Revelstoke_TSA",
                                         partition = ' vol > 150 ', 
                                         year = rep(seq (from = 2019, 
                                                         to = 2219, 
                                                         by = 5),
                                                    1), 
                                         flow = 1050000) # 210,000m^3^/year
))

#harvestFlow<-rbindlist(list(harvestFlowA,harvestFlowB,harvestFlowC)) # if > 1 harvest flow

patchSizeDist<- data.table(ndt= c(1,1,1,1,1,1,
                                  2,2,2,2,2,2,
                                  3,3,3,3,3,3,
                                  4,4,4,4,4,4,
                                  5,5,5,5,5,5), 
                           sizeClass = c(40,80,120,160,200,240), 
                           freq = c(0.3,0.3,0.1,0.1,0.1, 0.1,
                                    0.3,0.3,0.1,0.1,0.1, 0.1,
                                    0.2, 0.3, 0.125, 0.125, 0.125, 0.125,
                                    0.1,0.02,0.02,0.02,0.02,0.8,
                                    0.3,0.3,0.1,0.1,0.1, 0.1))

objects <- list(harvestFlow = harvestFlow, 
                patchSizeDist = patchSizeDist, 
                scenario = scenario)

paths <- list(cachePath = cacheDir,
              modulePath = moduleDir,
              inputPath = inputDir,
              outputPath = outputDir)

mySim <- simInit(times = times, 
                 params = parameters, 
                 modules = modules,
                 objects = objects, 
                 paths = paths)

# outputs to keep; these are tables that get used in the uploader
outputs(mySim) <- data.frame (objectName = c("harvestReport",
                                             "growingStockReport"))

#Run the model 1 time
system.time({mysimout<-spades(mySim)})

```




