---
title: "forestryCLUS"
author: ""
date: "08 April 2019"
output:
  html_document: 
    keep_md: yes
---

<!--
Copyright 2020 Province of British Columbia
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.-->

# Overview

This module provides the logic for simulating forestry decisions on the landscape. These decisions currently involve spatializing the harvest flow objectives which include: where, when and how much to harvest. These factors help determine policies related to harvest flows, opening size, seral distrubitions, road densitites, preservation areas, silvicultural systems, etc. More sophistication to these decisions would involve looking at the costs and benefits beyond the current time period; this requires optimization or improved heuristics -- which may be considered in the future. The general overview of forestryCLUS follows.

At each time step, harvest units (pixels or blocks) are ranked according to a priority (e.g., oldest first), this constructs a queue. This queue of harvest units are then subject to various constraints meant to meet objectives for the study area. Harvest units are harvested until either a constraint is binding, the queue is exhausted or the harvest flow is met. Next, the age of the forest is advanced to the next time period and the process is repeated. 

During the simulation various reports and information surrounding each pixel can be saved/recorded or used in a summary. Note these outputs are considered expected future outcomes given the inputs developed by the anlayst.For a historical selection of harvesting activities see [cutblockSeqPrepCLUS](https://github.com/bcgov/clus/tree/master/R/SpaDES-modules/cutblockSeqPrepCLUS). Both  cutblockSeqPrepCLUS and forestryCLUS build a list of landing locations through simulation time. One is historical while the other is one possible future realization.

# Usage
This module could be a parent module?? It relies on: 
1. dataloadCLUS (set up the clusdb) 
2. blockingCLUS (preforms the pixel aggregation into harvest units)
3. growingStockCLUS (increments the age and volume in pixels)
4. (Optionally) rsfCLUS (track resource selection functions)
5. (Optionally) roadCLUS (preforms the access to the harvest units)
6. uploaderCLUS (uploades the outputs to a shiny app)


# Prince George TSA Scenarios
business as usual (BAU); no new constraints, caribou or otherwise; establishes the current 'baseline' or benchmark to evaluate the potential impact of 'new' actions in caribou habitat

# Prince George TSA Parameters 

## New Caribou Constraints
BAU = beo, vqo, wha, uwr, fsw (fisheries senstive watersheds),parks and protected areas (nharv) and cw (community watersheds) 

## 'harvestPriority' parameter 
- used oldest first

- as alternative,  could focus on minimizzing 'disturabnce; for caribou, then older, higher volume stands
  - 'dist, age DESC, vol DESC' priortize based on:
      - 'dist', i.e., distance to disturbed pixel (closest first), then
      - 'age DESC', i.e., descending age (oldest first), then
      - 'vol DESC', i.e., descending volume (highest volume first)

## 'harvestFlow'
The current AAC (October 11, 2017) is set at 8,350,000 cubic metres per year for the first five years, and
7,350,000 cubic metres for the following five years. Given its size the TSA is divided into [eight supply blocks](https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/forestry/stewardship/forest-analysis-inventory/tsr-annual-allowable-cut/map_prince_george_tsa.pdf) with a maxmimum of 1.6 M m3 coming from supply blocks A&B and a maximum of 6.1 million cubic metres per year is attributed to the remaining supply
blocks (and reduced to 5. 1 million cubic metres in October 2022), of which 62,000 cubic
metres per year is attributed to deciduous-leading stands. A maximum of 750,000 cubic metres per year is attributed to bioenergy stands.

For south blocks, I started with 6,100,000m3/yr; was close, so dropped to 6,000,000m3/yr; was stable there.

For north blocks, I started with 1.6M m3/yr; 1.5M; 1.25; 1.15; 1.2 - final

## Below is the code chunk for running the sim
###SPADES

```{r module_usage}
library (SpaDES.core)
library (data.table)
source (paste0(here::here(), "/R/functions/R_Postgres.R"))

moduleDir <- file.path(paste0(here::here(), "/R/SpaDES-modules"))
inputDir <- file.path(paste0(here::here(), "/R/SpaDES-modules/forestryCLUS/inputs")) %>% reproducible::checkPath(create = TRUE)
outputDir <- file.path(paste0(here::here(), "/R/SpaDES-modules/forestryCLUS/outputs"))
cacheDir <- file.path(paste0(here::here(), "/R/SpaDES-modules/forestryCLUS"))
times <- list(start = 0, end = 40) # 5 year interval; 200 years = 40 intervals
parameters <- list(
  .progress = list(type = NA, interval = NA),
  .globals = list(),
  dataLoaderCLUS = list( 
                           dbName='clus',
                           save_clusdb = TRUE,
                           sqlite_dbname = "Prince_George_TSA",
                           useCLUSdb = paste0(here::here(), "/R/SpaDES-modules/dataLoaderCLUS/Prince_George_TSA_clusdb.sqlite"), 
                           nameBoundaryFile = "tsa_aac_bounds",
                           nameBoundaryColumn = "tsa_name",
                           nameBoundary = "Prince_George_TSA", # Prince_George_North_TSA   Prince_George_TSA
                           nameBoundaryGeom = 'wkb_geometry',
                           nameCompartmentRaster = "rast.tsa_aac_boundary",
                           nameCompartmentTable = "tsa_aac_bounds_vat",
                           nameMaskHarvestLandbaseRaster = 'rast.bc_thlb2018',
                           nameZoneRasters = c("rast.zone_cond_beo", 
                                               "rast.zone_cond_vqo", 
                                               "rast.zone_cond_wha", 
                                               "rast.zone_cond_uwr",
                                               "rast.zone_cond_fsw",
                                               "rast.zone_cond_nharv",
                                               "rast.zone_cond_cw",
                                           "rast.zone_cond_fisher_sb_wet",
                                           "rast.zone_cond_fisher_sb_dry",
                                           "rast.zone_cond_fisher_dry"
                                    ),
                           nameZoneTable = "zone_constraints",
                           # nameZonePriorityRaster = "rast.zone_cond_beo",
                           nameYieldsRaster = "rast.ycid_vdyp",
                           nameYieldTable = "yc_vdyp",
                           nameYieldsTransitionRaster = "rast.tipsy2018_id",
                           nameYieldTransitionTable = "yc_tipsy",
                           nameForestInventoryRaster = "rast.vri2019_id",
                           nameForestInventoryKey = "feature_id",
                           nameForestInventoryTable = "veg_comp_lyr_r1_poly2019",
                           nameForestInventoryAge = "proj_age_1",
                           nameForestInventoryHeight = "proj_height_1",
                           nameForestInventoryCrownClosure = "crown_closure",
                           nameForestInventoryTreed = "bclcs_level_2",
                           nameForestInventorySiteIndex = "site_index"),
  blockingCLUS = list(blockMethod ='pre', 
                      patchZone = 'rast.zone_cond_beo',
                      patchVariation = 6,
                      nameCutblockRaster ="rast.cns_cut_bl"),
  forestryCLUS = list(harvestBlockPriority = "age DESC", # "dist, age DESC, vol DESC"
                      reportHarvestConstraints = F,
                      adjacencyConstraint = 3),
  growingStockCLUS = list (periodLength = 5),
  roadCLUS = list(roadMethod = 'pre', 
                  nameCostSurfaceRas = 'rast.rd_cost_surface', 
                  nameRoads =  'rast.crds_all'),
   fisherCLUS = list(nameRasFisherTerritory = c('rast.zone_cond_fisher_sb_dry','rast.zone_cond_fisher_sb_wet','rast.zone_cond_fisher_dry'),nameRasWetlands = 'rast.wetland'),
 
  uploaderCLUS = list(aoiName = 'fisher_central_bc', # name of the schema that gets uplaoded to postgres
                      dbInfo  = list(keyring::key_get("vmdbhost", keyring="postgreSQL"), 
                                     keyring::key_get("vmdbuser", keyring="postgreSQL"), 
                                     keyring::key_get("vmdbpass", keyring="postgreSQL"),  
                                     keyring::key_get("vmdbname", keyring="postgreSQL"))
                  )
)

modules <- list("dataLoaderCLUS", 
                "growingStockCLUS", 
                "blockingCLUS", 
                "forestryCLUS", 
                "roadCLUS",  
                "fisherCLUS", 
                "uploaderCLUS"
                )



#scenario = data.table (name = "pg_bau", description = "Business as usual. Harvest flow = 6,000,000 m3/yr. Adjacency = 3m. Oldest first.")
scenario = data.table (name = "pg_all_terr_10per_max12yrs", description = "bau + maximum 10 % of the territory <= 12 years of age. Harvest flow = 6,000,000 m3/yr. Adjacency = 3m. Oldest first.")



harvestFlow <- rbindlist(list(data.table(compartment ="Prince_George_TSA", # Prince_George_North_TSA   Prince_George_TSA
                                         partition = ' vol > 182 and age >= 75  ', 
                                         period = rep( seq (from = 1, # run the 
                                                      to = 40, 
                                                      by = 1),
                                                      1), 
                                         flow = 30000000,
                                         partition_type = 'live') #6,000,000 / 30000000 //  1,200,000 / 6000000 
))

objects <- list(harvestFlow = harvestFlow, scenario = scenario)

paths <- list(cachePath = cacheDir,
              modulePath = moduleDir,
              inputPath = inputDir,
              outputPath = outputDir)

mySim <- simInit(times = times, 
                 params = parameters, 
                 modules = modules,
                 objects = objects, 
                 paths = paths)

#Run the model 1 time
system.time({mysimout<-spades(mySim)})

```

