---
title: "agglomerative_clustering"
output: html_document
date: '2022-07-13'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(igraph)
library(data.table)
```

## Bring in cost layer and convert to a table
```{r}
ras<-raster("C:/Users/klochhea/fetaMapper/data-raw/dry_cost_multi.tif")
ras.table<-data.table(cost=ras[])
ras.table[, pixelid := seq_len(.N)]
ras.table[, cost:=6-cost]
#ras.table[, cost:=cost + runif(nrow(ras.table), 0,0.01)]

ras.dt.den<-raster("C:/Users/klochhea/fetaMapper/data-raw/dry_denning.tif")
ras.dt<-ras.dt.den
#Get the XY
xy.ras<-data.table(raster::xyFromCell(ras.dt.den, 1:ncell(ras.dt.den)))
xy.ras$den<-ras.dt.den[]
test<-RANN::nn2(xy.ras[!is.na(den), c("x", "y")],xy.ras[is.na(den), c("x", "y")],k=1)
xy.ras[, dist:= 0]
xy.ras[is.na(den), dist:= test$nn.dists]
xy.ras[dist > 5000, dist:=5000]
xy.ras[, dist:=(dist/5000)]
ras.dt[]<-xy.ras$dist


ras.table[, cost:=cost*(xy.ras$dist) + runif(nrow(ras.table), 0,0.01)]

ras.dt.den[]<-ras.table$cost
```

## Get edge list
```{r}
edges<-data.table(SpaDES.tools::adj(returnDT= TRUE, directions = 8, numCol = ncol(ras), numCell=ncol(ras)*nrow(ras),
                                             cells = 1:as.integer(ncol(ras)*nrow(ras)))) 

edges[, to := as.integer(to)]
edges[, from := as.integer(from)]
edges[from < to, c("from", "to") := .(to, from)] #find the duplicates. Since this is non-directional graph no need for weights in two directions
edges<-unique(edges)#remove the duplicates
  
#Merge in the weights between pixels
edges.w1<-merge(x=edges, y=ras.table, by.x= "from", by.y ="pixelid", all.x= TRUE) #merge in the weights from a cost surface
setnames(edges.w1, c("from", "to", "w1_cost"))  #reformat
edges.w2<-data.table::setDT(merge(x=edges.w1, y=ras.table, by.x= "to", by.y ="pixelid", all.x= TRUE))#merge in the weights to a cost surface
setnames(edges.w2, c("from", "to", "w1_cost", "w2_cost")) #reformat
  
edges.w2[, weight:= abs(w1_cost-w2_cost)] #take the absolute cost between the two pixels
  

edges.weight<-edges.w2[complete.cases(edges.w2), c("from", "to", "weight")] #get rid of NAs caused by barriers. Drop the w1 and w2 costs.
edges.weight<-as.matrix(edges.weight[, id := seq_len(.N)]) #set the ids of the edge list. Faster than using as.integer(row.names())
```

## Get the graph
```{r}
  #g<-graph.lattice(c(nrow(sim$ras), ncol(sim$ras), 1))#instantiate the igraph object
g<-graph.edgelist(edges.weight[,1:2], dir = FALSE) #create the graph using to and from columns. Requires a matrix input
E(g)$weight<-edges.weight[,3]#assign weights to the graph. Requires a matrix input
  
g<-g %>% 
    set_vertex_attr("name", value = V(g))
g<-delete.vertices(g, degree(g) == 0) 

```

## Solve the MST
```{r}
g.mst_sub<-mst(g, weighted=TRUE)
paths.matrix<-data.table(cbind(noquote(get.edgelist(g.mst_sub)), E(g.mst_sub)$weight))
paths.matrix[, V1 := as.integer(V1)][, V2 := as.integer(V2)]

lut<-data.table(verts = as_ids(V(g)))[, ind := seq_len(.N)]
```

## Set the parameters of the clustering algorthm
```{r}
ncell = ras@nrows*ras@ncols
patchDist <- list(3000 ,  round(ncell/3000) )
resultset <-list(list(as.matrix(degree(g.mst_sub)), paths.matrix, 1, patchDist, 100, lut)) #the degree list (which is the number of connections to other pixels) and the edge list describing the to-from connections - with their weights
```

## import the function
```{r}
### additional functions
getBlocksIDs<- function(x){ 
  #---------------------------------------------------------------------------------#
  #This function uses resultset object as its input. 
  #The resultset object is a list of lists: 1.the degree list.
  #2. A list of edges (to and from) and weights; 3. The zone name; and
  #4. The patch size distribution. These are accessed via x[][[1-4]]
  #---------------------------------------------------------------------------------#
  message(paste0("getBlocksID for zone: ", x[][[3]])) #Let the user know what zone is being blocked
  
  .jinit(classpath= paste0(here::here(),"/Java/bin"), parameters="-Xmx2g", force.init = TRUE) #instantiate the JVM
  fhClass<-.jnew("forest_hierarchy.Forest_Hierarchy") # creates a new forest hierarchy object in java
  
  dg<- data.table(cbind(as.integer(rownames(x[][[1]])),as.integer(x[][[1]]))) #Sets the degree list
  dg<- data.table(tidyr::complete(dg, V1= seq(1:as.integer(max(dg[,1]))),fill = list(V2 = as.integer(-1))))#this is needed for indexing
  #TODO: remove this index dependancy in java where the index refers to the pixelid.
  d<-convertToJava(as.integer(unlist(dg[,"V2"]))) #convert to a java object
  
  #Set the patchsize distribution as a java object
  h<-convertToJava(data.frame(size= x[][[4]][[1]], n = as.integer(x[][[4]][[2]])), array.order = "column-major", data.frame.row.major = TRUE)
  h<-rJava::.jcast(h, getJavaClassName(h), convert.array = TRUE)
  
  to<-.jarray(as.matrix(x[][[2]][,1])) #set the "to" list as a java object
  from<-.jarray(as.matrix(x[][[2]][,2]))#set the "from" list as a java object
  weight<-.jarray(as.matrix(x[][[2]][,3])) #set the "weight" list as a java object
  fhClass$setRParms(to, from, weight, d, h, x[][[5]]) # sets the input R parameters <Edges> <Degree> <Histogram> <variation>
  fhClass$blockEdges2() # builds the blocks
  #blockids<-cbind(convertToR(fhClass$getBlocks()), as.integer(unlist(dg[,1]))) #creates a link between pixelid and blockid
  blockids<-cbind(convertToR(fhClass$getBlocks()), as.integer(x[][[6]]$verts)) #creates a link between pixelid and blockid
  #stop()
  fhClass$clearInfo() #This method clears the object so it can be sent for garbage collection
  
  rm(fhClass, dg, h, to, from, weight) #remove from memory
  gc() #call garbage collection in R
  jgc() #call garbage collection in java
  
  list(blockids) #add the output of pixelid and the corresponding blockid in a list
}

worker.init <- function(packages) { #used for setting up the environments of the cores
  for (p in packages) {
    library(p, character.only=TRUE) #need character.only=TRUE to evaluate p as a character
  }
  NULL #return NULL to avoid sending unnecessary data back to the master process
}

jgc <- function() .jcall("java/lang/System", method = "gc")

binFreqTable <- function(x, bins) {
  freq = hist(x, breaks=c(0,bins, 100000), include.lowest=TRUE, plot=FALSE)
  ranges = paste(head(freq$breaks,-1), freq$breaks[-1], sep=" - ")
  return(data.frame(range = ranges, frequency = freq$counts))
}

```

#run the algorthm
```{r}
Sys.setenv(JAVA_HOME='C:\\Program Files\\Java\\jdk-14.0.1')
options(java.parameters = "-Xmx2g")
library(rJava) #Calling the rJava library instantiates the JVM. Note: cannot instantiate the same JVM on both the cores and the master. 
library(jdx)
message("running java on one cluster")

blockids<-lapply(resultset, getBlocksIDs)  

ras2<-ras
ras2[]<-blockids[[1]][[1]][,1]


```