---
title: "forestryCLUS"
author: ""
date: "08 April 2019"
params:
  db_host: NULL
  db_port: NULL
  db_name: NULL
  db_user: NULL
  db_pass: NULL
output:
  html_document: 
    keep_md: yes
---

<!--
Copyright 2020 Province of British Columbia
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.-->

## Check if params are passed

```{r echo=FALSE}
print(paste("Checking params: db_host - ", params$db_host))
print(paste("Checking params: db_name -", params$db_name))
```

## Check reading env vars

```{r echo=FALSE}
print(paste("Checking env vars: db_host - ", Sys.getenv("DB_HOST")))
print(paste("Checking env vars: db_name - ", Sys.getenv("DB_NAME")))
```

Use the credentials to connect to the database.

```{r echo=FALSE}
params$db_host
params$db_port
# params$db_name
# params$db_user
# params$db_pass
Sys.getenv("DB_HOST")
Sys.getenv("DB_NAME")
```
