---
title: "Caribou_and_fire_sim"
author: "Elizabeth Kleynhans"
date: "2023-03-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source(here::here("R/functions/R_Postgres.R"))
library(tidyverse)
require (sf)
require (RPostgreSQL)
require (rpostgis)
require (fasterize)
require (raster)
require (tidyverse)
library(bcdata)

library(terra)
library(quickPlot)
library(data.table)
library(ggplot2)
library(SpaDES.tools)
library(SpaDES.addins)
library(SpaDES)
library(SpaDES.core)

```


```{r}
# get latest data off BCGW
ignit<-try(
  bcdc_query_geodata("WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL_INCIDENTS_SP") %>%
    filter(FIRE_YEAR > 2001) %>%
    filter(FIRE_TYPE == "Fire") %>%
    collect()
)

caribou<-try(
  bcdc_query_geodata("WHSE_WILDLIFE_INVENTORY.GCPB_CARIBOU_POPULATION_SP") %>%
    collect()
)

head(caribou)

```

# select a study area
```{r}
# get study area
study_area<-getSpatialQuery("SELECT * FROM tsa_boundaries where administrative_area_name in ('Bulkley Timber Supply Area', 'Cascadia Timber Supply Area', 'Great Bear Rainforest North Timber Supply Area', 'Great Bear Rainforest South Timber Supply Area', 'Kalum Timber Supply Area', 'Kispiox Timber Supply Area', 'Lakes Timber Supply Area', 'Morice Timber Supply Area', 'Pacific Timber Supply Area', 'Prince George Timber Supply Area', 'Quesnel Timber Supply Area', 'Williams Lake Timber Supply Area')")

study_area2<-study_area %>% group_by ( administrative_area_name) %>% summarise()
st_crs(study_area2)

ignit_2021<-ignit %>% filter(FIRE_YEAR==2021)

ignit_subset <- ignit_2021[study_area2, ]
ignit_subset_10<- ignit_subset %>% filter(CURRENT_SIZE >16)

length(ignit_subset$CURRENT_SIZE) # 363 locations caught fire
length(ignit_subset_10$CURRENT_SIZE) # 38 locations had fires > 16ha

ggplot() +
  geom_sf(data=study_area2) + 
  geom_sf(data=ignit_subset)  +
  geom_sf(dat=ignit_subset_10, col="red")
```


###########################################
## Determine distribution of ignitions since 2000 and use that distribution as something to sample number of fires off. Keep it constant into the future even thought this not ideal.

```{r}
ignit <- ignit[study_area2, ]

data <- ignit %>% group_by(FIRE_YEAR) %>% summarize(n=n()) %>% mutate(freq=n/sum(n)) 

my_data<-data$n

library(fitdistrplus)
plotdist(my_data, histo = TRUE, demp = TRUE)
descdist(my_data, discrete=FALSE, boot=500)

fit_w  <- fitdist(my_data, "weibull")
fit_g  <- fitdist(my_data, "gamma")
fit_ln <- fitdist(my_data, "lnorm")
fit_nr <- fitdist(my_data, "norm")

dists <- c("gamma","lnorm","weibull", "norm")
fit <- list()
for (i in 1:length(dists)){
  fit[[i]]  <- fitdist(my_data, dists[i])
}

for (i in 1:length(dists)){
  print(summary(fit[[i]]))
}

# from AIC weibull distribution is best
# Plot the results from the individually
#fitted distributions and compare
par(mfrow=c(2,2))
denscomp(fit_w)
denscomp(fit_g)
denscomp(fit_ln)
denscomp(fit_nr)

qqcomp(fit_w)
qqcomp(fit_g) # tells how well the distriontion fits the tails
qqcomp(fit_ln)
qqcomp(fit_nr)

ppcomp(fit_w)
ppcomp(fit_ln)
ppcomp(fit_g) # tells how well the center of the distribution fits
ppcomp(fit_nr)
# Overall it looks like the gamma distribution might be best

summary(fit_nr)

ggplot(data, aes(x = n)) +
  geom_histogram(aes(y=after_stat(density)),      # Histogram with density instead of count on y-axis
                   #binwidth=80,
                   colour="black", fill="lightblue") +
  #geom_density( fill="lightblue") + 
  stat_function(fun=dnorm, args=list(mean=fit_nr$estimate[1], sd=fit_nr$estimate[2])) +
  stat_function(fun=dweibull, args=list(shape=fit_w$estimate[1], scale=fit_w$estimate[2]), color="red") +
  labs(x = "n", y = "density", title = "Fitted normal (black) and weibull (red) with underlying data (blue)") 


ggplot(data, aes(x = n)) +
  geom_histogram(aes(y=after_stat(density)),      # Histogram with density instead of count on y-axis
                   #binwidth=80,
                   colour="black", fill="lightblue") +
  #geom_density( fill="lightblue") + 
  stat_function(fun=dweibull, args=list(shape=fit_w$estimate[1], scale=fit_w$estimate[2]), color="red") +
  labs(x = "n", y = "density", title = "Fitted weibull distribution with underlying data (blue)") 

#https://dk81.github.io/dkmathstats_site/rvisual-cont-prob-dists.html
# see above for plotting other distributions

# I think Ill use the normal distribution

```



```{r}
# 2021
total_ignition<-raster(" C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\tot_ignition_2021.tif")
escape.ras<-raster("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\Prob_escape_2021.tif")
spread.ras<-raster("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\Prob_spread_2021.tif")

# 2024
library(raster)
ignit <- list.files(path="C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\", pattern='tot_ignition', full.names=TRUE)
Prob_ignit <- lapply(ignit, raster)

escape <- list.files(path="C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\", pattern='Prob_escape', full.names=TRUE)
Prob_escape <- lapply(escape, raster)

spread <- list.files(path="C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\", pattern='Prob_spread', full.names=TRUE)
Prob_spread <- lapply(spread, raster)


# 2050
total_ignition_2049<-raster(" C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\tot_ignition_2049.tif")
escape.ras_2049<-raster("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\Prob_escape_2049.tif")
spread.ras_2049<-raster("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\Prob_spread_2049.tif")
crs(spread.ras)
crs(escape.ras)

# assign negative values (no data values) NA
total_ignition <- reclassify(total_ignition, cbind(-Inf, 0, NA), right=FALSE)
escape.ras <- reclassify(escape.ras, cbind(-Inf, 0, NA), right=FALSE)
spread.ras <- reclassify(spread.ras, cbind(-Inf, 0, NA), right=FALSE)

total_ignition_2049 <- reclassify(total_ignition_2049, cbind(-Inf, 0, NA), right=FALSE)
escape.ras_2049 <- reclassify(escape.ras_2049, cbind(-Inf, 0, NA), right=FALSE)
spread.ras_2049 <- reclassify(spread.ras_2049, cbind(-Inf, 0, NA), right=FALSE)

plot(total_ignition, col=rev(heat.colors(255)))
plot(spread.ras, col=rev(heat.colors(255)))
plot(escape.ras, col=rev(heat.colors(255)))

plot(total_ignition_2049, col=rev(heat.colors(255)))
plot(escape.ras_2049, col=rev(heat.colors(255)))
plot(spread.ras_2049, col=rev(heat.colors(255)))

spread.ras.2<-spread.ras-0.05
spread.ras_2049.2<-spread.ras_2049-0.05
plot(spread.ras.2, col=rev(heat.colors(255)))
plot(spread.ras_2049.2, col=rev(heat.colors(255)))
spread.ras.2 <- reclassify(spread.ras.2, cbind(-Inf, 0, NA), right=FALSE)
spread.ras_2049.2 <- reclassify(spread.ras_2049.2, cbind(-Inf, 0, NA), right=FALSE)


# crop the raster using the vector extent
ignit_crop <- crop(total_ignition, study_area2)
escape_crop <- crop(escape.ras, study_area2)
spread_crop <- crop(spread.ras.2, study_area2)

ignit_crop_49 <- crop(total_ignition_2049, study_area2)
escape_crop_49 <- crop(escape.ras_2049, study_area2)
spread_crop_49 <- crop(spread.ras_2049.2, study_area2)

# replacing NA's by zero
escape_crop[is.na(escape_crop[])] <- 0 
ignit_crop[is.na(ignit_crop[])] <- 0 
spread_crop[is.na(spread_crop[])] <- 0 

# replacing NA's by zero
escape_crop_49[is.na(escape_crop_49[])] <- 0 
ignit_crop_49[is.na(ignit_crop_49[])] <- 0 
spread_crop_49[is.na(spread_crop_49[])] <- 0 

```


## figure of ignition points
```{r}
#create landscape  raster with each pixel having a different idno
a <- raster(extent(spread_crop), 
  crs = st_crs(spread_crop)$proj4string, resolution = c(400, 400), vals = 1:ncell(ignit_crop))

# make the starting locations the same as the actual ignition locations. Expect to see similar distribution of fire sizes as seen in the original data.
test<-cbind(ignit_subset, st_coordinates(ignit_subset))
head(test)

pointCoordinates<-data.frame(test$X, test$Y)
head(pointCoordinates)

start_points=raster::extract(a, pointCoordinates)

test2<-cbind(test,start_points )

start_points<- unique(start_points) # there appear to be two starting cells that get ignited twice so Im removing the duplicates

#####
# plotting points on raster to check they are still correct
ignit_pts <- rasterToPoints(escape_crop, spatial = TRUE)
# Then to a 'conventional' dataframe
ignit_pts_df  <- data.frame(ignit_pts)

ignit_subset<-ignit_subset %>%
  mutate(escaped = case_when(CURRENT_SIZE > 16 ~ 1,
                           CURRENT_SIZE <= 16 ~ 0))

ggplot() +
 geom_raster(data = ignit_pts_df , aes(x = x, y = y, fill = Prob_escape_2021)) +
  geom_sf(data=ignit_subset, aes(color = as.factor(escaped)))  #+
  #geom_point(data = pointCoordinates, aes(x = test.X, y = test.Y))
#####
```

## 2021
```{r}
#create landscape  raster with each pixel having a different idno
a <- raster(extent(ignit_crop), 
  crs = st_crs(ignit_crop)$proj4string, resolution = c(400, 400), vals = 1:ncell(ignit_crop))

#no_ignitions=length(ignit_subset$CURRENT_SIZE) # number of ignitions (FIX this so its drawn from a distribution or pulled off a map or something)
n<-100 # number of reps
out<-list()
set.seed(123)

#####
#ignition.pts<-start_points
tot.area.burned<-integer(n)
tot.escapes<-integer(n)

for (i in 1:n) {
  
# initiate ignitions at randomly chosen points
no_ignitions<-round(rnorm(1, mean=mean(my_data), sd=sd(my_data)),0)
no_ignitions<-ifelse(no_ignitions<40, 40, no_ignitions)

startCells <- as.integer(sample(1:ncell(ignit_crop), no_ignitions))
#startCells<-start_points

#extract probability numbers from the igniton map
probs.ignit<-ignit_crop[startCells]
#draw random number from uniform distribution
random.num<-runif(no_ignitions)
#combine values into a datagram
#df<-as.data.frame(cbind(startCells, probs.ignit, random.num))
#select points that have an ignition probability greater than the randomly drawn number.
ignition.pts<- startCells[probs.ignit > random.num ]

# Now test if the fire can escape from the ignition point
  #extract probability numbers from the escape map
probs.escape<-escape_crop[ignition.pts]
#draw random number from uniform distribution
random.num<-runif(length(ignition.pts))
#combine values i
escape.pts<- ignition.pts[probs.escape > random.num ]

tot.escapes[i]<-length(escape.pts)


#dim(ignit_subset[(ignit_subset$CURRENT_SIZE>10),])

out[[i]]  <- spread2(a, start = escape.pts, spreadProb = spread_crop, asRaster = FALSE, allowOverlap = FALSE)
tot.area.burned[i]<-out[[i]][,.N]

}

out2<-data.table::rbindlist(out)
b<-table(a[out2$pixels])
b1<-b/n

b.tab<-data.table(b1)
b.tab$V1<-as.numeric(b.tab$V1)
a[]<-0
a[b.tab$V1]<-b.tab$N

plot(a)

```

```{r}
writeRaster(a, filename = "C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\Sim_run_results\\Caribou_2021_100reps.tif", format = "GTiff")
```

## Try sim for 2049
```{r}

#create landscape  raster with each pixel having a different idno
a <- raster(extent(ignit_crop_49), 
  crs = st_crs(ignit_crop_49)$proj4string, resolution = c(400, 400), vals = 1:ncell(ignit_crop_49))

#no_ignitions=length(ignit_subset$CURRENT_SIZE) # number of ignitions (FIX this so its drawn from a distribution or pulled off a map or something)
n<-100 # number of reps
out<-list()
set.seed(123)

#####
#ignition.pts<-start_points
tot.area.burned<-integer(n)
tot.escapes<-integer(n)

for (i in 1:n) {
  
# initiate ignitions at randomly chosen points
no_ignitions<-round(rnorm(1, mean=mean(my_data), sd=sd(my_data)),0)
no_ignitions<-ifelse(no_ignitions<40, 40, no_ignitions)

startCells <- as.integer(sample(1:ncell(ignit_crop_49), no_ignitions))
#startCells<-start_points

#extract probability numbers from the igniton map
probs.ignit<-ignit_crop_49[startCells]
#draw random number from uniform distribution
random.num<-runif(no_ignitions)
#combine values into a datagram
#df<-as.data.frame(cbind(startCells, probs.ignit, random.num))
#select points that have an ignition probability greater than the randomly drawn number.
ignition.pts<- startCells[probs.ignit > random.num ]

# Now test if the fire can escape from the ignition point
  #extract probability numbers from the escape map
probs.escape<-escape_crop_49[ignition.pts]
#draw random number from uniform distribution
random.num<-runif(length(ignition.pts))
#combine values i
escape.pts<- ignition.pts[probs.escape > random.num ]

tot.escapes[i]<-length(escape.pts)


#dim(ignit_subset[(ignit_subset$CURRENT_SIZE>10),])

out[[i]]  <- spread2(a, start = escape.pts, spreadProb = spread_crop_49, asRaster = FALSE, allowOverlap = FALSE)
tot.area.burned[i]<-out[[i]][,.N]

}

out2<-data.table::rbindlist(out)
b<-table(a[out2$pixels])
b1<-b/n

b.tab<-data.table(b1)
b.tab$V1<-as.numeric(b.tab$V1)
a[]<-0
a[b.tab$V1]<-b.tab$N

plot(a)

```

```{r}
writeRaster(a, filename = "C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\Sim_run_results\\Caribou_2049_100reps.tif", format = "GTiff")
```



```{r}
#question is it burning this many pixels because it runs out of pixels? Test this by increasing the area that is availabel to burn

# some other stats 
number_ignits<-list()

fire_size_end <- data.frame (matrix (ncol = 3, nrow = 0)) # add 'data' to the points
colnames (fire_size_end) <- c ("Var1", "Freq", "rep")

for (i in 1:n) {
  
  number_ignits[[i]]<-out[[i]][, .N, by = "initialPixels"]$N
  #number_ignits[[i]]<-length(unique(out[[i]]$initialPixels))
  
  fire_size_intermediate<-as.data.frame(table(out[[i]]$initialPixels))
  fire_size_intermediate$rep<-i
  
  fire_size_end<-rbind(fire_size_end, fire_size_intermediate)
  
}

fire_size_end$Freq2<-as.numeric(fire_size_end$Freq*16)

fire_size_end$rep<-as.factor(fire_size_end$rep)

ggplot(ignit_subset_10, aes(x=CURRENT_SIZE)) + 
  geom_density(show.legend = FALSE)

fire_size_end_1<-fire_size_end %>% filter(rep==1)

ggplot() + 
  geom_density(data=fire_size_end_1, aes(x=Freq2), show.legend = FALSE) +
  geom_density(data=ignit_subset_10, aes(x=CURRENT_SIZE), color="blue")


x<-aggregate(fire_size_end$Freq, by=list(Category=fire_size_end$Var1), FUN=median)

x<-x %>% rename(start_points=Category,
                size = x)

x$start_points<-as.numeric(as.character(x$start_points))
x2<-left_join(test2, x)
x2 <- x2 %>% mutate(size = ifelse(is.na(size), 1, size))

ggplot(data=x2) +    
   geom_histogram(aes(x=size), fill = "blue") +
#ggplot(data=x2) +    
   geom_histogram(aes(x=CURRENT_SIZE), fill = "green") 

hist(ignit_subset_10$CURRENT_SIZE, breaks=50)

library(reshape2)
# reshape data from wide to long format
long <- melt(x2, id= "start_points", measure.vars = c("size", "CURRENT_SIZE"))
g <- long%>%
  ggplot(aes(x=value, fill=variable)) +
  geom_histogram(alpha=0.3) #+
  #scale_x_log10()

g
```

I think this is correct because in the sim Im using the escaped layer to choose which ones escape
```{r}
###########################
# how many fires escaped i.e. grew bigger than 16 ha?

rep<-1:n
number_escaped<-as.data.frame(cbind(rep, tot.escapes, tot.area.burned))
number_escaped$tot.escapes
length(ignit_subset_10$CURRENT_SIZE)


# Basic density
p <- ggplot(number_escaped, aes(x=tot.escapes)) + 
  geom_density() + 
   xlim(0, 60)
# Add mean line
p + geom_vline(aes(xintercept=length(ignit_subset_10$CURRENT_SIZE)), color="blue", linetype="dashed", size=1)

# Basic density
# p2 <- ggplot(number_escaped, aes(x=tot.area.burned)) + 
#   geom_density() + 
#    xlim(0, 400000)
# # Add mean line
# p2 + geom_vline(aes(xintercept=sum(ignit_subset_10$CURRENT_SIZE)), color="blue", linetype="dashed", size=1)
#          

```