---
title: "Untitled"
author: "Elizabeth Kleynhans"
date: "2023-03-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(raster)
library(bcdata)
library(ggplot2)
library(tidyverse)
library(SpaDES.tools)
library(SpaDES.addins)
library(SpaDES)
library(SpaDES.core)
library(data.table)

source(here::here("R/functions/R_Postgres.R"))
```

# Need to determine distribution of ignitions
```{r}
# get latest data off BCGW
ignit<-try(
  bcdc_query_geodata("WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL_INCIDENTS_SP") %>%
    filter(FIRE_YEAR > 2000) %>%
    filter(FIRE_TYPE == "Fire") %>%
    collect()
)

caribou<-try(
  bcdc_query_geodata("WHSE_WILDLIFE_INVENTORY.GCPB_CARIBOU_POPULATION_SP") %>%
    collect()
)

head(caribou)

```


###########################################
## Determine distribution of ignitions since 2000 and use that distribution as something to sample number of fires off. Keep it constant into the future even thought this not ideal.

```{r}
ignit <- ignit[study_area2, ]

data <- ignit %>% group_by(FIRE_YEAR) %>% summarize(n=n()) %>% mutate(freq=n/sum(n)) 

my_data<-data$n

library(fitdistrplus)
plotdist(my_data, histo = TRUE, demp = TRUE)
descdist(my_data, discrete=FALSE, boot=500)

fit_w  <- fitdist(my_data, "weibull")
fit_g  <- fitdist(my_data, "gamma")
fit_ln <- fitdist(my_data, "lnorm")
fit_nr <- fitdist(my_data, "norm")

dists <- c("gamma","lnorm","weibull", "norm")
fit <- list()
for (i in 1:length(dists)){
  fit[[i]]  <- fitdist(my_data, dists[i])
}

for (i in 1:length(dists)){
  print(summary(fit[[i]]))
}

# from AIC weibull distribution is best
# Plot the results from the individually
#fitted distributions and compare
par(mfrow=c(2,2))
denscomp(fit_w)
denscomp(fit_g)
denscomp(fit_ln)
denscomp(fit_nr)

qqcomp(fit_w)
qqcomp(fit_g) # tells how well the distriontion fits the tails
qqcomp(fit_ln)
qqcomp(fit_nr)

ppcomp(fit_w)
ppcomp(fit_ln)
ppcomp(fit_g) # tells how well the center of the distribution fits
ppcomp(fit_nr)
# Overall it looks like the gamma distribution might be best

summary(fit_nr)

ggplot(data, aes(x = n)) +
  geom_histogram(aes(y=after_stat(density)),      # Histogram with density instead of count on y-axis
                   #binwidth=80,
                   colour="black", fill="lightblue") +
  #geom_density( fill="lightblue") + 
  stat_function(fun=dnorm, args=list(mean=fit_nr$estimate[1], sd=fit_nr$estimate[2])) +
  stat_function(fun=dweibull, args=list(shape=fit_w$estimate[1], scale=fit_w$estimate[2]), color="red") +
  labs(x = "n", y = "density", title = "Fitted normal (black) and weibull (red) with underlying data (blue)") 


ggplot(data, aes(x = n)) +
  geom_histogram(aes(y=after_stat(density)),      # Histogram with density instead of count on y-axis
                   #binwidth=80,
                   colour="black", fill="lightblue") +
  #geom_density( fill="lightblue") + 
  stat_function(fun=dweibull, args=list(shape=fit_w$estimate[1], scale=fit_w$estimate[2]), color="red") +
  labs(x = "n", y = "density", title = "Fitted weibull distribution with underlying data (blue)") 

#https://dk81.github.io/dkmathstats_site/rvisual-cont-prob-dists.html
# see above for plotting other distributions

# I think Ill use the normal distribution

```


## If determined distribution of ignitions of area start simulation from here!
```{r setup, include=FALSE}
ignit <- list.files(path="C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\Prob_fire_2011_2100\\", pattern='Prob_ignit', full.names=TRUE)
Prob_ignit <- lapply(ignit, raster)

escape <- list.files(path="C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\Prob_fire_2011_2100\\", pattern='Prob_escape', full.names=TRUE)
Prob_escape <- lapply(escape, raster)

spread <- list.files(path="C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\Prob_fire_2011_2100\\", pattern='Prob_spread', full.names=TRUE)
Prob_spread <- lapply(spread, raster)
```


```{r}
# get study area
study_area<-getSpatialQuery("SELECT * FROM tsa_boundaries where administrative_area_name in ('Bulkley Timber Supply Area', 'Cascadia Timber Supply Area', 'Great Bear Rainforest North Timber Supply Area', 'Great Bear Rainforest South Timber Supply Area', 'Kalum Timber Supply Area', 'Kispiox Timber Supply Area', 'Lakes Timber Supply Area', 'Morice Timber Supply Area', 'Pacific Timber Supply Area', 'Prince George Timber Supply Area', 'Quesnel Timber Supply Area', 'Williams Lake Timber Supply Area')")

study_area2<-study_area %>% group_by ( administrative_area_name) %>% summarise()
st_crs(study_area2)
```


```{r setup, include=FALSE}
Prob_ignit_2<-list()
Prob_escape_2<-list()
Prob_spread_2<-list()

# ignit
for (i in 1:length(ignit)) {
Prob_ignit_2[[i]] <- reclassify(Prob_ignit[[i]], cbind(-Inf, 0, NA), right=FALSE)

Prob_ignit_2[[i]] <- crop(Prob_ignit_2[[i]], study_area2)
Prob_ignit_2[[i]][is.na(Prob_ignit_2[[i]][])] <- 0 
}

# escape
for (i in 1:length(escape)) {
Prob_escape_2[[i]] <- reclassify(Prob_escape[[i]], cbind(-Inf, 0, NA), right=FALSE)

Prob_escape_2[[i]] <- crop(Prob_escape_2[[i]], study_area2)
Prob_escape_2[[i]][is.na(Prob_escape_2[[i]][])] <- 0 
}

# note my spread probabilities seem to be too high so I've reduced them by 0.5 
for (i in 1:length(spread)) {

Prob_spread_2[[i]] <- Prob_spread[[i]] 
Prob_spread_2[[i]] <- reclassify(Prob_spread_2[[i]], cbind(-Inf, 0, NA), right=FALSE)

Prob_spread_2[[i]] <- crop(Prob_spread_2[[i]], study_area2)
Prob_spread_2[[i]][is.na(Prob_spread_2[[i]][])] <- 0 

}

```

```{r}
#create landscape  raster with each pixel having a different idno
a<-list()
tot.area.burned<-list()
tot.escapes<-list()
n<-200 # number of reps
set.seed(123)

for (i in 1:length(Prob_ignit_2)) {
  
print(i)
  
a[[i]] <- raster(extent(Prob_ignit_2[[i]]), 
  crs = st_crs(Prob_ignit_2[[i]])$proj4string, resolution = c(400, 400), vals = 1:ncell(Prob_ignit_2[[i]]))

#no_ignitions=length(ignit_subset$CURRENT_SIZE) # number of ignitions (FIX this so its drawn from a distribution or pulled off a map or something)
out<-list()
#####
#ignition.pts<-start_points
tot.area.burned[[i]]<-integer(n)
tot.escapes[[i]]<-integer(n)

for (j in 1:n) {
  
# initiate ignitions at randomly chosen points
no_ignitions<-round(rnorm(1, mean=mean(my_data), sd=sd(my_data)),0)
no_ignitions<-ifelse(no_ignitions<40, 40, no_ignitions)

startCells <- as.integer(sample(1:ncell(Prob_ignit_2[[i]]), no_ignitions))
#startCells<-start_points

#extract probability numbers from the igniton map
probs.ignit<-Prob_ignit_2[[i]][startCells]
#draw random number from uniform distribution
random.num<-runif(no_ignitions)
#combine values into a datagram
#df<-as.data.frame(cbind(startCells, probs.ignit, random.num))
#select points that have an ignition probability greater than the randomly drawn number.
ignition.pts<- startCells[probs.ignit > random.num ]

# Now test if the fire can escape from the ignition point
  #extract probability numbers from the escape map
probs.escape<-Prob_escape_2[[i]][ignition.pts]
#draw random number from uniform distribution
random.num<-runif(length(ignition.pts))
#combine values i
escape.pts<- ignition.pts[probs.escape > random.num ]

tot.escapes[[i]][j]<-length(escape.pts)


#dim(ignit_subset[(ignit_subset$CURRENT_SIZE>10),])

out[[j]]  <- spread2(a[[i]], start = escape.pts, spreadProb = Prob_spread_2[[i]], asRaster = FALSE, allowOverlap = FALSE)
tot.area.burned[[i]][j]<-out[[j]][,.N]

}

out2<-data.table::rbindlist(out)
b<-table(a[[i]][out2$pixels])
b1<-b/n

b.tab<-data.table(b1)
b.tab$V1<-as.numeric(b.tab$V1)
a[[i]][]<-0
a[[i]][b.tab$V1]<-b.tab$N

plot(a[[i]])

}

plot(a[[i]])
```


```{r}
writeRaster(a[[1]], "C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\Sim_run_results\\sim_2011_2020.tif", overwrite=TRUE)

writeRaster(a[[2]], "C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\Sim_run_results\\sim_2021_2040.tif", overwrite=TRUE)

writeRaster(a[[3]], "C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\Sim_run_results\\sim_2041_2060.tif", overwrite=TRUE)

writeRaster(a[[4]], "C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\Sim_run_results\\sim_2061_2080.tif", overwrite=TRUE)


```


```{r}
ggplot() +
  geom_density(aes(tot.area.burned[[1]]), fill="lightgrey") +
  geom_vline(aes(xintercept=mean(tot.area.burned[[1]])), color="lightblue", linetype="dashed", size=1) +
  geom_density(aes(tot.area.burned[[2]]), fill="lightblue", alpha=0.4) +
  geom_vline(aes(xintercept=mean(tot.area.burned[[2]])), color="lightblue", linetype="dashed", size=1) +
  geom_density(aes(tot.area.burned[[3]]), fill="lightgreen", alpha=0.4) +
  geom_vline(aes(xintercept=mean(tot.area.burned[[3]])), color="lightgreen", linetype="dashed", size=1) +
  geom_density(aes(tot.area.burned[[4]]), fill ="purple", alpha=0.4) +
  geom_vline(aes(xintercept=mean(tot.area.burned[[4]])),
            color="purple", linetype="dashed", size=1) 

tot.area.burned.list<-unlist(tot.area.burned)
year<-c(rep('2011-2020',n), rep("2021-2040",n), rep("2041-2060",n), rep("2061-2080",n))

area_burned<-cbind(year,as.numeric(tot.area.burned.list))
area_burned$tot.area.burned.list<-as.character(as.character(tot.area.burned.list))

ggplot() +
  #geom_violin(aes(x=year, y=tot.area.burned.list)) +
  geom_boxplot(aes(x=year, y=tot.area.burned.list)) +
  xlab("Year") + ylab("Total area burned (ha)")

years<-c(2020, 2021, 2024, 2029, 2034, 2039, 2044, 2049)
mean_area<-lapply(tot.area.burned, mean)
mean_area<-unlist(mean_area)
mean_escape<-lapply(tot.escapes, mean)

years_burn<-as.data.frame(cbind(years, mean_area))
years_burn2<-years_burn %>% filter(years!=2021)

ggplot(data=years_burn2, aes(x=years, y=mean_area))+
  geom_bar(stat='identity') + 
  geom_smooth(method = "lm")

plot(years[c(1, 3:8)], mean_area[c(1, 3:8)]*16)
abline(years[c(1, 3:8)], mean_area[c(1, 3:8)]*16)

writeRaster(a[[1]], "C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\Sim_run_results\\caribou_2020.tif", overwrite=TRUE)
writeRaster(a[[4]], "C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\Sim_run_results\\caribou_2034.tif")
writeRaster(a[[8]], "C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\rasters\\Sim_run_results\\caribou_2049.tif")
```


