---
title: "ft_nelson_stsm_castor_report"
author: "Tyler Muhly"
date: '2023-02-02'
output: html_document
---

## Introduction
The purpose of this report is to present and compare the outputs from a [Castor forestry and land use simulator model](https://github.com/bcgov/castor) built using the [Spatial Discrete Event Simulation (SpaDES)](https://spades-core.predictiveecology.org/) platform in program R, to the Spatially Explicit
Timber Supply Model (STSM) built using the [SELES](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=14729e8f5430035cead9f38e708f4507c543ff9d).

The Castor and STSM models can be used to simulate forest harvest and estimate timber supply. They are not optimization models, they 


STSM has been used to estimate timber supply in support of timber supply reviews in British Columbia for over 15 years. 





-	Purpose is to compare Casto and STSM spatial timber supply models in a simple framework
-	Why are we comparing to STSM?
o	“Validate” Castor for other non-TSR processes
	i Castor e., increase confidence in forest harvest results
o	Have CLUS as another option in the model toolkit
	i.e., use CLUS for TSR, if of interest
•	Attractive aspects are open source, internally developed, may be more flexible in development


## Model Inputs
a.	Fort Nelson timber supply area
b.	Forest inventory and GandY curves from last determination
c.	Old growth constraints
i.	Landscape units
d.	Min 50 year harvest age
e.	Even-flow harvest
f.	Harvest queue
g.	“blocking” at pixel scale – no spatial blocking
h.	No adjacency constraints


-	Mid-point
o	Forest Estate Model Sample Clauses | Law Insider
o	Aggregation of Age Classes in Timber Resources Scheduling Models: Its Effects and Bias | Forest Science | Oxford Academic (oup.com)
-	5 year increment

[‎2023-‎02-‎01 12:19 PM]  Lochhead, Kyle FLNR:EX:  
they say what is currently out there aka time = 0....use that volume and harvest 10 years worth of timber....then at time period 2, increase the age by 10 years
for us its report the time=0 (no harvesting goes on), then increase the age by the midpoint of the timperiod (5 years) then go find 10 years worth of timber, then in timperiod 2 increase by 10 years....so time period 1 = 5 years, timperiod 2 = 15, as increments , timperiod 3 = 25

‘look-ahead’ in STSM the anaylts can hit flag itn eh model, and the model will look at year 9 in 10 yar time step and determine when initiating whether a span meets min age rewquirements at year 9
-	In tiem step, will satnd achieve min age or volume ,or both target, if yes, then harvest
-	Could affect spatial distribution
-	Most analysts use this fxn

Probability of initiation fo cutblock is driven by a number of parameters, depnign on how coarse/fine the analyst makes; sort cells based on preferences; preference value for cells; random selection; set seed
-	Oldest first; harvest queue


## Model Scenarios

a.	Oldest first 
b.	High volume first
c.	Old growth


## 4.	Model Outputs
a.	Indicators
i.	Annual
1.	Harvest Volume Flow
2.	Growing Stock
3.	Area harvested
4.	Volume/ha harvested
5.	Average age harvested
6.	LRSY
a.	
ii.	Spatial
1.	Harvesting Pattern under the same harvest queue
a.	Map output






