<!--
Copyright 2020 Province of British Columbia
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.-->

---
title: "Database creation for Morice TSA Analyses Version 1.0"
author: "Elizabeth Kleynhans"
date: "10 June 2020"
output: pdf_document
---

# Overview

The dataloaderCLUS preps the database and other objects required to run CLUS. A SQLite database is stored in memory called clusdb. This database can be saved to file using `save_clusdb = TRUE` or an existing clusdb can be used by specifying the path with `useCLUSdb = ".../clusdb.sqlite"`.

Here I set the parameters to create a database for the [Tree Farm Licence 14 (TFL14)](https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/forestry/stewardship/forest-analysis-inventory/tsr-annual-allowable-cut/tree-farm-license/14tfra_2019.pdf). TFL14 covers a total area of 152 000 hectares and is situated between the Purcell Mountains to the west and the Columbia River valley to the east. Several TSA's boarder with it including the Invermere TSA to the south and east, the Golden TSA to the north, and the Kootenay Lake TSA to the west. On April 18, 2019 the allowable annual cut was set at 180 000 cubic metres. 

One caribou herd overlap with TFL14 - Central Selkirks. 


# Usage
Set parameters for creating the database in the code chunk below.

```{r module_usage}
library(SpaDES)
library(SpaDES.core)
library(data.table)
library (keyring)

source(here::here("R/functions/R_Postgres.R"))

Sys.setenv(JAVA_HOME = 'C:\\Program Files\\Java\\jdk-14.0.1') #throws an error if pointing to different version of java (i.e., 32 vs 64 bit)

setPaths(modulePath = here::here("R/SpaDES-modules"))

getPaths() # shows where the 4 relevant paths are 


times <- list(start = 0, end = 0)
parameters <-  list(
  .progress = list(type = NA, interval = NA),
  .globals = list(),
  dataLoaderCLUS = list(dbName='clus',
                         save_clusdb = TRUE,
                         nameBoundaryFile="tsa_aac_bounds",
                         nameBoundaryColumn="tsa_name",
                         nameBoundary = "TFL23", # change this name
                         nameBoundaryGeom='wkb_geometry',
                         nameCompartmentRaster = "rast.tsa_aac_boundary",
                         nameCompartmentTable = "tsa_aac_bounds_vat",
                         nameMaskHarvestLandbaseRaster='rast.bc_thlb2018',
                         nameZoneRasters=c("rast.zone_cond_beo", # rasters of the zone constraints to include. Add all zone rasters that might be needed here. First 7 always stay.
                                           "rast.zone_cond_vqo", 
                                           "rast.zone_cond_wha", 
                                           "rast.zone_cond_uwr", 
                                           "rast.zone_cond_nharv", 
                                           "rast.zone_cond_fsw", 
                                           "rast.zone_cond_cw",
                                           "rast.zone_cond_noharvest_central_selkirks_crithab_or_herd",
                                           "rast.zone_cond_noharvest_columbia_south_crithab_or_herd",
                                           "rast.zone_cond_noharvest_monashee_crithab_or_herd",
                                           "rast.zone_cond_eccc_central_selkirks_crithab_or_herd",
                                           "rast.zone_cond_eccc_columbia_south_crithab_or_herd",
                                           "rast.zone_cond_eccc_monashee_crithab_or_herd"),
                        
                         nameZoneTable="zone_constraints", # table that defines the constraints in the rasters. Its a parent table so other tables inherit it
                         nameYieldsRaster = "rast.ycid_vdyp",# raster of stand id for VDYP ("natural origin") yields
                         nameYieldTable ="yc_vdyp", # VDYP yield  table
                         nameYieldsTransitionRaster = "rast.tipsy2018_id", # raster of stand id for TIPSY ("managed") yields
                         nameYieldTransitionTable ="yc_tipsy", # table that transitions stands onto TIPSY yield curve once they are cut
                         nameForestInventoryRaster ="rast.vri2018_id", # raster of the forest inventory 
                         nameForestInventoryKey = "feature_id", # unique id of each polygon 
                         nameForestInventoryTable = "veg_comp_lyr_r1_poly2018",# the invenotry data
                         nameForestInventoryAge = "proj_age_1",  # name of the age column in the inventory data - provides stand attributes added nameZoneRasts for diff herds and scenarios
                         nameForestInventoryHeight = "proj_height_1",
                         nameForestInventoryCrownClosure = "crown_closure",
                         nameForestInventorySiteIndex = "site_index" # name of the site index column in the inventory data
                    ),
  blockingCLUS = list(blockMethod='pre', 
                      patchZone = 'rast.zone_cond_beo',
                      patchVariation = 6,
                      nameCutblockRaster ="rast.cns_cut_bl",
                      useLandingsArea=FALSE),
  roadCLUS = list(roadMethod = 'pre', 
                  nameCostSurfaceRas = 'rast.rd_cost_surface', 
                  nameRoads =  'rast.crds_all'
                  ),
  rsfCLUS = list(calculateInterval = 1, 
                   criticalHabitatTable = "public.criticalhabitat_bc_vat",
                   randomEffectsTable = "public.rsf_re_coeff",
                   writeRSFRasters = TRUE,
                   checkRasters= FALSE),
  disturbanceCalcCLUS = list(calculateInterval = 1, 
                   criticalHabitatTable = "public.criticalhabitat_bc_vat",
                   criticalHabRaster = "rast.bc_crithab",
                   permDisturbanceRaster = "rast.perm_dist_rds",
                   recovery = 40), # might be 30 or 40 years
  survivalCLUS = list (caribou_herd_density = 0.05, # assign what is appropriate for the herd
                       nameRasCaribouHerd = "rast.bc_crithab", # raster of herd boundaries
                       tableCaribouHerd = "public.criticalhabitat_bc_vat"),
  uploaderCLUS = list(aoiName = 'tfl23',
                        dbInfo  = list(keyring::key_get("vmdbhost", keyring="postgreSQL"), keyring::key_get("vmdbuser", keyring="postgreSQL"), keyring::key_get("vmdbpass", keyring="postgreSQL"),  keyring::key_get("vmdbname", keyring="postgreSQL"))
                        ))


rsf_model_coeff <- data.table(getTableQuery("SELECT * FROM rsf_model_coeff WHERE population = 'DU9' and  species = 'caribou' and season IN ('A')") )
#rsf_model_coeff[, population:= 'Telkwa']

scenario = data.table(name="load_data", 
                      description = "dataloader")

patchSizeDist<- data.table(ndt= c(1,1,1,1,1,1,
                                  2,2,2,2,2,2,
                                  3,3,3,3,3,3,
                                  4,4,4,4,4,4,
                                  5,5,5,5,5,5), 
                           sizeClass = c(40,80,120,160,200,240), 
                           freq = c(0.3,0.3,0.1,0.1,0.1, 0.1,
                                    0.3,0.3,0.1,0.1,0.1, 0.1,
                                    0.2, 0.3, 0.125, 0.125, 0.125, 0.125,
                                    0.1,0.02,0.02,0.02,0.02,0.8,
                                    0.3,0.3,0.1,0.1,0.1, 0.1))
modules <- list("dataLoaderCLUS", "blockingCLUS", "roadCLUS", "rsfCLUS", "survivalCLUS","disturbanceCalcCLUS", "uploaderCLUS")
#modules <- list("dataLoaderCLUS", "roadCLUS")

objects <- list(patchSizeDist=patchSizeDist, rsf_model_coeff=rsf_model_coeff , scenario = scenario)
#objects <- list(patchSizeDist=patchSizeDist, scenario = scenario)

inputs <- list()
outputs <- list()

mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects)


system.time({
mysimout<-spades(mySim)
})

```

# Dependendices

First need an area of interest.
+nameBoundaryFile <- the vector data of the areas to consider. Defaults to caribou herd boundaries.
+nameBoundary<-The specific area of interest
+nameBoundaryColumn<-The column in the nameBoundaryFile that support the query for the area of interest
+nameBoundaryGeom<-the geometry column from which to run the spatial query containing the area of interest

The remaining files are:
+nameCompartmentRaster<- a provincial raster of compartments -- also known as supply blocks. Defaults to 1 compartment
+nameZoneRaster<-a provincial raster of management zones. Defaluts to 1 zone
+nameYieldRaster<-a provincial raster of id's that support a look up to yield tables. Defaults to 1 yield table
+nameAgeRaster<- a provincial raster of age. This can be set to zero, if correctly used to look up yields and constraints. Defaults to an age of 120
+nameCrownClosureRaster<- a provincial raster of crown closure. Used for management constraints. Defaults to 0 crown closure
+nameMaskHarvestLandbaseRaster<- a provincial raster of the timber harvesting landbase (THLB) that delinates area feasible to harvest timber. Defaults to all of the area of interest being eligible for harvesting.

# Events

The module only has an inititialization event for connecting to a database and establishing database objects


## Output data

The outputs contain the database connection object, functions needed to generate queries and the boundary and bounding box of the boundary needed for other queries

# Links to other modules

Links to every module required by CLUS

