<!--
Copyright 2020 Province of British Columbia
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.-->

---
title: "Database creation for Chilcotin Caribou Analysis"
author: "Tyler Muhly"
date: "27 August 2021"
output: pdf_document
---

# Overview

The dataloaderCLUS preps the database and other objects required to run CLUS. A SQLite database is stored in memory called clusdb. This database can be saved to file using `save_clusdb = TRUE` or an existing clusdb can be used by specifying the path with `useCLUSdb = ".../clusdb.sqlite"`.

Here I set the parameters to create a database for the [Quesnel timber supply area (TSA)](https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/timber-supply-review-and-allowable-annual-cut/allowable-annual-cut-timber-supply-areas/quesnel-tsa). The TSA is located in the Cariboo Natural Resource Region between the Coastal Mountain on the west and Cariboo Mountain on the east in the Fraser Basin and Interior Plateau. The Quesnel TSA encompasses approximately 1.28 million hectares of land. On June 16, 2017 the allowable annual cut was set at 2,607,000 cubic metres.

Several herds overlap with the Quesnel TSA - Barkerville, Itcha_Ilgachuz, Narrow Lake, North Cariboo, Tweedsmuir, and Wells Gray North. 


# Usage
Set parameters for creating the database in the code chunk below.

```{r module_usage}
library(SpaDES)
library(SpaDES.core)
library(data.table)
library (keyring)

source(here::here("R/functions/R_Postgres.R"))

Sys.setenv(JAVA_HOME = 'C:\\Program Files\\Java\\jdk-14.0.1') #throws an error if pointing to different version of java (i.e., 32 vs 64 bit)

setPaths(modulePath = here::here("R/SpaDES-modules"))

getPaths() # shows where the 4 relevant paths are 


times <- list(start = 0, end = 60) # 60
parameters <-  list(
  .progress = list(type = NA, interval = NA),
  .globals = list(),
  dataLoaderCLUS = list(dbName='clus',
                         save_clusdb = TRUE,
                         sqlite_dbname = "chilcotin_study_area", # chilcotin_study_area
                         nameBoundaryFile ="chilcotin_area_of_interest_habitat_v3", # study_area_chilcotin; chilcotin_area_of_interest_habitat
                         nameBoundaryColumn = "tsa_name", # tsa_name
                         nameBoundary = c ('Matrix', 'HEWSR', 'LESR', 'LEWR', 'out'), # c ('Quesnel_TSA_Matrix', 'Quesnel_TSA_HEWSR', 'Quesnel_TSA_LESR', 'Quesnel_TSA_LEWR', 'Quesnel_TSA_out', 'Williams_Lake_TSA_HEWSR', 'Williams_Lake_TSA_LESR', 'Williams_Lake_TSA_LEWR', 'Williams_Lake_TSA_Matrix', Williams_Lake_TSA_out')  
                        # c ('Matrix', 'HEWSR', 'LESR', 'LEWR', 'out')
                         nameBoundaryGeom = 'wkb_geometry',
                         nameCompartmentRaster = "rast.chilcotin_aoi_v3", #rast.study_area_chilcotin
                         nameCompartmentTable = "vat.chilcotin_aoi_v3",
                         nameMaskHarvestLandbaseRaster ='rast.thlb_2020_chilcotin', 
                         nameZoneRasters=c("rast.zone_cond_beo", 
                                           "rast.zone_cond_vqo", 
                                           "rast.zone_wha_2021", 
                                           "rast.zone_uwr_2021",  
                                           "rast.zone_cond_nharv", 
                                           "rast.zone_cond_fsw", 
                                           "rast.zone_cond_cw",
                                           
                                           #"rast.zone_cond_noharvest_barkerville_crithab_or_herd",
                                           "rast.zone_cond_noharvest_charlotte_alplands_crithab_or_herd",
                                           "rast.zone_cond_noharvest_itcha_ilgachuz_crithab_or_herd",
                                           #"rast.zone_cond_noharvest_narrow_lake_crithab_or_herd",
                                           #"rast.zone_cond_noharvest_north_cariboo_crithab_or_herd",
                                           "rast.zone_cond_noharvest_rainbows_crithab_or_herd",
                                           "rast.zone_cond_noharvest_tweedsmuir_crithab_or_herd",
                                           #"rast.zone_cond_noharvest_wells_gray_north_crithab_or_herd",
                                           
                                           #"rast.zone_cond_eccc_barkerville_crithab_or_herd",
                                           "rast.zone_cond_eccc_charlotte_alplands_crithab_or_herd",
                                           "rast.zone_cond_eccc_itcha_ilgachuz_crithab_or_herd",
                                           #"rast.zone_cond_eccc_narrow_lake_crithab_or_herd",
                                           #"rast.zone_cond_eccc_north_cariboo_crithab_or_herd",
                                           "rast.zone_cond_eccc_rainbows_crithab_or_herd",
                                           "rast.zone_cond_eccc_tweedsmuir_crithab_or_herd",
                                           #"rast.zone_cond_eccc_wells_gray_north_crithab_or_herd",
                                           
                                           #"rast.zone_cond_bc_barkerville_crithab",
                                           "rast.zone_cond_bc_charlotte_alplands_crithab",
                                           "rast.zone_cond_bc_itcha_ilgachuz_crithab",
                                           #"rast.zone_cond_bc_narrow_lake_crithab",
                                           #"rast.zone_cond_bc_north_cariboo_crithab",
                                           "rast.zone_cond_bc_rainbows_crithab",
                                           "rast.zone_cond_bc_tweedsmuir_crithab",
                                           #"rast.zone_cond_bc_wells_gray_north_crithab", 

                                           #"rast.zone_barkerville_groundhog_zones_20210303",
                                           #"rast.zone_smc_zones_20210315",
                                           
                                           "rast.zone_chilcotin_scenario2",
                                           "rast.zone_chilcotin_proposed_wha"
                                            ),
                        
                         nameZoneTable="zone.constraints", 
                        # nameZonePriorityRaster = "rast.zone_cond_beo",
                         nameZonePriorityRaster="rast.zone_cond_beo",
                         nameYieldsRaster = "rast.ycid_vdyp",
                         nameYieldTable ="yc_vdyp", # VDYP yield  table
                         nameYieldsTransitionRaster = "rast.tipsy2018_id", 
                         nameYieldTransitionTable ="yc_tipsy", 
                         nameForestInventoryRaster ="rast.vri2019_id", 
                         nameForestInventoryKey = "feature_id", # unique id of each polygon 
                         nameForestInventoryTable = "veg_comp_lyr_r1_poly2019",
                         nameForestInventoryAge = "proj_age_1",  
                         nameForestInventoryHeight = "proj_height_1",
                         nameForestInventoryCrownClosure = "crown_closure",
                         nameForestInventoryTreed = "bclcs_level_2",
                         nameForestInventorySiteIndex = "site_index" 
                    ),
  blockingCLUS = list(blockMethod='pre', 
                      patchZone = 'rast.zone_cond_beo',
                      patchVariation = 6,
                      nameCutblockRaster ="rast.cns_cut_bl",
                      useLandingsArea=FALSE),
  roadCLUS = list(roadMethod = 'pre', 
                  nameCostSurfaceRas = 'rast.rd_cost_surface', 
                  nameRoads =  'rast.rds_cariboo_2022' # updated roads data; previously used: rast.ce_road_2019
                  ),
  cutblockSeqPrepCLUS = list(startHarvestYear = 1960,
                             nameCutblockRaster= 'rast.cns_cut_bl', 
                             nameCutblockTable= 'cns_cut_bl_polygon', 
                             queryCutblocks = 'cutseq_centroid',
                             resetAge = TRUE
                              ),

  disturbanceCalcCLUS = list(calculateInterval = 100, 
                             criticalHabitatTable = "vat.vat_bc_crithab_and_herd",
                             criticalHabRaster = "rast.bc_crithab_and_herd",
                             permDisturbanceRaster = "rast.perm_dist_no_rds",
                             recovery = 30), 

  survivalCLUS = list (calculateInterval = 100,
                       caribou_herd_density = 0.05, # assign what is appropriate for the herd
                       nameRasCaribouHerd = "rast.caribou_herd", # raster of herd boundaries
                       tableCaribouHerd = "vat.caribou_herd_vat"),
  smcaribouAbundanceCLUS = list (calculateInterval = 100,
                                 nameRasSMCHerd = "rast.smc_herd_habitat", 
                                 tableSMCCoeffs = "vat.smc_coeffs"),
  uploaderCLUS = list(aoiName = 'chilcotin_caribou_plan',
                        dbInfo  = list(keyring::key_get("vmdbhost", keyring="postgreSQL"), 
                                       keyring::key_get("vmdbuser", keyring="postgreSQL"), 
                                       keyring::key_get("vmdbpass", keyring="postgreSQL"), 
                                       keyring::key_get("vmdbname", keyring="postgreSQL"))
                        ))

scenario = data.table(name="load_data", 
                      description = "dataloader")

patchSizeDist<- data.table(ndt= c(1,1,1,1,1,1,
                                  2,2,2,2,2,2,
                                  3,3,3,3,3,3,
                                  4,4,4,4,4,4,
                                  5,5,5,5,5,5), 
                           sizeClass = c(40,80,120,160,200,240), 
                           freq = c(0.3,0.3,0.1,0.1,0.1, 0.1,
                                    0.3,0.3,0.1,0.1,0.1, 0.1,
                                    0.2, 0.3, 0.125, 0.125, 0.125, 0.125,
                                    0.1,0.02,0.02,0.02,0.02,0.8,
                                    0.3,0.3,0.1,0.1,0.1, 0.1))

modules <- list("dataLoaderCLUS", 
                "blockingCLUS", 
                "roadCLUS",  
                #"survivalCLUS",
                #"disturbanceCalcCLUS",
                #"smcaribouAbundanceCLUS",
                #"uploaderCLUS",
                "cutblockSeqPrepCLUS")

objects <- list(patchSizeDist = patchSizeDist, 
                scenario = scenario)

inputs <- list()
outputs <- list()

mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects)


system.time({
mysimout<-spades(mySim)
})

```

# Dependendices

First need an area of interest.
+nameBoundaryFile <- the vector data of the areas to consider. Defaults to caribou herd boundaries.
+nameBoundary<-The specific area of interest
+nameBoundaryColumn<-The column in the nameBoundaryFile that support the query for the area of interest
+nameBoundaryGeom<-the geometry column from which to run the spatial query containing the area of interest

The remaining files are:
+nameCompartmentRaster<- a provincial raster of compartments -- also known as supply blocks. Defaults to 1 compartment
+nameZoneRaster<-a provincial raster of management zones. Defaluts to 1 zone
+nameYieldRaster<-a provincial raster of id's that support a look up to yield tables. Defaults to 1 yield table
+nameAgeRaster<- a provincial raster of age. This can be set to zero, if correctly used to look up yields and constraints. Defaults to an age of 120
+nameCrownClosureRaster<- a provincial raster of crown closure. Used for management constraints. Defaults to 0 crown closure
+nameMaskHarvestLandbaseRaster<- a provincial raster of the timber harvesting landbase (THLB) that delinates area feasible to harvest timber. Defaults to all of the area of interest being eligible for harvesting.

# Events

The module only has an inititialization event for connecting to a database and establishing database objects


## Output data

The outputs contain the database connection object, functions needed to generate queries and the boundary and bounding box of the boundary needed for other queries

# Links to other modules

Links to every module required by CLUS

