<!--
Copyright 2020 Province of British Columbia
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.-->

---
title: "Database creation for Fort St. John TSA Analyses Version 1.0"
author: "Kyle Lochhead"
date: "23 June 2020"
output: pdf_document
---

# Overview

The dataloaderCLUS preps the database and other objects required to run CLUS. A SQLite database is stored in memory called clusdb. This database can be saved to file using `save_clusdb = TRUE` or an existing clusdb can be used by specifying the path with `useCLUSdb = ".../clusdb.sqlite"`.

Here I set the parameters to create a database for the [Fort St. John timber supply area (TSA)](https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/timber-supply-review-and-allowable-annual-cut/allowable-annual-cut-timber-supply-areas/fort-st-john-tsa). The TSA is in northeastern British Columbia and is 4.6 million ha in size. The allowable annual cut (AAC) is 2,115,000 cubic metres, as of May 10, 2018. The TSA is partitioned with 1,200,000 cubic metres attributable to coniferous-leading stands of which at 672,000 cubic metres annually may be taken from the 'core' area. Deciduous species may be harvested up to 915,000 cubic metres, of which 512,000 cubic metres  may be taken from the 'core'. TSA overlaps with the Graham, Pink Mountain caribou herd in DU7, and several boreal (DU6) herds, including Westside Fort Nelson, Chinchaga, Snake-Sahtaneh. 

# Usage
Set parameters for creating the database in the code chunk below. 
```{r module_usage}
library(SpaDES)
library(SpaDES.core)
library(data.table)
library (keyring)

source(here::here("R/functions/R_Postgres.R"))

Sys.setenv(JAVA_HOME='C:\\Program Files\\Java\\jdk-14.0.1')
#Sys.setenv(JAVA_HOME = 'C:\\Program Files (x86)\\Java\\jre1.8.0_241') #throws an error if pointing to different version of java (i.e., 32 vs 64 bit)

setPaths(modulePath = here::here("R/SpaDES-modules"))

getPaths() # shows where the 4 relevant paths are

times <- list(start = 0, end = 0)
parameters <-  list(
  .progress = list(type = NA, interval = NA),
  .globals = list(),
  dataLoaderCLUS = list (dbName = 'clus', # name of the postgres database
                         save_clusdb = TRUE,
                         nameBoundaryFile = "tsa_aac_bounds", # name of the (TSA) boundary data in postgres
                         nameBoundaryColumn = "tsa_name", 
                         nameBoundary = "Fort_St_John_Core_TSA", # "Fort_St_John_Core_TSA"  Fort_St_John_TSA
                         nameBoundaryGeom = 'wkb_geometry', # geometry column name in the boundary file
                         nameCompartmentRaster = "rast.tsa_aac_boundary", 
                         nameCompartmentTable = "tsa_aac_bounds_vat", # boundary (TSA) names corresponding to raster id's
                         nameMaskHarvestLandbaseRaster = 'rast.bc_thlb2018', # THLB raster in postgres
                         nameZoneRasters = c("rast.zone_cond_beo", # rasters of the zone constraints to include
                                             "rast.zone_cond_vqo", 
                                             "rast.zone_cond_wha", 
                                             "rast.zone_cond_uwr",
                                             "rast.zone_cond_fsw", 
                                             "rast.zone_cond_nharv", # includes parks and no harvest OGMAs
                                             "rast.zone_cond_cw", 
                                             
                                             "rast.zone_cond_noharvest_graham_crithab_or_herd",  
                                             "rast.zone_cond_noharvest_pink_mountain_crithab_or_herd",
                                             "rast.zone_cond_noharvest_chinchaga_crithab_or_herd",
                                             "rast.zone_cond_noharvest_snake_sahtaneh_crithab_or_herd",
                                             "rast.zone_cond_noharvest_westside_fort_nelson_crithab_or_herd",
                                            
                                             "rast.zone_cond_eccc_graham_crithab_or_herd",                                                                             "rast.zone_cond_eccc_chinchaga_crithab_or_herd",
                                             "rast.zone_cond_eccc_pink_mountain_crithab_or_herd",
                                             "rast.zone_cond_eccc_snake_sahtaneh_crithab_or_herd",
                                             "rast.zone_cond_eccc_westside_fort_nelson_crithab_or_herd",
                                             
                                             "rast.zone_cond_bc_graham_crithab",
                                             
                                             "rast.zone_du7_scenario_20210330",
                                             
                                             "rast.pink_mtn_habitat",
                                             "rast.fn_aoi_fsj_tsa",
                                             "rast.graham_caribou_core_habitat",
                                             "rast.old_growth_fsj_tsa",
                                             "rast.brfn_areas_fsj",
                                             "rast.boreal_caribou_zone_2019",
                                             "rast.oldgrwth_def_rec63a",
                                             "rast.oldgrwth_def_rec63c",
                                             "rast.oldgrwth_def_rec63e",
                                             "rast.boreal_caribou_old",
                                             "rast.graham_caribou_old",
                                             "rast.pink_mtn_caribou_old",
                                             "rast.fn_aoi_caribou"
                                           ), 
                         nameZoneTable = "zone.constraints", 
                         nameYieldsRaster = "rast.ycid_vdyp", 
                         nameYieldTable = "yc_vdyp", 
                         nameYieldsTransitionRaster = "rast.tipsy2018_id", 
                         nameYieldTransitionTable = "yc_tipsy", 
                         nameForestInventoryRaster = "rast.vri2019_id",  
                         nameForestInventoryKey = "feature_id", 
                         nameForestInventoryTable = "veg_comp_lyr_r1_poly2019", 
                         nameForestInventoryAge = "proj_age_1", 
                         nameForestInventoryHeight = "proj_height_1", 
                         nameForestInventoryCrownClosure = "crown_closure",
                         nameForestInventoryTreed = "bclcs_level_2",
                         nameForestInventorySiteIndex = "site_index" 
                    ),
  blockingCLUS = list(blockMethod = 'pre', #
                      patchZone = 'rast.zone_cond_beo', 
                      patchVariation = 6,
                      nameCutblockRaster ="rast.cns_cut_bl", 
                      useLandingsArea = FALSE),
  roadCLUS = list(roadMethod = 'pre', 
                  nameCostSurfaceRas = 'rast.rd_cost_surface', 
                  nameRoads =  'rast.crds_all'# existing road network
                  ),
  # rsfCLUS = list (calculateInterval = 10, # at what time interval to calculate RSF
  #                 criticalHabitatTable = "public.vat_bc_crithab_and_herd",
  #                 randomEffectsTable = "public.rsf_re_coeff",
  #                 writeRSFRasters = TRUE,
  #                 checkRasters = FALSE),
  survivalCLUS = list (caribou_herd_density = 0.05, # assign what is appropriate for the herd
                       nameRasCaribouHerd = "rast.caribou_herd", # raster of herd boundaries
                       tableCaribouHerd = "public.caribou_herd_vat"),
  uploaderCLUS = list(aoiName = 'fort_st_john_tsa',
                      dbInfo  = list(keyring::key_get("vmdbhost", keyring="postgreSQL"), 
                                     keyring::key_get("vmdbuser", keyring="postgreSQL"), 
                                     keyring::key_get("vmdbpass", keyring="postgreSQL"),  
                                     keyring::key_get("vmdbname", keyring="postgreSQL"))),
  yieldUncertaintyCLUS = list (elevationRaster = 'rast.dem'), # elevation parameter needed to estimate uncertainty
  disturbanceCalcCLUS = list(calculateInterval = 5, # at what time interval to calculate disturbance
                             criticalHabitatTable = "public.vat_bc_crithab_and_herd",
                             criticalHabRaster = "rast.bc_crithab_and_herd",
                             permDisturbanceRaster = "rast.perm_dist_rds", # permanently disturbed features (never recover)
                             recovery = 40) # time for roads and cutblocks to 'recover' from disturbance
  )

# rsf_model_coeff <- data.table (getTableQuery ("SELECT * FROM rsf_model_coeff WHERE population = 'DU8' and  species = 'caribou' and season IN ('A')")) # use annual caribou RSF model coefficients for DU7
#rsf_model_coeff[, population := 'Tweedsmuir'] 

scenario = data.table(name="load_data_fsj_core", # load_data_fsj_nocore  load_data_fsj_core
                      description = "dataloader")

patchSizeDist<- data.table(ndt= c(1,1,1,1,1,1,
                                  2,2,2,2,2,2,
                                  3,3,3,3,3,3,
                                  4,4,4,4,4,4,
                                  5,5,5,5,5,5), 
                           sizeClass = c(40,80,120,160,200,240), 
                           freq = c(0.3,0.3,0.1,0.1,0.1, 0.1,
                                    0.3,0.3,0.1,0.1,0.1, 0.1,
                                    0.2, 0.3, 0.125, 0.125, 0.125, 0.125,
                                    0.1,0.02,0.02,0.02,0.02,0.8,
                                    0.3,0.3,0.1,0.1,0.1, 0.1))
modules <- list("dataLoaderCLUS", 
                "blockingCLUS",
                "roadCLUS",
                #"rsfCLUS",
                "survivalCLUS", 
                "uploaderCLUS", 
                "disturbanceCalcCLUS")

#objects <- list(patchSizeDist=patchSizeDist, rsf_model_coeff=rsf_model_coeff , scenario = scenario)
objects <- list(patchSizeDist = patchSizeDist,
                #rsf_model_coeff = rsf_model_coeff,
                scenario = scenario 
                )

inputs <- list()
outputs <- list()

mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects)

system.time({
mysimout<-spades(mySim)
})
```

# Dependendices

First need an area of interest.
+nameBoundaryFile <- the vector data of the areas to consider. Defaults to caribou herd boundaries.
+nameBoundary<-The specific area of interest
+nameBoundaryColumn<-The column in the nameBoundaryFile that support the query for the area of interest
+nameBoundaryGeom<-the geometry column from which to run the spatial query containing the area of interest

The remaining files are:
+nameCompartmentRaster<- a provincial raster of compartments -- also known as supply blocks. Defaults to 1 compartment
+nameZoneRaster<-a provincial raster of management zones. Defaluts to 1 zone
+nameYieldRaster<-a provincial raster of id's that support a look up to yield tables. Defaults to 1 yield table
+nameAgeRaster<- a provincial raster of age. This can be set to zero, if correctly used to look up yields and constraints. Defaults to an age of 120
+nameCrownClosureRaster<- a provincial raster of crown closure. Used for management constraints. Defaults to 0 crown closure
+nameMaskHarvestLandbaseRaster<- a provincial raster of the timber harvesting landbase (THLB) that delinates area feasible to harvest timber. Defaults to all of the area of interest being eligible for harvesting.

# Events

The module only has an inititialization event for connecting to a database and establishing database objects


## Output data

The outputs contain the database connection object, functions needed to generate queries and the boundary and bounding box of the boundary needed for other queries

# Links to other modules

Links to every module required by CLUS

