---
title: "survivalCASTOR"
author: "Tyler Muhly"
date: "20 August 2019"
output: pdf_document
---

# Overview
This module estimates the survival rate of adult female caribou in herd ranges as a function of the amount of early seral (i.e., 1 to 40 year old) forest in the range. The survival rate model comes from the reasearch done by [Wittmer et al. (2007)](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.1365-2656.2007.01220.x) (see details in '/R/caribou_habitat/25_Wittmer_caribou_model') on southern mountain caribou (Designatable Unit 9). Specifically, we apply the population-scale model that Wittmer et al. (2007) developed. 

The module requires input on forest age (output from the Castor forestry modules) and density of caribou herds. Currently, the caribou herd density parameter is static and must be set by the user. A caribou herd raster was derived from the provincial caribou herd boundary data set (see details in "/R/Params/caribou_herd_raster.rmd").

We caution against using the model outside of the southern mountain caribou population range, as it was developed using data only from that population, and thus may not be applicable to other parts of BC. 

# Usage

```{r module_usage}
library (SpaDES.core)
library (data.table)
library (here)
library (dplyr)
source (paste0 (here(),"/R/functions/R_Postgres.R"))

moduleDir <- file.path (paste0 (here(),"/R/SpaDES-modules"))
inputDir <- file.path (paste0 (here(), "/R")) %>% reproducible::checkPath (create = TRUE)
outputDir <- file.path (paste0 (here(), "/R/SpaDES-modules/survivalCASTOR/outputs"))
cacheDir <- file.path (paste0 (here(), "/R"))
times <- list (start = 0, end = 1)

parameters <- list (
  .progress = list (type = NA, interval = NA),
  .globals = list (),
  dataCASTOR = list (useCastorDB = "C:\\Work\\caribou\\clus_data\\clusdb.sqlite", # instantiated dbase
                         dbName = 'castor', # Database connection
                         saveCastorDB = FALSE, # don't save the dbase
                         # Study Area params below; make sure they are consistent with other modules
                         nameBoundaryFile = "study_area_compart",
                         nameBoundaryColumn = "tsb_number",
                         nameBoundary = c ("26A", "29B", "29C"), # DU7 
                         nameBoundaryGeom ='wkb_geometry',
                         nameCompartmentRaster = "rast.forest_tenure",
                         nameCompartmentTable = "forest_tenure_vat",
                         nameMaskHarvestLandbaseRaster = 'rast.bc_thlb2018',
                         nameZoneRasters = c ("rast.zone_cond_beo", "rast.zone_cond_vqo",  "rast.zone_cond_uwr", "rast.zone_cond_fsw", "rast.zone_cond_nharv"),
                         nameZoneTable = "zone_constraints",
                         nameAgeRaster = "rast.vri2017_projage1",
                         nameHeightRaster = "rast.vri2017_projheight1",
                         nameCrownClosureRaster = "rast.vri2017_crownclosure",
                         nameYieldTable = "yield_ex"),
  survivalCASTOR = list (caribou_herd_density = 0.05, # assign what is appropriate for the herd
                       nameRasCaribouHerd = "rast.caribou_herd", # raster of herd boundaries
                       tableCaribouHerd = "public.caribou_herd") # look-up table of herd names
)

modules <- list ("dataCASTOR", "survivalCASTOR")
objects <- list ()
paths <- list (
  cachePath = cacheDir,
  modulePath = moduleDir,
  inputPath = inputDir,
  outputPath = outputDir
)

mySim <- simInit (times = times, params = parameters, modules = modules,
                  objects = objects, paths = paths)
outputs (mySim) <- data.frame (objectName = c ("tableSurvivalReport")) # Consists of survival rate estimates for each herd in the study area at each time step. Gets saved in the 'outputs' folder of the module. 
system.time({
mysimout <- spades (mySim)
})
```

# Events
This module is pretty simple; there are two event types: 'init' and 'calculateSurvival' . The 'init' event identifies herds in the sim study area, calculates the survival rate in each of those herds at time 0 and saves the survival rate estimates as a data.table in the sim. The 'calculateSurvival' event calculates the survival rate in each herd at each scehduled time interval. 

# Data dependencies
## Input data
This module needs the 'age' field (i.e., age of forest) from the 'pixels' table in the sim RSQLite databases (castordb) that gets instantiated at the start of the sim in the dataCASTOR It also requires a density estimate (caribou/km^2^) that is currently set by the user and remains static throughout the scenario run.

## Output data
This module outputs a table that has the herd name identifer, proportion of forest area that is 1 to 40 years old in the herd area and the estimated survival rate of the herd at each time interval of the sim.

There was a request to summarize area of mature (prop_mature) and old forest (prtop_old) in caribou ranges, so these indicators were added to this module Dec. 2019. They are not needed to calcualte survival. Mature was defined as 80 to 120 years old and greater than 120 years old, respectively, but these can be modified as needed.  

# Links to other modules
The module will only work if the dataCASTOR castordb is instantiated as part of the Castor model. Otherwise you won't have the age data needed to make the survival rate calculation. 

# Future Improvements
A linkage to a caribou population model so that desnity estimates can be calculated dynamically as a function of changing adult female survival rates estimated here. 
