```{r, run cocela}

library(rJava) #Calling the rJava library instantiates the JVM. Note: cannot instantiate the same JVM on both the cores and the master. 
library(DBI)
library(raster)
#library(jdx)

Sys.setenv(JAVA_HOME = 'C:\\Program Files\\Java\\jdk-23.0.1') 
.jinit(classpath= paste0(here::here(),"/Java/castor/bin"), parameters="-Xmx2g", force.init = TRUE) #instantiate the JVM
.jaddClassPath(paste0(here::here(), "/Java/castor/sqlite-jdbc-3.41.2.1.jar"))
jgc <- function() .jcall("java/lang/System", method = "gc")

cocelaClass<-.jnew("castor.CellularAutomata")
cocelaClass$setRParms(
  as.character(paste0(here::here(),"/R/scenarios/boundary_fire/boundary_fire_r2_castordb.sqlite")), # db_location
  as.integer(210000), #harvMin
  as.integer(309000), #harvMaxm
  .jfloat(0.85), #growstockPercentage 
  as.integer(110), # ageThres
  as.integer(60), # planHorizon
  as.integer(5), # planLength
  .jfloat(150.0),# minHarvestVolume 
  .jfloat(0.2), # ageClusterWeight
  .jfloat(0.75) # harvestCluster Weight
)
cocelaClass$getCastorData()
cocelaClass$coEvolutionaryCellularAutomata()
jgc()
rm(cocelaClass)
gc()

test<-function(){
userdb <- dbConnect(RSQLite::SQLite(), dbname = paste0(here::here(), "/R/scenarios/boundary_fire/boundary_fire_r2_castordb.sqlite") ) 
ras.info<-dbGetQuery(userdb, "Select * from raster_info limit 1;")
ras<-raster(extent(ras.info$xmin, ras.info$xmax, ras.info$ymin, ras.info$ymax), nrow = ras.info$nrow, ncol = ras.info$ncell/ras.info$nrow, vals =0, crs = 3005)
ca<-dbGetQuery(userdb, "select * from ca_result_age order by pixelid;")
dbDisconnect(userdb)

ras[]<-ca$t10
plot(ras)
title("year:50")
ras[]<-ca$t9
plot(ras)
title("year:45")
ras[]<-ca$t8
plot(ras)
title("year:40")
ras[]<-ca$t7
plot(ras)
title("year:35")
ras[]<-ca$t6
plot(ras)
title("year:30")
ras[]<-ca$t5
plot(ras)
title("year:25")
ras[]<-ca$t4
plot(ras)
title("year:20")
ras[]<-ca$t3
plot(ras)
title("year:15")
ras[]<-ca$t2
plot(ras)
title("year:10")
ras[]<-ca$t1
plot(ras)
title("year:5")
}
test()

```

#set priority from cocela
```{r, set_pri}
userdb <- dbConnect(RSQLite::SQLite(), dbname = paste0(here::here(),"/R/SpaDES-modules/disturbanceCastor/test_castordb.sqlite") ) 
test<-dbGetQuery(userdb, "select pixelid, case when t1 = 0 then 1 
when t2 = 0 then 2 when t3 = 0 then 3 when t4 = 0 then 4 when t5 = 0 then 5 when t6 = 0 then 6 when t7 = 0 then 7 when t8 = 0 then 8 when t9 = 0 then 9 when t10 = 0 then 10 else 11 end priority
                 from ca_result_age order by pixelid;")
sql <- paste0("UPDATE pixels SET priority = :priority where pixelid = :pixelid")
        dbBegin(userdb)
        rs<-dbSendQuery(userdb, sql, test)
        dbClearResult(rs)
        dbCommit(userdb)
sql <- paste0("UPDATE blocks SET priority = :priority where blockid = :pixelid")
        dbBegin(userdb)
        rs<-dbSendQuery(userdb, sql, test)
        dbClearResult(rs)
        dbCommit(userdb)
dbDisconnect(userdb)

userdb <- dbConnect(RSQLite::SQLite(), dbname = paste0(here::here(), "/R/SpaDES-modules/disturbanceCastor/test_castordb.sqlite") ) 
ras.info<-dbGetQuery(userdb, "Select * from raster_info limit 1;")
ras<-raster(extent(ras.info$xmin, ras.info$xmax, ras.info$ymin, ras.info$ymax), nrow = ras.info$nrow, ncol = ras.info$ncell/ras.info$nrow, vals =0, crs = 3005)
ras[]<-dbGetQuery(userdb, "select priority from pixels order by pixelid;")$priority
plot(ras)
dbDisconnect(userdb)


```

#simulate harvesting and fire
```{r module_usage}
library(SpaDES.core)
library(SpaDES.experiment)
library(data.table)
library(dplyr)
source(here::here("R/functions/R_Postgres.R"))

moduleDir <- file.path(paste0(here::here(), "/R/SpaDES-modules"))
outputDir <- file.path(paste0(here::here(), "/R/scenarios/test_cocela/outputs"))


times <- list(start = 0, end = 10)
parameters <- list(
  .progress = list(type = NA, interval = NA),
  .globals = list(),
  dataCastor = list(saveCastorDB = FALSE,
                   useCastorDB = paste0(here::here(),"/R/SpaDES-modules/disturbanceCastor/test_castordb.sqlite")
  ),
  growingStockCastor = list(periodLength = 5),
  blockingCastor = list(blockMethod='none', 
                        patchZone = 'default',
                        patchVariation = 6),
  forestryCastor = list( activeZoneConstraint = 'default', 
                         harvestBlockPriority = " priority ASC, age DESC", 
                         adjacencyConstraint = TRUE),
  roadCastor = list (roadMethod = 'mst'
  ),
  disturbanceCastor = list (calculateInterval =  1, 
                            recovery = 300)
)

modules <- list("dataCastor", "growingStockCastor", "blockingCastor", "forestryCastor","roadCastor", "disturbanceCastor")

scenario = data.table(name="test", description = "test")
harvestFlow<- data.table(compartment ="all",
                         partition = ' (vol >= 150) ',
                         period = rep(seq(from = 1, to=10, by = 1),1), 
                         flow = 210000,
                         partition_type = 'live')

disturbanceFlow<- data.table(compartment ="all",
                             partition = ' treed = 1 ',
                             mean = log(35),
                             sd = 1,
                             period = rep(seq(from = 1, to=500, by = 1),1), 
                             flow = 500)
objects <- list(harvestFlow = harvestFlow, disturbanceFlow=disturbanceFlow, scenario = scenario)

paths <- list(
  modulePath = moduleDir,
  outputPath = outputDir)

mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects, paths = paths)
outputs(mySim) <- data.frame (objectName = c("harvestReport", "growingStockReport"))
#mysimout<-spades(mySim, debug = T)
mysimouts <- experiment(mySim, replicates = 100, .plotInitialTime = NA) # no plotting
```

# plot disturbance
```{r dist_plots}
userdb <- dbConnect(RSQLite::SQLite(), dbname = paste0(here::here(), "/R/SpaDES-modules/disturbanceCastor/test_castordb.sqlite") ) 
ras.info<-dbGetQuery(userdb, "Select * from raster_info limit 1;")
ras<-raster(extent(ras.info$xmin, ras.info$xmax, ras.info$ymin, ras.info$ymax), nrow = ras.info$nrow, ncol = ras.info$ncell/ras.info$nrow, vals =0, crs = 3005)

ras[]<-dbGetQuery(userdb, "select age from pixels order by pixelid;")$age
plot(ras)
dbDisconnect(userdb)

terra::plot(rast(paste0(here::here(), "/test_test_harvestBlocks.tif")))
terra::plot(rast(paste0(here::here(), "/test_test_mst_status_50.tif")))

```
