---
title: "Buffer AOI Boundaries"
output: html_document
---

Here i createa buffer of 50km around the Boundary TSA. This is because fires could start outside our area of interest and then burn into the TSA so we need this buffer. This file creates a shape file, a raster and a lookup table. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("R/functions/R_Postgres.R"))
library(data.table)
library(sf)
library(tidyverse)
layeraoi<-getSpatialQuery("SELECT * FROM study_area_compart limit 1")
#Create a provincial raster
prov.rast <- raster::raster(
  nrows = 15744, ncols = 17216, xmn = 159587.5, xmx = 1881187.5, ymn = 173787.5, ymx = 1748187.5, 
  crs = st_crs(layeraoi)$proj4string, resolution = c(100, 100), vals = 0)
```

 
```{r Boundary TSA}

#boundary.tsa <- st_make_valid (getSpatialQuery ("SELECT tsa_number, tsnmbrdscr, wkb_geometry FROM public.fadm_tsa_polygon WHERE tsnmbrdscr IN ('Boundary TSA', 'Arrow TSA', 'Cascadia TSA', 'Cranbrook TSA', 'Fraser TSA', 'Golden TSA', 'Invermere TSA', 'Kamloops TSA', 'Kootenay Lake TSA', 'Lillooet TSA', 'Merritt TSA', 'Okanagan TSA', 'Revelstoke TSA');"))

boundary.tsa <- st_make_valid (getSpatialQuery ("SELECT tsa_number, tsnmbrdscr, wkb_geometry FROM public.fadm_tsa_polygon WHERE tsnmbrdscr IN ('Boundary TSA');"))

boundary.tsa<-boundary.tsa %>% group_by ( tsa_number) %>% summarise()
st_crs(boundary.tsa)
plot(boundary.tsa["tsa_number"]) 

boundary.buffer<-st_buffer(boundary.tsa, dist = 50000)
#check it looks ok
ggplot() + geom_sf(data = boundary.buffer) + geom_sf(data = boundary.tsa)

#clip out locations below the boarder of BC

bc_bound<-st_make_valid(getSpatialQuery(("SELECT wkb_geometry FROM public.fadm_tsa_polygon")))
prov.bnd.bc<-sf::st_as_sf(bc_bound) %>% st_combine() %>% st_sf() #flatten layer
boundary_buf_clipped<-sf::st_intersection(boundary.buffer,st_buffer(prov.bnd.bc,0))
#check it looks ok
ggplot() + geom_sf(data = boundary_buf_clipped) + geom_sf(data = boundary.tsa)
boundary_buf_clipped<-boundary_buf_clipped %>% group_by ( tsa_number) %>% summarise()
boundary_buf_clipped$tsa_number<-as.integer(boundary_buf_clipped$tsa_number)
boundary_buf_clipped$tsa_name<-"Boundary TSA"

# save shapefile in postgres
conn <- DBI::dbConnect(dbDriver("PostgreSQL"), host = keyring::key_get ('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get ('dbname', keyring = 'postgreSQL'), port ='5432' ,user = keyring::key_get ('dbuser', keyring = 'postgreSQL'), password = keyring::key_get('dbpass', keyring = 'postgreSQL'))

st_write (obj = boundary_buf_clipped, 
          dsn = conn, 
          layer = c ("public", "boundary_tsa_buff_50km"))
dbDisconnect (conn)


# create lookup table
studyarea.vat <- as.data.table (unique (boundary_buf_clipped$tsa_number))
setnames (studyarea.vat, "tsa_number")
studyarea.vat [, value := seq_len(.N)]

studyarea2 <- merge (boundary_buf_clipped, studyarea.vat, by = "tsa_number")

# Rasterize 
ras.study.area <-fasterize::fasterize (st_cast (studyarea2, "MULTIPOLYGON"), prov.rast, field = "value") 
ras.study.area<-rast(ras.study.area)

writeRaster (ras.study.area, "study_area_boundary_buff_50km.tif", overwrite=TRUE)

# write data
conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))
DBI::dbWriteTable(conn, c("vat", "vat_boundary_tsa_buff_50km"), value= studyarea.vat, row.names = FALSE, overwrite = TRUE)

system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/study_area_boundary_buff_50km.tif -t 100x100 rast.boundary_tsa_buff_50km | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)

dbDisconnect(conn)
```

