<!--
Copyright 2023 Province of British Columbia
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.-->

---
title: "blockingCastor"
author: "Kyle Lochhead"
date: "03 October 2018"
output: pdf_document
---

# Purpose

"The accuracy of any attempt to model a forest system depends largely upon
the precision with which the site can be classified into homogeneous units" (Vanclay)

This module groups pixels together to form harvest units. The purpose of this process is to specfiy the distribution of patches formed through forestry activities. For a greater description of this process and the calibration of this module go [here](https://github.com/bcgov/castor/blob/master/reports/harvest/draft-CLUS-blocking.md) 

# Overview

The blockingCastor module has two types of blocking algorithums:

1. `pre` blocking which uses a graph based image segmentation approach
2. `dynamic` blocking which uses the concept of contagion spreading

The module sets and updates the blocks table within `castordb`. It requires - dataCastor and growingStockCastor to provide inputs.

# Usage

```{r module_usage}
library(data.table)
library(dplyr)
source(here::here("R/functions/R_Postgres.R"))

moduleDir <- paste0(here::here(),"/R/SpaDES-modules")
outputDir <- paste0(here::here(),"/R/SpaDES-modules/blockingCastor")

times <- list(start = 0, end = 0)

parameters <- list(
  .progress = list(type = NA, interval = NA),
  .globals = list(),
  dataCastor = list( saveCastorDB = TRUE,
                     randomLandscape = list(100,100,0,100,0,100),
                     randomLandscapeClusterLevel = 1.2,
                     randomLandscapeZoneConstraint = 
                       data.table(variable = 'age', threshold = 140, type = 'ge', percentage = 20, zoneid =1)
                     ),
  blockingCastor = list(blockMethod='pre', 
                      patchZone = 'default',
                      patchVariation = 6)
                        )
modules <- list("dataCastor", "blockingCastor")
objects <- list(scenario = data.table(name="test", description = "test"))
paths <- list(
  modulePath = moduleDir,
  outputPath = outputDir
)

set.seed(86) # need to set a seed for solving the mst-can have many optimal solutions
mySim <- SpaDES.core::simInitAndSpades(times = times, params = parameters, modules = modules,
                 objects = objects, paths = paths)
#eventDiagram(mySimOut)
```

# Events

There are two methods used in blockingCastor under the blockMethod parameter:

1. pre blocking ('pre') - aggregates pixels at one time step using a graph based segementation approach

2. dynamic blocking ('dynamic')  - aggregates pixels at multiple steps using a contagion approach

# Data dependencies

## Input data

A 'SQLite' database connection called castordb is required as an output from dataCastor.
A patch size distribution from the biodiversity guidebook is provided as the default.
A homogenetiy factor 


## Output data

A raster of block IDs (hu.tif).

# Links to other modules

dataCastor is required.


