---
title: "blockzones"
output: html_document
date: '2022-09-12'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(data.table)
source("C:/Users/KLOCHHEA/clus/R/functions/R_Postgres.R")
ProvRast <- raster(
  nrows = 15744, ncols = 17216, xmn = 159587.5, xmx = 1881187.5, ymn = 173787.5, ymx = 1748187.5, 
  crs = st_crs(getSpatialQuery("select * from bec_zone limit 1;"))$proj4string, resolution = c(100, 100), vals = 0
)
```

## purpse
An input to pre-blocking algorithm requires a zonal layer where patch size constraints should be implemented. This code makes a zonal layer based on landscape units within natural disturbance types.

## Get Data
The ladnscape units and thier natural disturabnce units will be used
```{r, dat}

#Get the landscape units
lu<-getSpatialQuery("SELECT lu_id, lu_name,
case 
	when beo = 'High' then 1 
	when beo = 'Intermediate' then 2
	when beo = 'Low' then 3
	when beo = 'NA' then 3
end as beo, wkb_geometry 
FROM public.rmp_lu_sp_polygon 
WHERE beo <> 'Multiple' AND rt_dt Is NULL Order by gis_ch_dt")
lu[is.na(lu$beo),]$beo<-3 # assign low to all that are blank
luid.ras<-fasterize::fasterize(sf= lu, raster = ProvRast , field = "lu_id")

pg_bio<-getSpatialQuery("SELECT atrb1_val as bec_label, atrb2_val as ndu, atrb5_val as unit, atrb3_val as district,  atrb7_val as old_targ, wkb_geometry FROM rmp_lg_pl_polygon where slrp_name = 'Prince George Timber Supply Area (TSA) Legal Order - Landscape Biodiversity Objective Order - Extent'")
pg_bio<-pg_bio %>% group_by(unit, old_targ) %>% summarize(wkb_geometry = st_union(wkb_geometry))
pg_bio$unit<-as.factor(pg_bio$unit)
pg_lut<-data.table(pg_char= as.factor(pg_bio$unit))
pg_lut<-pg_lut[!is.na(pg_char),][,pg:=seq_len(.N)]
pg_lut$pg_char<-as.character(pg_lut$pg_char)

pg_bio.ras<-fasterize::fasterize(sf= pg_bio, raster = ProvRast , field = "unit")

ndt<-getSpatialQuery("SELECT  wkb_geometry,
case
  WHEN natural_disturbance = 'NDT1' then 1
  WHEN natural_disturbance = 'NDT2' then 2
  WHEN natural_disturbance = 'NDT3' then 3
  WHEN natural_disturbance = 'NDT4' then 4
  else 5
end as ndt from public.bec_zone")

ndt.ras<-fasterize::fasterize(sf= ndt, raster = ProvRast , field = "ndt")

ndt.table<-data.table(ndt = ndt.ras[], lu = luid.ras[], pg = pg_bio.ras[])
ndt.table<-ndt.table[,pixelid:=seq_len(.N)]
ndt.table<-merge(ndt.table, pg_lut, by.x = "pg", by.y = "pg", all.x=TRUE)

ndt.table<-ndt.table[pg_char %in% c('A2', 'A3', 'A4'), ndt :=6][pg_char %in% c('A5', 'A6', 'D1', 'E1'), ndt :=7][pg_char %in% c('A7', 'A8', 'A9', 'A10', 'A11', 'A12', 'A13', 'D2', 'D3', 'D4', 'D5','D6', 'D7', 'E2', 'E3', 'E4', 'E5'), ndt :=8][pg_char %in% c('A1', 'E6', 'E7', 'E8'), ndt :=9][pg_char %in% c('E9', 'E10', 'E11'), ndt :=10][pg_char %in% c('E12', 'E13', 'E14', 'E15', 'E16', 'E17'), ndt :=11][pg_char %in% c('A14', 'A15', 'A16', 'A17'), ndt :=12][pg_char %in% c('A18', 'A19', 'A20', 'A21'), ndt :=13][pg_char %in% c('A22', 'A23', 'A24', 'A25'), ndt :=14]

ndt.table<-ndt.table[is.na(pg_char), key_ndt:=paste0(lu, "_", ndt)][!is.na(pg_char), key_ndt:=paste0(pg_char, "_", ndt)]

ndt.lut <- data.table(key_ndt= unique(ndt.table$key))
ndt.lut<-ndt.lut[,id:=seq_len(.N)]

ndt.table<-merge(ndt.table, ndt.lut, by.x = "key_ndt", by.y = "key_ndt", all.x=TRUE)
#### Create Raster
zone.ras<-ProvRast
zone.ras[ndt.table$pixelid]<-ndt.table$id

writeRaster(zone.ras, "zone_blocks.tif", overwrite =TRUE)
system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M ', here::here(), '/R/params/zone_blocks.tif -t 100x100 rast.zone_ndt_blocks |  psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = FALSE)

ndt.lut[, c("lu_name", "ndt2") := tstrsplit(key_ndt, "_", fixed=TRUE)]
ndt.lut<-ndt.lut[ndt2 != 'NA',]
ndt.lut$ndt2<-as.integer(ndt.lut$ndt2)
zones<-data.table(zoneid = ndt.lut$id, reference_zone = 'rast.zone_ndt_blocks', ndt =ndt.lut$ndt2, variable= '', threshold = 0.0, type = '', percentage = 0.0, multi_condition = NA, denom =NA, start = 0, stop = 250, label = 'blocking_zones')
zones$multi_condition<-as.character(zones$multi_condition)
zones$denom<-as.character(zones$denom)

#Upload the constraint table to the db
conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))

DBI::dbWriteTable(conn, c("zone", "blocking"), value= zones, row.names = FALSE, overwrite = TRUE) 
dbExecute(conn, "alter table zone.blocking alter column denom Type character varying;")
dbExecute(conn, "alter table zone.blocking alter column start Type integer;")
dbExecute(conn, "alter table zone.blocking alter column stop Type integer;")
dbExecute(conn, "ALTER TABLE zone.blocking INHERIT zone.constraints;")
dbDisconnect(conn)
```

