---
title: "fisher_flex_inputs"
output: html_document
date: '2022-05-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set up rasters
```{r, setup-ras}
library(data.table)
library(raster)
library(sf)
source(paste0(here::here(), "/R/functions/R_Postgres.R"))
library(fasterize)
lu<-getSpatialQuery("SELECT wkb_geometry 
FROM public.rmp_lu_sp_polygon limit 1")

ProvRast <- raster(
  nrows = 15744, ncols = 17216, xmn = 159587.5, xmx = 1881187.5, ymn = 173787.5, ymx = 1748187.5, 
  crs = st_crs(lu)$proj4string, resolution = c(100, 100), vals = 0
)

```

#Denning
```{r, denning}
denning<-getSpatialQuery("select shape, 
                          CASE WHEN (SPECIES_CD_1 LIKE 'AC%'  or SPECIES_CD_2 LIKE 'AC%' or  SPECIES_CD_3 LIKE 'AC%' or (SPECIES_CD_1 LIKE 'S%' and SPECIES_CD_2 IS NULL)) and (bec_zone_code = 'SBS' and bec_subzone in('wk','mk','mm','mw')) THEN 1
                               WHEN (SPECIES_CD_1 LIKE 'AC%'  or SPECIES_CD_2 LIKE 'AC%' or  SPECIES_CD_3 LIKE 'AC%' or (SPECIES_CD_1 LIKE 'S%' and SPECIES_CD_2 IS NULL)) and (bec_zone_code = 'SBS' and bec_subzone in ('dw','dh','dk')) THEN 2
                               WHEN (SPECIES_CD_1 LIKE 'A%'  or SPECIES_CD_2 LIKE 'A%') and ((bec_zone_code = 'SBPS' and bec_subzone in('xc','mc','dc','mk')) or (bec_zone_code = 'IDF' and bec_subzone in('dk','dc','mw','dw','ww')) or (bec_zone_code = 'MS' and bec_subzone in('xc','xk','dv','dm', 'xv', 'dk', 'dc'))) THEN 3
                               WHEN  (SPECIES_CD_1 LIKE 'F%' and SPECIES_CD_2  IS NULL) and ((bec_zone_code = 'SBPS' and bec_subzone in('xc','mc','dc','mk')) or (bec_zone_code = 'IDF' and bec_subzone in('dk','dc','mw','dw','ww')) or (bec_zone_code = 'MS' and bec_subzone in('xc','xk','dv','dm', 'xv', 'dk', 'dc'))) THEN 4
                               WHEN (SPECIES_CD_1 LIKE 'AC%'  or SPECIES_CD_2 LIKE 'AC%' or  SPECIES_CD_3 LIKE 'AC%') and ((bec_zone_code = 'BWBS' and bec_subzone in ('dk', 'mw', 'mk', 'wk')) or (bec_zone_code ='SBS' and bec_subzone = 'wk' and bec_variant ='2')) THEN 5
                               WHEN (SPECIES_CD_1 LIKE 'AT%'  or SPECIES_CD_2 LIKE 'AT%' or  SPECIES_CD_3 LIKE 'AT%')  and ((bec_zone_code = 'BWBS' and bec_subzone in ('dk', 'mw', 'mk', 'wk')) or (bec_zone_code ='SBS' and bec_subzone = 'wk' and bec_variant ='2')) THEN 6
                               ELSE 0
                               END as region from public.veg_comp_lyr_r1_poly2020 where bec_zone_code in ('SBS', 'IDF', 'MS', 'SBPS', 'BWBS')")

denning.ras<-fasterize::fasterize(sf= denning, raster = ProvRast , field = "region")
denning.ras[is.na(denning.ras[])]<-0
writeRaster(denning.ras, "den.tif", overwrite = T)
```
# Rust
```{r, rust}
rust<-getSpatialQuery("select shape, 
                          CASE WHEN (SPECIES_CD_1 LIKE 'S%'  or SPECIES_CD_2 LIKE 'S%' or SPECIES_CD_3 LIKE 'S%') and (bec_zone_code = 'SBS' and bec_subzone in('wk','mk','mm','mw')) THEN 1
                               WHEN (SPECIES_CD_1 LIKE 'S%'  or SPECIES_CD_2 LIKE 'S%' or  SPECIES_CD_3 LIKE 'S%')  and (bec_zone_code = 'SBS' and bec_subzone in ('dw','dh','dk')) THEN 2
                               WHEN  (SPECIES_CD_1 LIKE 'S%'  or SPECIES_CD_2 LIKE 'S%' or  SPECIES_CD_3 LIKE 'S%') and ((bec_zone_code = 'SBPS' and bec_subzone in('xc','mc','dc','mk')) or (bec_zone_code = 'IDF' and bec_subzone in('dk','dc','mw','dw','ww')) or (bec_zone_code = 'MS' and bec_subzone in('xc','xk','xv','dv','dm', 'dk', 'dc'))) THEN 3
                               WHEN  (SPECIES_CD_1 LIKE 'SW%'  or SPECIES_CD_2 LIKE 'SW%' or  SPECIES_CD_3 LIKE 'SW%') and ((bec_zone_code = 'BWBS' and bec_subzone in ('dk', 'mw', 'mk', 'wk')) or (bec_zone_code ='SBS' and bec_subzone = 'wk' and bec_variant ='2')) THEN 5
                               WHEN  (SPECIES_CD_1 LIKE 'SB%'  or SPECIES_CD_2 LIKE 'SB%' or  SPECIES_CD_3 LIKE 'SB%')  and ((bec_zone_code = 'BWBS' and bec_subzone in ('dk', 'mw', 'mk', 'wk')) or (bec_zone_code ='SBS' and bec_subzone = 'wk' and bec_variant ='2')) THEN 6
                               ELSE 0
                               END as region from public.veg_comp_lyr_r1_poly2020 where bec_zone_code in ('SBS', 'IDF', 'MS', 'SBPS', 'BWBS')")

rust.ras<-fasterize::fasterize(sf= rust, raster = ProvRast , field = "region")
rust.ras[is.na(rust.ras[])]<-0
writeRaster(rust.ras, "rus.tif", overwrite = T)
```
# Cavity
```{r, cavity}
cavity<-getSpatialQuery("select shape, 
                          CASE WHEN (SPECIES_CD_1 LIKE 'A%'  or SPECIES_CD_2 LIKE 'A%' or  SPECIES_CD_3 LIKE 'A%') and (bec_zone_code = 'SBS' and bec_subzone in('wk','mk','mm','mw')) THEN 1
                               WHEN (SPECIES_CD_1 LIKE 'A%'  or SPECIES_CD_2 LIKE 'A%' or  SPECIES_CD_3 LIKE 'A%')  and (bec_zone_code = 'SBS' and bec_subzone in ('dw','dh','dk')) THEN 2
                              ELSE 0
                               END as region from public.veg_comp_lyr_r1_poly2020 where bec_zone_code in ('SBS')")

cavity.ras<-fasterize::fasterize(sf= cavity, raster = ProvRast , field = "region")
cavity.ras[is.na(cavity.ras[])]<-0
writeRaster(cavity.ras, "cav.tif", overwrite = T)
```
#CWD
```{r, cwd}
cwd<-getSpatialQuery("select shape, 
                          CASE WHEN (bec_zone_code = 'SBS' and bec_subzone in('wk','mk','mm','mw')) THEN 1
                               WHEN (bec_zone_code = 'SBS' and bec_subzone in ('dw','dh','dk')) THEN 2
                               WHEN  (((SPECIES_CD_1 LIKE 'S%' and SPECIES_PCT_1>=25) or (SPECIES_CD_2 LIKE 'S%' and SPECIES_PCT_2>=25) or (SPECIES_CD_3 LIKE 'S%' and SPECIES_PCT_3>=25)) or ((SPECIES_CD_1 LIKE 'AT%' and SPECIES_PCT_1>=25) or (SPECIES_CD_2 LIKE 'AT%' and SPECIES_PCT_2>=25) or (SPECIES_CD_3 LIKE 'AT%' and SPECIES_PCT_3>=25))) and ((bec_zone_code = 'SBPS' and bec_subzone in('xc','mc','dc','mk')) or (bec_zone_code = 'IDF' and bec_subzone in('dk','dc','mw','dw','ww')) or (bec_zone_code = 'MS' and bec_subzone in('xc','xk','dv','dm', 'dk', 'dc', 'xv'))) THEN 3
                               WHEN ((bec_zone_code = 'BWBS' and bec_subzone in ('dk', 'mw', 'mk', 'wk')) or (bec_zone_code ='SBS' and bec_subzone = 'wk' and bec_variant ='2')) THEN 5
                               ELSE 0
                               END as region from public.veg_comp_lyr_r1_poly2020 where bec_zone_code in ('SBS', 'IDF', 'MS', 'SBPS', 'BWBS')")

cwd.ras<-fasterize::fasterize(sf= cwd, raster = ProvRast , field = "region")
cwd.ras[is.na(cwd.ras[])]<-0
writeRaster(cwd.ras, "cwd.tif", overwrite = T)
```
#mov (this is really an id for fisher zone tho)
```{r, movement.fisher}
mov<-getSpatialQuery("select shape, 
                          CASE WHEN (bec_zone_code = 'SBS' and bec_subzone in('wk','mk','mm','mw')) THEN 1
                               WHEN (bec_zone_code = 'SBS' and bec_subzone in ('dw','dh','dk')) THEN 2
                               WHEN ((bec_zone_code = 'SBPS' and bec_subzone in('xc','mc','dc','mk')) or (bec_zone_code = 'IDF' and bec_subzone in('dk','dc','mw','dw','ww')) or (bec_zone_code = 'MS' and bec_subzone in('xc','xk','dv','dm', 'dk', 'dc', 'xv'))) THEN 3
                               WHEN ((bec_zone_code = 'BWBS' and bec_subzone in ('dk', 'mw', 'mk', 'wk')) or (bec_zone_code ='SBS' and bec_subzone = 'wk' and bec_variant ='2')) THEN 5
                               WHEN ((bec_zone_code = 'BWBS' and bec_subzone in ('dk', 'mw', 'mk', 'wk')) or (bec_zone_code ='SBS' and bec_subzone = 'wk' and bec_variant ='2')) THEN 6
                               ELSE 0
                               END as region from public.veg_comp_lyr_r1_poly2021 where bec_zone_code in ('SBS', 'IDF', 'MS', 'SBPS', 'BWBS')")

movp.ras<-fasterize::fasterize(sf= mov, raster = ProvRast , field = "region")
movp.ras[is.na(movp.ras[])]<-0
writeRaster(movp.ras, "movp.tif", overwrite = T)
```

#FETAS
```{r, fetas}
fish.constraints.columbia<-st_read("C:/Users/klochhea/fetaMapper/data-raw/test_columbia.shp")
fish.constraints.boreal<-st_read("C:/Users/klochhea/fetaMapper/data-raw/test_boreal.shp")
prov.sf.fisher<-rbind(fish.constraints.boreal,fish.constraints.columbia )

prov.fetas.ras<-fasterize::fasterize(sf= prov.sf.fisher, raster = ProvRast , field = "fid")
writeRaster(prov.fetas.ras, "fetas.tif", overwrite = T)
```

#FLEX
```{r, flex}
sf.obj<-getSpatialQuery("SELECT shape, CASE WHEN (bec_zone_code = 'SBS' and bec_subzone in('wk','mk','mm','mw')) THEN 2
                                                      WHEN (bec_zone_code = 'SBS' and bec_subzone in ('dw','dh','dk')) THEN 3
                                                      WHEN ((bec_zone_code = 'SBPS' and bec_subzone in('xc','mc','dc','mk')) or (bec_zone_code = 'IDF' and bec_subzone in('dk','dc','mw','dw','ww')) or (bec_zone_code = 'MS' and bec_subzone in('xc','xk','dv','dm', 'dk', 'dc'))) THEN 4
                                                      WHEN ((bec_zone_code = 'BWBS' and bec_subzone in ('dk', 'mw', 'mk', 'wk')) or (bec_zone_code ='SBS' and bec_subzone = 'wk' and bec_variant ='2')) THEN 1
                                         END as pop from public.veg_comp_lyr_r1_poly2020 where bec_zone_code in ('SBS', 'IDF', 'MS', 'SBPS', 'BWBS')")
library(dplyr)
sf.obj2<-sf.obj[!is.na(sf.obj$pop),]
sf.obj2<-sf.obj2 %>% group_by(pop) %>% summarize()

```