---
title: "Scripts for creating Nass parameters"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source (here::here("R/functions/R_Postgres.R"))
library (data.table)
library (sf)
library (tidyverse)
library (raster)
library (fasterize)

data.dir <- "G:\\!Workgrp\\Analysts\\!Project\\TSA_Projects\\active\\Nass_TSA\\2022\\andrew_deliverables\\Nass_almost_BaseCase_03_16\\Nass\\"

#Create a provincial raster
layeraoi<-getSpatialQuery("SELECT * FROM study_area_compart limit 1")
prov.rast <- raster::raster(
  nrows = 15744, ncols = 17216, xmn = 159587.5, xmx = 1881187.5, ymn = 173787.5, ymx = 1748187.5, 
  crs = st_crs(layeraoi)$proj4string, resolution = c(100, 100), vals = 0)
```

## Nass Area of Interest
```{r Nass TSA}

nass.tsa <- st_make_valid (getSpatialQuery ("SELECT tsa_number, tsbnmbrdsc, wkb_geometry FROM public.fadm_tsa_polygon WHERE tsa_number = '43' AND tsbnmbrdsc != '';"))
nass.tsa.supply.blocks <- st_make_valid (getSpatialQuery ("SELECT tsa_number, tsbnmbrdsc, wkb_geometry FROM public.fadm_tsa_polygon WHERE tsbnmbrdsc = 'Nass TSA Stewart Block' OR tsbnmbrdsc = 'Nass TSA Block E';"))

# null.block <- st_difference(nass.tsa, st_union(st_geometry(st_intersection(nass.tsa, nass.tsa.supply.blocks))))
# nass.tsa.supply.blocks <- rbind (nass.tsa.supply.blocks, null.block)

names(nass.tsa) [names(nass.tsa) == "tsa_number"] <- "tsa_name"
nass.tsa$tsa_name <- "Nass_TSA"

names(nass.tsa.supply.blocks) [names(nass.tsa.supply.blocks) == "tsbnmbrdsc"] <- "supply_block"
nass.tsa.supply.blocks$supply_block [nass.tsa.supply.blocks$supply_block == "Nass TSA Stewart Block"] <- "Stewart_Block"
nass.tsa.supply.blocks$supply_block [nass.tsa.supply.blocks$supply_block == "Nass TSA Block E"] <- "Block_E"
#nass.tsa.supply.blocks$supply_block <- nass.tsa.supply.blocks$supply_block %>% replace_na ('null_block')

supply.blocks.vat <- as.data.table (unique (nass.tsa.supply.blocks$supply_block))
setnames (supply.blocks.vat, "supply_block") 
supply.blocks.vat [, value := seq_len(.N)]
nass.tsa.supply.blocks <- merge (nass.tsa.supply.blocks, supply.blocks.vat, by = "supply_block")

nass.tsa$tsa_value <- as.integer (1)
nass.tsa.vat <- as.data.table (unique (nass.tsa$tsa_name))
nass.tsa.vat [, value := seq_len(.N)]

# st_write (nass.tsa.supply.blocks,"nass_supply_blocks.shp")
# ogr2ogr -f PostgreSQL PG:"dbname=clus port=5432 user= password= host=" SCHEMA=comaprison_nass C:\Work\git\clus\R\Params\nass_supply_blocks.shp nass_supply_blocks  -a_srs EPSG:3005 -progress --config PG_USE_COPY YES -nlt PROMOTE_TO_MULTI -lco SCHEMA=comparison_nass

# Rasterize 
ras.nass.supply.blocks <-fasterize::fasterize (st_cast (nass.tsa.supply.blocks, "MULTIPOLYGON"), prov.rast, field = "value") 
#ras.nass.supply.blocks [is.na(ras.nass.supply.blocks[])] <- 0 
ras.nass.all <-fasterize::fasterize (st_cast (nass.tsa, "MULTIPOLYGON"), prov.rast, field = "tsa_value") 
#ras.nass.all [is.na(ras.nass.all[])] <- 0 

writeRaster (ras.nass.supply.blocks, "nass_supply_blocks.tif", overwrite = T)
writeRaster (ras.nass.all, "nass_all.tif", overwrite = T)

# write data
conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))

setnames (supply.blocks.vat, c ("attribute", "value")) # Note use convention; always name these value and attribute
DBI::dbWriteTable(conn, c("comparison_nass", "vat_supply_blocks"), value = supply.blocks.vat, row.names = FALSE, overwrite = TRUE)
setnames (nass.tsa.vat, c ("attribute", "value")) # Note use convention; always name these value and attribute
DBI::dbWriteTable(conn, c("comparison_nass", "vat_tsa"), value = nass.tsa.vat, row.names = FALSE, overwrite = TRUE)

system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/Params/nass_supply_blocks.tif -t 100x100 comparison_nass.rast_supply_blocks | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)

system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/Params/nass_all.tif -t 100x100 comparison_nass.rast_tsa | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)

dbDisconnect(conn)
```

## THLB
```{r thlb}

thlb <- raster::raster (paste0 (data.dir, "gisData\\grids\\thlbContribution.tif")) 

# values have been multiplied to make them 0 to 10,000; divide by 10,000 to make it a value 0 to 1
thlb <- thlb / 10000

## Upload data to db
crs(thlb) <- "+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs"
writeRaster(thlb, file = "thlb.tif", format = "GTiff", overwrite = TRUE)
system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/thlb.tif -t 100x100 comparison_nass.rast_thlb_nass | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)

```

## Growth and Yield

```{r g and y data}

## TABLES
# volume table: VolumeBase.txt: Base case stand volume lookup table, with one row for each AU in the Nass TSA and volume values taken from the tsa43_vdyp and tsa43_tipsy PostGreSQL dumpfile provided.
tab.vol <- read.table(paste0 (data.dir, "inputFiles\\VolumeBase.txt"), header = T, sep = '\t')



tab.count <- tab.vol %>%                              
           group_by(AU) %>%
            tally ()

test2 <- tab.count %>%
          dplyr::filter (count > 1) # there are multiple volumes and heights for AU's why?


test <- tab.vol %>%
          filter (AU == 51277)

colnames(tab.vol) <- c('ycid', "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "110", "120", "130", "140", "150", "160", "170", "180", "190", "200", "210", "220", "230", "240", "250")
# reshape the table to long form
tab.vol <- melt (as.data.table(tab.vol), 
                  id.vars = "ycid",
                  measure.vars = list (age = c ("0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "110", "120", "130", "140", "150", "160", "170", "180", "190", "200", "210", "220", "230", "240", "250")),
                  value.name = "tvol",
                  variable.name = "age")

# height table: HeightBase.txt: Base case stand height lookup table, with one row for each AU in the Nass TSA and height values provided.
tab.height <- read.table(paste0 (data.dir, "inputFiles\\HeightBase.txt"), header = T, sep = '\t')
# reshape the table to long form
colnames(tab.height) <- c('ycid', "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "110", "120", "130", "140", "150", "160", "170", "180", "190", "200", "210", "220", "230", "240", "250")
tab.height <- melt (as.data.table(tab.height), 
                  id.vars = "ycid",
                  measure.vars = list (age = c ("0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "110", "120", "130", "140", "150", "160", "170", "180", "190", "200", "210", "220", "230", "240", "250")),
                  value.name = "height",
                  variable.name = "age")

# join the tables
tab.gy <- full_join (tab.vol, tab.height, by = c("ycid", "age"))


# analysis units: AUInfoBase.txt: Initial base case AUInfo file, with one row for each AU in the Nass TSA
tab.au <- read.table(paste0 (data.dir, "inputFiles\\AUInfoBase.txt"), header = T, sep = '\t')






## RASTERS
# "unmanaged" analysis unit raster; there are two the same "AU_inital" and "AU_unmanaged"
rast.au.unman <- raster::raster (paste0 (data.dir, "gisData\\grids\\AU_unmanaged.tif")) 
# "managed" analysis unit raster
rast.au.man <- raster::raster (paste0 (data.dir, "gisData\\grids\\AU_managed.tif")) 


```


## UWR

```{r uwr}
# only one conditional harvest UWR defined
# u-6-018
# For TSR, constraint is defined as 30% of productive forest area in zone >120 y.o.

# don't know what 'productive forest' is, so multiply that area by the UWR area and use total area in CLUS
prod.for <- raster::raster (paste0 (data.dir, "gisData\\grids\\ProductiveForest.tif")) 
uwr <- raster::raster (paste0 (data.dir, "gisData\\grids\\uwrZone.tif"))
uwr.prod <- uwr * prod.for
crs(uwr.prod) <- "+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs"
writeRaster(uwr.prod, file = "uwr_prod.tif", format = "GTiff", overwrite = TRUE)
system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/uwr_prod.tif -t 100x100 comparison_nass.rast_zone_uwr | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)

#Create zone constraint table
zone_uwr <- data.table (zoneid = as.integer (1), type = 'ge', variable = 'age', threshold = as.numeric(121), reference_zone = 'comparison_nass.rast_zone_uwr', percentage = 30, ndt = as.integer (0), label = 'u-6-018', multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))

conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))

DBI::dbWriteTable(conn, c("comparison_nass", "zone_uwr"), value = zone_uwr, row.names = FALSE, overwrite = TRUE) 
dbExecute(conn, "ALTER TABLE comparison_nass.zone_uwr ALTER COLUMN denom TYPE VARCHAR;")
dbExecute (conn, paste0("ALTER TABLE comparison_nass.zone_uwr INHERIT comparison_nass.zone_constraints_nass"))

dbDisconnect(conn)

```

## BEC BEO

 - 'standard' LUs
```{r bec biodiversity emphasis options}

# biodiversity emphasis options are forest age constraints applied by BEC zone and landscape unit combinations, within 'productive' forest

# The LU/BEC spatial areas/rasters are combined here to create a unique identifier for each BEC/LU combo
  # these combos seem to be able to be handled within SELES
prod.for <- raster::raster (paste0 (data.dir, "gisData\\grids\\ProductiveForest.tif")) 
lu <- raster::raster (paste0 (data.dir, "gisData\\grids\\lu.tif")) 
# LU classes: 1:Bear  2:Bowser  3:BrownBear  4:CambriaIcefield  5:Craven  6:GreenvilleKalum  7:Kinskuch  8:Kiteen  9:Kwinamuck  10:Madely  11:Muskaboo  12:NassRiverKalum  13:Oweegee  14:Sallysout 15:SpatsiziRiver  16:TaylorDamdochax  17:Tchitin  18:Tintina  19:White  20:Wildfire
bec <- raster::raster (paste0 (data.dir, "gisData\\grids\\BecBeo.tif"))
# BEC classes: 1:BAFAunL  2:BAFAunI  3:BAFAunH  4:CMAunL  5:CMAunI  6:CMAunH  7:CWHwmL  8:CWHwmI  9:CWHwmH  10:CWHws2L  11:CWHws2I  12:CWHws2H  13:ESSFunL 14:ESSFunI  15:ESSFunH 16:ESSFunpL 17:ESSFunpI 18:ESSFunpH  19:ESSFwvL  20:ESSFwvI  21:ESSFwvH  22:ESSFwvpL  23:ESSFwvpI  24:ESSFwvpH  25:ICHmc1L  26:ICHmc1I    27:ICHmc1H  28:ICHmc1aL  29:ICHmc1aI  30:ICHmc1aH  31:ICHmc2L 32:ICHmc2I  33:ICHmc2H  34:ICHvcL  35:ICHvcI  36:ICHvcH  37:MHmm1L  38:MHmm1I  39:MHmm1H  40:MHmm2L  41:MHmm2I  42:MHmm2H  43:MHmmpL  44:MHmmpI  45:MHmmpH  46:SBSmc2L  47:SBSmc2I  48:SBSmc2H  49:SBSunL  50:SBSunI


#-----------
# Here I put the BEC zones into groups with the same constraints by 'reclassifying' the bec raster
  # These BEC Zones have a 9% of the LU they are in > 250 y.o.: CWHws2L, CWHws2I, ICHmc1L, ICHmc1I, ICHmc1aL, ICHmc1aI, ICHmc2L, ICHmc2I; make these class 1
  # These BEC Zones have a 11% of the LU they are in > 140 y.o.: SBSmc2L, SBSmc2I, SBSunL, SBSunI; make these class 2
  # These BEC Zones have a 13% of the LU they are in > 250 y.o.: CWHwmL, CWHwmI, CWHws2H, ICHmc1H, ICHmc1aH, ICHmc2H, ICHvcL, ICHvcI; make these class 3
  # These BEC Zones have a 16% of the LU they are in > 140 y.o.: SBSmc2H; make these class 4
  # These BEC Zones have a 19% of the LU they are in > 250 y.o.: BAFAunL, BAFAunI, CMAunL, CMAunI, CWHwmH, ESSFunL, ESSFunI, ESSFunpL, ESSFunpI, ESSFwvL, ESSFwvI, ESSFwvpL, ESSFwvpI, ICHvcH, MHmm1L, MHmm1I, MHmm2L, MHmm2I, MHmmpL, MHmmpI; make these class 5
  # These BEC Zones have a 28% of the LU they are in > 250 y.o.: BAFAunH, CMAunH, ESSFunH, ESSFunpH, ESSFwvH, ESSFwvpH, MHmm1H, MHmm2H, MHmmpH; make these class 6
m <- c (10,1, 11,1, 25,1, 26,1, 28,1, 29,1, 31,1, 32,1, 46,2, 47,2, 49,2, 50,2, 7,3, 8,3, 12,3, 27,3, 30,3, 33,3, 34,3, 35,3, 48,4, 1,5, 2,5, 4,5, 9,5, 13,5,  14,5, 16,5, 17,5, 19,5, 20,5, 22,5, 23,5, 36,5, 37,5, 38,5, 40,5,  41,5, 43,5, 44,5, 3,6, 15,6, 18,6, 21,6, 24,6, 39,6, 42,6, 45,6)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.reclass <- raster::reclassify (bec, rclmat)

#---------
# Then I create reclassified raster of each unique LU and multiply by the BEC class to create the unique BEC/LU zones

## BEAR
m <- c (1,1, 2,0, 3,0, 4,0, 5,0, 6,0, 7,0, 8,0, 9,0, 10,0, 11,0, 12,0, 13,0, 14,0, 15,0, 16,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.bear <- raster::reclassify (lu, rclmat)
bec.bear <- lu.bear * bec.reclass
unique(getValues(bec.bear)) # contains BEC class 3 (13% of the LU they are in > 250 y.o.) and 5 (19% of the LU they are in > 250 y.o.)
m <- c (3,1, 5,2)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.bear.fin <- raster::reclassify (bec.bear, rclmat)
zone_beo_bear <- data.table (zoneid = as.integer (c(1,2)), type = 'ge', variable = 'age', threshold = as.numeric(251), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (13,19), ndt = as.integer (0), label = c ('bear class 3', 'bear class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))

## BOWSER
m <- c (1,0, 2,1, 3,0, 4,0, 5,0, 6,0, 7,0, 8,0, 9,0, 10,0, 11,0, 12,0, 13,0, 14,0, 15,0, 16,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.bowser <- raster::reclassify (lu, rclmat)
bec.bowser <- lu.bowser * bec.reclass
unique(getValues(bec.bowser)) # contains BEC class 3 (13% of the LU they are in > 250 y.o.) and 5 (19% of the LU they are in > 250 y.o.)
m <- c (3,3, 5,4)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.bowser.fin <- raster::reclassify (bec.bowser, rclmat)

zone_beo_bowser <- data.table (zoneid = as.integer (c(3,4)), type = 'ge', variable = 'age', threshold = as.numeric(251), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (13,19), ndt = as.integer (0), label = c ('bowser class 3', 'bowser class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))

zone_beo <- rbind (zone_beo_bear, zone_beo_bowser)
rm (zone_beo_bear, zone_beo_bowser)
gc ()

## BrownBear
m <- c (1,0, 2,0, 3,1, 4,0, 5,0, 6,0, 7,0, 8,0, 9,0, 10,0, 11,0, 12,0, 13,0, 14,0, 15,0, 16,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.brown <- raster::reclassify (lu, rclmat)
bec.brown <- lu.brown * bec.reclass
unique(getValues(bec.brown)) # contains BEC class 1 (9% of the LU they are in > 250 y.o.), 3 (13% of the LU they are in > 250 y.o.) and 5 (19% of the LU they are in > 250 y.o.)
m <- c (1,5, 3,6, 5,7)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.brown.fin <- raster::reclassify (bec.brown, rclmat)

zone_beo_brown <- data.table (zoneid = as.integer (c(5,6,7)), type = 'ge', variable = 'age', threshold = as.numeric(251), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (9,13,19), ndt = as.integer (0), label = c ('brownbear class 1', 'brownbear class 3', 'brownbear class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))

zone_beo <- rbind (zone_beo, zone_beo_brown)
rm (zone_beo_brown)
gc ()

## CambriaIcefield
m <- c (1,0, 2,0, 3,0, 4,1, 5,0, 6,0, 7,0, 8,0, 9,0, 10,0, 11,0, 12,0, 13,0, 14,0, 15,0, 16,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.camb <- raster::reclassify (lu, rclmat)
bec.camb <- lu.camb * bec.reclass
unique(getValues(bec.camb)) # contains BEC class 3 (13% of the LU they are in > 250 y.o.) and 5 (19% of the LU they are in > 250 y.o.)
m <- c (3,8, 5,9)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.camb.fin <- raster::reclassify (bec.camb, rclmat)
zone_beo_camb <- data.table (zoneid = as.integer (c(8,9)), type = 'ge', variable = 'age', threshold = as.numeric(251), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (13,19), ndt = as.integer (0), label = c ('CambriaIcefield class 3', 'CambriaIcefield class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_camb)
rm (zone_beo_camb)
gc ()

## CRAVEN
m <- c (1,0, 2,0, 3,0, 4,0, 5,1, 6,0, 7,0, 8,0, 9,0, 10,0, 11,0, 12,0, 13,0, 14,0, 15,0, 16,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.crav <- raster::reclassify (lu, rclmat)
bec.crav <- lu.crav * bec.reclass
unique(getValues(bec.crav)) # contains BEC class 2 (11% of the LU they are in > 140 y.o.), 3 (13% of the LU they are in > 250 y.o.) and 5 (19% of the LU they are in > 250 y.o.)
m <- c (2,10, 3,11, 5,12)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.crav.fin <- raster::reclassify (bec.crav, rclmat)
zone_beo_crav <- data.table (zoneid = as.integer (c(10,11,12)), type = 'ge', variable = 'age', threshold = as.numeric(c (141,251,251)), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (11,13,19), ndt = as.integer (0), label = c ('Craven class 2', 'Craven class 3', 'Craven class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_crav)
rm (zone_beo_crav)
gc ()

## GreenvilleKalum
m <- c (1,0, 2,0, 3,0, 4,0, 5,0, 6,1, 7,0, 8,0, 9,0, 10,0, 11,0, 12,0, 13,0, 14,0, 15,0, 16,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.green <- raster::reclassify (lu, rclmat)
bec.green <- lu.green * bec.reclass
unique(getValues(bec.green)) # contains BEC class 5 (19% of the LU they are in > 250 y.o.)
m <- c (5,13)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.green.fin <- raster::reclassify (bec.green, rclmat)
zone_beo_green <- data.table (zoneid = as.integer (c(13)), type = 'ge', variable = 'age', threshold = as.numeric(c (251)), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (19), ndt = as.integer (0), label = c ('GreenvilleKalum class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_green)
rm (zone_beo_green)
gc ()

## Kinskuch
m <- c (1,0, 2,0, 3,0, 4,0, 5,0, 6,0, 7,1, 8,0, 9,0, 10,0, 11,0, 12,0, 13,0, 14,0, 15,0, 16,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.kins <- raster::reclassify (lu, rclmat)
bec.kins <- lu.kins * bec.reclass
unique(getValues(bec.kins)) # class 1 (9% of the LU they are in > 250 y.o.), 3 (13% of the LU they are in > 250 y.o.) and 5 (19% of the LU they are in > 250 y.o.)
m <- c (1,14, 3,15, 5,16)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.kins.fin <- raster::reclassify (bec.kins, rclmat)
zone_beo_kins <- data.table (zoneid = as.integer (c(14,15,16)), type = 'ge', variable = 'age', threshold = as.numeric(c (251)), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (9,13,19), ndt = as.integer (0), label = c ('Kinskuch class 1', 'Kinskuch class 3', 'Kinskuch class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_kins)
rm (zone_beo_kins)
gc ()

## Kiteen
m <- c (1,0, 2,0, 3,0, 4,0, 5,0, 6,0, 7,0, 8,1, 9,0, 10,0, 11,0, 12,0, 13,0, 14,0, 15,0, 16,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.kit <- raster::reclassify (lu, rclmat)
bec.kit <- lu.kit * bec.reclass
unique(getValues(bec.kit)) # class 1 (9% of the LU they are in > 250 y.o.)
m <- c (1,17)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.kit.fin <- raster::reclassify (bec.kit, rclmat)
zone_beo_kit <- data.table (zoneid = as.integer (c(17)), type = 'ge', variable = 'age', threshold = as.numeric(c (251)), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (9), ndt = as.integer (0), label = c ('Kiteen class 1'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_kit)
rm (zone_beo_kit)
gc ()

## Kwinamuck
m <- c (1,0, 2,0, 3,0, 4,0, 5,0, 6,0, 7,0, 8,0, 9,1, 10,0, 11,0, 12,0, 13,0, 14,0, 15,0, 16,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.kwin <- raster::reclassify (lu, rclmat)
bec.kwin <- lu.kwin * bec.reclass
unique(getValues(bec.kwin)) # class 1 (9% of the LU they are in > 250 y.o.) and 5 (19% of the LU they are in > 250 y.o.)
m <- c (1,18, 5,19)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.kwin.fin <- raster::reclassify (bec.kwin, rclmat)
zone_beo_kwin <- data.table (zoneid = as.integer (c(18,19)), type = 'ge', variable = 'age', threshold = as.numeric(c (251)), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (9,19), ndt = as.integer (0), label = c ('Kwinamuck class 1', 'Kwinamuck class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_kwin)
rm (zone_beo_kwin)
gc ()

## Madely
m <- c (1,0, 2,0, 3,0, 4,0, 5,0, 6,0, 7,0, 8,0, 9,0, 10,1, 11,0, 12,0, 13,0, 14,0, 15,0, 16,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.mad <- raster::reclassify (lu, rclmat)
bec.mad <- lu.mad * bec.reclass
unique(getValues(bec.mad)) # class 1 (9% of the LU they are in > 250 y.o.), 3 (13% of the LU they are in > 250 y.o.)  and 5 (19% of the LU they are in > 250 y.o.)
m <- c (1,20, 3,21, 5,22)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.mad.fin <- raster::reclassify (bec.mad, rclmat)
zone_beo_mad <- data.table (zoneid = as.integer (c(20,21,22)), type = 'ge', variable = 'age', threshold = as.numeric(c (251)), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (9,13,19), ndt = as.integer (0), label = c ('Madely class 1', 'Madely class 3', 'Madely class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_mad)
rm (zone_beo_mad)
gc ()

## Muskaboo
m <- c (1,0, 2,0, 3,0, 4,0, 5,0, 6,0, 7,0, 8,0, 9,0, 10,0, 11,1, 12,0, 13,0, 14,0, 15,0, 16,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.musk <- raster::reclassify (lu, rclmat)
bec.musk <- lu.musk * bec.reclass
unique(getValues(bec.musk)) # class 2 (11% of the LU they are in > 140 y.o.) and 5 (19% of the LU they are in > 250 y.o.)
m <- c (2,23, 5,24)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.musk.fin <- raster::reclassify (bec.musk, rclmat)
zone_beo_musk <- data.table (zoneid = as.integer (c(23,24)), type = 'ge', variable = 'age', threshold = as.numeric(c (141,251)), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (11,19), ndt = as.integer (0), label = c ('Muskaboo class 2', 'Muskaboo class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_musk)
rm (zone_beo_musk)
gc ()

## NassRiverKalum
m <- c (1,0, 2,0, 3,0, 4,0, 5,0, 6,0, 7,0, 8,0, 9,0, 10,0, 11,0, 12,1, 13,0, 14,0, 15,0, 16,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.nass <- raster::reclassify (lu, rclmat)
bec.nass <- lu.nass * bec.reclass
unique(getValues(bec.nass)) # class 3 (13% of the LU they are in > 250 y.o.) and 6 (28% of the LU they are in > 250 y.o.)
m <- c (3,25, 6,26)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.nass.fin <- raster::reclassify (bec.nass, rclmat)
zone_beo_nass <- data.table (zoneid = as.integer (c(25,26)), type = 'ge', variable = 'age', threshold = as.numeric(c (251)), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (13,28), ndt = as.integer (0), label = c ('NassRiverKalum class 3', 'NassRiverKalum class 6'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_nass)
rm (zone_beo_nass)
gc ()

## Oweegee
m <- c (1,0, 2,0, 3,0, 4,0, 5,0, 6,0, 7,0, 8,0, 9,0, 10,0, 11,0, 12,0, 13,1, 14,0, 15,0, 16,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.owee <- raster::reclassify (lu, rclmat)
bec.owee <- lu.owee * bec.reclass
unique(getValues(bec.owee)) # class 3 (13% of the LU they are in > 250 y.o.) and 5 (19% of the LU they are in > 250 y.o.)
m <- c (3,27, 5,28)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.owee.fin <- raster::reclassify (bec.owee, rclmat)
zone_beo_owee <- data.table (zoneid = as.integer (c(27,28)), type = 'ge', variable = 'age', threshold = as.numeric(c (251)), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (13,19), ndt = as.integer (0), label = c ('Oweegee class 3', 'Oweegee class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_owee)
rm (zone_beo_owee)
gc ()

## Sallysout
m <- c (1,0, 2,0, 3,0, 4,0, 5,0, 6,0, 7,0, 8,0, 9,0, 10,0, 11,0, 12,0, 13,0, 14,1, 15,0, 16,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.sally <- raster::reclassify (lu, rclmat)
bec.sally <- lu.sally * bec.reclass
unique(getValues(bec.sally)) # class 1 (9% of the LU they are in > 250 y.o.), 2  (11% of the LU they are in > 140 y.o.), 3 (13% of the LU they are in > 250 y.o.) and 5 (19% of the LU they are in > 250 y.o.)
m <- c (1,29, 2,30, 3,31, 5,32)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.sally.fin <- raster::reclassify (bec.sally, rclmat)
zone_beo_sally <- data.table (zoneid = as.integer (c(29,30,31,32)), type = 'ge', variable = 'age', threshold = as.numeric(c (251,141,251,251)), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (9,11,13,19), ndt = as.integer (0), label = c ('Sallysout class 1', 'Sallysout class 2', 'Sallysout class 3', 'Sallysout class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_sally)
rm (zone_beo_sally)
gc ()

## SpatsiziRiver
m <- c (1,0, 2,0, 3,0, 4,0, 5,0, 6,0, 7,0, 8,0, 9,0, 10,0, 11,0, 12,0, 13,0, 14,0, 15,1, 16,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.spat <- raster::reclassify (lu, rclmat)
bec.spat <- lu.spat * bec.reclass
unique(getValues(bec.spat)) # class 5 (19% of the LU they are in > 250 y.o.)
m <- c (5,33)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.spat.fin <- raster::reclassify (bec.spat, rclmat)
zone_beo_spat <- data.table (zoneid = as.integer (c(33)), type = 'ge', variable = 'age', threshold = as.numeric(c (251)), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (19), ndt = as.integer (0), label = c ('SpatsiziRiver class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_spat)
rm (zone_beo_spat)
gc ()

## TaylorDamdochax
m <- c (1,0, 2,0, 3,0, 4,0, 5,0, 6,0, 7,0, 8,0, 9,0, 10,0, 11,0, 12,0, 13,0, 14,0, 15,0, 16,1, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.tay <- raster::reclassify (lu, rclmat)
bec.tay <- lu.tay * bec.reclass
unique(getValues(bec.tay)) #  class 1 (9% of the LU they are in > 250 y.o.), 2 (11% of the LU they are in > 140 y.o.), 3 (13% of the LU they are in > 250 y.o.) and 5 (19% of the LU they are in > 250 y.o.)
m <- c (1,34, 2,35, 3,36, 5,37)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.tay.fin <- raster::reclassify (bec.tay, rclmat)
zone_beo_tay <- data.table (zoneid = as.integer (c(34,35,36,37)), type = 'ge', variable = 'age', threshold = as.numeric(c (251,141,251,251)), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (9,11,13,19), ndt = as.integer (0), label = c ('TaylorDamdochax class 1', 'TaylorDamdochax class 2', 'TaylorDamdochax class 3', 'TaylorDamdochax class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_tay)
rm (zone_beo_tay)
gc ()

## Tchitin
m <- c (1,0, 2,0, 3,0, 4,0, 5,0, 6,0, 7,0, 8,0, 9,0, 10,0, 11,0, 12,0, 13,0, 14,0, 15,0, 16,0, 17,1, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.tchi <- raster::reclassify (lu, rclmat)
bec.tchi <- lu.tchi * bec.reclass
unique(getValues(bec.tchi)) #  class 3 (13% of the LU they are in > 250 y.o.) and 6 (28% of the LU they are in > 250 y.o.)
m <- c (3,38, 6,39)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.tchi.fin <- raster::reclassify (bec.tchi, rclmat)
zone_beo_tchi <- data.table (zoneid = as.integer (c(38,39)), type = 'ge', variable = 'age', threshold = as.numeric(c (251)), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (13,6), ndt = as.integer (0), label = c ('Tchitin class 3', 'Tchitin class 6'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_tchi)
rm (zone_beo_tchi)
gc ()

## Tintina
m <- c (1,0, 2,0, 3,0, 4,0, 5,0, 6,0, 7,0, 8,0, 9,0, 10,0, 11,0, 12,0, 13,0, 14,0, 15,0, 16,0, 17,0, 18,1, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.tint <- raster::reclassify (lu, rclmat)
bec.tint <- lu.tint * bec.reclass
unique(getValues(bec.tint)) #  class 1 (9% of the LU they are in > 250 y.o.), 3 (13% of the LU they are in > 250 y.o.) and 5 (19% of the LU they are in > 250 y.o.)
m <- c (1,40, 3,41, 5,42)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.tint.fin <- raster::reclassify (bec.tint, rclmat)
zone_beo_tint <- data.table (zoneid = as.integer (c(40,41,42)), type = 'ge', variable = 'age', threshold = as.numeric(c (251)), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (9,13,19), ndt = as.integer (0), label = c ('Tintina class 1', 'Tintina class 3', 'Tintina class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_tint)
rm (zone_beo_tint)
gc ()

## White
m <- c (1,0, 2,0, 3,0, 4,0, 5,0, 6,0, 7,0, 8,0, 9,0, 10,0, 11,0, 12,0, 13,0, 14,0, 15,0, 16,0, 17,0, 18,0, 19,1, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.white <- raster::reclassify (lu, rclmat)
bec.white <- lu.white * bec.reclass
unique(getValues(bec.white)) #  class 1 (9% of the LU they are in > 250 y.o.), 3 (13% of the LU they are in > 250 y.o.) and 5 (19% of the LU they are in > 250 y.o.)
m <- c (1,43, 3,44, 5,45)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.white.fin <- raster::reclassify (bec.white, rclmat)
zone_beo_white <- data.table (zoneid = as.integer (c(43,44,45)), type = 'ge', variable = 'age', threshold = as.numeric(c (251)), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (9,13,19), ndt = as.integer (0), label = c ('White class 1', 'White class 3', 'White class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_white)
rm (zone_beo_white)
gc ()

## Wildfire
m <- c (1,0, 2,0, 3,0, 4,0, 5,0, 6,0, 7,0, 8,0, 9,0, 10,0, 11,0, 12,0, 13,0, 14,0, 15,0, 16,0, 17,0, 18,0, 19,0, 20,1)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.wild <- raster::reclassify (lu, rclmat)
bec.wild <- lu.wild * bec.reclass
unique(getValues(bec.wild)) #  class 3 (13% of the LU they are in > 250 y.o.) and 5 (19% of the LU they are in > 250 y.o.)
m <- c (3,46, 5,47)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.wild.fin <- raster::reclassify (bec.wild, rclmat)
zone_beo_wild <- data.table (zoneid = as.integer (c(46,47)), type = 'ge', variable = 'age', threshold = as.numeric(c (251)), reference_zone = 'comparison_nass.rast_zone_beo_prod', percentage = c (13,19), ndt = as.integer (0), label = c ('Wildfire class 3', 'Wildfire class 5'), multi_condition = as.character (''), denom = as.character (''), start = as.integer (0), stop = as.integer (0))
zone_beo <- rbind (zone_beo, zone_beo_wild)
rm (zone_beo_wild)
gc ()

## All zones together
rast.beo <- bec.bear.fin + bec.bowser.fin + bec.brown.fin + bec.camb.fin + bec.crav.fin + bec.green.fin + bec.kins.fin + bec.kit.fin + bec.kwin.fin + bec.mad.fin + bec.musk.fin + bec.nass.fin + bec.owee.fin + bec.sally.fin + bec.spat.fin + bec.tay.fin + bec.tchi.fin + bec.tint.fin + bec.white.fin + bec.wild.fin

## Multiply by productive forest
rast.beo.prod <- rast.beo * prod.for

## Upload data to db
crs(rast.beo) <- "+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs"
writeRaster(rast.beo, file = "beo.tif", format = "GTiff", overwrite = TRUE)
system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/beo.tif -t 100x100 comparison_nass.rast_zone_beo | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)

crs(rast.beo.prod) <- "+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs"
writeRaster(rast.beo.prod, file = "beo_prod.tif", format = "GTiff", overwrite = TRUE)
system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/beo_prod.tif -t 100x100 comparison_nass.rast_zone_beo_prod | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)

conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))
DBI::dbWriteTable(conn, c("comparison_nass", "zone_beo"), value = zone_beo, row.names = FALSE, overwrite = TRUE) 
dbExecute(conn, "ALTER TABLE comparison_nass.zone_beo ALTER COLUMN denom TYPE VARCHAR;")
dbExecute (conn, paste0("ALTER TABLE comparison_nass.zone_beo INHERIT comparison_nass.zone_constraints_nass"))

dbDisconnect(conn)

```


- SRMP LUs 
```{r bec biodiversity emphasis options, SRMP LUs}

# biodiversity emphasis options are forest age constraints applied by BEC zone and landscape unit combinations, within 'productive' forest; these apply to SRMP LU's

# The LU/BEC spatial areas/rasters are combined here to create a unique identifier for each BEC/LU combo
  # these combos seem to be able to be handled within SELES
prod.for <- raster::raster (paste0 (data.dir, "gisData\\grids\\ProductiveForest.tif")) 
lu.srmp <- raster::raster (paste0 (data.dir, "gisData\\grids\\lu_srmp.tif")) 
unique(getValues(lu.srmp))
# LU classes: 1:Bear 2:Bowser  3:BrownBear  4:CambriaIcefield  6:GreenvilleKalum  7:Kinskuch  8:Kiteen  9:Kwinamuck  10:Madely  12:NassRiverKalum  17:Tchitin  18:Tintina  19:White  20:Wildfire
bec <- raster::raster (paste0 (data.dir, "gisData\\grids\\BecBeo.tif"))
# BEC classes: 1:BAFAunL  2:BAFAunI  3:BAFAunH  4:CMAunL  5:CMAunI  6:CMAunH  7:CWHwmL  8:CWHwmI  9:CWHwmH  10:CWHws2L  11:CWHws2I  12:CWHws2H  13:ESSFunL 14:ESSFunI  15:ESSFunH 16:ESSFunpL 17:ESSFunpI 18:ESSFunpH  19:ESSFwvL  20:ESSFwvI  21:ESSFwvH  22:ESSFwvpL  23:ESSFwvpI  24:ESSFwvpH  25:ICHmc1L  26:ICHmc1I    27:ICHmc1H  28:ICHmc1aL  29:ICHmc1aI  30:ICHmc1aH  31:ICHmc2L 32:ICHmc2I  33:ICHmc2H  34:ICHvcL  35:ICHvcI  36:ICHvcH  37:MHmm1L  38:MHmm1I  39:MHmm1H  40:MHmm2L  41:MHmm2I  42:MHmm2H  43:MHmmpL  44:MHmmpI  45:MHmmpH  46:SBSmc2L  47:SBSmc2I  48:SBSmc2H  49:SBSunL  50:SBSunI

#-----------
# Here I put the BEC zones into groups with the same constraints by 'reclassifying' the bec raster
# These BEC Zones have a max 100% of the LU they are in < 40 y.o. (NO CONSTRAINT?): BAFAunH, BAFAunI, BAFAunL, CMAunH, CMAunI, CMAunL, CWHwmH, CWHwmL, CWHws2H, CWHws2I, CWHws2L, ESSFunH, ESSFunI, ESSFunL, ESSFunpH, ESSFunpL, ESSFwvH, ESSFwvpH, ESSFwvpL, ESSFunpI, ESSFwvpI, ICHmc1aH, ICHmc1aI, ICHmc1aL, ICHmc1H, ICHmc2H, ICHmc2I, ICHmc2L, ICHvcH, MHmm1H, MHmm1I, MHmm1L, MHmm2H, MHmmpH, MHmmpI, MHmmpL, SBSmc2H, SBSmc2I, SBSmc2L, SBSunI, SBSunL; CLASS 1
# These BEC Zones have a 70% of the LU they are in > 40 y.o. and 36% of the LU they are in > 80 y.o.: CWHwmI; CLASS 2
# These BEC Zones have a 78% of the LU they are in > 40 y.o. and 36% of the LU they are in > 120 y.o.: ESSFwvI; CLASS 3
# These BEC Zones have a 19% of the LU they are in > 120 y.o. and 0% of the LU they are in < 40 y.o. (NO CONSTRAINT?): ESSFwvL; CLASS 4
# These BEC Zones have a 31% of the LU they are in > 100 y.o. and 64% of the LU they are in > 40 y.o.: ICHmc1I; CLASS 5
# These BEC Zones have a 15% of the LU they are in > 100 y.o. and max 100% of the LU they are in < 40 y.o. (NO CONSTRAINT): ICHmc1L; CLASS 6
# These BEC Zones have a 34% of the LU they are in > 100 y.o. and 70% of the LU  are in > 40 y.o: ICHvcI; CLASS 7
# These BEC Zones have a 17% of the LU they are in > 100 y.o. and max 100% of the LU they are in < 40 y.o. (NO CONSTRAINT): ICHvcL; CLASS 8
# These BEC Zones have a 78% of the LU they are in > 40 y.o. and 36% of the LU they are in > 120 y.o.: MHmm2I; CLASS 9
 # These BEC Zones have a 19% of the LU they are in > 120 y.o. and max 100% of the LU they are in < 40 y.o. (NO CONSTRAINT): MHmm2L; CLASS 10

m <- c (1,1, 2,1, 3,1, 4,1, 5,1, 6,1, 7,1, 8,2, 9,1, 10,1, 11,1, 12,1, 13,1, 14,1, 15,1, 16,1, 17,1, 18,1, 19,4, 20,3, 21,1, 22,1, 23,1, 24,1, 25,6, 26,5, 27,1, 28,1, 29,1, 30,1, 31,1, 32,1, 33,1, 34,8, 35,7, 36,1, 37,1, 38,1, 39,1, 40,10, 41,9, 42,1, 43,1, 44,1, 45,1, 46,1, 47,1, 48,1, 49,1, 50,1)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.reclass <- raster::reclassify (bec, rclmat)

#---------
# Then I create reclassified raster of each unique LU and multiply by the BEC class to create the unique BEC/LU zones

# LU classes: 1:Bear 2:Bowser  3:BrownBear  4:CambriaIcefield  6:GreenvilleKalum  7:Kinskuch  8:Kiteen  9:Kwinamuck  10:Madely  12:NassRiverKalum  17:Tchitin  18:Tintina  19:White  20:Wildfire

## BEAR
m <- c (1,1, 2,0, 3,0, 4,0, 6,0, 7,0, 8,0, 9,0, 10,0, 12,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.bear <- raster::reclassify (lu.srmp, rclmat)
bec.bear <- lu.bear * bec.reclass
unique(getValues(bec.bear)) # contains BEC class 1 (no constraint), 2 (70% of the LU they are in > 40 y.o. and 36% of the LU they are in > 80 y.o.) and 9 (78% of the LU they are in > 40 y.o. and 36% of the LU they are in > 120 y.o.)
m <- c (1,1, 2,2, 9,3)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.bear.fin <- raster::reclassify (bec.bear, rclmat)
zone_beo_bear <- data.table (zoneid = as.integer (c(1,2,2,3,3)), 
                             type = c ('', 'ge', 'ge', 'ge', 'ge'),
                             variable = 'age', 
                             threshold = as.numeric ( c(41, 41, 81, 41, 121)), 
                             reference_zone = 'comparison_nass.rast_zone_beo_lrmp_prod', 
                             percentage = c (100, 70, 36, 78, 36), ndt = as.integer (0), 
                             label = c ('bear class 1', 'bear class 2', 'bear class 2', 'bear class 9', 'bear class 9'), 
                             multi_condition = as.character (''), 
                             denom = as.character (''), start = as.integer (0), stop = as.integer (0))

## BOWSER
m <- c (1,0, 2,1, 3,0, 4,0, 6,0, 7,0, 8,0, 9,0, 10,0, 12,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.bowser <- raster::reclassify (lu.srmp, rclmat)
bec.bowser <- lu.bowser * bec.reclass
unique(getValues(bec.bowser)) 
# contains BEC class 1 (no constraint), 8 (17% of the LU they are in > 100 y.o.) and 10 (19% of the LU they are in > 120 y.o.)
m <- c (1,4, 8,5, 10,6)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.bowser.fin <- raster::reclassify (bec.bowser, rclmat)
zone_beo_bowser <- data.table (zoneid = as.integer (c(4,5,6)), 
                             type = c ('', 'ge', 'ge'),
                             variable = 'age', 
                             threshold = as.numeric ( c(41, 101, 121)), 
                             reference_zone = 'comparison_nass.rast_zone_beo_lrmp_prod', 
                             percentage = c (100, 17, 19), ndt = as.integer (0), 
                             label = c ('bowser class 1', 'bowser class 8', 'bowser class 10'), 
                             multi_condition = as.character (''), 
                             denom = as.character (''), start = as.integer (0), stop = as.integer (0))

## BrownBear
m <- c (1,0, 2,0, 3,1, 4,0, 6,0, 7,0, 8,0, 9,0, 10,0, 12,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.brown <- raster::reclassify (lu.srmp, rclmat)
bec.brown <- lu.brown * bec.reclass
unique(getValues(bec.brown)) 
# contains BEC class 1 (no constraint), 6 (15% of the LU they are in > 100 y.o.), 8 (17% of the LU they are in > 100 y.o.) and 10 (19% of the LU they are in > 120 y.o.)
m <- c (1,7, 6,8, 8,9, 10,10)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.brown.fin <- raster::reclassify (bec.brown, rclmat)
zone_beo_brown <- data.table (zoneid = as.integer (c(7,8,9,10)), 
                             type = c ('', 'ge', 'ge', 'ge'),
                             variable = 'age', 
                             threshold = as.numeric ( c(41, 101, 101, 121)), 
                             reference_zone = 'comparison_nass.rast_zone_beo_lrmp_prod', 
                             percentage = c (100, 15, 17, 19), ndt = as.integer (0), 
                             label = c ('BrownBear class 1', 'BrownBear class 6', 'BrownBear class 8', 'BrownBear class 10'), 
                             multi_condition = as.character (''), 
                             denom = as.character (''), start = as.integer (0), stop = as.integer (0))

## CambriaIcefield
m <- c (1,0, 2,0, 3,0, 4,1, 6,0, 7,0, 8,0, 9,0, 10,0, 12,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.camb <- raster::reclassify (lu.srmp, rclmat)
bec.camb <- lu.camb * bec.reclass
unique(getValues(bec.camb)) 
# contains BEC class 1 (no constraint), 8 (17% of the LU they are in > 100 y.o.) and 10 (19% of the LU they are in > 120 y.o.)
m <- c (1,11, 8,12, 10,13)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.camb.fin <- raster::reclassify (bec.camb, rclmat)
zone_beo_camb <- data.table (zoneid = as.integer (c(11,12,13)), 
                             type = c ('', 'ge', 'ge'),
                             variable = 'age', 
                             threshold = as.numeric ( c(41, 101, 121)), 
                             reference_zone = 'comparison_nass.rast_zone_beo_lrmp_prod', 
                             percentage = c (100, 17, 19), ndt = as.integer (0), 
                             label = c ('CambriaIcefield class 1', 'CambriaIcefield class 8', 'CambriaIcefield class 10'), 
                             multi_condition = as.character (''), 
                             denom = as.character (''), start = as.integer (0), stop = as.integer (0))

## GreenvilleKalum
m <- c (1,0, 2,0, 3,0, 4,0, 6,1, 7,0, 8,0, 9,0, 10,0, 12,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.green <- raster::reclassify (lu.srmp, rclmat)
bec.green <- lu.green * bec.reclass
unique(getValues(bec.green)) 
# contains BEC class 1 (no constraint), 8 (17% of the LU they are in > 100 y.o.) and 10 (19% of the LU they are in > 120 y.o.)
m <- c (1,14)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.green.fin <- raster::reclassify (bec.green, rclmat)
zone_beo_green <- data.table (zoneid = as.integer (c(14)), 
                             type = c (''),
                             variable = 'age', 
                             threshold = as.numeric ( c(41)), 
                             reference_zone = 'comparison_nass.rast_zone_beo_lrmp_prod', 
                             percentage = c (100), ndt = as.integer (0), 
                             label = c ('GreenvilleKalum class 1'), 
                             multi_condition = as.character (''), 
                             denom = as.character (''), start = as.integer (0), stop = as.integer (0))

## Kinskuch
m <- c (1,0, 2,0, 3,0, 4,0, 6,0, 7,1, 8,0, 9,0, 10,0, 12,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.kins <- raster::reclassify (lu.srmp, rclmat)
bec.kins <- lu.kins * bec.reclass
unique(getValues(bec.kins)) 
# contains BEC class 1 (no constraint), 5 (31% of the LU they are in > 100 y.o. and 64% of the LU they are in > 40 y.o.), 7 (34% of the LU they are in > 100 y.o. and 70% of the LU  are in > 40 y.o) and 9 (78% of the LU they are in > 40 y.o. and 36% of the LU they are in > 120 y.o.)
m <- c (1,15, 5,16, 7,17, 9,18)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.kins.fin <- raster::reclassify (bec.kins, rclmat)
zone_beo_kins <- data.table (zoneid = as.integer (c(15,16,16,17,17,18,18)), 
                             type = c ('', 'ge', 'ge', 'ge', 'ge', 'ge', 'ge'),
                             variable = 'age', 
                             threshold = as.numeric ( c(41, 101, 41, 101, 41, 41, 121)), 
                             reference_zone = 'comparison_nass.rast_zone_beo_lrmp_prod', 
                             percentage = c (100, 31, 64, 34, 70, 78, 36), ndt = as.integer (0), 
                             label = c ('Kinskuch class 1', 'Kinskuch class 5', 'Kinskuch class 5', 'Kinskuch class 7', 'Kinskuch class 7', 'Kinskuch class 9', 'Kinskuch class 9'), 
                             multi_condition = as.character (''), 
                             denom = as.character (''), start = as.integer (0), stop = as.integer (0)) 

## Kiteen
### Little OVerlap with AOI
# m <- c (1,0, 2,0, 3,0, 4,0, 6,0, 7,0, 8,1, 9,0, 10,0, 12,0, 17,0, 18,0, 19,0, 20,0)
# rclmat <- matrix (m, ncol = 2, byrow = TRUE)
# lu.kit <- raster::reclassify (lu.srmp, rclmat)
# bec.kit <- lu.kit * bec.reclass
# unique(getValues(bec.kit)) 
# # contains BEC class 1 (no constraint) and 6 (15% of the LU they are in > 100 y.o.)
# m <- c (1,1, 6,2)
# rclmat <- matrix (m, ncol = 2, byrow = TRUE)
# bec.kit.fin <- raster::reclassify (bec.kit, rclmat)
# zone_beo_kit <- data.table (zoneid = as.integer (c(1,2)), 
#                              type = c ('', 'ge'),
#                              variable = 'age', 
#                              threshold = as.numeric ( c(41, 101)), 
#                              reference_zone = 'comparison_nass.rast_zone_beo_lrmp_prod', 
#                              percentage = c (100, 15), ndt = as.integer (0), 
#                              label = c ('Kiteen class 1', 'Kiteen class 6'), 
#                              multi_condition = as.character (''), 
#                              denom = as.character (''), start = as.integer (0), stop = as.integer (0)) 

## Kwinamuck
m <- c (1,0, 2,0, 3,0, 4,0, 6,0, 7,0, 8,0, 9,1, 10,0, 12,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.kwin <- raster::reclassify (lu.srmp, rclmat)
bec.kwin <- lu.kwin * bec.reclass
unique(getValues(bec.kwin)) 
# contains BEC class 1 (no constraint) and 10 (19% of the LU they are in > 120 y.o.)
m <- c (1,19, 10,20)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.kwin.fin <- raster::reclassify (bec.kwin, rclmat)
zone_beo_kwin <- data.table (zoneid = as.integer (c(19,20)), 
                             type = c ('', 'ge'),
                             variable = 'age', 
                             threshold = as.numeric ( c(41, 121)), 
                             reference_zone = 'comparison_nass.rast_zone_beo_lrmp_prod', 
                             percentage = c (100, 19), ndt = as.integer (0), 
                             label = c ('Kwinamuck class 1', 'Kwinamuck class 10'), 
                             multi_condition = as.character (''), 
                             denom = as.character (''), start = as.integer (0), stop = as.integer (0))

## Madely
m <- c (1,0, 2,0, 3,0, 4,0, 6,0, 7,0, 8,0, 9,0, 10,1, 12,0, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.mad <- raster::reclassify (lu.srmp, rclmat)
bec.mad <- lu.mad * bec.reclass
unique(getValues(bec.mad)) 
# contains BEC class 1 (no constraint), 5 (31% of the LU they are in > 100 y.o. and 64% of the LU they are in > 40 y.o.), 7 (34% of the LU they are in > 100 y.o. and 70% of the LU  are in > 40 y.o) and 9 (78% of the LU they are in > 40 y.o. and 36% of the LU they are in > 120 y.o.)
m <- c (1,21, 5,22, 7,23, 9,24)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.mad.fin <- raster::reclassify (bec.mad, rclmat)
zone_beo_mad <- data.table (zoneid = as.integer (c(21,22,22,23,23,24,24)), 
                             type = c ('', 'ge', 'ge', 'ge', 'ge', 'ge', 'ge'),
                             variable = 'age', 
                             threshold = as.numeric ( c(41, 101, 41, 101, 41, 41, 121)), 
                             reference_zone = 'comparison_nass.rast_zone_beo_lrmp_prod', 
                             percentage = c (100, 31, 64, 34, 70, 78, 36), ndt = as.integer (0), 
                             label = c ('Madely class 1', 'Madely class 5', 'Madely class 5', 'Madely class 7', 'Madely class 7', 'Madely class 9', 'Madely class 9'), 
                             multi_condition = as.character (''), 
                             denom = as.character (''), start = as.integer (0), stop = as.integer (0))

## NassRiverKalum
m <- c (1,0, 2,0, 3,0, 4,0, 6,0, 7,0, 8,0, 9,0, 10,0, 12,1, 17,0, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.nass <- raster::reclassify (lu.srmp, rclmat)
bec.nass <- lu.nass * bec.reclass
unique(getValues(bec.nass)) 
# contains BEC class 1 (no constraint)
m <- c (1,25)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.nass.fin <- raster::reclassify (bec.nass, rclmat)
zone_beo_nass <- data.table (zoneid = as.integer (c(25)), 
                             type = c (''),
                             variable = 'age', 
                             threshold = as.numeric ( c(41)), 
                             reference_zone = 'comparison_nass.rast_zone_beo_lrmp_prod', 
                             percentage = c (100), ndt = as.integer (0), 
                             label = c ('NassRiverKalum class 1'), 
                             multi_condition = as.character (''), 
                             denom = as.character (''), start = as.integer (0), stop = as.integer (0))

## Tchitin 
m <- c (1,0, 2,0, 3,0, 4,0, 6,0, 7,0, 8,0, 9,0, 10,0, 12,0, 17,1, 18,0, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.tchi <- raster::reclassify (lu.srmp, rclmat)
bec.tchi <- lu.tchi * bec.reclass
unique(getValues(bec.tchi)) 
# contains BEC class 1 (no constraint)
m <- c (1,26)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.tchi.fin <- raster::reclassify (bec.tchi, rclmat)
zone_beo_tchi <- data.table (zoneid = as.integer (c(26)), 
                             type = c (''),
                             variable = 'age', 
                             threshold = as.numeric ( c(41)), 
                             reference_zone = 'comparison_nass.rast_zone_beo_lrmp_prod', 
                             percentage = c (100), ndt = as.integer (0), 
                             label = c ('Tchitin class 1'), 
                             multi_condition = as.character (''), 
                             denom = as.character (''), start = as.integer (0), stop = as.integer (0))
 
## Tintina 
m <- c (1,0, 2,0, 3,0, 4,0, 6,0, 7,0, 8,0, 9,0, 10,0, 12,0, 17,0, 18,1, 19,0, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.tint <- raster::reclassify (lu.srmp, rclmat)
bec.tint <- lu.tint * bec.reclass
unique(getValues(bec.tint)) 
# contains BEC class 1 (no constraint), 6 (15% of the LU they are in > 100 y.o.), 8 (17% of the LU they are in > 100 y.o.) and 10 (19% of the LU they are in > 120 y.o.)
m <- c (1,27, 6,28, 8,29, 10,30)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.tint.fin <- raster::reclassify (bec.tint, rclmat)
zone_beo_tint <- data.table (zoneid = as.integer (c(27, 28, 29, 30)), 
                             type = c ('', 'ge', 'ge', 'ge'),
                             variable = 'age', 
                             threshold = as.numeric ( c(41, 101, 101, 121)), 
                             reference_zone = 'comparison_nass.rast_zone_beo_lrmp_prod', 
                             percentage = c (100, 15, 17, 19), ndt = as.integer (0), 
                             label = c ('Tintina class 1', 'Tintina class 6', 'Tintina class 8', 'Tintina class 10'), 
                             multi_condition = as.character (''), 
                             denom = as.character (''), start = as.integer (0), stop = as.integer (0))

## White 
m <- c (1,0, 2,0, 3,0, 4,0, 6,0, 7,0, 8,0, 9,0, 10,0, 12,0, 17,0, 18,0, 19,1, 20,0)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.white <- raster::reclassify (lu.srmp, rclmat)
bec.white <- lu.white * bec.reclass
unique(getValues(bec.white)) 
# contains BEC class 1 (no constraint), 5 (31% of the LU they are in > 100 y.o. and 64% of the LU they are in > 40 y.o.), 7 (34% of the LU they are in > 100 y.o. and 70% of the LU  are in > 40 y.o) and 9 (78% of the LU they are in > 40 y.o. and 36% of the LU they are in > 120 y.o.)
m <- c (1,31, 5,32, 7,33, 9,34)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.white.fin <- raster::reclassify (bec.white, rclmat)
zone_beo_white <- data.table (zoneid = as.integer (c(31, 32, 32, 33, 33, 34, 34)), 
                             type = c ('', 'ge', 'ge', 'ge', 'ge', 'ge', 'ge'),
                             variable = 'age', 
                             threshold = as.numeric ( c(41, 101, 41, 101, 41, 41, 121)), 
                             reference_zone = 'comparison_nass.rast_zone_beo_lrmp_prod', 
                             percentage = c (100, 31, 64, 34, 70, 78, 36), ndt = as.integer (0), 
                             label = c ('White class 1', 'White class 5', 'White class 5', 'White class 7', 'White class 7', 'White class 9', 'White class 9'), 
                             multi_condition = as.character (''), 
                             denom = as.character (''), start = as.integer (0), stop = as.integer (0))

## Wildfire 
m <- c (1,0, 2,0, 3,0, 4,0, 6,0, 7,0, 8,0, 9,0, 10,0, 12,0, 17,0, 18,0, 19,0, 20,1)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
lu.wild <- raster::reclassify (lu.srmp, rclmat)
bec.wild <- lu.wild * bec.reclass
unique(getValues(bec.wild)) 
# contains BEC class 1 (no constraint), 7 (34% of the LU they are in > 100 y.o. and 70% of the LU  are in > 40 y.o) and 9 (78% of the LU they are in > 40 y.o. and 36% of the LU they are in > 120 y.o.)
m <- c (1,35, 7,36, 9,37)
rclmat <- matrix (m, ncol = 2, byrow = TRUE)
bec.wild.fin <- raster::reclassify (bec.wild, rclmat)
zone_beo_wild <- data.table (zoneid = as.integer (c(35, 36, 36, 37, 37)), 
                             type = c ('', 'ge', 'ge', 'ge', 'ge'),
                             variable = 'age', 
                             threshold = as.numeric ( c(41, 101, 41, 41, 121)), 
                             reference_zone = 'comparison_nass.rast_zone_beo_lrmp_prod', 
                             percentage = c (100, 34, 70, 78, 36), ndt = as.integer (0), 
                             label = c ('Wildfire class 1', 'Wildfire class 7', 'Wildfire class 7', 'Wildfire class 9', 'Wildfire class 9'), 
                             multi_condition = as.character (''), 
                             denom = as.character (''), start = as.integer (0), stop = as.integer (0))

## All zones together
zone_beo_lrmp <- Reduce (function(dtf1, dtf2) merge (dtf1, dtf2, all = TRUE), 
                               list (zone_beo_bear, zone_beo_bowser, zone_beo_brown, zone_beo_camb, zone_beo_green, zone_beo_kins, zone_beo_kwin, zone_beo_mad, zone_beo_nass, zone_beo_tchi, zone_beo_tint, zone_beo_white, zone_beo_wild))

rast.beo <- bec.bear.fin + bec.bowser.fin + bec.brown.fin + bec.camb.fin + bec.green.fin + bec.kins.fin + bec.kit.fin + bec.kwin.fin + bec.mad.fin + bec.nass.fin + bec.tchi.fin + bec.tint.fin + bec.white.fin + bec.wild.fin

## Multiply by productive forest
rast.beo.prod <- rast.beo * prod.for

## Upload data to db
crs(rast.beo) <- "+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs"
writeRaster(rast.beo, file = "beo.tif", format = "GTiff", overwrite = TRUE)
system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/beo.tif -t 100x100 comparison_nass.rast_zone_beo_lrmp | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)

crs(rast.beo.prod) <- "+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs"
writeRaster(rast.beo.prod, file = "beo_prod.tif", format = "GTiff", overwrite = TRUE)
system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/beo_prod.tif -t 100x100 comparison_nass.rast_zone_beo_lrmp_prod | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)

conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))
DBI::dbWriteTable(conn, c("comparison_nass", "zone_beo_lrmp"), value = zone_beo_lrmp, row.names = FALSE, overwrite = TRUE) 
dbExecute(conn, "ALTER TABLE comparison_nass.zone_beo_lrmp ALTER COLUMN denom TYPE VARCHAR;")
dbExecute (conn, paste0("ALTER TABLE comparison_nass.zone_beo_lrmp INHERIT comparison_nass.zone_constraints_nass"))

dbDisconnect(conn)

```


## IRMs

```{r, irm}

# max 35% below 3m tall
# constraint applies by LU, within THLB
thlb <- raster::raster (paste0 (data.dir, "gisData\\grids\\thlbContribution.tif")) / 10000
# values have been multiplied to make them 0 to 10,000; divide by 10,000 to make it a value 0 to 1
rast.irm <- raster::raster (paste0 (data.dir, "gisData\\grids\\IRMzone.tif")) 
rast.lu <- raster::raster (paste0 (data.dir, "gisData\\grids\\lu.tif")) 
# LU classes: 1:Bear  2:Bowser  3:BrownBear  4:CambriaIcefield  5:Craven  6:GreenvilleKalum  7:Kinskuch  8:Kiteen  9:Kwinamuck  10:Madely  11:Muskaboo  12:NassRiverKalum  13:Oweegee  14:Sallysout 15:SpatsiziRiver  16:TaylorDamdochax  17:Tchitin  18:Tintina  19:White  20:Wildfire
unique(getValues(rast.lu))

rast.lu.irm <- rast.irm * rast.lu
unique(getValues(rast.lu.irm))

zone_irm <- data.table (zoneid = as.integer (c(1:20)), 
                             type = 'ge',
                             variable = 'height', 
                             threshold = as.numeric (3), 
                             reference_zone = 'comparison_nass.rast_zone_irm_lu', 
                             percentage = 65, ndt = as.integer (0), 
                             label = c ('bear', 'bowser', 'brownbear', 'cambriaicefield', 'craven', 'greenvillekalum',
                                        'kinsuch', 'kiteen', 'kwinamuck', 'madely', 'muskaboo', 'nassriverkalum', 'oweegee',
                                        'sallysout', 'spatsiziriver', 'taylordamdochax', 'tchitin', 'tintina', 'white',
                                        'wildfire'), 
                             multi_condition = as.character (''), 
                             denom = as.character ('thlb > 0'), start = as.integer (0), stop = as.integer (0))

## Upload data to db
crs(rast.irm) <- "+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs"
writeRaster(rast.irm, file = "irm.tif", format = "GTiff", overwrite = TRUE)
system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/irm.tif -t 100x100 comparison_nass.rast_zone_irm | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)

crs(rast.lu.irm) <- "+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs"
writeRaster(rast.lu.irm, file = "irm_lu.tif", format = "GTiff", overwrite = TRUE)
system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/irm_lu.tif -t 100x100 comparison_nass.rast_zone_irm_lu | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)

conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))
DBI::dbWriteTable(conn, c("comparison_nass", "zone_irm_lu"), value = zone_irm, row.names = FALSE, overwrite = TRUE) 
dbExecute(conn, "ALTER TABLE comparison_nass.zone_irm_lu ALTER COLUMN denom TYPE VARCHAR;")
dbExecute (conn, paste0("ALTER TABLE comparison_nass.zone_irm_lu INHERIT comparison_nass.zone_constraints_nass"))

dbDisconnect(conn)

```




## VQO

```{r vqo}
# VQO's apply to productive forest and 'VQOold'

# vqoPvacL, vqoPvacM, vqoPvacH, vqoRvacL, vqoRvacM, vqoRvacH, vqoPRvacL, vqoPRvacM, vqoPRvacH, vqoMvacL, vqoMvacM, vqoMvacH



# don't know what 'productive forest' is, so multiply that area by the UWR area and use total area in CLUS
prod.for <- raster::raster (paste0 (data.dir, "gisData\\grids\\ProductiveForest.tif")) 

```

