---
title: "Partnership Agreement Raster"
author: "Kyle Lochhead"
date: "May 26, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(data.table)
source("C:/Users/KLOCHHEA/clus/R/functions/R_Postgres.R")
library(tidyverse)
prov.rast <- raster::raster(
  nrows = 15744, ncols = 17216, xmn = 159587.5, xmx = 1881187.5, ymn = 173787.5, ymx = 1748187.5, 
  crs = st_crs(getSpatialQuery("Select * from bc_carib_poly_20090904 limit 1"))$proj4string, resolution = c(100, 100), vals = 0)
```

## Purpose

The constraints as per the partnership agreement.

### 35% disturbance in A1, B1, B4 and B5
```{r, partnership}

partnership<-getSpatialQuery("SELECT * from mtn_caribou_pa_jan_2020;")
partnership[partnership$ogc_fid %in% c(3,4,7,8,9), ]$ogc_fid<-0

ras.partnership <-fasterize::fasterize(partnership, prov.rast, field = "ogc_fid")
writeRaster(ras.partnership , "raspartnership.tif", overwrite = TRUE)

zone.partnership<-rbindlist(list(data.table(zoneid =c(1,2,5,6), reference_zone = 'rast.zone_cond_partnership_agreement', ndt =0, variable ='dist', threshold = 500, type = 'ge', percentage =65),data.table(zoneid =0, reference_zone = 'rast.zone_cond_partnership_agreement', ndt =0, variable ='', threshold = 0, type = 'nh', percentage =0)))
zone.partnership<-zone.partnership[,zoneid:=as.integer(zoneid)]
zone.partnership<-zone.partnership[,ndt:=as.integer(ndt)]
zone.partnership<-zone.partnership[,threshold:=as.numeric(threshold)]

conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))

DBI::dbWriteTable(conn, c("public", paste0("zone_partnership_agreement")), value= zone.partnership, row.names = FALSE, overwrite = TRUE)
 dbExecute(conn, paste0("ALTER TABLE zone_partnership_agreement INHERIT zone_constraints"))
 dbDisconnect(conn)

#upload to db
  system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/raspartnership.tif -t 100x100', paste0(' rast.zone_cond_partnership_agreement'),' | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)


```

