---
title: "Proposed UWR"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(data.table)
source("C:/Users/KLOCHHEA/clus/R/functions/R_Postgres.R")
layeraoi<-getSpatialQuery("SELECT * FROM study_area_compart limit 1") #just need the projection string
prov.rast <- raster::raster(
  nrows = 15744, ncols = 17216, xmn = 159587.5, xmx = 1881187.5, ymn = 173787.5, ymx = 1748187.5, 
  crs = st_crs(layeraoi)$proj4string, resolution = c(100, 100), vals = 0)

```

## Proposed UWR

In this script, the rpoposed UWRs are formatted to be included as constraints in the CLUS.

```{r, whitesail}
prop.uwr<-st_read("C:/Users/klochhea/clus/CLUSshpExport/CLUSshpExport.shp")
prop.uwr<-st_transform(prop.uwr, 3005)

plot(prop.uwr)

#RAsterize 
ras.prop.uwr <-fasterize::fasterize(prop.uwr, prov.rast, field = "ID") 
raster::plot(ras.prop.uwr)
writeRaster(ras.prop.uwr, "prop_uwr.tif")

zone.uwr<-data.table(zoneid = as.integer(1), reference_zone='rast.proposed_uwr', variable = 'age', ndt= as.integer(0), threshold = as.numeric(40), type = 'le', percentage = as.numeric(18))


```
## Commit to postgreSQL
```{r, commit_db}

conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))

DBI::dbWriteTable(conn, c("public", "zone_proposed_uwr"), value= zone.uwr, row.names = FALSE, overwrite = TRUE)

#dbExecute(conn, "ALTER TABLE zone_vqo INHERIT zone_constraints")
dbDisconnect(conn)

#upload to db
system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/prop_uwr.tif -t 100x100 rast.proposed_uwr | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)
```

