---
title: "Rasterize Roads"
author: "Kyle Lochhead"
date: "July 30, 2019"
output: html_document
---

<!-- # Copyright 2018 Province of British Columbia
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(rpostgis)
library(raster)
source(paste0(here::here(),"/R/functions/R_Postgres.R"))
# Set up Provincial raster based on hectares BC extent, 1ha resolution and projection
prov.rast <- raster(
  nrows = 15744, ncols = 17216, xmn = 159587.5, xmx = 1881187.5, ymn = 173787.5, ymx = 1748187.5, 
  crs = 3005, resolution = c(100, 100), vals = 0
)

```

## Purpose

This code converts the line geometry of roads to raster form. Where each pixel value represents the presence of roads.

```{r, roads}
# Roads layers to make
# the key provincial-scale roads data source here is the cumulative effects program integrated roads data; public.integrated_roads
roads_sf_perm <- getSpatialQuery("SELECT shape,  -2  as road FROM public.integrated_roads_2021 where integrated_road_class_num <= 2 or (dra_road_name_full is not null AND dra_road_class <> 'trail');")
roads_sf <- getSpatialQuery("SELECT shape,  -1  as road FROM public.integrated_roads_2021 where integrated_road_class_num > 2")

# the above logic defines highways and roads with a name that are not trails as 'permanent' roads (-2), and all other roads types as non-permanent (-1)

# integrated_road_class_num definitions are below:
# class 1 = Highway/Arterial (freeway, highway, arterial, collector, ramp, yield )
# class 2 = Primary - Paved (local, resource, strata, alleyway, lane, driveway)
# class 3 = Secondary, FSR, Local (FSR, Local, service, recreational, resource, OGC long-term all weather)
# class 4 = Tertiary, Other (permit roads, in-block, restricted, proposed, seasonal, overgrown, decommissioned, trail, runway) 


# other data sources may be used; Cariboo_Consolidated_Roads
roads_sf_perm <- getSpatialQuery("SELECT shape,  -2  as road FROM public.cariboo_consolidated_roads where TRANSPORT_LINE_SURFACE_CODE = 'P' or (STRUCTURED_NAME_1 is not null AND TRANSPORT_LINE_TYPE_CODE <> 'TRL');")
roads_sf <- getSpatialQuery("SELECT shape,  -1  as road FROM public.cariboo_consolidated_roads where TRANSPORT_LINE_SURFACE_CODE <> 'P'")
# above queries follow the same logic as with integrated_roads

#Buffer the MULTILINESTRINGS
roads_sf_perm<-roads_sf_perm %>% st_buffer(dist = 51)
roads_sf<-roads_sf %>% st_buffer(dist = 51)

#Rasterize
road_perm<-fasterize::fasterize(st_cast(roads_sf_perm, "MULTIPOLYGON"), prov.rast, field = "road")
road_perm[is.na(road_perm[])]<-0

road<-fasterize::fasterize(st_cast(roads_sf, "MULTIPOLYGON"), prov.rast, field = "road")
road[is.na(road[])]<-0

out_road<-road_perm + road
out_road[out_road[] < -2]<- -2
writeRaster(out_road, "ce_road_class_2022.tif", overwrite = TRUE)

#upload to db
#system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/ften_road.tif -t 100x100 rast.rds_ften | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)

```

## Create a distance raster

```{r, dist_to}

library(raster)
library(data.table)


out_road<-raster("ce_road_class_2022.tif")
pixels <- data.table(c(t(raster::as.matrix(out_road)))) 
pixels <- pixels[, pixelid := seq_len(.N)][V1 < 0, ]
        
outPts <- data.table(xyFromCell(out_road,pixels$pixelid))

mill_sinks<-data.table(read.csv("mill_locations_2023.csv", sep =","))

dist<-RANN::nn2(mill_sinks[, c('xcoord', 'ycoord')], 
                       outPts[, c('x', 'y')], 
                       k = 1)
pixels$dist<-dist$nn.dists

out_road[pixels$pixelid]<-pixels$dist
writeRaster(out_road, "ce_road_dists_2022.tif")
 
```

## create road input

```{r }
library(raster)
library(data.table)

road.dists<-raster("ce_road_dists_2022.tif")
road.class<-raster("ce_road_class_2022.tif")

#reclass the road class
road.class[road.class[]==0]<-NA
road.class[road.class[] == -2] <- 0
road.class[road.class[] == -1] <- 1

road.dists[road.dists[]==0]<-NA

road.out<-road.class*road.dists
writeRaster(road.out, "ce_road_2022.tif", overwrite =T)

#system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/road_clus.tif -t 100x100 rast.rds_cariboo_2022 | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)
```