---
title: "Study Area Boundaries"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("R/functions/R_Postgres.R"))
library(data.table)
library(sf)
library(tidyverse)
library(rgeos)
layeraoi<-getSpatialQuery("SELECT * FROM study_area_compart limit 1")
#Create a provincial raster
prov.rast <- raster::raster(
  nrows = 15744, ncols = 17216, xmn = 159587.5, xmx = 1881187.5, ymn = 173787.5, ymx = 1748187.5, 
  crs = st_crs(layeraoi)$proj4string, resolution = c(100, 100), vals = 0)

```
# get data
```{r, data4}
forest.tenure<-getSpatialQuery("SELECT tsa_name, wkb_geometry FROM study_area_compart where tsa_name in ('Quesnel TSA', 'Lakes TSA', 'Morice TSA', 'Bulkley TSA', 'Williams Lake TSA', 'Kamloops TSA', '100 Mile House TSA', 'Golden TSA', 'Revelstoke TSA', 'Okanagan TSA', 'Kootenay Lake TSA', 'Invermere TSA', 'Cranbrook TSA', 'Arrow TSA', 'Dawson Creek TSA', 'Robson Valley TSA') or tsb_number in ('24C', '24D','24E','24F','24G','24H','24I', '16A', '16B', '16C', '16D', '16E', '16F', '16G', '16H', '16I', '16J', '16K', '16P')")

forest.tenure2<-forest.tenure %>% group_by ( tsa_name) %>% summarise()
st_crs(forest.tenure2)
plot(forest.tenure2["tsa_name"]) #check 

#Spatial partitions
pg_north<-getSpatialQuery("SELECT tsa_name, wkb_geometry FROM study_area_compart where tsb_number in ('24A', '24B')")
pg_north$tsa_name<-"Prince George North TSA"
pg_north<- pg_north %>% group_by (tsa_name) %>% summarise()
st_crs(pg_north)

fort_st_john_core<-sf::st_read("//spatialfiles2.bcgov/work/FOR/VIC/HTS/ANA/Workarea/dstuart/TSA40_FtStJohn/SENSITIVITIES/GeographicPartition/Core_ForLegal/TSA40_Core_shapes/TSA40_core.shp")
fort_st_john_core$tsa_name<-"Fort St John Core TSA"
fort_st_john_core<- fort_st_john_core %>% group_by (tsa_name) %>% summarise()
st_crs(fort_st_john_core)<-st_crs(pg_north)
names(fort_st_john_core)<-c("tsa_name", "wkb_geometry")
st_geometry(fort_st_john_core) <- "wkb_geometry"
plot(fort_st_john_core["tsa_name"]) 

fort_st_john <-sf::st_read("//spatialfiles2.bcgov/work/FOR/VIC/HTS/ANA/Workarea/dstuart/TSA40_FtStJohn/SENSITIVITIES/GeographicPartition/Core_ForLegal/TSA40_Core_shapes/iLU_TSA40_.shp", query = "SELECT * FROM \"iLU_TSA40_\" where c_p =2")
fort_st_john$tsa_name <- "Fort St John TSA"
fort_st_john <- fort_st_john  %>% group_by (tsa_name) %>% summarise()
st_crs(fort_st_john)<-st_crs(pg_north)
names(fort_st_john)<-c("tsa_name", "wkb_geometry")
st_geometry(fort_st_john) <- "wkb_geometry"
plot(fort_st_john["tsa_name"]) 

cascadia_toc<-getSpatialQuery("SELECT tsa_name, wkb_geometry FROM study_area_compart where tsb_number in ('45O')")
cascadia_toc$tsa_name<-'Cascadia TOC TSA'
cascadia_toc<-cascadia_toc %>% group_by (tsa_name) %>% summarise()

cascadia_tko<-getSpatialQuery("SELECT tsa_name, wkb_geometry FROM study_area_compart where tsb_number in ('45K', '45K1', '45K2')")
cascadia_tko$tsa_name<-'Cascadia TKO TSA'
cascadia_tko<- cascadia_tko%>% group_by (tsa_name) %>% summarise()

cascadia_tcc<-getSpatialQuery("SELECT tsa_name, wkb_geometry FROM study_area_compart where tsb_number in ('45C5','45C6','45C7','45C8')")
cascadia_tcc$tsa_name<-'Cascadia TCC TSA'
cascadia_tcc<- cascadia_tcc %>% group_by (tsa_name) %>% summarise()

mackenzie_sw <-getSpatialQuery("SELECT tsa_name, wkb_geometry FROM study_area_compart where tsb_number in ('16L', '16O', '16M', '16N')")
mackenzie_sw$tsa_name<-'MacKenzie SW TSA'
mackenzie_sw <-mackenzie_sw %>% group_by (tsa_name) %>% summarise()
st_crs(mackenzie_sw)

###TFLs
tfl <-getSpatialQuery("SELECT for_fl_id as tsa_name, wkb_geometry FROM tfl_all_polygon")
tfl<-tfl%>% group_by (tsa_name) %>% summarise()
st_crs(tfl)<-st_crs(pg_north)
plot(tfl["tsa_name"]) 

###GBR TSA's
#TSA boundary data was taken from https://www2.gov.bc.ca/gov/content/industry/crown-land-water/land-use-planning/regions/west-coast/great-bear-rainforest/great-bear-rainforest-legal-direction-agreements

# GBR North
gbr_north<-sf::st_read("//spatialfiles2.bcgov/work/FOR/VIC/HTS/ANA/Workarea/ekleynhans/GBRO_ScheduleShapefiles_20160120/GBRSchB_CNC_20160104.shp")
gbr_north$tsa_name<-"Great Bear Rainforest North TSA"
gbr_north<- gbr_north %>% group_by (tsa_name) %>% summarise()
st_crs(gbr_north)<-st_crs(pg_north)
names(gbr_north)<-c("tsa_name", "wkb_geometry")
st_geometry(gbr_north) <- "wkb_geometry"

# Now removing the tfl's out of GBR
tfl_union<-st_union(tfl)
tfl2<-st_intersection(tfl_union, gbr_north)
gbr_north2<-st_difference(gbr_north,tfl2)
plot(gbr_north2)

#GBR South
gbr_south<-sf::st_read("//spatialfiles2.bcgov/work/FOR/VIC/HTS/ANA/Workarea/ekleynhans/GBRO_ScheduleShapefiles_20160120/GBRSchC_SCC_20151105.shp")
gbr_south$tsa_name<-"Great Bear Rainforest South TSA"
gbr_south<- gbr_south %>% group_by (tsa_name) %>% summarise()
st_crs(gbr_south)<-st_crs(pg_north)
names(gbr_south)<-c("tsa_name", "wkb_geometry")
st_geometry(gbr_south) <- "wkb_geometry"

# Now removing the tfl's out of GBR
tfl3<-st_intersection(tfl_union, gbr_south)
gbr_south2<-st_difference(gbr_south,tfl3)
plot(gbr_south2)


```

#Combine them into one dataset
```{r, mergethem}

forest.tenure3<-rbind(forest.tenure2, pg_north, mackenzie_sw, fort_st_john, fort_st_john_core, cascadia_tcc, cascadia_toc, cascadia_tko, tfl) 

forest.tenure.vat<-unique(forest.tenure3$tsa_name)
forest.tenure.vat2<-unlist(lapply(forest.tenure.vat, function(x){
  gsub( " ", "_", x)
}), use.names = FALSE)
forest.tenure.vat3<-data.table(cbind(forest.tenure.vat, forest.tenure.vat2))
setnames(forest.tenure.vat3, c("tsa_name", "tsa_name2"))
forest.tenure.vat3<-forest.tenure.vat3[,value:=seq_len(.N)]
forest.tenure4<-merge(forest.tenure3,forest.tenure.vat3)

#get ride of the tsa_name -- its sperated by spaces
forest.tenure4$tsa_name<-NULL
setnames(forest.tenure4, c("tsa_name2"), c("tsa_name"))

#Call value tsa_number
forest.tenure5<-forest.tenure4
setnames(forest.tenure5, c("value"), c("tsa_number"))
st_write(forest.tenure5, "forest_tenures_GBR.shp", delete_layer=TRUE)
#ogr2ogr -f PostgreSQL PG:"dbname=clus port = 5432 user=postgres password=postgres" C:\Users\klochhea\clus\R\Params\forest_tenures.shp -overwrite -a_srs EPSG:3005 -progress --config PG_USE_COPY YES -nlt PROMOTE_TO_MULTI
#Alter table forest_ten rename to tsa_aac_bounds;
#GRANT ALL ON TABLE public.tsa_aac_bounds TO postgres;
#GRANT ALL ON TABLE public.tsa_aac_bounds TO clus_project;
#GRANT ALL ON TABLE public.tsa_aac_bounds TO tmuhly;


conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))

DBI::dbWriteTable(conn, c("public", "tsa_aac_bounds_GBR"), value= forest.tenure5, row.names = FALSE, overwrite = TRUE) 

dbDisconnect(conn)


#RAsterize 
ras.forest.tenure <-fasterize::fasterize(st_cast(forest.tenure4, "MULTIPOLYGON"), prov.rast, field = "tsa_number") 
raster::plot(ras.forest.tenure)
writeRaster(ras.forest.tenure, "forest_ten_GBR.tif")

```

## Commit to postgreSQL
```{r, commit_db}

conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))

forest.tenure.vat3$tsa_name<-NULL
setnames(forest.tenure.vat3, c("tsa_name2"), c("tsa_name"))
DBI::dbWriteTable(conn, c("public", "tsa_aac_bounds_vat_GBR"), value= forest.tenure.vat3, row.names = FALSE, overwrite = TRUE)

#dbExecute(conn, "ALTER TABLE zone_vqo INHERIT zone_constraints")
dbDisconnect(conn)

#upload to db
system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/forest_ten_GBR.tif -t 100x100 rast.tsa_aac_boundary_GBR | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)
```

