---
title: "Study Area Boundaries"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("C:/Users/KLOCHHEA/clus/R/functions/R_Postgres.R")
library(data.table)
library(sf)
library(tidyverse)
layeraoi<-getSpatialQuery("SELECT * FROM study_area_compart limit 1")
#Create a provincial raster
prov.rast <- raster::raster(
  nrows = 15744, ncols = 17216, xmn = 159587.5, xmx = 1881187.5, ymn = 173787.5, ymx = 1748187.5, 
  crs = st_crs(layeraoi)$proj4string, resolution = c(100, 100), vals = 0)


forest.tenure<-getSpatialQuery("SELECT tsb_number, tsa_number, tsa_name, wkb_geometry FROM study_area_compart where tsa_name in ('Quesnel TSA', 'Lakes TSA') or tsb_number in ('24C', '24D','24E','24F','24G','24H','24I')")
plot(forest.tenure)
forest.tenure2<-forest.tenure %>% group_by (tsa_number, tsa_name) %>% summarise()
st_crs(forest.tenure2)

st_write(forest.tenure2, "forest_ten.shp", delete_layer=TRUE)
#ogr2ogr -f PostgreSQL PG:"dbname=clus port = 5432 user=klochhea" C:\Users\klochhea\clus\R\Params\forest_ten.shp -overwrite -a_srs EPSG:3005 -progress --config PG_USE_COPY YES -nlt PROMOTE_TO_MULTI
#Alter table forest_ten rename to tsa_area_bounds;
#GRANT ALL ON TABLE public.tsa_area_bounds TO postgres;
#GRANT ALL ON TABLE public.tsa_area_bounds TO clus_project;
#GRANT ALL ON TABLE public.tsa_area_bounds TO tmuhly;


#RAsterize 
ras.forest.tenure <-fasterize::fasterize(st_cast(forest.tenure2, "MULTIPOLYGON"), prov.rast, field = "tsa_number") 
raster::plot(ras.forest.tenure)
writeRaster(ras.forest.tenure, "forest_ten.tif")

st_geometry(forest.tenure2) <- NULL
forest.tenure2<-data.table(forest.tenure2)
forest.tenure2<-forest.tenure2[,value:=tsa_number]
forest.tenure2<-forest.tenure2[,tsa_number:=NULL]

```

## Commit to postgreSQL
```{r, commit_db}

conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))

DBI::dbWriteTable(conn, c("public", "tsa_area_bounds_vat"), value= forest.tenure2, row.names = FALSE, overwrite = TRUE)

#dbExecute(conn, "ALTER TABLE zone_vqo INHERIT zone_constraints")
dbDisconnect(conn)

#upload to db
system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/forest_ten.tif -t 100x100 rast.tsa_area_bounds_r | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)
```

