---
title: "tipsy curves"
author: "Kyle Lochhead"
date: "July 24, 2019"
output: html_document
---
## TIPSY CURVES USING WILDLIFE REPORT
```{r setup, include=FALSE, eval = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
source("C:/Users/KLOCHHEA/clus/R/functions/R_Postgres.R")
meta_tbl<-read.table("D:/Data/TIPSY/2020/MSYT_prov_reference.csv", sep= ",", header = TRUE)
colnames(meta_tbl)<-tolower(colnames(meta_tbl))

current_tbl<-read.table("D:/Data/TIPSY/2020/MSYT_prov_current_input_output.csv", sep= ",", header = FALSE,nrows = 5000)
names(current_tbl)<-c("feature_id,", "stand1", "stand2", "year", "height", " vol_gross", "vol_conifer", "basal_area", "qmd", "sph", "vpt", "crown_closure", "vol_dec", "tvol")

future_tbl<-read.table("D:/Data/TIPSY/2020/MSYT_prov_future_input_output.csv", sep= ",", header = FALSE,nrows = 5000)
names(future_tbl)<-c("feature_id,", "stand1", "stand2", "year", "height", " vol_gross", "vol_conifer", "basal_area", "qmd", "sph", "vpt", "crown_closure", "vol_dec", "tvol")

future_logged_tbl<-read.table("D:/Data/TIPSY/2020/MSYT_prov_future_logged_vdyp_input_output.csv", sep= ",", header = FALSE,nrows = 5000)
names(future_logged_tbl)<-c("feature_id,", "stand1", "stand2", "year", "height", " vol_gross", "vol_conifer", "basal_area", "qmd", "sph", "vpt", "crown_closure", "vol_dec", "tvol")

conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))

DBI::dbWriteTable(conn, c("public", "tipsy_meta_2020"), value= meta_tbl, row.names = FALSE, overwrite = TRUE) 
DBI::dbWriteTable(conn, c("public", "tipsy_future_2020"), value= future_tbl, row.names = FALSE, overwrite = TRUE)
dbDisconnect(conn)
## Renamed table to tipsy_prov_2020
cmd <- paste0("\\copy tipsy_prov_2020 from program 'cmd /c \"type D:\\Data\\TIPSY\\2020\\MSYT_prov_future_input_output.csv" , "\"' delimiter ',' csv header")
cmd <- shQuote(cmd)
system2("psql",args=c('-d clus -c',cmd),wait=TRUE,stderr=TRUE)

## REnameed to tipsy_current_prov_2020
cmd <- paste0("\\copy tipsy_current_prov_2020 from program 'cmd /c \"type D:\\Data\\TIPSY\\2020\\MSYT_prov_current_input_output.csv" , "\"' delimiter ',' csv header")
cmd <- shQuote(cmd)
system2("psql",args=c('-d clus -c',cmd),wait=TRUE,stderr=TRUE)

```



##OLD
```{r setup, include=FALSE, eval = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
source("C:/Users/KLOCHHEA/clus/R/functions/R_Postgres.R")

#input layer table
input_tbl<-read.table("S:/ANA/PROJECTS/CLUS/Data/TIPSY/prov/tipsy_vols_prov.csv", sep= ",", header = TRUE,nrows = 5000)
colnames(input_tbl)<-tolower(colnames(input_tbl))

ht_tbl<-read.table("S:/ANA/PROJECTS/CLUS/Data/TIPSY/prov/tipsy_heights_prov/tipsy_heights_prov.csv", sep= ",", header = TRUE,nrows = 5000)
colnames(ht_tbl)<-tolower(colnames(ht_tbl))

conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))

DBI::dbWriteTable(conn, c("public", "tipsy_prov"), value= input_tbl, row.names = FALSE, overwrite = TRUE) 
DBI::dbWriteTable(conn, c("public", "tipsy_ht_prov"), value= ht_tbl, row.names = FALSE, overwrite = TRUE)
dbDisconnect(conn)
```


## Commit to postgres
```{r, load_output, eval = FALSE}
cmd <- paste0("\\copy tipsy_prov from program 'cmd /c \"type F:\\Data\\tipsy_vols_prov.csv" , "\"' delimiter ',' csv header")
cmd <- shQuote(cmd)
system2("psql",args=c('-d clus -c',cmd),wait=TRUE,stderr=TRUE)

cmd <- paste0("\\copy tipsy_ht_prov from program 'cmd /c \"type F:\\Data\\tipsy_heights_prov.csv" , "\"' delimiter ',' csv header")
cmd <- shQuote(cmd)
system2("psql",args=c('-d clus -c',cmd),wait=TRUE,stderr=TRUE)

```

## Spatialize the TIPSY curve ids

```{r, tipsy}

vri.ras<-raster(paste0(here::here(),"/R/params/vri_id2018.tif"))

```