---
title: "Study Area Boundaries"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("R/functions/R_Postgres.R"))
library(data.table)
library(sf)
library(tidyverse)
library(rgeos)
layeraoi<-getSpatialQuery("SELECT * FROM study_area_compart limit 1")
#Create a provincial raster
prov.rast <- raster::raster(
  nrows = 15744, ncols = 17216, xmn = 159587.5, xmx = 1881187.5, ymn = 173787.5, ymx = 1748187.5, 
  crs = st_crs(layeraoi)$proj4string, resolution = c(100, 100), vals = 0)

```
# get data
```{r, data4}
forest.tenure<-getSpatialQuery("SELECT tsa_name, wkb_geometry FROM study_area_compart where tsa_name in ('Quesnel TSA', 'Lakes TSA', 'Morice TSA', 'Bulkley TSA', 'Williams Lake TSA', 'Kamloops TSA', '100 Mile House TSA', 'Golden TSA', 'Revelstoke TSA', 'Okanagan TSA', 'Kootenay Lake TSA', 'Invermere TSA', 'Cranbrook TSA', 'Arrow TSA', 'Dawson Creek TSA', 'Robson Valley TSA') or tsb_number in ('24C', '24D','24E','24F','24G','24H','24I', '16A', '16B', '16C', '16D', '16E', '16F', '16G', '16H', '16I', '16J', '16K', '16P')")

forest.tenure2<-forest.tenure %>% group_by ( tsa_name) %>% summarise()
st_crs(forest.tenure2)
plot(forest.tenure2["tsa_name"]) #check 


###TFLs
tfl <-getSpatialQuery("SELECT for_fl_id as tsa_name, wkb_geometry FROM tfl_all_polygon")
tfl<-tfl%>% group_by (tsa_name) %>% summarise()
st_crs(tfl)<-st_crs(forest.tenure2)
plot(tfl["tsa_name"]) 

###GBR TSA's
#TSA boundary data was taken from https://www2.gov.bc.ca/gov/content/industry/crown-land-water/land-use-planning/regions/west-coast/great-bear-rainforest/great-bear-rainforest-legal-direction-agreements

# GBR North
gbr_north<-sf::st_read("//spatialfiles2.bcgov/work/FOR/VIC/HTS/ANA/Workarea/ekleynhans/GBRO_ScheduleShapefiles_20160120/GBRSchB_CNC_20160104.shp")
gbr_north$tsa_name<-"Great Bear Rainforest North TSA"
gbr_north<- gbr_north %>% group_by (tsa_name) %>% summarise()
st_crs(gbr_north)<-st_crs(forest.tenure2)
names(gbr_north)<-c("tsa_name", "wkb_geometry")
st_geometry(gbr_north) <- "wkb_geometry"

# Now removing the tfl's out of GBR North
tfl_union<-st_union(tfl)
tfl2<-st_intersection(tfl_union, gbr_north)
gbr_north2<-st_difference(gbr_north,tfl2)
plot(gbr_north2)

#GBR South
gbr_south<-sf::st_read("//spatialfiles2.bcgov/work/FOR/VIC/HTS/ANA/Workarea/ekleynhans/GBRO_ScheduleShapefiles_20160120/GBRSchC_SCC_20151105.shp")
gbr_south$tsa_name<-"Great Bear Rainforest South TSA"
gbr_south<- gbr_south %>% group_by (tsa_name) %>% summarise()
st_crs(gbr_south)<-st_crs(forest.tenure2)
names(gbr_south)<-c("tsa_name", "wkb_geometry")
st_geometry(gbr_south) <- "wkb_geometry"

# Now removing the tfl's out of GBR South
tfl3<-st_intersection(tfl_union, gbr_south)
gbr_south2<-st_difference(gbr_south,tfl3)
plot(gbr_south2)

# looks mostly good when checked against https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/forestry/timber-tenures/tfl_tsa_district_map.pdf

# UBC GBR study boundary
aoi<-getSpatialQuery("SELECT ogc_fid, retention , wkb_geometry FROM public.ssg_retention_thlb_dslv")
aoi$tsa_name<- "UBC study boundary"

aoi2<-aoi %>% group_by (tsa_name) %>% summarise()
aoi3<- st_buffer(aoi2,0)
st_crs(aoi3)<-st_crs(forest.tenure2)
names(aoi3)<-c("tsa_name", "wkb_geometry")
st_geometry(aoi3) <- "wkb_geometry"
st_is_valid(aoi3)

plot(aoi3) #check 
aoi$tsa_number<-1

aoi_rast <-fasterize::fasterize(st_cast(aoi3, "MULTIPOLYGON"), prov.rast) 
```
#Combine them into one dataset
```{r, mergethem}

forest.tenure3<-rbind(forest.tenure2, tfl, aoi3) 

forest.tenure.vat<-unique(forest.tenure3$tsa_name)
forest.tenure.vat2<-unlist(lapply(forest.tenure.vat, function(x){
  gsub( " ", "_", x)
}), use.names = FALSE)
forest.tenure.vat3<-data.table(cbind(forest.tenure.vat, forest.tenure.vat2))
setnames(forest.tenure.vat3, c("tsa_name", "tsa_name2"))
forest.tenure.vat3<-forest.tenure.vat3[,value:=seq_len(.N)]
forest.tenure4<-merge(forest.tenure3,forest.tenure.vat3)

#get rid of the tsa_name -- its separated by spaces
forest.tenure4$tsa_name<-NULL
setnames(forest.tenure4, c("tsa_name2", "geometry"), c("tsa_name", "wkb_geometry"))
st_geometry(forest.tenure4) <- "wkb_geometry"
plot(forest.tenure4[52,])


#Call value tsa_number
forest.tenure5<-forest.tenure4
setnames(forest.tenure5, c("value"), c("tsa_number"))
st_write(forest.tenure5, "ubc_gbr_boundaries.shp", delete_layer=TRUE)

# commit the shape file to postgres
# this works for loading the shape file onto Kyles Postgres. Run these sections of code below in R and fill in the details in the script for command prompt. Then run the ogr2ogr script in command prompt to get the table into postgres

host=keyring::key_get('dbhost', keyring = 'postgreSQL')
user=keyring::key_get('dbuser', keyring = 'postgreSQL')
dbname=keyring::key_get('dbname', keyring = 'postgreSQL')
password=keyring::key_get('dbpass', keyring = 'postgreSQL')

ogr2ogr -f "PostgreSQL" PG:"host= user= dbname= password= port=5432" C:\\Work\\caribou\\clus\\R\\Params\\ubc_gbr_boundaries.shp -overwrite -a_srs EPSG:3005 -progress --config PG_USE_COPY YES -nlt PROMOTE_TO_MULTI

# In PGAdmin run these lines of code to alter the table i.e. change its name and grant permissions
# Alter table forest_ten rename to tsa_aac_bounds_gbr;
# GRANT ALL ON TABLE public.tsa_aac_bounds_gbr TO postgres;
# GRANT ALL ON TABLE public.tsa_aac_bounds_gbr TO clus_project;
# GRANT ALL ON TABLE public.tsa_aac_bounds_gbr TO tmuhly;
# GRANT ALL ON TABLE public.tsa_aac_bounds_gbr TO ekleynha;
# GRANT ALL ON TABLE public.tsa_aac_bounds_gbr TO klochhea;



#RAsterize 
ras.forest.tenure <-fasterize::fasterize(st_cast(forest.tenure4, "MULTIPOLYGON"), prov.rast, field = "tsa_number") 
raster::plot(ras.forest.tenure)
writeRaster(ras.forest.tenure, "ubc_gbr_boundaries.tif", overwrite=TRUE)

ras.forest.tenure_crop <- crop(aoi_rast,ras.forest.tenure )
plot(ras.forest.tenure_crop, col="black")



```

## Commit to postgreSQL
```{r, commit_db}

conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))

forest.tenure.vat3$tsa_name<-NULL
setnames(forest.tenure.vat3, c("tsa_name2"), c("tsa_name"))
DBI::dbWriteTable(conn, c("public", "ubc_gbr_boundaries_vat"), value= forest.tenure.vat3, row.names = FALSE, overwrite = TRUE)

#dbExecute(conn, "ALTER TABLE zone_vqo INHERIT zone_constraints")
dbDisconnect(conn)

#upload to db
system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/ubc_gbr_boundaries.tif -t 100x100 rast.ubc_gbr_boundaries | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)
```




# get data
```{r, data4}
aoi<-getSpatialQuery("SELECT ogc_fid, retention , wkb_geometry FROM public.ssg_retention_thlb_dslv")
aoi$grouping<- 1
aoi$aoi_name<-"gbr_ubc_study_boundary"

aoi2<-aoi %>% group_by (grouping) %>% summarise()
st_crs(aoi2)
plot(aoi2) #check 

aoi2$aoi_name<- "gbr_ubc_study_boundary"
aoi2$grouping<- NULL
st_geometry(aoi2) <- "wkb_geometry"
st_write(aoi2, "ubc_gbr.shp", delete_layer=TRUE)

# commit the shape file to postgres
# this works for loading the shape file onto Kyles Postgres. Run these sections of code below in R and fill in the details in the script for command prompt. Then run the ogr2ogr script in command prompt to get the table into postgres

host=keyring::key_get('dbhost', keyring = 'postgreSQL')
user=keyring::key_get('dbuser', keyring = 'postgreSQL')
dbname=keyring::key_get('dbname', keyring = 'postgreSQL')
password=keyring::key_get('dbpass', keyring = 'postgreSQL')



ogr2ogr -f "PostgreSQL" PG:"host= user= dbname= password= port=5432" C:\Work\caribou\clus\R\Params\ubc_gbr.shp -overwrite -a_srs EPSG:3005 -progress --config PG_USE_COPY YES -nlt PROMOTE_TO_MULTI

# In PGAdmin run these lines of code to alter the table i.e. change its name and grant permissions
# Alter table forest_ten rename to tsa_aac_bounds_gbr;
# GRANT ALL ON TABLE public.tsa_aac_bounds_gbr TO postgres;
# GRANT ALL ON TABLE public.tsa_aac_bounds_gbr TO clus_project;
# GRANT ALL ON TABLE public.tsa_aac_bounds_gbr TO tmuhly;
# GRANT ALL ON TABLE public.tsa_aac_bounds_gbr TO ekleynha;
# GRANT ALL ON TABLE public.tsa_aac_bounds_gbr TO klochhea;



#RAsterize 
ubc.aoi <-fasterize::fasterize(st_cast(aoi2, "MULTIPOLYGON"), prov.rast) 
raster::plot(ubc.aoi)
writeRaster(ubc.aoi, "ubc_gbr.tif", overwrite=TRUE)

```


## Commit to postgreSQL
```{r, commit_db}

conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))


DBI::dbWriteTable(conn, c("public", "ubc_gbr_vat"), value= aoi2, row.names = FALSE, overwrite = TRUE)

#dbExecute(conn, "ALTER TABLE zone_vqo INHERIT zone_constraints")
dbDisconnect(conn)

#upload to db
 system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/ubc_gbr.tif -t 100x100 rast.ubc_gbr | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)
```

