---
title: "vdyp curves"
author: "Kyle Lochhead"
date: "July 24, 2019"
output: html_document
---

```{r setup, include=FALSE, eval = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
source("C:/Users/KLOCHHEA/clus/R/functions/R_Postgres.R")

#input layer table
input_tbl<-read.table(paste0(here::here(),"/VDYP/VRI2018/VEG_COMP_VDYP7_INPUT_LAYER_TBL_2019.csv"), sep= ",", header = TRUE, nrows = 5000)
colnames(input_tbl)<-tolower(colnames(input_tbl))
conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))

#DBI::dbWriteTable(conn, c("public", "vdyp_input_layer"), value= input_tbl, row.names = FALSE, overwrite = TRUE) 
dbDisconnect(conn)

#input poly table
input_poly<-read.table(paste0(here::here(),"/VDYP/VRI2018/VEG_COMP_VDYP7_INPUT_POLY_TBL_2019.csv"), sep= ",", header = TRUE, nrows = 5000)
colnames(input_poly)<-tolower(colnames(input_poly))
conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))

#DBI::dbWriteTable(conn, c("public", "vdyp_input_layer"), value= input_poly, row.names = FALSE, overwrite = TRUE) 
dbDisconnect(conn)


#output table
output_tbl<-read.table(paste0(here::here(),"/VDYP/VRI2018/output_125.csv"), sep= ",", header = TRUE, nrows = 5000)
colnames(output_tbl)<-tolower(colnames(output_tbl))
conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))

#DBI::dbWriteTable(conn, c("public", "vdyp_output"), value= output_tbl, row.names = FALSE, overwrite = TRUE) 
dbDisconnect(conn)

#error table - make as 
#CREATE TABLE public.vdyp_error
#(
#    error text COLLATE pg_catalog."default"
#)
#WITH (
##    OIDS = FALSE
#)
#TABLESPACE pg_default;

#ALTER TABLE public.vdyp_error
#    OWNER to clus_project;
#
#GRANT ALL ON TABLE public.vdyp_error TO clus_project;
    
```


## Commit to postgres
```{r, load_output, eval = FALSE}
cmd <- paste0("\\copy vdyp_input_poly_2020 from program 'cmd /c \"type D:\\Data\\VDYP\\2020\\VEG_COMP_VDYP7_INPUT_POLY_TBL_2020.csv" , "\"' delimiter ',' csv header")
cmd <- shQuote(cmd)
system2("psql",args=c('-d clus -c',cmd),wait=TRUE,stderr=TRUE)

cmd <- paste0("\\copy vdyp_input_layer_2020 from program 'cmd /c \"type D:\\Data\\VDYP\\2020\\VEG_COMP_VDYP7_INPUT_LAYER_TBL_2020.csv" , "\"' delimiter ',' csv header")
cmd <- shQuote(cmd)
system2("psql",args=c('-d clus -c',cmd),wait=TRUE,stderr=TRUE)

cmd <- paste0("\\copy vdyp_output_2020 from program 'cmd /c \"type D:\\Data\\VDYP\\2020\\output_125.csv" , "\"' csv header")
cmd <- shQuote(cmd)
system2("psql",args=c('-d clus -c',cmd),wait=TRUE,stderr=TRUE)

cmd <- paste0("\\copy vdyp_error from program 'cmd /c \"type E:\\Data\\error_125.txt" , "\"' ")
cmd <- shQuote(cmd)
system2("psql",args=c('-d clus -c',cmd),wait=TRUE,stderr=TRUE)


```

## HBS

```{r, hbs_data, eval = FALSE}
tbl<-read.table(paste0(here::here(), "/VDYP/hbs_data.csv"), sep= ",", header = TRUE, nrows = 50 )
colnames(tbl)<-tolower(colnames(tbl))
conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))
DBI::dbWriteTable(conn, c("public", "vdyp_hbsr"), value= tbl, row.names = FALSE, overwrite = TRUE) 
dbDisconnect(conn)


cmd <- paste0("\\copy vdyp_hbs from program 'cmd /c \"type E:\\Data\\VDYP\\hbs_data.csv" , "\"' csv header")
cmd <- shQuote(cmd)
system2("psql",args=c('-d clus -c',cmd),wait=TRUE,stderr=TRUE)

```


## Create raster of yield ids from yc_grp
```{r, yld_raster, eval = FALSE}
vri<-data.table(getSpatialQuery("SELECT yc_grp, geometry FROM vdyp_vri2018 where yc_grp IS NOt NULL"))
lu_table<-data.table(getTableQuery("SELECT distinct(yc_grp) FROM vdyp_test3 ORDER by yc_grp;"))
lu_table[,ycid:= seq_len(.N)]
lu_table[,ycid := ycid*-1]

colnames(lu_table)<-tolower(colnames(lu_table))
conn<-DBI::dbConnect(dbDriver("PostgreSQL"), host=keyring::key_get('dbhost', keyring = 'postgreSQL'), dbname = keyring::key_get('dbname', keyring = 'postgreSQL'), port='5432' ,user=keyring::key_get('dbuser', keyring = 'postgreSQL') ,password= keyring::key_get('dbpass', keyring = 'postgreSQL'))
DBI::dbWriteTable(conn, c("public", "yc_vdyp_vat"), value= lu_table, row.names = FALSE, overwrite = TRUE) 
dbDisconnect(conn)

vri<-merge(vri, lu_table, by.x = 'yc_grp', by.y = 'yc_grp', all.x = TRUE)
ProvRast <- raster(
  nrows = 15744, ncols = 17216, xmn = 159587.5, xmx = 1881187.5, ymn = 173787.5, ymx = 1748187.5, 
  crs = st_crs(getSpatialQuery("SELECT geometry FROM vdyp_vri2018 limit 1"))$proj4string, resolution = c(100, 100), vals = 0
)
class(vri)

yc.ras<-fasterize::fasterize(sf= st_as_sf(vri), raster = ProvRast , field = 'ycid')
writeRaster(yc.ras, file="yc.tif", format="GTiff", overwrite=TRUE)
system("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', here::here(), '/R/params/yc.tif -t 100x100 rast.ycid_vdyp | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)

```
