---
title: "Scripts for creating parameters for whitebark pine analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source (here::here("R/functions/R_Postgres.R"))
library (data.table)
library (sf)
library (tidyverse)
library (raster)
library (fasterize)

data.dir <- "D:\\clus_data\\whitebark_pine\\"

#Create a provincial raster
layeraoi<-getSpatialQuery("SELECT * FROM study_area_compart limit 1")
prov.rast <- raster::raster(
  nrows = 15744, ncols = 17216, xmn = 159587.5, xmx = 1881187.5, ymn = 173787.5, ymx = 1748187.5, 
  crs = st_crs(layeraoi)$proj4string, resolution = c(100, 100), vals = 0)

conn <- DBI::dbConnect (dbDriver ("PostgreSQL"),
                        host = keyring::key_get('dbhost', keyring = 'postgreSQL'),
                        dbname = keyring::key_get('dbname', keyring = 'postgreSQL'),
                        port = '5432',
                        user = keyring::key_get('dbuser', keyring = 'postgreSQL'),
                        password = keyring::key_get('dbpass', keyring = 'postgreSQL'))
```

## Whitebark Pine Management Zones
### BC Core Habitat

```{r, bc core habitat}

hab.bc.core <- sf::st_read (paste0 (data.dir, "BC CORE WBP/BC_CORE_WBP.shp"))
hab.bc.core$zone <- 1
ras.hab.bc.core <- fasterize::fasterize (hab.bc.core, prov.rast, field = "zone")
writeRaster (ras.hab.bc.core, paste0 (data.dir, "raster_bc_core.tif"), overwrite = TRUE)      
system ("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', 
                                  data.dir, '/raster_bc_core.tif -t 100x100 rast.zone_whitebark_bc_core_habitat | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)

#Create zone constraint table for raster with all zones
zone.hab.bc.core <- data.table (zoneid = as.integer(1), 
                                 type = 'nh', variable = NA, threshold = 0, 
                                 reference_zone = 'rast.zone_whitebark_bc_core_habitat', 
                                 percentage = 0, ndt = as.integer(0), multi_condition = NA,
                                 denom = as.character(NA), 
                                 start = as.integer(0),
                                 stop = as.integer(250))
DBI::dbWriteTable (conn, c ("zone", "zone_whitebark_bc_core_habitat"), value = zone.hab.bc.core, row.names = FALSE, overwrite = TRUE)
dbExecute (conn, paste0 ("ALTER TABLE zone.zone_whitebark_bc_core_habitat ALTER COLUMN denom TYPE VARCHAR;"))
dbExecute (conn, paste0 ("ALTER TABLE zone.zone_whitebark_bc_core_habitat ALTER COLUMN variable TYPE TEXT;"))
dbExecute (conn, paste0 ("ALTER TABLE zone.zone_whitebark_bc_core_habitat ALTER COLUMN multi_condition TYPE TEXT;"))
dbExecute (conn, paste0 ("ALTER TABLE zone.zone_whitebark_bc_core_habitat INHERIT zone.constraints"))
dbDisconnect (conn)

```

### ECCC Habitat
```{r eccc critical habitat}

hab.eccc <- sf::st_read (paste0 (data.dir, "ECCC Critical Habitat/ECCC Critical Habitat.shp"))
hab.eccc.dissolve <- hab.eccc %>% group_by (CRITICAL_6) %>% summarize() # Dissolve
hab.eccc.vat <- data.table (st_drop_geometry (hab.eccc.dissolve [, c ('CRITICAL_6')]))  
hab.eccc.vat [, value := as.integer (c (2,1))] 
setnames (hab.eccc.vat, "CRITICAL_6", "type")
hab.eccc.dissolve <- merge (hab.eccc.dissolve, hab.eccc.vat, by.x = "CRITICAL_6", by.y = "CRITICAL_6")
ras.hab.eccc.dissolve <- fasterize::fasterize (hab.eccc.dissolve, prov.rast, field = "value")
writeRaster (ras.hab.eccc.dissolve, paste0 (data.dir, "raster_eccc.tif"), overwrite = TRUE) 
system ("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', 
                                  data.dir, '/raster_eccc.tif -t 100x100 rast.zone_whitebark_eccc_habitat | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)

#Create zone constraint table for raster with all zones
zone.hab.eccc <- data.table (zoneid = as.integer( c(1, 2)), 
                                 type = 'nh', variable = '', threshold = 0, 
                                 reference_zone = 'rast.zone_whitebark_eccc_habitat', 
                                 percentage = 0, ndt = as.integer(0), multi_condition = '',
                                 denom = as.character(NA), 
                                 start = as.integer(0),
                                 stop = as.integer(250))
DBI::dbWriteTable (conn, c ("zone", "zone_whitebark_eccc_habitat"), value = zone.hab.eccc, row.names = FALSE, overwrite = TRUE)
dbExecute (conn, paste0 ("ALTER TABLE zone.zone_whitebark_eccc_habitat ALTER COLUMN denom TYPE VARCHAR;"))
dbExecute (conn, paste0 ("ALTER TABLE zone.zone_whitebark_eccc_habitat ALTER COLUMN variable TYPE TEXT;"))
dbExecute (conn, paste0 ("ALTER TABLE zone.zone_whitebark_eccc_habitat ALTER COLUMN multi_condition TYPE TEXT;"))
dbExecute (conn, paste0 ("ALTER TABLE zone.zone_whitebark_eccc_habitat INHERIT zone.constraints"))
DBI::dbWriteTable(conn, c("vat", "whitebark_eccc_habitat"), value = hab.eccc.vat, row.names = FALSE, overwrite = TRUE)
dbDisconnect (conn)

```
### Potential Range
```{r potential range}
hab.pot <- sf::st_read (paste0 (data.dir, "WBP Potential Range/WBP_Potential_Range.shp"))
hab.pot$value <- 1
ras.hab.pot <- fasterize::fasterize (hab.pot, prov.rast, field = "value")
writeRaster (ras.hab.pot, paste0 (data.dir, "raster_habiat_pot.tif"), overwrite = TRUE)      
system ("cmd.exe", input = paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', 
                                  data.dir, '/raster_habiat_pot.tif -t 100x100 rast.zone_whitebark_potential_range | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus'), show.output.on.console = FALSE, invisible = TRUE)
#Create zone constraint table for raster with all zones
zone.hab.pot <- data.table (zoneid = as.integer(1), 
                                 type = 'nh', variable = NA, threshold = 0, 
                                 reference_zone = 'rast.zone_whitebark_potential_range', 
                                 percentage = 0, ndt = as.integer(0), multi_condition = NA,
                                 denom = as.character(NA), 
                                 start = as.integer(0),
                                 stop = as.integer(250))
DBI::dbWriteTable (conn, c ("zone", "zone_whitebark_potential_range"), value = zone.hab.pot, row.names = FALSE, overwrite = TRUE)
dbExecute (conn, paste0 ("ALTER TABLE zone.zone_whitebark_potential_range ALTER COLUMN denom TYPE VARCHAR;"))
dbExecute (conn, paste0 ("ALTER TABLE zone.zone_whitebark_potential_range ALTER COLUMN variable TYPE TEXT;"))
dbExecute (conn, paste0 ("ALTER TABLE zone.zone_whitebark_potential_range ALTER COLUMN multi_condition TYPE TEXT;"))
dbExecute (conn, paste0 ("ALTER TABLE zone.zone_whitebark_potential_range INHERIT zone.constraints"))
dbDisconnect (conn)

```


