---
title: "Caribou Habitat README"
author: "Tyler Muhly"
date: "18/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Caribou Habitat Folder
This rmd briefly describes the 'caribou habitat' folder in the caribou and land use simulater (CLUS) model. The purpose of scripts in the 'caribou habitat' folder is to document code used to create models of resource development impacts on caribou. The code does not interface with the CLUS model, i.e., they are not 'modules' in the set of 'SpaDES-modules'. Rather, the code documents how components of the caribou-specific modules were created and parameterized. 

The code in this folder currently documents two modeling approaches that are implemented in CLUS as SpaDES modules: a new resource selection function (RSF) model and a previously published caribou survival model ( [Wittmer et al. 2007](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.1365-2656.2007.01220.x)). These are implemented as part of the CLUS model in the 'rsfCLUS' module and the 'survivalCLUS' module, respectively. 

### Caribou Resource Selection Function (RSF) Models
The caribou RSF was developed within several files in this folder. The original approach of the RSF was to create a comprehensive, generalizable spatial model of caribou habitat quality across caribou range in British Columbia (BC). However, the approach evolved, and later versions of the model were developed to focus exclusively on the effects of forestry distrubance on caribou.  

The file '01_caribou_habitat_download_data.R' documents the source of spatial habtiat data used in the RSF analysis. The file '02_caribou_habitat_model_data_prep.R' then documents how this spatial habitat data was rasterized to create standardized spatial measures of habitat across British Columbia.   

The file '03_caribou_habitat_model_telemetry_data_prep_doc.Rmd' documents how the caribou location data was processed and linked to the spatial habitat data. Caribou location data was sourced from BC government caribou telemetry databases. This data was filtered and cleaned-up prior to linking to spatial habitat data, and was also used to calculate caribou home ranges. The home ranges were used to define a sample of spatial locations 'available' to caribou on the landscape, a key step of the RSF modeling approach. 

The file '04_caribou_forest_cutblock_RSF_prep.R' describes how the cutblock-specific RSF model covariates were developed for estimating the effects of cutblocks on caribou. This included documenting how cutblocks were classified into age classes. The files '05_caribou_fire_RSF_prep_full_script.R' and '06_caribou_beetle_RSF_prep_full_script.R' describe the same approach, but for fire and beetle disturbance, respectively.  

The folder 'rsf_v1" contains the files used to create the first version of the RSF model. Seperate files were created for models developed for each unique designatable unit (DU), i.e., DU6 (boreal), DU7, DU8 and DU9, and season (early winter, late winter and summer) combination. These models were useful for understanding the influence of several habitat features on caribou distribution. In particular, they showed how relatively 'permanent' features of the landscape, i.e., flat, high elevation mountain plateaus in mountainous areas, and low productivity, conifer wetland types in the boreal, have a very influential effect on caribou distribution. However, these effects tended to 'over-power' the effects of forestry disturbance on caribou distribution in the model, diminishing the utility of the RSF model as an indicator of forestry disturbances on caribou. In addition, expert review suggested they inadequately represented caribou habitat selection across different herds. Outputs from the 'version 1' RSF model were initially incorporated into the rsfCLUS module, but are not ideal as an indicator of forestry impacts on caribou distribution. 

The file '07_RSF_version2.R' was developed as a simplified version of the 'version 1' RSF model. It fits models with fewer habitat covariates (i.e., roads, cutblocks, wetland type (boreal only) and bigeoclimatic zone) and aggregated seasonal data into an annual model. Within the file, seperate models for each DU were fit. Although these models were simpler, expert review determined that they did not adequately represent variability in caribou habitat use across herds. Perhaps they were overly simplistic, but regardless, it was clear that fitting a generalizable habitat model across a DU was problematic using the spatial habitat data that we have. Results of this model were not incorporated into the rsfCLUS module.

The file '08_RSF_version3.RMD' documents the latest version of the RSF model. It simplifies the model to focus exclusively on the effects of forest cutblocks and resource roads on caribou. This approach eliminated the need to adequately model variabilty in caribou habitat use across large areas, instead focussing on modeling the variability in caribou response to disturbance. Simplifying the model by removing habitat covariates allowed us to incoporate some complexity into the model structure to more adequately address variability in caribou responses to habitat disturbance. Specifically, we included some random effects in the model to estimate individual-level and herd-level variability in caribou response to cutblocks and roads. The herd-level random effects can be used to estimate herd-specific effects of disturbance on caribou. Unsampled herds can be modeled using the 'population-level' (i.e., a 'typical' or 'average') fixed effects of disturbance on caribou. In addition, we included functional responses to disturbance into the model. Functional responses empirically account for how caribou respond to cutblocks and roads as a function of how fragmented by cutblocks and roads the landscape is around them. Results of this model have been incorporated into the rsfCLUS module to indicate potential impacts of forestry activity on caribou distribution, and thus the quality of caribou habitat. We are also working on linking this model to caribou population trends by relating model outputs calculated within the boundaries of caribou herds from 2003 to present, based on historic spatial-temporal data on cutblocks on roads, to population trend data in those herds over that same period. This will provide insight into how useful the indicator is of forestry disturbance effects on caribou populations. 
 
### Caribou Survival Model
The file '09_Wittmer_caribou_model' describes a model developed and published by Wittmer et al. 2007 that relates the area of early seral forest in a caribou herd range to survival rates of adult females in those ranges. This was used to create the 'survivalCLUS' module, which provides an indicator of forestry impacts on caribou that is linked to caribou habitat rather than survival. However, some caution is warranted when using this indicator, as it was developed for a sample of southern mountain caribou (DU9) only, and the sample size was relatively small. For this reason, outputs should be viewed as relative impacts on caribou survival rate, and not absolute measures of survival rate.

### Other Analyses
The file '10_caribou_boreal_disturbance_tsr_analysis.R' was a script used to calculate potential future habitat 'disturbance' for boreal caribou (as defined by Environment and Climate Change Canada), using spatial forest cutblock outputs from the Fort St. John and Fort Nelson timber supply models. The script can be used as a template for calculating forestry impacts on caribou using outputs from timber supply models. 

The file '11_caribou_range_habitat_attributes.R' is a script to calculate habitat characterisitics measured by spatial datasets in caribou herd boundaries. This can be used to summarize habitat attributes in caribou herd ranges, or any area of interest. 

## Archive, Data and Images Folders
The 'archive' folder stores some scripts that were not completed or are no longer in use. The 'data' and 'images' folders store data and images needed to run the .rmd files.