<!--
Copyright 2020 Province of British Columbia
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.-->

---
title: "Database creation for Fort St. John TSA Analyses Version 2.0"
author: "Kyle Lochhead"
date: "03 June 2022"
output: pdf_document
---

# Overview

The area of interest(aoi) is the columbian fisher population.

# Usage
Set parameters for creating the database in the code chunk below. 
```{r module_usage}
library(SpaDES)
library(SpaDES.core)
library(data.table)
library(dplyr)
library (keyring)

source(here::here("R/functions/R_Postgres.R"))

Sys.setenv(JAVA_HOME='C:\\Program Files\\Java\\jdk-14.0.1')
#Sys.setenv(JAVA_HOME = 'C:\\Program Files (x86)\\Java\\jre1.8.0_241') #throws an error if pointing to different version of java (i.e., 32 vs 64 bit)

setPaths(modulePath = here::here("R/SpaDES-modules"),
         outputPath = here::here("R/scenarios/test_FLEX/"))

getPaths() # shows where the 4 relevant paths are

times <- list(start = 0, end = 20)
parameters <-  list(
  .progress = list(type = NA, interval = NA),
  .globals = list(),
  dataLoaderCLUS = list (dbName = 'clus', # name of the postgres database
                         #save_clusdb = TRUE,
                         useCLUSdb = paste0(here::here(), "/R/scenarios/fisher_pop/fisher_columbian_pop_clusdb.sqlite"),
                         sqlite_dbname = "fisher_columbian_pop",
                         nameBoundaryFile = "fisher_ci_boreal_units_fine", # name of the (TSA) boundary data in postgres
                         nameBoundaryColumn = "pop_unit", 
                         nameBoundary = "Central Interior", 
                         nameBoundaryGeom = 'wkb_geometry', # geometry column name in the boundary file
                         nameCompartmentRaster = "rast.tsa_aac_boundary", 
                         nameCompartmentTable = "vat.tsa_aac_bounds_vat", # boundary (TSA) names corresponding to raster id's
                         nameMaskHarvestLandbaseRaster = 'rast.thlb_2020', #'rast.bc_thlb2018'
                         nameZoneRasters = c("rast.zone_cond_nharv", # includes parks and no harvest OGMAs
                                             "rast.zone_cond_vqo", 
                                             "rast.zone_wha_2021", 
                                             "rast.zone_uwr_2021", 
                                             "rast.zone_cond_fsw", 
                                             "rast.zone_cond_cw",
                                             "rast.zone_cond_beo"
                                           ), 
                     nameZoneTable = "zone.constraints",
                           # nameZonePriorityRaster = "rast.zone_cond_beo",
                        nameYieldsRaster = "rast.ycid_vdyp_2020",
                        nameYieldTable = "yc_vdyp_2020",
                        nameYieldsCurrentRaster = "rast.ycid_tipsy_current_2020",
                        nameYieldCurrentTable = "tipsy_current_prov_2020",
                        nameYieldsTransitionRaster = "rast.ycid_tipsy_prov_2020",
                        nameYieldTransitionTable = "tipsy_prov_2020",
                        nameForestInventoryRaster = "rast.vri2020_id",
                        nameForestInventoryKey = "feature_id",
                        nameForestInventoryTable = "veg_comp_lyr_r1_poly2020",
                        nameForestInventoryAge = "proj_age_1",
                        nameForestInventoryHeight = "proj_height_1",
                        nameForestInventoryCrownClosure = "crown_closure",
                        nameForestInventoryTreed = "bclcs_level_2",
                        nameForestInventorySiteIndex = "site_index",
                        nameForestInventoryBasalArea= "basal_area",
                        nameForestInventoryQMD = "quad_diam_125"),
  blockingCLUS = list(blockMethod = 'pre', 
                      patchZone = 'rast.zone_cond_beo', 
                      patchVariation = 6,
                      nameCutblockRaster ="rast.cns_cut_bl", 
                      useLandingsArea = FALSE),
  growingStockCLUS = list(periodLength = 5),
  forestryCLUS = list( harvestBlockPriority = " age DESC ", 
                      reportHarvestConstraints = T,
                      adjacencyConstraint = 0),
                      #salvageRaster = 'rast.dead_vol_125_2020'),
  roadCLUS = list(roadMethod = 'pre', 
                  nameCostSurfaceRas = 'rast.rd_cost_surface', 
                  nameRoads =  'rast.ce_road_2019'# existing road network
                  ),
  fisherCLUS = list(
    nameFetaRaster = 'rast.feta_id',
    nameRasWetlands = 'rast.wetland'
  ),
    FLEX = list(
    # "iterations" = 100, # hard coding it in for 100 simulations, better for output
    # "yrs.to.run" = 10,
    "simulations" = 200,
    "propFemales" = 0.3, 
    "maxAgeFemale" = 9,
    "dist_mov" = 1.0,
    "TS" = 10,
    "D2_param" = "Max",
    "name_out" = "Cariboo",
    "sim_order" = 2
    ),
   uploaderCLUS = list(aoiName = 'columbian', 
                      dbInfo  = list('165.227.35.74', 'klochhea', 'XVneCw86',  'clus'))
  )

scenario = data.table(name="no_harvest",
                      description = "no harvesting.")

patchSizeDist<- data.table(ndt= c(1,1,1,1,1,1,
                                  2,2,2,2,2,2,
                                  3,3,3,3,3,3,
                                  4,4,4,4,4,4,
                                  5,5,5,5,5,5), 
                           sizeClass = c(40,80,120,160,200,240), 
                           freq = c(0.3,0.3,0.1,0.1,0.1, 0.1,
                                    0.3,0.3,0.1,0.1,0.1, 0.1,
                                    0.2, 0.3, 0.125, 0.125, 0.125, 0.125,
                                    0.1,0.02,0.02,0.02,0.02,0.8,
                                    0.3,0.3,0.1,0.1,0.1, 0.1))

harvestFlow <- rbindlist(list(data.table(compartment ="Quesnel_TSA",
                                         partition = ' vol > 150 ', 
                                         period = rep( seq (from = 1, # run the 
                                                      to = 40, 
                                                      by = 1),
                                                    1), 
                                         flow = 6750000,
                                         partition_type = 'live'), 
                               
                              data.table(compartment ="Williams_Lake_TSA",
                                         partition = ' vol > 110 ', 
                                         period = rep( seq (from = 1, # run the 
                                                      to = 40, 
                                                      by = 1),
                                                    1), 
                                         flow = 8090000,
                                         partition_type = 'live'),
                              
                              data.table(compartment ="Onehundred_Mile_House_TSA",
                                         partition = ' vol > 150 ', 
                                         period = rep( seq (from = 1, # run the 
                                                      to = 40, 
                                                      by = 1),
                                                    1), 
                                         flow = 4890000,
                                         partition_type = 'live')
                              
))

modules <- list("dataLoaderCLUS", 
                #"blockingCLUS",
                "growingStockCLUS",
                #"forestryCLUS",
                "fisherCLUS",
                #"roadCLUS",
                #"FLEX"
                "uploaderCLUS"
                )

#objects <- list(patchSizeDist=patchSizeDist, rsf_model_coeff=rsf_model_coeff , scenario = scenario)
objects <- list(patchSizeDist = patchSizeDist,
                harvestFlow = harvestFlow,
                scenario = scenario 
                )

inputs <- list()
mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects)
outputs(mySim) <- data.frame (objectName = c("growingStockReport","fisherReport"))

system.time({
mysimout<-spades(mySim)
})
```

# Dependendices

First need an area of interest.
+nameBoundaryFile <- the vector data of the areas to consider. Defaults to caribou herd boundaries.
+nameBoundary<-The specific area of interest
+nameBoundaryColumn<-The column in the nameBoundaryFile that support the query for the area of interest
+nameBoundaryGeom<-the geometry column from which to run the spatial query containing the area of interest

The remaining files are:
+nameCompartmentRaster<- a provincial raster of compartments -- also known as supply blocks. Defaults to 1 compartment
+nameZoneRaster<-a provincial raster of management zones. Defaluts to 1 zone
+nameYieldRaster<-a provincial raster of id's that support a look up to yield tables. Defaults to 1 yield table
+nameAgeRaster<- a provincial raster of age. This can be set to zero, if correctly used to look up yields and constraints. Defaults to an age of 120
+nameCrownClosureRaster<- a provincial raster of crown closure. Used for management constraints. Defaults to 0 crown closure
+nameMaskHarvestLandbaseRaster<- a provincial raster of the timber harvesting landbase (THLB) that delinates area feasible to harvest timber. Defaults to all of the area of interest being eligible for harvesting.

# Events

The module only has an inititialization event for connecting to a database and establishing database objects


## Output data

The outputs contain the database connection object, functions needed to generate queries and the boundary and bounding box of the boundary needed for other queries

# Links to other modules

Links to every module required by CLUS

