---
title: "Run models for fire ignition prediction map"
author: "Elizabeth Kleynhans"
date: '2022-09-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("R/functions/R_Postgres.R"))
library(data.table)
library(sf)
library(tidyverse)
library(rgeos)

```

# Import the data and fire regime types layer
```{r}
dat<-st_read( "C:\\Work\\caribou\\clus_data\\Fire\\Fire_sim_data\\data\\Skeena_Omineca_Thompson_Okanagan\\Fisher_study_area_veg_FWI.gpkg")

dat<-st_transform(dat, 3005)

table(dat$idno) # check there is only one record per idno

# lightning caused fires
future_clim<-read.csv("C:\\Work\\caribou\\clus_data\\Fire\\Fire_sim_data\\data\\Skeena_Omineca_Thompson_Okanagan\\Fisher_study_area_8GCMs_ensemble_ssp370_2041MP.csv")

future_clim$mean_Tave07_Tave08_Tave09<-(future_clim$Tave07 +future_clim$Tave08 + future_clim$Tave09)/3
future_clim$mean_Tmax07_Tmax08<- (future_clim$Tmax07 + future_clim$Tmax08)/2
future_clim$mean_Tave07_Tave08<- (future_clim$Tave07 + future_clim$Tave08)/2
future_clim$mean_Tave06_Tave07_Tave08<-(future_clim$Tave06 +future_clim$Tave07 + future_clim$Tave08)/3
future_clim$mean_PPT07_PPT08_PPT09 <- (future_clim$PPT07 + future_clim$PPT08 + future_clim$PPT09)/3
future_clim$mean_PPT06_PPT07_PPT08 <- (future_clim$PPT06 + future_clim$PPT07 + future_clim$PPT08)/3


future_clim_2<- future_clim %>% dplyr::select(ID1, ID2, Latitude, Longitude, Elevation, Tmax01: PPT12, mean_Tave07_Tave08_Tave09:mean_PPT06_PPT07_PPT08) %>%
  rename(idno=ID1,
         frt=ID2)

table(is.na(future_clim_2$frt))
future_clim_2$mean_Tave07_Tave08_Tave09<-(future_clim_2$Tave07+future_clim_2$Tave08+future_clim_2$Tave09)/3
future_clim_2$mean_Tmax07_Tmax08_Tmax09<-(future_clim_2$Tmax07+future_clim_2$Tmax08+future_clim_2$Tmax09)/3
future_clim_2$mean_PPT05_PPT06_PPT07_PPT08<-(future_clim_2$PPT05 + future_clim_2$PPT06 + future_clim_2$PPT07 + future_clim_2$PPT08)/4

future_clim_2<-future_clim_2 %>%
    mutate(climate1_2050 = case_when(
                            frt == "9" ~ Tmax05,
                            frt == "10" ~ mean_Tave07_Tave08_Tave09 ,
                            frt == "11" ~ mean_Tmax07_Tmax08_Tmax09,
                            frt == "12" ~ mean_Tmax07_Tmax08,
                            frt == "13" ~ Tave07,
                            frt == "14" ~ mean_Tave07_Tave08,
                            frt == "15" ~ mean_Tave06_Tave07_Tave08 ,
                            TRUE ~ NA_real_))



#Repeat for climate 2

future_clim_2 <- future_clim_2 %>%
  mutate(climate2_2050 = if_else(frt==5, as.numeric(mean_PPT05_PPT06_PPT07_PPT08),
                    if_else(frt==10, as.numeric(mean_PPT07_PPT08_PPT09),
                    if_else(frt==11, as.numeric(mean_PPT07_PPT08_PPT09),
                    if_else(frt==13, as.numeric(PPT07),
                    if_else(frt==15, as.numeric(mean_PPT06_PPT07_PPT08), NA_real_))))))

names(future_clim_2)

future_clim_3<-future_clim_2 %>% dplyr::select(idno, frt, climate1_2050, climate2_2050)
table(future_clim_3$frt)
dat2<-left_join(dat, future_clim_3)

length(dat2$idno)

# create dummy variables for FWI_veg
dat2$veg_C1 <- ifelse(dat2$FWI_veg == 'C-1', 1, 0)
dat2$veg_C2 <- ifelse(dat2$FWI_veg == 'C-2', 1, 0)
dat2$veg_C3 <- ifelse(dat2$FWI_veg == 'C-3', 1, 0)
dat2$veg_C4 <- ifelse(dat2$FWI_veg == 'C-4', 1, 0)
dat2$veg_C5 <- ifelse(dat2$FWI_veg == 'C-5', 1, 0)
dat2$veg_C7 <- ifelse(dat2$FWI_veg == 'C-7', 1, 0)
dat2$veg_D12 <- ifelse(dat2$FWI_veg == 'D-1/2', 1, 0)
dat2$veg_M12 <- ifelse(dat2$FWI_veg == 'M-1/2', 1, 0)
dat2$veg_M3 <- ifelse(dat2$FWI_veg == 'M-3', 1, 0)
dat2$veg_N <- ifelse(dat2$FWI_veg == 'N', 1, 0)
dat2$veg_O1ab <- ifelse(dat2$FWI_veg == 'O-1a/b', 1, 0)
dat2$veg_S1 <- ifelse(dat2$FWI_veg == 'S-1', 1, 0)
dat2$veg_S2 <- ifelse(dat2$FWI_veg == 'S-2', 1, 0)
dat2$veg_S3 <- ifelse(dat2$FWI_veg == 'S-3', 1, 0)
#dat2$veg_W <- ifelse(dat2$FWI_veg == 'W', 1, 0)

names(dat2)
table(dat2$frt, dat2$FWI_veg)

# no_ignition<-dat2 %>% 
#   filter(frt %in% c(9,10,11,12,13,14,15)) %>%
#   filter(FWI_veg =="W" | bclcs_level_5 %in% c("GL", "LA"))
# table(no_ignition$frt)
# table(no_ignition$FWI_veg)
# 
# dat3<- dat2 %>% filter(frt %in% c(9,10,11,12,13,14,15)) %>%
#   filter(FWI_veg !="W" | !bclcs_level_5 %in% c("GL", "LA"))

```


### FRT 9

```{r}
frt9<- dat2 %>% filter(frt==9)

no_ignit9<-frt9 %>% filter(FWI_veg=="W" | bclcs_level_5 %in% c("GL", "LA"))
no_ignit9$logit_P<-0
no_ignit9$prob_ignition<-0
frt9_2<- frt9 %>% filter(FWI_veg!="W")
frt9_3<-frt9_2 %>% filter(!bclcs_level_5 %in% c("GL", "LA"))

table(frt9_3$FWI_veg)
#NOTE C-2 is the intercept
frt9_3$FWI_veg[frt9_3$FWI_veg=="D-1/2"]<-"C-7"
frt9_3$FWI_veg[frt9_3$FWI_veg=="C-5"]<-"C-7"
frt9_3$FWI_veg[frt9_3$FWI_veg=="C-4"]<-"C-2"

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_frt9_lightning.csv")

model_coef_table


# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
frt9_3$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt9_3$climate1_2050 +
  model_coef_table[[4]]*frt9_3$veg_C1 +
  model_coef_table[[5]]*frt9_3$veg_C2 +
  model_coef_table[[6]]*frt9_3$veg_C7 +
  model_coef_table[[7]]*frt9_3$veg_M12 +
  model_coef_table[[8]]*frt9_3$veg_N +
  model_coef_table[[9]]*frt9_3$veg_O1ab +
  model_coef_table[[10]]*frt9_3$Elevation

head(frt9_3)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt9_3$prob_ignition<-exp(frt9_3$logit_P)/(1+exp(frt9_3$logit_P))

summary(frt9_3$prob_ignition)

frt_9<-rbind(frt9_3, no_ignit9)
hist(frt_9$prob_ignition)


```

### FRT 10

```{r}
frt10<- dat2 %>% filter(frt==10)

no_ignit10<-frt10 %>% filter(FWI_veg=="W" | bclcs_level_5 %in% c("GL", "LA"))
no_ignit10$logit_P<-0
no_ignit10$prob_ignition<-0
frt10_2<- frt10 %>% filter(FWI_veg!="W")
frt10_3<-frt10_2 %>% filter(!bclcs_level_5 %in% c("GL", "LA"))


table(frt10_3$FWI_veg)
#NOTE C-2 is the intercept
frt10_3$FWI_veg[frt10_3$FWI_veg=="S-1"]<-"M-1/2"
frt10_3$FWI_veg[frt10_3$FWI_veg=="S-2"]<-"M-1/2"
frt10_3$FWI_veg[frt10_3$FWI_veg=="C-4"]<-"C-2"

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT10_lightning.csv")

model_coef_table


# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
frt10_3$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt10_3$climate1_2050 +
  model_coef_table[[4]]*frt10_3$climate2_2050 +
  model_coef_table[[5]]*frt10_3$veg_C3 +
  model_coef_table[[6]]*frt10_3$veg_C5 +
  model_coef_table[[7]]*frt10_3$veg_C7 +
  model_coef_table[[8]]*frt10_3$veg_D12 +
  model_coef_table[[9]]*frt10_3$veg_M12 +
  model_coef_table[[10]]*frt10_3$veg_N +
  model_coef_table[[11]]*frt10_3$veg_O1ab +
  model_coef_table[[12]]*frt10_3$Elevation

head(frt10_3)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt10_3$prob_ignition<-exp(frt10_3$logit_P)/(1+exp(frt10_3$logit_P))

summary(frt10_3$prob_ignition)
hist(frt10_3$prob_ignition)
frt_10<-rbind(frt10_3, no_ignit10)

```

# FRT 11
```{r}
frt11<- dat2 %>% filter(frt==11)

no_ignit11<-frt11 %>% filter(FWI_veg=="W" | bclcs_level_5 %in% c("GL", "LA"))
no_ignit11$logit_P<-0
no_ignit11$prob_ignition<-0
frt11_2<- frt11 %>% filter(FWI_veg!="W")
frt11_3<-frt11_2 %>% filter(!bclcs_level_5 %in% c("GL", "LA"))


#NOTE C-1 is the intercept
table(frt11_3$FWI_veg)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT11_lightning.csv")
model_coef_table

frt11_3$FWI_veg[frt11_3$FWI_veg=="C-5"]<-"C-7"
frt11_3$FWI_veg[frt11_3$FWI_veg=="D-1/2"]<-"C-7"
frt11_3$FWI_veg[frt11_3$FWI_veg=="S-1"]<-"M-1/2"
frt11_3$FWI_veg[frt11_3$FWI_veg=="S-2"]<-"M-1/2"
frt11_3$FWI_veg[frt11_3$FWI_veg=="S-3"]<-"M-1/2"
frt11_3$FWI_veg[frt11_3$FWI_veg=="O-1a/b"]<-"C-3"



#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

frt11_3$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt11_3$climate1_2050 +
  model_coef_table[[4]]*frt11_3$climate2_2050 +
  model_coef_table[[5]]*frt11_3$veg_C1 +
  model_coef_table[[6]]*frt11_3$veg_C2 +
  model_coef_table[[7]]*frt11_3$veg_C7 +
  model_coef_table[[8]]*frt11_3$veg_M12 +
  model_coef_table[[9]]*frt11_3$veg_N

head(frt11_3)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt11_3$prob_ignition<-exp(frt11_3$logit_P)/(1+exp(frt11_3$logit_P))

summary(frt11_3$prob_ignition)
hist(frt11_3$prob_ignition)
frt_11<-rbind(frt11_3, no_ignit11)
hist(frt_11$prob_ignition)
```


# FRT 12
```{r}
frt12<- dat2 %>% filter(frt==12)

no_ignit12<-frt12 %>% filter(FWI_veg=="W" | bclcs_level_5 %in% c("GL", "LA"))
no_ignit12$logit_P<-0
no_ignit12$prob_ignition<-0
frt12_2<- frt12 %>% filter(FWI_veg!="W")
frt12_3<-frt12_2 %>% filter(!bclcs_level_5 %in% c("GL", "LA"))


#NOTE C-1 is the intercept
table(frt12_3$FWI_veg)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT12_lightning.csv")
model_coef_table

frt12_3$FWI_veg[frt12_3$FWI_veg=="S-3"]<-"S-2"
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

frt12_3$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt12_3$climate1_2050 +
  model_coef_table[[4]]*frt12_3$veg_C2 +
  model_coef_table[[5]]*frt12_3$veg_C3 +
  model_coef_table[[6]]*frt12_3$veg_C4 +
  model_coef_table[[7]]*frt12_3$veg_C5 +
  model_coef_table[[8]]*frt12_3$veg_C7 +
  model_coef_table[[9]]*frt12_3$veg_D12 +
  model_coef_table[[10]]*frt12_3$veg_M12 +
  model_coef_table[[11]]*frt12_3$veg_M3 +
  model_coef_table[[12]]*frt12_3$veg_N +
  model_coef_table[[13]]*frt12_3$veg_O1ab +
  model_coef_table[[14]]*frt12_3$veg_S1 +
  model_coef_table[[15]]*frt12_3$veg_S2 + 
  model_coef_table[[16]]*frt12_3$Elevation

head(frt12_3)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt12_3$prob_ignition<-exp(frt12_3$logit_P)/(1+exp(frt12_3$logit_P))

summary(frt12_3$prob_ignition)
hist(frt12_3$prob_ignition)
frt_12<-rbind(frt12_3, no_ignit12)
hist(frt_12$prob_ignition)
```

# FRT 13
```{r}
frt13<- dat2 %>% filter(frt==13)

no_ignit13<-frt13 %>% filter(FWI_veg=="W" | bclcs_level_5 %in% c("GL", "LA"))
no_ignit13$logit_P<-0
no_ignit13$prob_ignition<-0
frt13_2<- frt13 %>% filter(FWI_veg!="W")
frt13_3<-frt13_2 %>% filter(!bclcs_level_5 %in% c("GL", "LA"))


table(frt13_3$FWI_veg)
# NOTE C2 is the intercept
frt13_3$FWI_veg[frt13_3$FWI_veg=="C-1"]<-"C-3"
frt13_3$FWI_veg[frt13_3$FWI_veg=="C-4"]<-"C-2"
frt13_3$FWI_veg[frt13_3$FWI_veg=="M-3"]<-"O-1a/b"

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT13_lightning.csv")
model_coef_table

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

frt13_3$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt13_3$climate1_2050 +
  model_coef_table[[4]]*frt13_3$climate2_2050 +
  model_coef_table[[5]]*frt13_3$veg_C3 +
  model_coef_table[[6]]*frt13_3$veg_C5 +
  model_coef_table[[7]]*frt13_3$veg_C7 +
  model_coef_table[[8]]*frt13_3$veg_D12 +
  model_coef_table[[9]]*frt13_3$veg_M12 +
  model_coef_table[[10]]*frt13_3$veg_N +
  model_coef_table[[11]]*frt13_3$veg_O1ab +
  model_coef_table[[12]]*frt13_3$veg_S1 +
  model_coef_table[[13]]*frt13_3$veg_S2 + 
  model_coef_table[[14]]*frt13_3$veg_S3 + 
  model_coef_table[[15]]*frt13_3$Elevation

head(frt13_3)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt13_3$prob_ignition<-exp(frt13_3$logit_P)/(1+exp(frt13_3$logit_P))

summary(frt13_3$prob_ignition)
frt_13<-rbind(frt13_3, no_ignit13)

hist(frt_13$prob_ignition)

```

# FRT 14

```{r}

frt14<- dat2 %>% filter(frt==14)

no_ignit14<-frt14 %>% filter(FWI_veg=="W" | bclcs_level_5 %in% c("GL", "LA"))
no_ignit14$logit_P<-0
no_ignit14$prob_ignition<-0
frt14_2<- frt14 %>% filter(FWI_veg!="W")
frt14_3<-frt14_2 %>% filter(!bclcs_level_5 %in% c("GL", "LA"))


table(frt14_3$FWI_veg)
# NOTE C-2 is the intercept
frt14_3$FWI_veg[frt14_3$FWI_veg=="C-4"]<-"C-2"
frt14_3$FWI_veg[frt14_3$FWI_veg=="S-3"]<-"S-1"

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT14_lightning.csv")
model_coef_table

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

frt14_3$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt14_3$climate1_2050 +
  model_coef_table[[4]]*frt14_3$veg_C3 +
  model_coef_table[[5]]*frt14_3$veg_C5 +
  model_coef_table[[6]]*frt14_3$veg_C7 +
  model_coef_table[[7]]*frt14_3$veg_D12 +
  model_coef_table[[8]]*frt14_3$veg_M12 +
  model_coef_table[[9]]*frt14_3$veg_M3 +
  model_coef_table[[10]]*frt14_3$veg_N +
  model_coef_table[[11]]*frt14_3$veg_O1ab +
  model_coef_table[[12]]*frt14_3$veg_S1 

head(frt14_3)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt14_3$prob_ignition<-exp(frt14_3$logit_P)/(1+exp(frt14_3$logit_P))

summary(frt14_3$prob_ignition)
hist(frt14_3$prob_ignition)
frt_14<-rbind(frt14_3, no_ignit14)
hist(frt_14$prob_ignition)
#plot(frt14[frt14$prob_ignition,])
```

# FRT 15

```{r}
frt15<- dat2 %>% filter(frt==15)

no_ignit15<-frt15 %>% filter(FWI_veg=="W" | bclcs_level_5 %in% c("GL", "LA"))
no_ignit15$logit_P<-0
no_ignit15$prob_ignition<-0
frt15_2<- frt15 %>% filter(FWI_veg!="W")
frt15_3<-frt15_2 %>% filter(!bclcs_level_5 %in% c("GL", "LA"))

table(frt15_3$FWI_veg)
# C-3 is the intercept
frt15_3$FWI_veg[frt15_3$FWI_veg=="C-2"]<-"C-3" 
frt15_3$FWI_veg[frt15_3$FWI_veg=="O-1a/b"]<-"C-3" 
frt15_3$FWI_veg[frt15_3$FWI_veg=="S-1"]<-"S-3" 

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT15_lightning.csv")
model_coef_table

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

# note climate 1 and elevation were correlated 0.76 so I removed climate 1 because the model without climate 1 but with elevation had a smaller AIC than the opposite
frt15_3$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt15_3$climate2_2050 +
  model_coef_table[[4]]*frt15_3$veg_C5 +
  model_coef_table[[5]]*frt15_3$veg_C7 +
  model_coef_table[[6]]*frt15_3$veg_D12 +
  model_coef_table[[7]]*frt15_3$veg_M12 +
  model_coef_table[[8]]*frt15_3$veg_N +
  model_coef_table[[9]]*frt15_3$veg_S3 +
  model_coef_table[[10]]*frt15_3$Elevation

head(frt15_3)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt15_3$prob_ignition<-exp(frt15_3$logit_P)/(1+exp(frt15_3$logit_P))

summary(frt15_3$prob_ignition)

hist(frt15_3$prob_ignition)
#plot(frt15[frt15$prob_ignition,])
frt_15<-rbind(frt15_3, no_ignit15)
hist(frt_15$prob_ignition)
```


### now combine all FRT's and plot it
```{r}
frt_all<- rbind(rbind(rbind(rbind(rbind(rbind(frt_10, frt_12), frt_13), frt_14), frt_15), frt_9), frt_11)

names(frt_all)
frtall<-frt_all %>% dplyr::select(idno:climate2_2050, logit_P:geom)

hist(frtall$prob_ignition)

st_write(frtall, "C:\\Work\\caribou\\clus_data\\Fire\\Fire_sim_data\\data\\Skeena_Omineca_Thompson_Okanagan\\fisher_study_area_lighting_ignit_2050_final.gpkg", delete_layer=TRUE, driver="GPKG")


names(frtall)
frtall2<- frtall %>% select(idno, frt, prob_ignition)
st_write(frtall2, "C:\\Work\\caribou\\clus_data\\Fire\\Fire_sim_data\\data\\Skeena_Omineca_Thompson_Okanagan\\Prob_lighting_ignit_2050.gpkg", delete_layer=TRUE, driver="GPKG")


```

# create raster

```{r}

layeraoi<-getSpatialQuery("SELECT * FROM study_area_compart limit 1")
#Create a provincial raster
prov.rast <- raster::raster ( # standardized provincial raster with no data in it
                              nrows = 15744, ncols = 17216, 
                              xmn = 159587.5, xmx = 1881187.5, 
                              ymn = 173787.5, ymx = 1748187.5, 
                              crs = "+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs", 
                              resolution = c(100, 100),                               
                              vals = 0)


study_area<-getSpatialQuery("SELECT tsa_name, tsa_number, wkb_geometry FROM study_area_compart where tsa_name in ('Quesnel TSA', 'Williams Lake TSA',  '100 Mile House TSA')")

study_area2<-study_area %>% group_by ( tsa_name, tsa_number) %>% summarise()
st_crs(study_area2)

study_area2<-st_as_sf(study_area2)
ras.aoi2 <- crop(prov.rast, study_area2)

##########

library(sp)
library(rgdal)
library(raster)
library(gstat)
fit.p.ign <- gstat::gstat(formula = prob_ignition ~ 1, data = frt_all2, nmax = 4)

maxint <- raster::interpolate(ras.aoi2, model=fit.p.ign) # this is pretty slow
z <- mask(maxint, ras.aoi2)
plot(z, col=rev(heat.colors(255)))



# ras.frt <- fasterize::fasterize (frt_all, prov.rast, field = "prob_ignition")
# plot(ras.frt)
# 
# plot(ras.aoi2)

#writeRaster(maxint, file=" C:\\Work\\caribou\\clus_data\\Fire\\Fire_sim_data\\data\\Probability_of_lightning_Ignition_Quesnell_WilliamsL_100Mile_allFRT_800m.tif", format="GTiff", overwrite=TRUE)

writeRaster(z, file=" C:\\Work\\caribou\\clus_data\\Fire\\Fire_sim_data\\data\\Probability_of_Escape_Quesnell_WilliamsL_100Mile_allFRT_800m.tif", format="GTiff", overwrite=TRUE)

# run this in R:
paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', 'C:/Work/caribou/clus_data/Fire/Fire_sim_data/data/Probability_of_lightning_Ignition_Quesnell_WilliamsL_100Mile_allFRT_800m.tif -t 100x100 rast.prob_lightning_ignit_quesnel_williamsl_100mile | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/clus')
# then copy the output thats between the " " from the above and paste it into the cmd and run that... should show Insert 0  1 lots of times.

```


