---
title: "Run models for fire ignition prediction map"
author: "Elizabeth Kleynhans"
date: '2022-09-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("R/functions/R_Postgres.R"))
library(data.table)
library(sf)
library(tidyverse)
library(rgeos)
library(mapview)
library(tmap)

```

# Import the data and fire regime types layer
```{r}
dat<-st_read( "C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\Skeena_Omineca_Thompson_Okanagan\\fisher_study_area_person_dat.gpkg")

dat<-st_transform(dat, 3005)
names(dat)

table(dat$idno) # check there is only one record per idno

## Create empty vector
dat$climate1<-0
head(dat)

dat$mean_PPT05_PPT06_PPT07_PPT08  <-(dat$PPT05 + dat$PPT06 + dat$PPT07 + dat$PPT08)/4
dat$mean_Tave05_Tave06_Tave07_Tave08<-(dat$Tave05 + dat$Tave06 + dat$Tave07 + dat$Tave08)/4
dat$mean_Tave04_Tave05_Tave06<-(dat$Tave04 + dat$Tave05 + dat$Tave06)/3
dat$mean_PPT05_PPT06<- (dat$PPT05 + dat$PPT06)/2
dat$mean_PPT04_PPT05_PPT06<- (dat$PPT04 + dat$PPT05 + dat$PPT06)/3

## Create empty vector
dat$climate1<-0
head(dat)

dat<-dat %>%
    mutate(climate1 = case_when(frt == 5 ~ as.numeric(PPT05), 
                                frt == 7 ~ as.numeric(PPT03), 
                                frt == 9 ~ Tave05, 
                                frt == 10 ~ mean_Tave05_Tave06_Tave07_Tave08,
                                frt == 11 ~ Tave09, 
                                frt == 12 ~ mean_Tave04_Tave05_Tave06,
                                frt == 13 ~ Tmax09,
                                frt == 14 ~ as.numeric(mean_PPT05_PPT06),
                                frt == 15 ~ Tave04,
                                TRUE ~ NA_real_))

#Repeat for climate 2
dat$climate2<-0

#Perform mutate to get the applicable variable for each row
dat<-dat %>%
    mutate(climate2 = case_when(frt == 10 ~ as.numeric(mean_PPT05_PPT06_PPT07_PPT08),
                                frt == 12 ~ as.numeric(mean_PPT04_PPT05_PPT06),
                                frt == 15 ~ as.numeric(PPT04),
                                TRUE ~ NA_real_))

head(dat)



table(dat$idno)

```


```{r}
# create dummy variables for FWI_veg

dat$veg_C1 <- ifelse(dat$FWI_veg == 'C-1', 1, 0)
dat$veg_C2 <- ifelse(dat$FWI_veg == 'C-2', 1, 0)
dat$veg_C3 <- ifelse(dat$FWI_veg == 'C-3', 1, 0)
dat$veg_C4 <- ifelse(dat$FWI_veg == 'C-4', 1, 0)
dat$veg_C5 <- ifelse(dat$FWI_veg == 'C-5', 1, 0)
dat$veg_C7 <- ifelse(dat$FWI_veg == 'C-7', 1, 0)
dat$veg_D12 <- ifelse(dat$FWI_veg == 'D-1/2', 1, 0)
dat$veg_M12 <- ifelse(dat$FWI_veg == 'M-1/2', 1, 0)
dat$veg_M3 <- ifelse(dat$FWI_veg == 'M-3', 1, 0)
dat$veg_N <- ifelse(dat$FWI_veg == 'N', 1, 0)
dat$veg_O1ab <- ifelse(dat$FWI_veg == 'O-1a/b', 1, 0)
dat$veg_S1 <- ifelse(dat$FWI_veg == 'S-1', 1, 0)
dat$veg_S2 <- ifelse(dat$FWI_veg == 'S-2', 1, 0)
dat$veg_S3 <- ifelse(dat$FWI_veg == 'S-3', 1, 0)
dat$veg_W <- ifelse(dat$FWI_veg == 'W', 1, 0)

names(dat)
table(dat$frt, dat$FWI_veg)
dat$log_dist_roads_m<-log(dat$dist_roads_m + 1)
dat$log_dist_infr_m<-log(dat$dist_infr_m + 1)

```

```{r}
##Slope
DEM_slope <- raster("T:\\FOR\\VIC\\HTS\\ANA\\PROJECTS\\CASTOR\\Data\\dem\\all_bc\\slope_ha_bc_3005.tif")
##Aspect
DEM_aspect <- raster("T:\\FOR\\VIC\\HTS\\ANA\\PROJECTS\\CASTOR\\Data\\dem\\all_bc\\aspect_ha_bc_3005.tif")

rasStack = stack(DEM_slope, DEM_aspect)
head(rasStack)

##Try this first
test<-cbind(dat, st_coordinates(dat))
head(test)

pointCoordinates<-data.frame(test$X, test$Y)
head(pointCoordinates)
#crs(pointCoordinates) #No CRS when a dataframe

##Extract DEM values from stacked layer
rasValue2=raster::extract(rasStack, pointCoordinates)
head(rasValue2)
dim(rasValue2) #200298 values
dim(dat)#200298 values

#Append new information
dat2<-cbind(dat, rasValue2)

```


### FRT 9

```{r}
frt9<- dat2 %>% filter(frt==9) # 15 water
frt9$bclcs_level_5[is.na(frt9$bclcs_level_5)]<-"missing"
table(frt9$bclcs_level_5)
frt9_2<- frt9 %>% filter(!FWI_veg %in% c("W", "N")) # 179 GL
table(frt9_2$bclcs_level_5)
frt9_3<- frt9_2 %>% filter(bclcs_level_5!="GL")

frt9_no_fuel<- frt9 %>% filter(FWI_veg %in% c("W", "N"))
frt9_no_fuel2<-frt9_2 %>% filter(bclcs_level_5=="GL")
frt9_no_fuel3<-rbind(frt9_no_fuel,frt9_no_fuel2)

table(frt9_3$FWI_veg)

frt9_3$FWI_veg[frt9_3$FWI_veg=="C-1"]<-"C-2"
frt9_3$FWI_veg[frt9_3$FWI_veg=="C-4"]<-"C-2"
frt9_3$FWI_veg[frt9_3$FWI_veg=="C-5"]<-"C-7"
frt9_3$FWI_veg[frt9_3$FWI_veg=="D-1/2"]<-"M-1/2"


model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_frt9_escape.csv")
model_coef_table

# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
frt9_3$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt9_3$climate1 +
  model_coef_table[[4]]*frt9_3$veg_C3 +
  model_coef_table[[5]]*frt9_3$veg_C7 +
  model_coef_table[[6]]*frt9_3$veg_M12 +
  model_coef_table[[7]]*frt9_3$veg_O1ab +
  model_coef_table[[8]]*frt9_3$slope_ha_bc_3005 +
  model_coef_table[[9]]*frt9_3$dist_roads
   
  
head(frt9_3)

frt9_3$prob_ignition<-exp(frt9_3$logit_P)/(1+exp(frt9_3$logit_P))


frt9_no_fuel3$logit_P<-0
frt9_no_fuel3$prob_ignition<-0

frt9_4<-rbind(frt9_3, frt9_no_fuel3)
dim(frt9)
dim(frt9_4)

hist(frt9_4$prob_ignition)

frt9_4<-st_as_sf(frt9_4)


```


### FRT 10

```{r}
frt10<- dat2 %>% filter(frt==10) # 15 water
frt10$bclcs_level_5[is.na(frt10$bclcs_level_5)]<-"missing"
table(frt10$bclcs_level_5)
frt10_2<- frt10 %>% filter(FWI_veg != "W") # 179 GL
table(frt10_2$bclcs_level_5)
frt10_3<- frt10_2 %>% filter(bclcs_level_5!="GL")

frt10_no_fuel<- frt10 %>% filter(FWI_veg == "W")
frt10_no_fuel2<-frt10_2 %>% filter(bclcs_level_5=="GL")
frt10_no_fuel3<-rbind(frt10_no_fuel,frt10_no_fuel2)

table(frt10_3$FWI_veg)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT10_escape.csv")

model_coef_table

# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
frt10_3$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt10_3$climate1 +
  model_coef_table[[4]]*frt10_3$climate2 +
  model_coef_table[[5]]*frt10_3$log_dist_roads_m +
  model_coef_table[[6]]*frt10_3$log_dist_infr_m
   
  
head(frt10_3)

frt10_3$prob_ignition<-exp(frt10_3$logit_P)/(1+exp(frt10_3$logit_P))


frt10_no_fuel3$logit_P<-0
frt10_no_fuel3$prob_ignition<-0

frt10_4<-rbind(frt10_3, frt10_no_fuel3)
dim(frt10)
dim(frt10_4)

hist(frt10_4$prob_ignition)

frt10_4<-st_as_sf(frt10_4)


```


### FRT 11

```{r}
frt11<- dat2 %>% filter(frt==11) # 15 water
frt11$bclcs_level_5[is.na(frt11$bclcs_level_5)]<-"missing"
table(frt11$bclcs_level_5)
frt11_2<- frt11 %>% filter(FWI_veg != "W") # 179 GL
table(frt11_2$bclcs_level_5)
frt11_3<- frt11_2 %>% filter(bclcs_level_5!="GL")

frt11_no_fuel<- frt11 %>% filter(FWI_veg == "W")
frt11_no_fuel2<-frt11_2 %>% filter(bclcs_level_5=="GL")
frt11_no_fuel3<-rbind(frt11_no_fuel,frt11_no_fuel2)

table(frt11_3$FWI_veg)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_frt11_escape.csv")

model_coef_table

# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
frt11_3$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt11_3$climate1 +
  model_coef_table[[5]]*frt11_3$log_dist_roads_m +
  model_coef_table[[6]]*frt11_3$log_dist_infr_m
   
  
head(frt11_3)

frt11_3$prob_ignition<-exp(frt11_3$logit_P)/(1+exp(frt11_3$logit_P))


frt11_no_fuel3$logit_P<-0
frt11_no_fuel3$prob_ignition<-0

frt11_4<-rbind(frt11_3, frt11_no_fuel3)
dim(frt11)
dim(frt11_4)

hist(frt11_4$prob_ignition)

frt11_4<-st_as_sf(frt11_4)


```


# FRT 12
```{r}
frt12<- dat2 %>% filter(frt==12) # 15 water
frt12$bclcs_level_5[is.na(frt12$bclcs_level_5)]<-"missing"
table(frt12$bclcs_level_5)
frt12_2<- frt12 %>% filter(FWI_veg != "W") # 179 GL
table(frt12_2$bclcs_level_5)
frt12_3<- frt12_2 %>% filter(!bclcs_level_5%in% c("GL", "LA"))

frt12_no_fuel<- frt12 %>% filter(FWI_veg == "W")
frt12_no_fuel2<-frt12_2 %>% filter(bclcs_level_5%in% c("GL", "LA"))
frt12_no_fuel3<-rbind(frt12_no_fuel,frt12_no_fuel2)
table(frt12_3$FWI_veg)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT12_escape.csv")

model_coef_table

# C1 is the intercept
frt12_3$FWI_veg[frt12_3$FWI_veg=="C-4"]<-"C-2" #C-4 and C-2 have very similar ROS
frt12_3$FWI_veg[frt12_3$FWI_veg=="S-3"]<-"M-1/2"
frt12_3$FWI_veg[frt12_3$FWI_veg=="S-1"]<-"M-1/2"
frt12_3$FWI_veg[frt12_3$FWI_veg=="S-2"]<-"M-1/2"

# C12 is the intercept

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

frt12_3$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt12_3$climate2 +
  model_coef_table[[4]]*frt12_3$veg_C2 +
  model_coef_table[[5]]*frt12_3$veg_C3 +
  model_coef_table[[6]]*frt12_3$veg_C5 +
  model_coef_table[[7]]*frt12_3$veg_C7 +
  model_coef_table[[8]]*frt12_3$veg_D12 +
  model_coef_table[[9]]*frt12_3$veg_M12 +
  model_coef_table[[10]]*frt12_3$veg_M3 +
  model_coef_table[[11]]*frt12_3$veg_N +
  model_coef_table[[12]]*frt12_3$veg_O1ab +
  model_coef_table[[13]]*frt12_3$slope_ha_bc_3005 +
  model_coef_table[[14]]*frt12_3$sum_win +
  model_coef_table[[15]]*frt12_3$log_dist_roads_m +
  model_coef_table[[16]]*frt12_3$log_dist_infr_m 
  

head(frt12_3)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt12_3$prob_ignition<-exp(frt12_3$logit_P)/(1+exp(frt12_3$logit_P))

summary(frt12_3$prob_ignition)

frt12_no_fuel3$logit_P<-0
frt12_no_fuel3$prob_ignition<-0

frt12_4<-rbind(frt12_3, frt12_no_fuel3)
dim(frt12)
dim(frt12_4)

hist(frt12_4$prob_ignition)

```

# FRT 13
```{r}
frt13<- dat2 %>% filter(frt==13) # 15 water
frt13$bclcs_level_5[is.na(frt13$bclcs_level_5)]<-"missing"
table(frt13$bclcs_level_5)
frt13_2<- frt13 %>% filter(FWI_veg != "W") # 179 GL
table(frt13_2$bclcs_level_5)
frt13_3<- frt13_2 %>% filter(bclcs_level_5!="LA")

frt13_no_fuel<- frt13 %>% filter(FWI_veg == "W")
frt13_no_fuel2<-frt13_2 %>% filter(bclcs_level_5=="LA")
frt13_no_fuel3<-rbind(frt13_no_fuel,frt13_no_fuel2)
table(frt13_3$FWI_veg)
table(frt13$FWI_veg)


model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT13_escape.csv")
model_coef_table

frt13_3$FWI_veg[frt13_3$FWI_veg=="C-4"]<-"C-2" #C-4 and C-2 have very similar ROS
# c-2 is the intercept

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

frt13_3$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt13_3$climate1 +
  model_coef_table[[4]]*frt13_3$veg_C3 +
  model_coef_table[[5]]*frt13_3$veg_C5 +
  model_coef_table[[6]]*frt13_3$veg_C7 +
  model_coef_table[[7]]*frt13_3$veg_D12 +
  model_coef_table[[8]]*frt13_3$veg_M12 +
  model_coef_table[[9]]*frt13_3$veg_N +
  model_coef_table[[10]]*frt13_3$veg_O1ab +
  model_coef_table[[11]]*frt13_3$veg_S1 +
  model_coef_table[[12]]*frt13_3$veg_S3 +
  model_coef_table[[13]]*frt13_3$slope_ha_bc_3005.1 +
  model_coef_table[[14]]*frt13_3$Elevation +
  model_coef_table[[15]]*frt13_3$sum_win +
  model_coef_table[[16]]*frt13_3$log_dist_roads_m +
  model_coef_table[[17]]*frt13_3$log_dist_infr_m 
  

head(frt13_3)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt13_3$prob_ignition<-exp(frt13_3$logit_P)/(1+exp(frt13_3$logit_P))

summary(frt13_3$prob_ignition)

#join back places where fires cannot start
frt13_no_fuel3$logit_P<-0
frt13_no_fuel3$prob_ignition<-0

frt13_4<-rbind(frt13_3, frt13_no_fuel3)
dim(frt13)
dim(frt13_4)

hist(frt13_4$prob_ignition)

```

# FRT 14

```{r}

frt14<- dat2 %>% filter(frt==14) # 15 water
frt14$bclcs_level_5[is.na(frt14$bclcs_level_5)]<-"missing"
table(frt14$bclcs_level_5)
frt14_2<- frt14 %>% filter(FWI_veg != "W") # 179 GL
table(frt14_2$bclcs_level_5)
frt14_3<- frt14_2 %>% filter(bclcs_level_5!="LA")

frt14_no_fuel<- frt14 %>% filter(FWI_veg == "W")
frt14_no_fuel2<-frt14_2 %>% filter(bclcs_level_5=="LA")
frt14_no_fuel3<-rbind(frt14_no_fuel,frt14_no_fuel2)
table(frt14_3$FWI_veg)
table(frt14$FWI_veg)

frt14_3$FWI_veg[frt14_3$FWI_veg=="C-4"]<-"C-3"
frt14_3$FWI_veg[frt14_3$FWI_veg=="M-3"]<-"O-1a/b"
frt14_3$FWI_veg[frt14_3$FWI_veg=="C-2"]<-"C-3"
frt14_3$FWI_veg[frt14_3$FWI_veg=="S-1"]<-"M-1/2"

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT14_escape.csv")
model_coef_table

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
# C-3 is the intercept
frt14_3$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt14_3$climate1 +
  model_coef_table[[4]]*frt14_3$veg_C5 +
  model_coef_table[[5]]*frt14_3$veg_C7 +
  model_coef_table[[6]]*frt14_3$veg_D12 +
  model_coef_table[[7]]*frt14_3$veg_M12 +
  model_coef_table[[8]]*frt14_3$veg_N +
  model_coef_table[[9]]*frt14_3$veg_O1ab +
  model_coef_table[[10]]*frt14_3$sum_win +
  model_coef_table[[11]]*frt14_3$log_dist_roads_m +
  model_coef_table[[12]]*frt14_3$log_dist_infr_m 
  
  

head(frt14_3)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt14_3$prob_ignition<-exp(frt14_3$logit_P)/(1+exp(frt14_3$logit_P))

summary(frt14_3$prob_ignition)

#plot(frt14[frt14$prob_ignition,])


frt14_no_fuel3$logit_P<-0
frt14_no_fuel3$prob_ignition<-0

frt14_4<-rbind(frt14_3, frt14_no_fuel3)
dim(frt14)
dim(frt14_4)

hist(as.numeric(frt14_4$prob_ignition))

```

# FRT 15

```{r}

frt15<- dat2 %>% filter(frt==15) # 15 water
frt15$bclcs_level_5[is.na(frt15$bclcs_level_5)]<-"missing"
table(frt15$bclcs_level_5)
frt15_2<- frt15 %>% filter(FWI_veg != "W") # 179 GL
table(frt15_2$bclcs_level_5)
frt15_3<- frt15_2 %>% filter(bclcs_level_5!="GL")

frt15_no_fuel<- frt15 %>% filter(FWI_veg == "W")
frt15_no_fuel2<-frt15_2 %>% filter(bclcs_level_5=="GL")
frt15_no_fuel3<-rbind(frt15_no_fuel,frt15_no_fuel2)
table(frt15_3$FWI_veg)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT15_escape.csv")
model_coef_table

frt15_3$FWI_veg[frt15_3$FWI_veg=="S-1"]<-"S-3"
frt15_3$FWI_veg[frt15_3$FWI_veg=="C-7"]<-"C-5"
frt15_3$FWI_veg[frt15_3$FWI_veg=="O-1a/b"]<-"C-3"

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

# note climate 1 and elevation were correlated 0.76 so I removed climate 1 because the model without climate 1 but with elevation had a smaller AIC than the opposite
frt15_3$logit_P<- model_coef_table[[2]] +
  model_coef_table[[3]]*frt15_3$climate2 +
  model_coef_table[[4]]*frt15_3$veg_C5 +
  model_coef_table[[5]]*frt15_3$veg_D12 +
  model_coef_table[[6]]*frt15_3$veg_M12 +
  model_coef_table[[7]]*frt15_3$veg_N +
  model_coef_table[[8]]*frt15_3$veg_S3 +
  model_coef_table[[9]]*frt15_3$slope_ha_bc_3005 +
  model_coef_table[[10]]*frt15_3$log_dist_infr_m 
  

head(frt15_3)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt15_3$prob_ignition<-exp(frt15_3$logit_P)/(1+exp(frt15_3$logit_P))

summary(frt15_3$prob_ignition)


frt15_no_fuel3$logit_P<-0
frt15_no_fuel3$prob_ignition<-0

frt15_4<-rbind(frt15_3, frt15_no_fuel3)
dim(frt15)
dim(frt15_4)

hist(frt15_4$prob_ignition)
```


### now combine all FRT's and plot it
```{r}
frt_all<- rbind(rbind(rbind(rbind(frt10_4, frt12_4), frt13_4), frt14_4), frt15_4)

frt_all
hist(frt_all$prob_ignition)


st_write(frt_all, "C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\Probability_of_escape_Quesnell_WilliamsL_100Mile_allFRT_800m_2.gpkg", delete_layer=TRUE, driver="GPKG")
dim(dat)

# create raster

layeraoi<-getSpatialQuery("SELECT * FROM study_area_compart limit 1")
#Create a provincial raster
prov.rast <- raster::raster ( # standardized provincial raster with no data in it
                              nrows = 15744, ncols = 17216, 
                              xmn = 159587.5, xmx = 1881187.5, 
                              ymn = 173787.5, ymx = 1748187.5, 
                              crs = "+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs", 
                              resolution = c(100, 100),                               
                              vals = 0)


study_area<-getSpatialQuery("SELECT tsa_name, tsa_number, wkb_geometry FROM study_area_compart where tsa_name in ('Quesnel TSA', 'Williams Lake TSA',  '100 Mile House TSA')")

study_area2<-study_area %>% group_by ( tsa_name, tsa_number) %>% summarise()
st_crs(study_area2)

study_area2<-st_as_sf(study_area2)
ras.aoi2 <- crop(prov.rast, study_area2)

x<-rasterize(frt_all, ras.aoi2, field="prob_ignition", update=TRUE)
#x<-fasterize::fasterize(frt_all, ras.aoi2, field="prob_ignition", update=TRUE)
plot(x)

writeRaster(x, file=" C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\Probability_of_Escape_Quesnell_WilliamsL_100Mile_allFRT_800m_fasterize_try.tif", format="GTiff", overwrite=TRUE)

##########

library(sp)
library(rgdal)
library(raster)
library(gstat)
fit.p.ign <- gstat::gstat(formula = prob_ignition ~ 1, data = frt_all, nmax = 4, set = list(idp = .5))

maxint <- raster::interpolate(ras.aoi2, model=fit.p.ign) # this is pretty slow
plot(maxint, col=rev(heat.colors(255)))

# can I just do matrix maths on the rasters?



# ras.frt <- fasterize::fasterize (frt_all, prov.rast, field = "prob_ignition")
# plot(ras.frt)
# 
# plot(ras.aoi2)

writeRaster(maxint, file=" C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\Probability_of_Escape_Quesnell_WilliamsL_100Mile_allFRT_800m.tif", format="GTiff", overwrite=TRUE)

# run this in R:
paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', 'C:/Work/caribou/castor_data/Fire/Fire_sim_data/data/Probability_of_Escape_Quesnell_WilliamsL_100Mile_allFRT_800m.tif -t 100x100 rast.prob_lightning_ignit_quesnel_williamsl_100mile | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/castor')
# then copy the output thats between the " " from the above and paste it into the cmd and run that... should show Insert 0  1 lots of times.

```

Test whether fire map makes sense.
```{r}

```


