---
title: "Run models for fire ignition prediction map"
author: "Elizabeth Kleynhans"
date: '2022-09-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("R/functions/R_Postgres.R"))
library(data.table)
library(sf)
library(tidyverse)
library(rgeos)
library(mapview)
library(tmap)

```

# Import the data and fire regime types layer
```{r}
dat<-st_read( "C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\Fire_data_all_Quesnell_WilliamsL_100Mile_FRT_800m.gpkg")

dat<-st_transform(dat, 3005)

table(dat$idno) # check there is only one record per idno

dat_person<-dat_person %>%
    mutate(climate1 = case_when(
                                frt == "5" ~ mean_PPT06_PPT07,
                                frt == "7" ~ mean_Tave04_Tave05_Tave06_Tave07_Tave08_Tave09_Tave10,
                                frt == "9" ~ Tmax05, # NDT4
                                frt == "10" ~ mean_PPT06_PPT07_PPT08_PPT09,
                                frt == "11" ~ mean_Tave08_Tave09_Tave10,
                                frt == "12" ~ mean_Tmax04_Tmax05_Tmax06_Tmax07_Tmax08_Tmax09_Tmax10,
                                frt == "13" ~ mean_Tave07_Tave08_Tave09,
                                frt == "14" ~ mean_Tmax04_Tmax05_Tmax06_Tmax07_Tmax08_Tmax09_Tmax10,
                                frt == "15" ~ mean_Tave07_Tave08_Tave09,
                               TRUE ~ NA_real_))

# #Repeat for climate 2
 dat_person$climate2<-"NA"
# 
# #Perform mutate to get the applicable variable for each row
dat_person<-dat_person %>%
    mutate(climate2 = case_when(
                                frt == "13" ~ mean_PPT07_PPT08_PPT09,
                                frt == "15" ~ mean_PPT07_PPT08_PPT09,
                               TRUE ~ NA_real_))


table(dat$idno)

```

# extract distance to road and distance to infrastructure.
```{r}
# bring distance rasters back in
# import roads distance raster
roads_dist <- raster("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\dist_roads.tif")
crs(roads_dist)

# import infrastructure data
dist_rail<- raster("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\dist_rail.tif")
dist_power<- raster("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\dist_power.tif")
dist_oil<- raster("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\dist_oil.tif")
dist_mines<- raster("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\dist_mines.tif")
dist_urban<- raster("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\dist_urban.tif")

rasStackinfrastructure = stack(roads_dist,dist_rail, dist_power, dist_oil, dist_mines, dist_urban)


crs(rasStackinfrastructure) # EPSG 9001. Hmm should probably change to 3005
res(rasStackinfrastructure) # at ha scale ... perfect

```

Bring back points from the 05_Distance_to_Road_Data_Prep.rmd file, jion the infrastructure data and create a new column that is the shortest distance to any infrastructure type.

```{r}
##Extract Coordinates
x2<- st_centroid(dat)

x<-st_coordinates(x2)
test<-cbind(dat, x)

head(test)

pointCoordinates<-data.frame(test$X, test$Y)
head(pointCoordinates)
#crs(pointCoordinates) #No CRS when a dataframe
##Extract Wind values from stacked layer
rasValue3=raster::extract(rasStackinfrastructure, pointCoordinates)
head(rasValue3)
str(rasValue3)
names(rasValue3)
str(x)# 200292 values

#Append new information
 dat2<-cbind(dat, rasValue3)

head(dat2)
crs(dat2)

dat2$dist_infr<-0

dat2$dist_infr<-
  ifelse(dat2$dist_rail < dat2$dist_power, dat2$dist_rail, dat2$dist_power)

dat2$dist_infr<-
  ifelse(dat2$dist_oil < dat2$dist_infr, dat2$dist_oil, dat2$dist_infr)

dat2$dist_infr<-
  ifelse(dat2$dist_mines < dat2$dist_infr, dat2$dist_mines, dat2$dist_infr)

dat2$dist_infr<-
  ifelse(dat2$dist_urban < dat2$dist_infr, dat2$dist_urban, dat2$dist_infr)

dat2$dist_infr_m<-dat2$dist_infr*100
dat2$dist_roads_m<-dat2$dist_roads*100

```


```{r}
sf::st_write(dat2, dsn = "C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\Quesnel_WilliamsL_100Mile_points_with_rds_infrastructure.gpkg", delete_layer=TRUE)

##Save to personal drive
#ogr2ogr -f "PostgreSQL" PG:"host=localhost user=postgres dbname=postgres password=postgres port=5432" C:\\Work\\caribou\\castor\\R\\fire_sim\\tmp\\Data_clim_DEM_roads_wind_infra.shp -overwrite -a_srs EPSG:3005 -progress --config PG_USE_COPY YES -nlt PROMOTE_TO_MULTI

dat<-st_read("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\Quesnel_WilliamsL_100Mile_points_with_rds_infrastructure.gpkg")
```


```{r}
# create dummy variables for FWI_veg

dat$veg_C2 <- ifelse(dat$FWI_veg == 'C-2', 1, 0)
dat$veg_C3 <- ifelse(dat$FWI_veg == 'C-3', 1, 0)
dat$veg_C4 <- ifelse(dat$FWI_veg == 'C-4', 1, 0)
dat$veg_C5 <- ifelse(dat$FWI_veg == 'C-5', 1, 0)
dat$veg_C7 <- ifelse(dat$FWI_veg == 'C-7', 1, 0)
dat$veg_D12 <- ifelse(dat$FWI_veg == 'D-1/2', 1, 0)
dat$veg_M12 <- ifelse(dat$FWI_veg == 'M-1/2', 1, 0)
dat$veg_M3 <- ifelse(dat$FWI_veg == 'M-3', 1, 0)
dat$veg_N <- ifelse(dat$FWI_veg == 'N', 1, 0)
dat$veg_O1ab <- ifelse(dat$FWI_veg == 'O-1a/b', 1, 0)
dat$veg_S1 <- ifelse(dat$FWI_veg == 'S-1', 1, 0)
dat$veg_S2 <- ifelse(dat$FWI_veg == 'S-2', 1, 0)
dat$veg_S3 <- ifelse(dat$FWI_veg == 'S-3', 1, 0)
dat$veg_W <- ifelse(dat$FWI_veg == 'W', 1, 0)

names(dat)
table(dat$frt, dat$FWI_veg)
dat$log_dist_roads_m<-log(dat$dist_roads_m + 1)
dat$log_dist_infr_m<-log(dat$dist_infr_m + 1)

no_ignition<-dat %>% 
  filter(frt %in% c(10,12,13,14,15)) %>%
  filter(FWI_veg =="W") %>%
  filter(bclcs_level_5 %in% c("GL", "LA"))
table(no_ignition$frt)
table(no_ignition$bclcs_level_5)

dat2<- dat %>% filter(frt %in% c(10,12,13,14,15)) %>%
  filter(FWI_veg !="W") %>%
  filter(!bclcs_level_5 %in% c("GL", "LA"))
table(dat2$bclcs_level_5)


```
### FRT 10

```{r}
frt10<- dat2 %>% filter(frt==10) 
table(frt10$FWI_veg)
# note C-2 is the intercept!

#frt10$FWI_veg[frt10$FWI_veg=="C-2"]<-"C-3" # because in the original model there were few C-2 observations i lumped them with C-3 since they seemed similar in fire behaviour (Perrakis pg 6)
frt10$FWI_veg[frt10$FWI_veg=="C-4"]<-"C-2"
frt10$FWI_veg[frt10$FWI_veg=="M-1/2"]<-"C-3"
frt10$FWI_veg[frt10$FWI_veg=="O-1a/b"]<-"C-3"
frt10$FWI_veg[frt10$FWI_veg=="S-1"]<-"C-2"

# I did not have any O-1a/b types when I fitted the statistical model. Looking at how the diference categories perform I have decided to include O-1a/b in the C-3 type because theyhave the most similar ROS. See fig on pg 5 of Perrakis.
# note FWI_veg type C-3 is the intercept.

table(frt10$FWI_veg)
model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT10_person.csv")

model_coef_table

# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
frt10$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt10$climate1 +
  model_coef_table[[4]]*frt10$dist_roads_m +
  model_coef_table[[5]]*frt10$veg_C3 +
  model_coef_table[[6]]*frt10$veg_C5 +
  model_coef_table[[7]]*frt10$veg_C7 +
  model_coef_table[[8]]*frt10$veg_D12 +
  model_coef_table[[9]]*frt10$veg_N
head(frt10)

frt10$prob_ignition<-exp(frt10$logit_P)/(1+exp(frt10$logit_P))


frt10_no_fuel<-no_ignition %>% filter(frt==10)

frt10_no_fuel$logit_P<-0
frt10_no_fuel$prob_ignition<-0

frt10_2<-rbind(frt10, frt10_no_fuel)
dim(frt10)
dim(frt10_2)

hist(frt10_2$prob_ignition)


```

# FRT 12
```{r}
frt12<- dat2 %>% filter(frt==12)

table(frt12$FWI_veg)
model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT12_person.csv")
model_coef_table

# NOTE C2 is the intercept!
#frt12$FWI_veg[frt12$FWI_veg=="C-2"]<-"C-3" 
frt12$FWI_veg[frt12$FWI_veg=="C-4"]<-"C-2" #C-4 and C-2 have very similar ROS
frt12$FWI_veg[frt12$FWI_veg=="S-2"]<-"M-1/2"
table(frt12$FWI_veg) 
# C-2 is the intercept

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

frt12$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt12$climate1 +
  model_coef_table[[4]]*frt12$Elevation +
  model_coef_table[[5]]*frt12$log_dist_roads_m +
  model_coef_table[[6]]*frt12$log_dist_infr_m +
  model_coef_table[[7]]*frt12$veg_C3 +
  model_coef_table[[8]]*frt12$veg_C5 +
  model_coef_table[[9]]*frt12$veg_C7 +
  model_coef_table[[10]]*frt12$veg_D12 +
  model_coef_table[[11]]*frt12$veg_M12 +
  model_coef_table[[12]]*frt12$veg_M3 +
  model_coef_table[[13]]*frt12$veg_N +
  model_coef_table[[14]]*frt12$veg_O1ab +
  model_coef_table[[15]]*frt12$veg_S1 

head(frt12)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt12$prob_ignition<-exp(frt12$logit_P)/(1+exp(frt12$logit_P))

summary(frt12$prob_ignition)

frt12_no_fuel<-no_ignition %>% filter(frt==12)

frt12_no_fuel$logit_P<-0
frt12_no_fuel$prob_ignition<-0

frt12_2<-rbind(frt12, frt12_no_fuel)
dim(frt12)
dim(frt12_2)
hist(frt12_2$prob_ignition)

```

# FRT 13
```{r}
frt13<- dat2 %>% filter(frt==13)
table(frt13$FWI_veg)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT13_person.csv")
model_coef_table

# NOTE C2 is the intercept
#frt13$FWI_veg[frt13$FWI_veg=="C-2"]<-"C-3"
frt13$FWI_veg[frt13$FWI_veg=="C-4"]<-"C-2" 
frt13$FWI_veg[frt13$FWI_veg=="S-2"]<-"M-1/2"

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

frt13$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt13$climate1 +
  model_coef_table[[4]]*frt13$climate2 +
  model_coef_table[[5]]*frt13$Elevation +
  model_coef_table[[6]]*frt13$log_dist_roads_m +
  model_coef_table[[7]]*frt13$log_dist_infr_m +
  model_coef_table[[8]]*frt13$veg_C3 +
  model_coef_table[[9]]*frt13$veg_C5 +
  model_coef_table[[10]]*frt13$veg_C7 +
  model_coef_table[[11]]*frt13$veg_D12 +
  model_coef_table[[12]]*frt13$veg_M12 +
  model_coef_table[[13]]*frt13$veg_M3 +
  model_coef_table[[14]]*frt13$veg_N +
  model_coef_table[[15]]*frt13$veg_O1ab +
  model_coef_table[[16]]*frt13$veg_S1 +
  model_coef_table[[17]]*frt13$veg_S3 
  

head(frt13)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt13$prob_ignition<-exp(frt13$logit_P)/(1+exp(frt13$logit_P))

summary(frt13$prob_ignition)

#join back places where fires cannot start
frt13_no_fuel<-no_ignition %>% filter(frt==13) 

frt13_no_fuel$logit_P<-0
frt13_no_fuel$prob_ignition<-0

frt13_2<-rbind(frt13, frt13_no_fuel)
dim(frt13)
dim(frt13_2)

hist(frt13_2$prob_ignition)

```

# FRT 14

```{r}

frt14<- dat2 %>% filter(frt==14)
table(frt14$FWI_veg)
#NOTE C2 is the intercept
#frt14$FWI_veg[frt14$FWI_veg=="C-2"]<-"C-3"
frt14$FWI_veg[frt14$FWI_veg=="C-4"]<-"C-3"
frt14$FWI_veg[frt14$FWI_veg=="S-2"]<-"M-1/2"

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT14_person.csv")
model_coef_table

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

frt14$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt14$climate1 +
  model_coef_table[[4]]*frt14$log_dist_roads_m +
  model_coef_table[[5]]*frt14$log_dist_infr_m +
  model_coef_table[[6]]*frt14$veg_C3 +
  model_coef_table[[7]]*frt14$veg_C5 +
  model_coef_table[[8]]*frt14$veg_C7 +
  model_coef_table[[9]]*frt14$veg_D12 +
  model_coef_table[[10]]*frt14$veg_M12 +
  model_coef_table[[11]]*frt14$veg_N +
  model_coef_table[[12]]*frt14$veg_O1ab +
  model_coef_table[[13]]*frt14$veg_S1 
  

head(frt14)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt14$prob_ignition<-exp(frt14$logit_P)/(1+exp(frt14$logit_P))

summary(frt14$prob_ignition)

#plot(frt14[frt14$prob_ignition,])

#join back places where fires cannot start
frt14_no_fuel<-no_ignition %>% filter(frt==14)

frt14_no_fuel$logit_P<-0
frt14_no_fuel$prob_ignition<-0

frt14_2<-rbind(frt14, frt14_no_fuel)
dim(frt14)
dim(frt14_2)

hist(frt14_2$prob_ignition)

```

# FRT 15

```{r}

frt15<- dat2 %>% filter(frt==15)
table(frt15$FWI_veg)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT15_person.csv")
model_coef_table
# note C-3 is the intercept term

frt15$FWI_veg[frt15$FWI_veg=="C-7"]<-"C-5"

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

# note climate 1 and elevation were correlated 0.76 so I removed climate 1 because the model without climate 1 but with elevation had a smaller AIC than the opposite
frt15$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt15$climate1 +
  model_coef_table[[4]]*frt15$climate2 +
  model_coef_table[[5]]*frt15$log_dist_roads_m +
  model_coef_table[[6]]*frt15$log_dist_infr_m +
  model_coef_table[[7]]*frt15$veg_C5 +
  model_coef_table[[8]]*frt15$veg_D12 +
  model_coef_table[[9]]*frt15$veg_M12 +
  model_coef_table[[10]]*frt15$veg_N +
  model_coef_table[[11]]*frt15$veg_O1ab +
  model_coef_table[[12]]*frt15$veg_S3
  

head(frt15)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt15$prob_ignition<-exp(frt15$logit_P)/(1+exp(frt15$logit_P))

summary(frt15$prob_ignition)

#join back places where fires cannot start
frt15_no_fuel<-no_ignition %>% filter(frt==15)

frt15_no_fuel$logit_P<-0
frt15_no_fuel$prob_ignition<-0

frt15_2<-rbind(frt15, frt15_no_fuel)
dim(frt15)
dim(frt15_2)

hist(frt15_2$prob_ignition)
```


### now combine all FRT's and plot it
```{r}
frt_all<- rbind(rbind(rbind(rbind(frt10_2, frt12_2), frt13_2), frt14_2), frt15_2)

frt_all


st_write(frt_all, "C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\Probability_of_person_Ignition_Quesnell_WilliamsL_100Mile_allFRT_800m.gpkg", delete_layer=TRUE, driver="GPKG")
```


```{r}
# create raster

layeraoi<-getSpatialQuery("SELECT * FROM study_area_compart limit 1")
#Create a provincial raster
prov.rast <- raster::raster ( # standardized provincial raster with no data in it
                              nrows = 15744, ncols = 17216, 
                              xmn = 159587.5, xmx = 1881187.5, 
                              ymn = 173787.5, ymx = 1748187.5, 
                              crs = "+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs", 
                              resolution = c(100, 100),                               
                              vals = 0)


study_area<-getSpatialQuery("SELECT tsa_name, tsa_number, wkb_geometry FROM study_area_compart where tsa_name in ('Quesnel TSA', 'Williams Lake TSA',  '100 Mile House TSA')")

study_area2<-study_area %>% group_by ( tsa_name, tsa_number) %>% summarise()
st_crs(study_area2)

study_area2<-st_as_sf(study_area2)
ras.aoi2 <- crop(prov.rast, study_area2)

##########

library(sp)
library(rgdal)
library(raster)
library(gstat)
fit.p.ign <- gstat::gstat(formula = prob_ignition ~ 1, data = frt_all, nmax = 4)

maxint <- raster::interpolate(ras.aoi2, model=fit.p.ign) # this is pretty slow
z <- mask(maxint, ras.aoi2)
plot(z, col=rev(heat.colors(255)))


writeRaster(maxint, file=" C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\Probability_of_Person_Ignition_Quesnell_WilliamsL_100Mile_allFRT_800m.tif", format="GTiff", overwrite=TRUE)
```


```{r}
person.ignit<-raster(" C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\Probability_of_Person_Ignition_Quesnell_WilliamsL_100Mile_allFRT_800m.tif")

lightning.ignit<-raster(" C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\Probability_of_lightning_Ignition_Quesnell_WilliamsL_100Mile_allFRT_800m.tif")


#P(Ignition) = P(lightning) x  (1-P(human)) + P(human) x (  1-P(lightning)) # Formula was used in this paper: https://iopscience.iop.org/article/10.1088/1748-9326/ac03da (Barros et.al. (2021) Contrasting the role of human- and lightning-caused wildfires on future fire regimes on a Central Oregon landscape. )

total.ignit <- (lightning.ignit * (1-person.ignit)) + (person.ignit * (1-lightning.ignit))

plot(total.ignit, col=rev(heat.colors(255)))


writeRaster(total.ignit, file=" C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\prob_of_lightning_and_person_ignition.tif", format="GTiff", overwrite=TRUE)


# run this in R:
paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', 'C:/Work/caribou/castor_data/Fire/Fire_sim_data/data/prob_of_lighting_ignition.tif -t 100x100 rast.prob_lightning_ignit_quesnel_williamsl_100mile | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/castor')
# then copy the output thats between the " " from the above and paste it into the cmd and run that... should show Insert 0  1 lots of times.

```

Test whether fire map makes sense.
```{r}

```


