---
title: "Fire ignition - description of methods"
author: "Elizabeth Kleynhans and Cora Skaien"
date: "25/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Broad overview of wild fire simulation project

The goal of this project is to simulate fire into the future. To do this I (Liz) am roughly following the methods outlined by Marchal et al. (2020) Turning down the heat: Vegetation feedbacks limit fire regime responses to global warming. Ecosystems 23: 204-216. (https://link.springer.com/article/10.1007/s10021-019-00398-2).
Briefly, the process of wildfires is split into three steps 1) ignition, 2) escape, and 3) spread. For the ignition and escape steps, the plan is to develop a statistical model using climate and vegetation parameters that best describe each process. Then I simulate the process forward by using the derived parameters and climate and vegetation data predicted for the future. More details of how the  statistical model is derived for fire ignitions is also outlined in 
Marchal.et.a.l 2017. Exploiting poisson additivity to predict fire frequency from maps of fire weather and land cover in boreal forests of Quebec, Canada. Ecography 40: 200 - 209. I roughly follow this. More details of the scripts used and exact methods I follow for ignition are described in the next section. For escape I was planning on doing what Marchal et al 2020 did. The way to model fire spread I'm less clear on. Cora is scoping out ideas from sigmoidal growth using fire duration and final size, and using MODIS satellite detections (but most of our fires are <500 ha, so this method may not be appropriate).


## Overview of the ignition module

This module provides the logic for simulating fire ignitions on the landscape. The main goal is to create a map of the probability of ignition for each year into the future. We develop a logistic regression model examining the presence or absence (available) of a fire ignition in relation to the climate, vegetation and topographyof the area. Because BC is so large and bioclimatically diverse, we perform a separate logistic regression model for each Natural Disturbance Type (NDT; formerly attempted by separate BEC zones, but data limitation was an issue). Splitting the analysis up by NDT hopefully helps to improve the predictive power of the model.   

## Historical data used to obtain logistic regression parameters 

#1. Determining locations of fires
Fire ignition locations for all of BC for the years 2002 to 2020 are obtained from https://catalogue.data.gov.bc.ca/dataset/fire-incident-locations-historical. The script to prepare this data can be found in C:\Work\caribou\clus\R\fire_sim\01_fire_ignition_data_prep.R. The ignition locations include fires started by humans, lightning, and other causes such as prescribed burns. In these models, we assess the probability of fires for lightning caused and person-caused fires separately and prepare the data for use in both. For human caused fires, we use road densities per km^2, but something like the human footprint index could be considered instead, and this human-metric is included in the statistical model in addition to vegetation, topography and climate data. 

#2. Obtaining Climate Data
Climate data for the locations where fires were and were not observed are obtained from climateBC (http://climatebc.ca/) for all years 2002 to 2020 The script to prepare this data can be found in C:\Work\caribou\clus\R\fire_sim\02_climate_data_prep.R. 
Briefly, the script obtains the lat, long coordinates of fire ignition locations and samples locations where fires were not observed to start, using a 500 m buffer around locations where fires did start. It then creates a csv file with these locations that is used to manually extract monthly average climate variables from climateBC (http://climatebc.ca/) for all years 2002 to 2020. After the climate data has been extracted from ClimateBC this data is reimported into the script and the mean monthly drought code for the months May - September is calculated for each year. After running this script I get the maximum temperature, minimum temperature, average temperature, total precipitation, and mean monthly drought code for the months May - September for each year 2002 - 2020 for all fire ignition locations and randomly sampled (available fire ignition locations (fire absence)) locations on the landscape. I save this climate data in postgres so that for the same locations I can query the VRI for vegetation data. 

#3. Obtaining Slope and Aspect data from DEM
Some studies have found that slope and aspect can impact the ignition and spread of fires given the differences in solar radiation and dryness. Slope and aspect have previously been extracted for the entirety of BC and can be located here "T:\\FOR\\VIC\\HTS\\ANA\\PROJECTS\\CLUS\\Data\\dem\\all_bc\\slope_ha_bc.tif"
and here
"T:\\FOR\\VIC\\HTS\\ANA\\PROJECTS\\CLUS\\Data\\dem\\all_bc\\aspect_ha_bc.tif"

We also use the basic DEM layer to get elevation as well. Here is where the elevation data is held: T:\FOR\VIC\HTS\ANA\PROJECTS\CLUS\Data\dem\all_bc

Using these files, we can extract the slope, aspect and elevation for each GPS location from our fire data, which is done in file 03_DEM_data_prep. Using these three metrics, we can calculate things like heatload, solar radiation, etc. - however, in model selection, slope, aspect and elevation on their own seem to perform better than these calculated metrics.


#4. Obtaining Road Density data
Many studies have shown that road density is a significant factor in the number of human-caused fires. As a result, we use the integrated roads shape file to extract the length of roads her km2 for each location identified in files 01-03 prior. The work for this is shown in 04_road_density_data_prep. Some papers use road density, others use distance to road. Many assume constant road network over time. We have roadclus which can estimate road networks moving backwards and can increase accuracy. For the initial model, we are using the 2018 roads map and assuming consistent road density from 2002-2020. These predictions may need to be improved moving forward to backcast to 2002. Kyle suggests that little road change expected moving forward so there is likely a long buffer in which the 2018 road maps will likely be fairly accurate.

Roads can be found here: public.integrated_roads  --> however, large dataset, likely cannot be brought into R
Code for roads from Kyle: https://github.com/bcgov/clus/blob/master/R/roads/current_roads.R
	T:\FOR\VIC\HTS\ANA\PROJECTS\CLUS\Data\Roads\roads_ha_bc\crds_all_roads.tif
	(Note: each year, roads change)
	Note: roads data has all roads awarded tenure and they may not have ever been built on the landscape.  https://www.bcauditor.com/pubs/2021/management-forest-service-roads
	Roadclus module does backcasting across landscape: https://github.com/bcgov/clus/tree/master/R/SpaDES-modules/roadCLUS


#5. Obtaining Wind Speeds
We used the Canadian Wind Atlas (http://www.windatlas.ca/maps-en.php) to download all polygons over the entirety of BC. From this, we then combined all polygons together and made a raster for wind speed for the perimeter of BC. The steps to perform this are described in 05_Wind_Speed_Data_Prep. Once this raster was created, we were able to extract the estimated average wind speed for spring and summer for each of the ignition points. This data is used only in the escape and spread models, and not in the ignition model.

The created rasters can be found here:
"D:\\Fire\\fire_data\\raw_data\\GovCanadaWindFiles\\wind_summer_clipped_224.tif"
"D:\\Fire\\fire_data\\raw_data\\GovCanadaWindFiles\\wind_spring_raster_224.tif"

#6. Determining the distance to different types of infrastructure

Whether or not fires spread into surrounding areas is not as simple as what the environment is like; instead, we have fire fighting efforts that can alter the course of a fire, reduce its spread, and extinguish the fire. The closer the fire is to infrastructure, such as urban settings, power lines, railroads, and major projects, the more likely that fire fighting efforts will be increased. Thus, we will determine the distance from each fire location to each category of infrastructure and assess patterns for impact on fire escape, size and spread.

Below are some layers that were used in QGIS to determine the shortest distance of each point to a source within each layer:
1. Municipalities: note that this only includes the incorporated municipalities and not the unincorporated municipalities.
https://catalogue.data.gov.bc.ca/dataset/municipalities-legally-defined-administrative-areas-of-bc
2. BC transmission lines: these provide power to municipalities and are often easy to access.
https://catalogue.data.gov.bc.ca/dataset/bc-transmission-lines
3. Railway track lines: these are important for transporting goods across the province and can be made a priority.
https://catalogue.data.gov.bc.ca/dataset/railway-track-line#edc-pow
4. Major Natural Resource Projects
https://catalogue.data.gov.bc.ca/dataset/natural-resource-sector-major-projects-points#edc-pow
5. BC Dams
https://catalogue.data.gov.bc.ca/dataset/bc-dams#edc-pow
6. Mines
https://maps.gov.bc.ca/ess/hm/imap4m/?catalogLayers=7738,7739&scale=8000000.0&center=-14435520.3411,8238977.65217
https://governmentofbc.maps.arcgis.com/home/item.html?id=b8ea19982bd74db3bd968d3c7f038e43

The resultant layer can be found here:
"D:\\Fire\\fire_data\\raw_data\\ClimateBC_Data\\Data_clim_DEM_roads_wind_infra.shp"

#7. Obtaining VRI data for each location
VRI (vegetation resource inventory) data is downloaded from (https://catalogue.data.gov.bc.ca/dataset/vri-historical-vegetation-resource-inventory-2002-2019-). To query the VRI, we use the script C:\Work\caribou\clus\R\fire_sim\07_vri_data_prep.R. We could only obtain VRI data for the years 2002 - 2020 and this is why the fire statistical model is fit to these years. From the VRI, we obtain for each ignition location and randomly sampled location the type of vegetation e.g. coniferous forest, mixed forest, deciduous forest, shrub land, water, etc. I also obtain the projected height of the forest, the projected age of the forest, and the predicted volume of the forest. The queries are run in postgres since this is much faster than R. Detailed methods for how to do this are outlined in the script file. At the end, fire, climate and vegetation data for every year is imported into R and amalgamated so the statistical analysis can be run using these variables. 

Note, once the VRI data is appended, our data become polygons instead of point data, so do any analyses needed at the point level prior (maybe there is a way to fix this?).

The final datasets used to fit the statistical equations can be found in postgres (KyleCLUS) under the name public.dat_person_for_analysis and  public.dat_lightning_for_analysis_Nov.


## Statistics: Ignition Models

To select the best single fire weather covariate, we first conducted exploratory graphical analyses of the correlations between fire frequency and various fire weather variables. Then we fit generalized linear models for each fire weather variable using a binomial error structure with logarithmic link for each NDT (5 levels). Candidate variables were monthly average temperature, monthly maximum temperature, monthly precipitation and the five mean drought codes (MDC’s). We also added various two, three or fourth-month means of these values (e.g. for May, June, July and August) to test for seasonal effects (e.g. spring vs. summer). These methods loosely follow those described by Marchal et al. (2017) Ecography (https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.01849) Supporting Information Appendix 1. The goal is to try to figure out which is the best climate variable or climate variables to include in the models for each NDT. We run simple models of the form: logb(p/1-p) = B0 + B1x1 or logb(p/1-p) = B0 + B1x1 + B2x2 or logb(p/1-p) = B0 + B1x1 + B2x2 + B3x1x2
and extract the AIC as a means for comparison. Currently no transformations of the variables are used, but it is reasonable to hypothesize an overall linear relationship with precipitation and temperature for fire as opposed to hump-shape patterns; however, these patterns may not be entirely linear and may be more sigmoidal.

We also calculate the AUC by splitting the data into a training and validation data set. Finally, we repeat the analysis calculating the AIC and AUC using training and validation data sets 100 times taking the average of both the AIC and AUC values. These are the values that we spit out into a csv file so that I can examine which climate variable is best for each NDT. The script used to run this analysis can be found here C:\Work\caribou\clus\R\fire_sim\08_ignition_climate_variable_selection.R. 

After determining the top candidate climate variable for each NDT separately by using the climate variable with the lowest average AIC, we fit the full model with vegetation and topography data. We split this into three categories (one climate model, one VRI model and one topography model) and then combine the top model from each category. The variables we consider for the lightning caused fire models are and the best climate variable, vegetation type (as determined by bclcs_level_4), slope, aspect, elevation, stand height, stand age, and stand volume. The problem is that volume, age and height data are only available for treed areas and probably only for public land and not private. As a result, we decided to split the analysis in each NDT into an analysis for treed areas and another analysis for non-treed areas. For the full treed model, we include vegetation type, projected height, projected age, stand volume and the best climate variable(s). The variables we consider for the person caused fire models are and the best climate variable, vegetation type (as determined by bclcs_level_4), slope, aspect, elevation, and road density. We repeated the analyses for non-treed areas, which included climate variable + vegetation type (and roads for person-caused fires).

Note: we attempt to do 100 iterations for these models too, but I realize that after Peter and I altered the code to have big.mod, I am not positive that the average values com out; instead it might just be the final run, and this needs to be investigated.

The vegetation type categories we include are:
Treed coniferous, treed mixed, treed broadleaf, shrub (both tall and short shrubs are lumped together), open - this includes most other categories including Bryoid-Lichens, Bryoid-moss, bryoids, exposed land, herb, herb-forbs, herb-graminoids, rock/rubbles, and snow/ice. Lastly, we classify areas that were disturbed by a stand replacing event within the last 15 years as disturbed. 

This file can be found here: C:\Work\caribou\clus\R\fire_sim\08_Fire_ignition_model_fits_by_NDT.Rmd


##Escape Models: Data prep and statistical analyses

We prepared the data for the escape models by selecting only the fire data (and excluding the locations created in ignition where fires did not occur). We decided to make the cut-off for escape as 1 ha (following Marchal et al. 2020), but others use a cutoff of 3 ha (Wang et al. 2016) or 10 ha (Parisien et al. 2013). Detailed methods can be found in 10_fire_escape_data_prep.

Briefly, we create a column that indicates whether a fire escaped or not. We then assign the wind speed of the time of that fire to either spring or summer, depending on when the fire ignited. This was done for both lightning and person caused fires separately.

In 11_escape_climate_variable_selection, we performed similar methods as to 08_ignition_climate_variable_selection, wherein we fit generalized linear models for each fire weather variable using a binomial error structure with logarithmic link for each NDT (5 levels). Candidate variables were monthly average temperature, monthly maximum temperature, monthly precipitation and the five mean drought codes (MDC’s). We also added various two, three or fourth-month means of these values (e.g. for May, June, July and August) to test for seasonal effects (e.g. spring vs. summer). These methods loosely follow those described by Marchal et al. (2017) Ecography (https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.01849) Supporting Information Appendix 1. The goal is to try to figure out which is the best climate variable or climate variables to include in the models for each NDT. We run simple models of the form: logb(p/1-p) = B0 + B1x1 or logb(p/1-p) = B0 + B1x1 + B2x2 or logb(p/1-p) = B0 + B1x1 + B2x2 + B3x1x2
and extract the AIC as a means for comparison. Currently no transformations of the variables are used, but it is reasonable to hypothesize an overall linear relationship with precipitation and temperature for fire as opposed to hump-shape patterns; however, these patterns may not be entirely linear and may be more sigmoidal.

We calculate the AUC by splitting the data into a training and validation data set. Finally, we repeat the analysis calculating the AIC and AUC using training and validation data sets 100 times taking the average of both the AIC and AUC values. These are the values that we spit out into a csv file so that I can examine which climate variable is best for each NDT.

After determining the top candidate climate variable for each NDT separately by using the climate variable with the lowest average AIC (this script can be found in 11_fire_escape_model_fits_by_NDT), we fit the full model with vegetation, topography VRI and infrastructure data. We split this into four categories (one climate model, one VRI model, one topography model and one infrastructure model) and then combine the top model from each category. These analyses are found in all the scripts starting with 12_.

The variables we consider for the lightning caused fire models are and the best climate variable, vegetation type (as determined by bclcs_level_4), slope, aspect, elevation, stand height, stand age, stand volume, road density (km/km-square), landuse, distance to different types of infrastructure (e.g., municipalities, mines, etc), windspeed and temperature difference from time of fire from the month prior. We split the analyses for each NDT into an analysis for treed areas and another analysis for non-treed areas. For the full treed models, we include projected height, projected age, stand volume along with the rest of the mentioned variables; for non-treed variables, these VRI metrics are not included. 

## Spread Models: Part 1 - Fire Size

We prepared the data for the spread models by selecting only the fire data that had "escaped" (i.e., fire size >1 ha). Data for this file contains previous manipulations: wind at the time of fire (spring or summer), temperature difference at time of fire from month prior. Detailed methods can be found in 13_fire_spread_fire_size.

We calculate the goodness of fit by splitting the data into a training and validation data set. We repeat the analysis calculating the AIC, R-square (validation, adjusted), RSME and MAE using training and validation data sets 100 times taking the average of both the values. 

After determining the top candidate climate variable for each NDT separately by using the climate variable with the lowest average AIC, we fit the full model with vegetation, topography VRI and infrastructure data. We split this into four categories (one climate model, one VRI model, one topography model and one infrastructure model) and then combine the top model from each category. These analyses are found in all the scripts starting with 12_.

The variables we consider for the lightning caused fire models are and the best climate variable, vegetation type (as determined by bclcs_level_4), slope, aspect, elevation, stand height, stand age, stand volume, road density (km/km-square), landuse, distance to different types of infrastructure (e.g., municipalities, mines, etc), windspeed and temperature difference from time of fire from the month prior. We split the analyses for each NDT into an analysis for treed areas and another analysis for non-treed areas. For the full treed models, we include projected height, projected age, stand volume along with the rest of the mentioned variables; for non-treed variables, these VRI metrics are not included. 

## Spread Models: Part 2 - Adjacent Cells

For this analysis, we selected the fire perimeter for all fires from 2002-2020. We then created a 150 m buffer around each fire. From here, we made a grid of points at 100 m intervals to represent one hectare spaces. We selected all points within the 150 m fire perimeter, and randomly selected 20% of the points within the fire perimeters. These steps were performed in QGIS. For each point, we extracted information on topography (slope, elevation, aspect), VRI (classifications for treed, non-treed, and other variables), distance to infrastructure (e.g., municipalities). Detailed methods can be found in 14_fire_spread_polygons_data_prep.

Analyses are conducted for all lightning and person caused fires combined (trees and non-treed). We calculate the AUC by splitting the data into a training and validation data set. We repeat the analysis calculating the AIC and AUC using training and validation data sets 100 times taking the average of both the AIC and AUC values. 


## Future climate and vegetation data

For projecting fire ignitions forward, we need predicted data collected for the future. For vegetation data, we hope to use the CLUS model which pulls volume, height and age data from tipsy curves and we should be able to access this data during a CLUS run. Need to speak to Kyle about this. Also need to determine accounting for when land might be harvested, changing the land type once again.

For climate data I (Liz) talked to Colin Mahony. Colin suggested I down scale climate data on the fly. I've not quite done this I did down scale the climate data for one Global Climate change model and generated rasters for each year and month from 2020 to 2100. I need to include more gcm models though. Detailed methods for what I did and the script to do this can be found in the file: C:\Work\caribou\clus\R\fire_sim\101_future_climate_data_prep.Rmd.

Lastly in script C:\Work\caribou\clus\R\fire_sim\102_compile_future_data.R I try to amalgamate the raster data so that I can easily query it. This is not complete though.


### Other ideas related to modelling spread

#Spread important files:
https://catalogue.data.gov.bc.ca/dataset/fire-perimeters-historical/resource/f635b5a6-c810-4623-9286-df9386b1ee75

Thoughts: Could use MODIS to determine spread, but suggested by Parks 2014 (who developed the methods) that this may only be accurate on fires >500 ha and ours are mostly much smaller. Could use sigmoidal growth if we know fire size and duration of burn, but this misses out on fine-scale topography and conditions (also we do not currently have fire duration data); could assume circular growth, as described in Parisien et al. (2013). Many assume maximum spread hours of 4 hours per day, and some put a cap on number of spread days (e.g., 7 days, Wang et al. 2016).

 
#Other considerations
1. Mountain pine beetle:
https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/forest-health/forest-pests/bark-beetles/mountain-pine-beetle/mpb-projections

Mountain pine beetle killed trees are more likely to ignite and burn. https://www.fs.fed.us/research/highlights/highlights_display.php?in_high_id=395

Useful layers:
https://catalogue.data.gov.bc.ca/dataset/bark-beetle-susceptibility-rating#edc-pow
https://catalogue.data.gov.bc.ca/dataset/pest-infestation-polygons-current
https://catalogue.data.gov.bc.ca/dataset/pest-infestation-polygons-historic
https://catalogue.data.gov.bc.ca/dataset/vri-2020-forest-vegetation-composite-dead-layer-d-

2. Fire mitigation
Often burn probability maps are created to compare against mitigation alternatives and different climate scenarios (Beverly and McLouglin 2019). I would REALLY like to include fire mitigation into the probability for each (ignition, escape and spread) down the road and see if there is any difference. 

3. Wildfire Fuel Typing: https://cfs.nrcan.gc.ca/publications?id=39432
This seems like a challenging process. It has been done for some years more recently, but not for all years (and now on a schedule of every 2 years). It is indicated that it requires specialized knowledge of formal research and "real world" experience to refine layers and variables. If there is interest, there may be great value in attempting to create these following the same methods for the missing years from the completed data layers. Many of the inputs do, however, derive from variables that are currently included in the models. Authors make reference to the Crown Fire Initiation and Spread (CFIS) system designed by Cruz et al. 2003b, Cruz et al. 2005, Alexnader et al. 2006. - probably worht investigating.

#Incorporate into TSA stuff
1. Perform analyses at province level
2. Then overlay TSA layer and get summaries of important variables for each after runs, including rotation and average patch size (and variability).
 https://catalogue.data.gov.bc.ca/dataset/fadm-timber-supply-area-tsa
 
 **Query TFLs out, otherwise look here: https://catalogue.data.gov.bc.ca/dataset/fadm-tree-farm-license-current-view-tfl-
