---
title: "Run models for fire ignition prediction map"
author: "Elizabeth Kleynhans"
date: '2022-09-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("R/functions/R_Postgres.R"))
library(data.table)
library(sf)
library(tidyverse)
library(rgeos)

```

# Import the data and fire regime types layer
```{r}
dat<-st_read( "C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\BC_all_dat_400m_final.gpkg")

dat<-st_transform(dat, 3005)
dat$frt<-as.factor(dat$frt)


#If you need to open the table listing the top climate
climate_variables_lightning<-read.csv("C:/Work/caribou/castor_data/Fire/Fire_sim_data/data/climate_AIC_results_lightning_FRT_summary.csv")

climate_variables_lightning

 # Lightning caused fires
dat$mean_Tave05_Tave06_Tave07_Tave08 <- (dat$Tave05 + dat$Tave06 + dat$Tave07 + dat$Tave08)/4
dat$mean_PPT05_PPT06_PPT07_PPT08<-(dat$PPT05 + dat$PPT06 + dat$PPT07 + dat$PPT08)/4

dat$meanRH05_RH06_RH07<-(dat$RH05 + dat$RH06 + dat$RH07)/3

dat$mean_Tave07_Tave08_Tave09 <- (dat$Tave07 + dat$Tave08 + dat$Tave09)/3
dat$mean_PPT07_PPT08_PPT09<-(dat$PPT07 + dat$PPT08 + dat$PPT09)/3
dat$mean_Tmax07_Tmax08_Tmax09<-(dat$Tmax07 + dat$Tmax08 + dat$Tmax09)/3

dat$mean_Tmax07_Tmax08<-(dat$Tmax07 + dat$Tmax08)/2

dat$mean_Tave07_Tave08<- (dat$Tave07 + dat$Tave08)/2

dat$mean_Tave06_Tave07_Tave08 <- (dat$Tave06 + dat$Tave07 + dat$Tave08)/3
dat$mean_PPT06_PPT07_PPT08 <- (dat$PPT06 + dat$PPT07 + dat$PPT08)/3



dat$climate1<-"NA"
dat<-dat %>%
    mutate(climate1 = case_when(
                            frt == "5" ~ mean_Tave05_Tave06_Tave07_Tave08 ,
                            frt == "7" ~ meanRH05_RH06_RH07,
                            frt == "9" ~ Tmax05,
                            frt == "10" ~ mean_Tave07_Tave08_Tave09 ,
                            frt == "11" ~ mean_Tmax07_Tmax08_Tmax09,
                            frt == "12" ~ mean_Tmax07_Tmax08,
                            frt == "13" ~ Tave07,
                            frt == "14" ~ mean_Tave07_Tave08,
                            frt == "15" ~ mean_Tave06_Tave07_Tave08 ,
                            TRUE ~ NA_real_))

#Repeat for climate 2
dat$climate2<-"NA"
# # 

dat <- dat %>%
  mutate(climate2 = if_else(frt==5, mean_PPT05_PPT06_PPT07_PPT08,
                            if_else(frt==10, mean_PPT07_PPT08_PPT09,
                                    if_else(frt==11, mean_PPT07_PPT08_PPT09,
                                    if_else(frt==13, as.numeric(PPT07),
                                            if_else(frt==15, mean_PPT06_PPT07_PPT08, NA_real_))))))

# create dummy variables for FWI_veg
dat$veg_C1 <- ifelse(dat$FWI_veg == 'C-1', 1, 0)
dat$veg_C2 <- ifelse(dat$FWI_veg == 'C-2', 1, 0)
dat$veg_C3 <- ifelse(dat$FWI_veg == 'C-3', 1, 0)
dat$veg_C4 <- ifelse(dat$FWI_veg == 'C-4', 1, 0)
dat$veg_C5 <- ifelse(dat$FWI_veg == 'C-5', 1, 0)
dat$veg_C7 <- ifelse(dat$FWI_veg == 'C-7', 1, 0)
dat$veg_D12 <- ifelse(dat$FWI_veg == 'D-1/2', 1, 0)
dat$veg_M12 <- ifelse(dat$FWI_veg == 'M-1/2', 1, 0)
dat$veg_M3 <- ifelse(dat$FWI_veg == 'M-3', 1, 0)
dat$veg_N <- ifelse(dat$FWI_veg == 'N', 1, 0)
dat$veg_O1ab <- ifelse(dat$FWI_veg == 'O-1a/b', 1, 0)
dat$veg_S1 <- ifelse(dat$FWI_veg == 'S-1', 1, 0)
dat$veg_S2 <- ifelse(dat$FWI_veg == 'S-2', 1, 0)
dat$veg_S3 <- ifelse(dat$FWI_veg == 'S-3', 1, 0)
#dat$veg_W <- ifelse(dat$FWI_veg == 'W', 1, 0)

names(dat)
table(dat$frt, dat$FWI_veg)

dat$frt[dat$frt==3]<-5

no_ignition1<-dat %>% 
  filter(FWI_veg =="W")

ignition1<-dat %>% 
  filter(FWI_veg !="W")

no_ignition2<-ignition1 %>% 
  filter(bclcs_level_5 %in% c("GL", "LA"))

no_ignition<-rbind(no_ignition1, no_ignition2)

ignition2<-ignition1 %>% 
  filter(!bclcs_level_5 %in% c("GL", "LA"))

dim(no_ignition)
```

### FRT 5

```{r}
frt5<- ignition2 %>% filter(frt==5)
head(frt5)

table(frt5$FWI_veg)

frt5_na<-frt5 %>% filter(FWI_veg == "N")
frt5<-frt5 %>% filter(FWI_veg != "N")

#NOTE C-2 is the intercept
frt5$veg_C7 <- ifelse(frt5$FWI_veg == 'C-5', 1, frt5$veg_C7) # change C-5 to C-7
frt5$veg_C2 <- ifelse(frt5$FWI_veg == 'C-4', 1, frt5$veg_C2) # change C-4 to C-2
frt5$veg_M12 <- ifelse(frt5$FWI_veg == 'S-1', 1, frt5$veg_M12) # change S-1 to M-1/2
frt5$veg_C7 <- ifelse(frt5$FWI_veg == 'S-2', 1, frt5$veg_C7)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_frt5_lightning.csv")

model_coef_table


# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
frt5$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt5$climate2 +
  model_coef_table[[4]]*frt5$veg_C1 +
  model_coef_table[[5]]*frt5$veg_C3 +
  model_coef_table[[6]]*frt5$veg_C7 +
  model_coef_table[[7]]*frt5$veg_D12 +
  model_coef_table[[8]]*frt5$veg_M12 +
  model_coef_table[[9]]*frt5$veg_O1ab +
  model_coef_table[[10]]*frt5$elevation

head(frt5)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt5$prob_ignition<-exp(frt5$logit_P)/(1+exp(frt5$logit_P))

summary(frt5$prob_ignition)
hist(frt5$prob_ignition)

# Adding the veg_type = N back here. I removed the FWI_veg="N" because there was only 1 occurence of this veg type in the orignial model.
frt5_na$logit_P<-0
frt5_na$prob_ignition<-0

frt5<-rbind(frt5, frt5_na)

```

FRT 7 
```{r}
frt7<- ignition2 %>% filter(frt==7)

table(frt7$FWI_veg)

frt7_na<-frt7 %>% filter(FWI_veg == "N")
frt7<-frt7 %>% filter(FWI_veg != "N")

#NOTE C-2 is the intercept
frt7$veg_C2 <- ifelse(frt7$FWI_veg == 'C-4', 1, frt7$veg_C2)
frt7$veg_M12 <- ifelse(frt7$FWI_veg == 'C-7', 1, frt7$veg_M12)
frt7$veg_M12 <- ifelse(frt7$FWI_veg == 'C-5', 1, frt7$veg_M12)
frt7$veg_M12 <- ifelse(frt7$FWI_veg == 'S-1', 1, frt7$veg_M12)
frt7$veg_M12 <- ifelse(frt7$FWI_veg == 'S-2', 1, frt7$veg_M12)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_frt7_lightning.csv")

model_coef_table


# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
frt7$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt7$climate1 +
  model_coef_table[[4]]*frt7$veg_C1 +
  model_coef_table[[5]]*frt7$veg_C3 +
  model_coef_table[[7]]*frt7$veg_D12 +
  model_coef_table[[8]]*frt7$veg_M12 +
  model_coef_table[[9]]*frt7$veg_O1ab

head(frt7)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt7$prob_ignition<-exp(frt7$logit_P)/(1+exp(frt7$logit_P))

summary(frt7$prob_ignition)
hist(frt7$prob_ignition)

# Adding the veg_type = N back here. I removed the FWI_veg="N" because there was only 1 occurence of this veg type in the orignial model.
frt7_na$logit_P<-0
frt7_na$prob_ignition<-0

frt7<-rbind(frt7, frt7_na)

```



### FRT 9

```{r}
frt9<- ignition2 %>% filter(frt==9)

table(frt9$FWI_veg)
#NOTE C-3 is the intercept
frt9$veg_C2 <- ifelse(frt9$FWI_veg == 'C-4', 1, frt9$veg_C2)
frt9$veg_C7 <- ifelse(frt9$FWI_veg == 'D-1/2', 1, frt9$veg_C7)
frt9$veg_C7 <- ifelse(frt9$FWI_veg == 'C-5', 1, frt9$veg_C7)
frt9$veg_M12 <- ifelse(frt9$FWI_veg == 'S-1', 1, frt9$veg_M12)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_frt9_lightning.csv")

model_coef_table


# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
frt9$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt9$climate1 +
  model_coef_table[[4]]*frt9$veg_C1 +
  model_coef_table[[5]]*frt9$veg_C2 +
  model_coef_table[[6]]*frt9$veg_C7 +
  model_coef_table[[7]]*frt9$veg_M12 +
  model_coef_table[[8]]*frt9$veg_N +
  model_coef_table[[9]]*frt9$veg_O1ab +
  model_coef_table[[10]]*frt9$elevation

head(frt9)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt9$prob_ignition<-exp(frt9$logit_P)/(1+exp(frt9$logit_P))

summary(frt9$prob_ignition)
hist(frt9$prob_ignition)


```

### FRT 10

```{r}
frt10<- ignition2 %>% filter(frt==10)

table(frt10$FWI_veg)
#NOTE C-2 is the intercept
frt10$veg_C3 <- ifelse(frt10$FWI_veg == 'C-1', 1, frt10$veg_C3)
frt10$veg_C2 <- ifelse(frt10$FWI_veg == 'C-4', 1, frt10$veg_C2)
frt10$veg_M12 <- ifelse(frt10$FWI_veg == 'S-1', 1, frt10$veg_M12)
frt10$veg_M12 <- ifelse(frt10$FWI_veg == 'S-2', 1, frt10$veg_M12)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT10_lightning.csv")

model_coef_table


# put coefficients into model formula
#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk
frt10$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt10$climate1 +
  model_coef_table[[4]]*frt10$climate2 +
  model_coef_table[[5]]*frt10$veg_C3 +
  model_coef_table[[6]]*frt10$veg_C5 +
  model_coef_table[[7]]*frt10$veg_C7 +
  model_coef_table[[8]]*frt10$veg_D12 +
  model_coef_table[[9]]*frt10$veg_M12 +
  model_coef_table[[10]]*frt10$veg_N +
  model_coef_table[[11]]*frt10$veg_O1ab +
  model_coef_table[[12]]*frt10$elevation

head(frt10)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt10$prob_ignition<-exp(frt10$logit_P)/(1+exp(frt10$logit_P))

summary(frt10$prob_ignition)
hist(frt10$prob_ignition)


```

# FRT 11
```{r}
frt11<- ignition2 %>% filter(frt==11)

#NOTE C-3 is the intercept
table(frt11$FWI_veg)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT11_lightning.csv")
model_coef_table

frt11$veg_C7 <- ifelse(frt11$FWI_veg == 'C-5', 1, frt11$veg_C7)
frt11$veg_C7 <- ifelse(frt11$FWI_veg == 'D-1/2', 1, frt11$veg_C7)
frt11$veg_M12 <- ifelse(frt11$FWI_veg == 'S-1', 1, frt11$veg_M12)
frt11$veg_M12 <- ifelse(frt11$FWI_veg == 'S-2', 1, frt11$veg_M12)
frt11$veg_M12 <- ifelse(frt11$FWI_veg == 'S-3', 1, frt11$veg_M12)
frt11$veg_C3 <- ifelse(frt11$FWI_veg == 'O-1a/b', 1, frt11$veg_C3)


#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

frt11$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt11$climate1 +
  model_coef_table[[4]]*frt11$climate2 +
  model_coef_table[[5]]*frt11$veg_C1 +
  model_coef_table[[6]]*frt11$veg_C2 +
  model_coef_table[[7]]*frt11$veg_C7 +
  model_coef_table[[8]]*frt11$veg_M12 +
  model_coef_table[[9]]*frt11$veg_N

head(frt11)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt11$prob_ignition<-exp(frt11$logit_P)/(1+exp(frt11$logit_P))

summary(frt11$prob_ignition)
hist(frt11$prob_ignition)

```



# FRT 12
```{r}
frt12<- ignition2 %>% filter(frt==12)

#NOTE C-1 is the intercept
table(frt12$FWI_veg)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT12_lightning.csv")
model_coef_table

frt12$veg_S1 <- ifelse(frt12$FWI_veg == 'S-3', 1, frt12$veg_S1)

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

frt12$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt12$climate1 +
  model_coef_table[[4]]*frt12$veg_C2 +
  model_coef_table[[5]]*frt12$veg_C3 +
  model_coef_table[[6]]*frt12$veg_C4 +
  model_coef_table[[7]]*frt12$veg_C5 +
  model_coef_table[[8]]*frt12$veg_C7 +
  model_coef_table[[9]]*frt12$veg_D12 +
  model_coef_table[[10]]*frt12$veg_M12 +
  model_coef_table[[11]]*frt12$veg_M3 +
  model_coef_table[[12]]*frt12$veg_N +
  model_coef_table[[13]]*frt12$veg_O1ab +
  model_coef_table[[14]]*frt12$veg_S1 +
  model_coef_table[[15]]*frt12$veg_S2 + 
  model_coef_table[[16]]*frt12$elevation

head(frt12)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt12$prob_ignition<-exp(frt12$logit_P)/(1+exp(frt12$logit_P))

summary(frt12$prob_ignition)
hist(frt12$prob_ignition)

```

# FRT 13
```{r}
frt13<- ignition2 %>% filter(frt==13)

table(frt13$FWI_veg)
# NOTE C2 is the intercept
#frt13$FWI_veg[frt13$FWI_veg=="C-2"]<-"C-3"
frt13$veg_C2 <- ifelse(frt13$FWI_veg == 'C-4', 1, frt13$veg_C2)
frt13$veg_C3 <- ifelse(frt13$FWI_veg == 'C-1', 1, frt13$veg_C3)
frt13$veg_O1ab <- ifelse(frt13$FWI_veg == 'M-3', 1, frt13$veg_O1ab)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT13_lightning.csv")
model_coef_table

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

frt13$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt13$climate1 +
  model_coef_table[[4]]*frt13$climate2 +
  model_coef_table[[5]]*frt13$veg_C3 +
  model_coef_table[[6]]*frt13$veg_C5 +
  model_coef_table[[7]]*frt13$veg_C7 +
  model_coef_table[[8]]*frt13$veg_D12 +
  model_coef_table[[9]]*frt13$veg_M12 +
  model_coef_table[[10]]*frt13$veg_N +
  model_coef_table[[11]]*frt13$veg_O1ab +
  model_coef_table[[12]]*frt13$veg_S1 +
  model_coef_table[[13]]*frt13$veg_S2 + 
  model_coef_table[[14]]*frt13$veg_S3 + 
  model_coef_table[[15]]*frt13$elevation

head(frt13)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt13$prob_ignition<-exp(frt13$logit_P)/(1+exp(frt13$logit_P))

summary(frt13$prob_ignition)

hist(frt13$prob_ignition)

```

# FRT 14

```{r}

frt14<- ignition2 %>% filter(frt==14)

table(frt14$FWI_veg)
# NOTE C-2 is the intercept

frt14$veg_C2 <- ifelse(frt14$FWI_veg == 'C-4', 1, frt14$veg_C2)
frt14$veg_C7 <- ifelse(frt14$FWI_veg == 'S-2', 1, frt14$veg_C7)
frt14$veg_M12 <- ifelse(frt14$FWI_veg == 'S-3', 1, frt14$veg_M12)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT14_lightning.csv")
model_coef_table

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

frt14$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt14$climate1 +
  model_coef_table[[4]]*frt14$veg_C3 +
  model_coef_table[[5]]*frt14$veg_C5 +
  model_coef_table[[6]]*frt14$veg_C7 +
  model_coef_table[[7]]*frt14$veg_D12 +
  model_coef_table[[8]]*frt14$veg_M12 +
  model_coef_table[[9]]*frt14$veg_M3 +
  model_coef_table[[10]]*frt14$veg_N +
  model_coef_table[[11]]*frt14$veg_O1ab +
  model_coef_table[[12]]*frt14$veg_S1 

head(frt14)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt14$prob_ignition<-exp(frt14$logit_P)/(1+exp(frt14$logit_P))

summary(frt14$prob_ignition)
hist(frt14$prob_ignition)

#plot(frt14[frt14$prob_ignition,])
```

# FRT 15

```{r}

frt15<- ignition2 %>% filter(frt==15)
table(frt15$FWI_veg)
# C-3 is the intercept
frt15$veg_C3 <- ifelse(frt15$FWI_veg == 'C-2', 1, frt15$veg_C3)
frt15$veg_C3 <- ifelse(frt15$FWI_veg == 'O-1a/b', 1, frt15$veg_C3)

model_coef_table<-read.csv("D:\\Fire\\fire_data\\raw_data\\top_mod_table_FRT15_lightning.csv")
model_coef_table

#logit(p) = b0+b1X1+b2X2+b3X3….+bkXk

# note climate 1 and elevation were correlated 0.76 so I removed climate 1 because the model without climate 1 but with elevation had a smaller AIC than the opposite
frt15$logit_P<- model_coef_table[[2]] + 
  model_coef_table[[3]]*frt15$climate2 +
  model_coef_table[[4]]*frt15$veg_C5 +
  model_coef_table[[5]]*frt15$veg_C7 +
  model_coef_table[[6]]*frt15$veg_D12 +
  model_coef_table[[7]]*frt15$veg_M12 +
  model_coef_table[[8]]*frt15$veg_N +
  model_coef_table[[9]]*frt15$veg_S3 +
  model_coef_table[[10]]*frt15$elevation

head(frt15)
# y = e^(b0 + b1*x) / (1 + e^(b0 + b1*x))
frt15$prob_ignition<-exp(frt15$logit_P)/(1+exp(frt15$logit_P))

summary(frt15$prob_ignition)

hist(frt15$prob_ignition)
#plot(frt15[frt15$prob_ignition,])
```


### now combine all FRT's and plot it
```{r}
frt_all<-rbind(rbind(rbind(rbind(rbind(rbind(rbind(rbind(frt10, frt12), frt13), frt14), frt15), frt9), frt11), frt5),frt7)

names(frt_all)
frtall<-frt_all %>% dplyr::select(idno:elevation, bclcs_level_4, bclcs_level_5,FWI_veg:dist_roads_m, dist_infrastructure_m:Tmax12, Tave01:RH12, climate1, climate2, logit_P:geom)
names(no_ignition)
names(frtall)
no_ignition<-no_ignition %>% dplyr::select(idno:elevation, bclcs_level_4, bclcs_level_5,FWI_veg:dist_roads_m, dist_infrastructure_m:Tmax12, Tave01:RH12, climate1:geom)
no_ignition$logit_P<-0
no_ignition$prob_ignition<-0

frt_all2<-rbind(frtall, no_ignition)
hist(frt_all2$prob_ignition)

```
save the data
```{r}
st_write(frt_all2, "C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\BC_lighting_ignit_final.gpkg", delete_layer=TRUE, driver="GPKG")

```


# create raster

```{r}
frt_all2<-st_read("C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\BC_lighting_ignit_final.gpkg")



layeraoi<-getSpatialQuery("SELECT * FROM study_area_compart limit 1")
#Create a provincial raster
prov.rast <- raster::raster ( # standardized provincial raster with no data in it
                              nrows = 15744, ncols = 17216, 
                              xmn = 159587.5, xmx = 1881187.5, 
                              ymn = 173787.5, ymx = 1748187.5, 
                              crs = "+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs", 
                              resolution = c(100, 100),                               
                              vals = 0)


study_area<-getSpatialQuery("SELECT * FROM study_area_compart")

study_area2<-study_area %>% group_by ( tsa_name, tsa_number) %>% summarise()
st_crs(study_area2)

study_area2<-st_as_sf(study_area2)
ras.aoi2 <- crop(prov.rast, study_area2)

##########

library(sp)
library(rgdal)
library(raster)
library(gstat)
fit.p.ign <- gstat::gstat(formula = prob_ignition ~ 1, data = frt_all2, nmax = 4)

maxint <- raster::interpolate(prov.rast, model=fit.p.ign) # this is pretty slow
z <- mask(maxint, prov.rast)
plot(z, col=rev(heat.colors(255)))



# ras.frt <- fasterize::fasterize (frt_all, prov.rast, field = "prob_ignition")
# plot(ras.frt)
# 
# plot(ras.aoi2)

#writeRaster(maxint, file=" C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\Probability_of_lightning_Ignition_Quesnell_WilliamsL_100Mile_allFRT_800m.tif", format="GTiff", overwrite=TRUE)

writeRaster(z, file=" C:\\Work\\caribou\\castor_data\\Fire\\Fire_sim_data\\data\\BC\\BC_Lightning_ignition_probability_2021.tif", format="GTiff", overwrite=TRUE)

# run this in R:
paste0('raster2pgsql -s 3005 -d -I -C -M -N 2147483648  ', 'C:/Work/caribou/castor_data/Fire/Fire_sim_data/data/Probability_of_lightning_Ignition_Quesnell_WilliamsL_100Mile_allFRT_800m.tif -t 100x100 rast.prob_lightning_ignit_quesnel_williamsl_100mile | psql postgres://', keyring::key_get('dbuser', keyring = 'postgreSQL'), ':', keyring::key_get('dbpass', keyring = 'postgreSQL'), '@', keyring::key_get('dbhost', keyring = 'postgreSQL'), ':5432/castor')
# then copy the output thats between the " " from the above and paste it into the cmd and run that... should show Insert 0  1 lots of times.

```


