---
title: "FDW BCGW Data Extract to Cloud: SETUP"
output: html_document
---

## Set up FDW for data from BCGW to Digital Ocean PostgreSQL Server

Processing AR2021 data.  

Processing date: `r Sys.Date()` 


Using Foreign Data Wrapper: oracle_fdw  


# create schema for loading


```{r cloud_connection, eval=TRUE,message=FALSE,warning=FALSE}

library(RPostgreSQL)

cloud <- '159.203.39.152'
database <- 'msyt'

con <- dbConnect('PostgreSQL',host=cloud,dbname=database)



```

```{r test_connection,eval=TRUE,message=FALSE,warning=FALSE}

a <- dbGetQuery(con,'select * from test')

```

create a loading schema that is based on AR year.  

create two server objects within the loading schema.  

- oradb_idwprod1
- oradb_dbp01


```{sql setup_init,eval=TRUE,connection=con}

-- set up for FDW using a transfer shcmea
-- \dn  lists the present schemas
-- \dx lists the extensions

drop schema if exists load_2021 cascade;
drop server if exists oradb_idwprod1 cascade;
drop server if exists oradb_dbp01 cascade;

-- establish the loading schema
--\dn+ 
create schema if not exists load_2021;

-- to drop an existing server object:
-- drop server oradb_idwprod1 cascade;

-- set up the server object from BCGW
--\des+
create server oradb_idwprod1 foreign data wrapper oracle_fdw options (dbserver '//bcgw.bcgov/idwprod1.bcgov' );

-- map a user
--\deu+
create user mapping for postgres server oradb_idwprod1 options (user 'dwaddell', password 'idwprod1_next04');




select now();

```

```{sql pre_delete_results, eval=FALSE,connection=con}


drop table if exists msyt_2021.rslt_activity_treatment_unit;
drop table if exists msyt_2021.rslt_forest_cover;
drop table if exists msyt_2021.rslt_forest_cover_inv_svw;
drop table if exists msyt_2021.rslt_forest_cover_layer;
drop table if exists msyt_2021.rslt_forest_cover_lyer_species;
drop table if exists msyt_2021.rslt_forhealth_rslt;
drop table if exists msyt_2021.rslt_opening;
drop table if exists msyt_2021.rslt_planting_rslt;
drop table if exists msyt_2021.rslt_stocking_stndrd_unit;
drop table if exists msyt_2021.genetic_worth;

select now(); 



```


```{sql pre_delete_veg, eval=FALSE,connection=con}

drop table if exists msyt_2021.veg_comp;
drop table if exists msyt_2021.veg_comp_spatial;


select now();

```


```{sql pre_delete_foreign_results, eval=FALSE,connection=con}

drop foreign table if exists load_2021.rslt_activity_treatment_unit;
drop foreign table if exists load_2021.rslt_forest_cover;
drop foreign table if exists load_2021.rslt_forest_cover_inv_svw;
drop foreign table if exists load_2021.rslt_forest_cover_layer;
drop foreign table if exists load_2021.rslt_forest_cover_lyer_species;
drop foreign table if exists load_2021.rslt_forhealth_rslt;
drop foreign table if exists load_2021.rslt_opening_svw;
drop foreign table if exists load_2021.rslt_planting_rslt;
drop foreign table if exists load_2021.rslt_stocking_stndrd_unit;
drop foreign table if exists load_2021.seedlot_genetic_worth;

select now();

```


```{sql pre_delete_foreign_vri, eval=FALSE,connection=con}

drop foreign table if exists load_2021.veg_comp;
drop foreign table if exists load_2021.veg_comp_spatial;



```

## note that the schema msyt_2021 needs to be manually deleted.



```{r eval=TRUE}

z <- dbDisconnect(con)

```



