---
title: "Barkerville and Wells Gray North "
author: "Kyle Lochhead, Elizabeth Kleynhans and Tyler Muhly"
date: "08/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require (kableExtra)
require (data.table)
require (here)
require (dplyr)
require (ggplot2)
require (scales)
require (knitr)
```


### Modeled Annual Harvested Volume

```{r, table 1, barkerville and wells scenario volume, echo = F, error = F, eval = T, include = T, message = F}
# data.harvest <- read.csv (here ("reports/scenarios/data", "harvest.csv"))
# data.summ <- data.harvest %>% # get summary data
#               filter (scenario == "wells_gray_north_nh_crit_aNA_rNA") %>%
#                       summarise (sum (volume)/40)

table.volume = data.table (
  herd = c ("NA", "NA", "Barkerville", "Barkerville", "Barkerville", "Barkerville", "NA", "Barkerville", 
            "Barkerville", "Barkerville", "Barkerville", "Barkerville", "Wells Gray North", "Wells Gray North",
            "Wells Gray North", "Wells Gray North", "Wells Gray North"),
  scenario = c ("BAU", "BAU", "BC Herd Plan", "ECCC Recovery Strategy", "BC Herd Plan", "ECCC Recovery Strategy",
                "BAU", "BC Herd Plan", "ECCC Recovery Strategy", "BC Herd Plan", "ECCC Recovery Strategy",  
                "No Harvest", "BC Herd Plan", "ECCC Recovery Strategy", "BC Herd Plan", "ECCC Recovery Strategy",
                "No Harvest"),
  adjacency = c (0, 1.5, 1.5, 1.5, 1.5, 1.5, 3, 3, 3, 3, 3, 0, 3, 3, 3, 3, 0),
  recovery = c (0, 0, 40, 40, 30, 30, 0, 40, 40, 30, 30, 0, 40, 40, 30, 30, 0),
  annual_volume = c (3460143, 3460473, 3382252, 3367355, 3386819, 3367624, 3519953, 3463082, 3448524, 
                     3449003, 3392700, 3392700, 3471256, 3433411, 3489364, 3433411, 3368536),
  diff_annual_volume = c (0, 0, -78221, -93118, -73654, -92849, 0, -56871, -71429, -70950, -127253, -67443, -48697,
                          -86542, -30589, -86542, -91607),
  perc_diff_tot_volume = c ("0", "0", "2%", "3%", "2%", "3%", "0", "2%", "2%", "2%", "4%", "2%", "1%", "2%", "1%",
                            "2%", "3%")
)
kable (table.volume,
       caption = "<b>Table 1. Annual Harvested Volume Over a 200 Year Period in the Quesnel and Williams Lake Timber Supply Areas Under Different Barkerville and Wells Gray North Caribou Recovery Scenarios.<b>",
       col.names = c("Caribou Herd",
                     "Scenario",
                     "Adjacency Height Requirement (m)",
                     "Habitat Recovery Time (Years)",
                     "Average Annual Volume (m3)",
                     "Difference in Annual Volume (m3)",
                     "Percent Difference in Annual Volume"),
       format.args = list (big.mark = ","),
       align = rep( c('l', 'l', 'c', 'c', 'c', 'c', 'c'))) %>%
  kable_styling (position = "left",
                 bootstrap_options = c("striped", "hover"),
                 fixed_thead = T,
                 full_width = F,
                 font_size = 11) %>%
  footnote (general = "BAU = business-as-usual scenario; ECCC = Environment and Climate Change Canada; BC = British Columbia",
            fixed_small_size = T)
```




### Disturbance Indicator

```{r, FIG 1, Quesnel disturbance Barkerville scenario compare, echo = F, error = F, eval = T, include = T, message = F, warning = F}
data.dist <- read.csv (here ("reports/scenarios/data", "disturbance.csv"))
data.dist <- data.dist %>%
              filter (scenario == "itchas_bau_a3_rNA" | scenario == "barkerville_bc_herd_plan_a3_r40" | 
                      scenario == "barkerville_eccc_a3_r40" | scenario == "barkerville_bc_herd_plan_a3_r30" |
                      scenario == "barkerville_eccc_a3_r30" | scenario == "barkerville_nh_crit_aNA_rNA") %>%
              filter (critical_hab == "Barkerville HEWSR" | critical_hab == "Barkerville Matrix")
data.dist$scenario <- ordered (data.dist$scenario, 
                               levels = c ("barkerville_nh_crit_aNA_rNA", "itchas_bau_a3_rNA", 
                                         "barkerville_bc_herd_plan_a3_r40", "barkerville_eccc_a3_r40",
                                         "barkerville_bc_herd_plan_a3_r30", "barkerville_eccc_a3_r30"))
data.dist.ques <- data.dist %>%
                    filter (compartment == "Quesnel_TSA")

ggplot (data.dist.ques, aes (x = timeperiod, y = dist500_per, color = scenario, linetype = scenario)) +
  geom_line (position = position_dodge (width = 1)) + 
  facet_grid (. ~critical_hab) +
  labs (title = "Figure 1. Proportion of Area Disturbed in Barkerville Critical Habitat 
in the Quesnel TSA Under the Different Habitat Management Scenarios.", 
        x = "Future Year", 
        y = "Percent Disturbed",
        caption = "BAU = business-as-usual scenario; 
ECCC = Environment and Climate Change Canada; 
BC = British Columbia") + 
  scale_color_discrete (name = "Scenario", labels = c("No Harvest", "BAU, 3m, 0 years", "BC Herd Plan, 3m, 40 years",
                                                      "ECCC, 3m, 40 years", "BC Herd Plan, 3m, 30 years", 
                                                      "ECCC, 3m, 30 years")) +
  scale_linetype_discrete (name = "Scenario", labels = c("No Harvest", "BAU, 3m, 0 years", 
                                                         "BC Herd Plan, 3m, 40 years", "ECCC, 3m, 40 years", 
                                                         "BC Herd Plan, 3m, 30 years", "ECCC, 3m, 30 years")) +
  theme (#legend.position = c (0.15, 0.75),
         legend.title = element_text(size = 10),
         legend.text = element_text( size = 8))
```


```{r, FIG 2, Williams Lake disturbance Barkerville scenario compare, echo = F, error = F, eval = T, include = T, message = F, warning = F}
data.dist <- read.csv (here ("reports/scenarios/data", "disturbance.csv"))
data.dist <- data.dist %>%
              filter (scenario == "itchas_bau_a3_rNA" | scenario == "barkerville_bc_herd_plan_a3_r40" | 
                      scenario == "barkerville_eccc_a3_r40" | scenario == "barkerville_bc_herd_plan_a3_r30" |
                      scenario == "barkerville_eccc_a3_r30" | scenario == "barkerville_nh_crit_aNA_rNA") %>%
              filter (critical_hab == "Barkerville HEWSR" | critical_hab == "Barkerville Matrix")
data.dist$scenario <- ordered (data.dist$scenario, 
                               levels = c ("barkerville_nh_crit_aNA_rNA", "itchas_bau_a3_rNA", 
                                         "barkerville_bc_herd_plan_a3_r40", "barkerville_eccc_a3_r40",
                                         "barkerville_bc_herd_plan_a3_r30", "barkerville_eccc_a3_r30"))
data.dist.wl <- data.dist %>%
                    filter (compartment == "Williams_Lake_TSA")

ggplot (data.dist.wl, aes (x = timeperiod, y = dist500_per, color = scenario, linetype = scenario)) +
  geom_line (position = position_dodge (width = 1)) + 
  facet_grid (. ~critical_hab) +
  labs (title = "Figure 2. Proportion of Area Disturbed in Barkerville Critical Habitat 
in the Williams Lake TSA Under the Different Habitat Management Scenarios.", 
        x = "Future Year", 
        y = "Percent Disturbed",
        caption = "BAU = business-as-usual scenario; 
ECCC = Environment and Climate Change Canada; 
BC = British Columbia") + 
  scale_color_discrete (name = "Scenario", labels = c("No Harvest", "BAU, 3m, 0 years", "BC Herd Plan, 3m, 40 years",
                                                      "ECCC, 3m, 40 years", "BC Herd Plan, 3m, 30 years", 
                                                      "ECCC, 3m, 30 years")) +
  scale_linetype_discrete (name = "Scenario", labels = c("No Harvest", "BAU, 3m, 0 years", 
                                                         "BC Herd Plan, 3m, 40 years", "ECCC, 3m, 40 years", 
                                                         "BC Herd Plan, 3m, 30 years", "ECCC, 3m, 30 years")) +
  theme (#legend.position = c (0.15, 0.75),
         legend.title = element_text(size = 10),
         legend.text = element_text( size = 8))
```


```{r, FIG 3, Quesnel disturbance Wells Gray North scenario compare, echo = F, error = F, eval = T, include = T, message = F, warning = F}
data.dist <- read.csv (here ("reports/scenarios/data", "disturbance.csv"))
data.dist <- data.dist %>%
              filter (scenario == "itchas_bau_a3_rNA" | scenario == "wells_gray_north_nh_crit_aNA_rNA" | 
                      scenario == "wgn_eccc_a3_r40" | scenario == "wgn_eccc_a3_r30" |
                      scenario == "wgn_bc_herd_plan_a3_r40" | scenario == "wgn_bc_herd_plan_a3_r30") %>%
              filter (critical_hab == "Wells Gray North HEWSR" | critical_hab == "Wells Gray North Matrix")
data.dist$scenario <- ordered (data.dist$scenario, 
                               levels = c ("wells_gray_north_nh_crit_aNA_rNA", "itchas_bau_a3_rNA", 
                                            "wgn_bc_herd_plan_a3_r40", "wgn_eccc_a3_r40",
                                            "wgn_bc_herd_plan_a3_r30", "wgn_eccc_a3_r30"))
data.dist.ques <- data.dist %>%
                    filter (compartment == "Quesnel_TSA")

ggplot (data.dist.ques, aes (x = timeperiod, y = dist500_per, color = scenario, linetype = scenario)) +
  geom_line (position = position_dodge (width = 1)) + 
  facet_grid (. ~critical_hab) +
  labs (title = "Figure 3. Proportion of Area Disturbed in Wells Gray North Critical Habitat 
in the Quesnel TSA Under the Different Habitat Management Scenarios.", 
        x = "Future Year", 
        y = "Percent Disturbed",
        caption = "BAU = business-as-usual scenario; 
ECCC = Environment and Climate Change Canada; 
BC = British Columbia") + 
  scale_color_discrete (name = "Scenario", labels = c("No Harvest", "BAU, 3m, 0 years", "BC Herd Plan, 3m, 40 years",
                                                      "ECCC, 3m, 40 years", "BC Herd Plan, 3m, 30 years", 
                                                      "ECCC, 3m, 30 years")) +
  scale_linetype_discrete (name = "Scenario", labels = c("No Harvest", "BAU, 3m, 0 years", 
                                                         "BC Herd Plan, 3m, 40 years", "ECCC, 3m, 40 years", 
                                                         "BC Herd Plan, 3m, 30 years", "ECCC, 3m, 30 years")) +
  theme (#legend.position = c (0.15, 0.75),
         legend.title = element_text(size = 10),
         legend.text = element_text( size = 8))
```


```{r, FIG 4, Williams Lake disturbance Wells Gray North scenario compare, echo = F, error = F, eval = T, include = T, message = F, warning = F}
data.dist <- read.csv (here ("reports/scenarios/data", "disturbance.csv"))
data.dist <- data.dist %>%
              filter (scenario == "itchas_bau_a3_rNA" | scenario == "wells_gray_north_nh_crit_aNA_rNA" | 
                      scenario == "wgn_eccc_a3_r40" | scenario == "wgn_eccc_a3_r30" |
                      scenario == "wgn_bc_herd_plan_a3_r40" | scenario == "wgn_bc_herd_plan_a3_r30") %>%
              filter (critical_hab == "Wells Gray North HEWSR" | critical_hab == "Wells Gray North Matrix")
data.dist$scenario <- ordered (data.dist$scenario, 
                               levels = c ("wells_gray_north_nh_crit_aNA_rNA", "itchas_bau_a3_rNA", 
                                            "wgn_bc_herd_plan_a3_r40", "wgn_eccc_a3_r40",
                                            "wgn_bc_herd_plan_a3_r30", "wgn_eccc_a3_r30"))
data.dist.wl <- data.dist %>%
                    filter (compartment == "Williams_Lake_TSA")

ggplot (data.dist.wl, aes (x = timeperiod, y = dist500_per, color = scenario, linetype = scenario)) +
  geom_line (position = position_dodge (width = 1)) + 
  facet_grid (. ~critical_hab) +
  labs (title = "Figure 4. Proportion of Area Disturbed in Wells Gray North  Critical Habitat 
in the Williams Lake TSA Under the Different Habitat Management Scenarios.", 
        x = "Future Year", 
        y = "Percent Disturbed",
        caption = "BAU = business-as-usual scenario; 
ECCC = Environment and Climate Change Canada; 
BC = British Columbia") + 
  scale_color_discrete (name = "Scenario", labels = c("No Harvest", "BAU, 3m, 0 years", "BC Herd Plan, 3m, 40 years",
                                                      "ECCC, 3m, 40 years", "BC Herd Plan, 3m, 30 years", 
                                                      "ECCC, 3m, 30 years")) +
  scale_linetype_discrete (name = "Scenario", labels = c("No Harvest", "BAU, 3m, 0 years", 
                                                         "BC Herd Plan, 3m, 40 years", "ECCC, 3m, 40 years", 
                                                         "BC Herd Plan, 3m, 30 years", "ECCC, 3m, 30 years")) +
  theme (#legend.position = c (0.15, 0.75),
         legend.title = element_text(size = 10),
         legend.text = element_text( size = 8))
```


