---
title: "Moose model ideas"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

- here are some ideas and lit. review about how to go about developing a 'moose model' for caribou recovery

## Possible Approaches
- Doug Lewis model:
  - models moose forage supply (eg. kg/ha) as a function of forest age by BEC type
  - could be used as an indicator of moose population carrying capacity (i.e., max density) in an area
  - could be used to show 'bottom-up' efefct of forest harvest on moose density and consequently wolf 
    density and ultimately predation risk for caribou
  - general idea would be to calculate forage value of a ha based on BEC type and forest age, then sum 
    those values for whatever area of interest to calculate total forage available
    - then need some literature to covnert forage to moose density
    - can use the Fuller and/or Kuzyk wolf modesl to convert moose biomass to wolf density 

- Schneidman (2018) moose RSF model (http://web.unbc.ca/~michael/Pubs/Scheideman_MSc_Thesis.pdf)
  - some study areas overlap/adjacent to caribou areas:
    - PG South near Narrow Lake
    - Entiako near Tweedsmuir/Itcha
  - five seasons:
    - late winter (Jan 15 to Apr 25)
    - calving (Apr 26 to Jun 20)
    - summer (June 21 to Sept 12)
    - fall (Sept 13 to Nov 20)
    - early winter (Nov 21 to Jan 14)
  - fit second and third order models using logistic regression and evaluated model fit using AIC

  - second-order models (note for multi-models: I've added the model weigth as a multiplier to the 
    coefficient value):
    - Entiako 
      - Late Winter: wx = exp ((HR * 0.9))
      - Calving: wx = exp ((HR * 0.72))
      - Summer: wx = exp ((HR * 0.72))
      - Fall: wx = exp ((CO * (13.08 * 0.45)) + (PI * (9.29 * 0.45)) + (D * (41.97 * 0.45)) +
                        (W * (27.52 * 0.45)) + (NC * ((7.34 * 0.55) + (9.77 * 0.45))) + 
                        (OC * (14 * 0.45)) + (FP * (16.96 * 0.45)) + (FO * (-23.23 * 0.45)) +
                        (OF * (13.02 * 0.45)) + (RD * ((-0.91 * 0.55) + (0.63 * 0.45))) + 
                        (HR * ((0.5 * 0.55) + (0.97 * 0.45))))  
      - Early Winter:  wx = exp ((NC * (4.97 * 0.63)) + (RD * (0 * 0.63)) + 
                                (HR * ((0.7 * 0.63) + (0.66 * 0.37))))
    - PG South
      - Late Winter: wx = exp ((CO * (2.97 * 0.31)) + (PI * (1.08 * 0.31)) + (D * (2.27 * 0.31)) +
                               (W * (-3.12 * 0.31)) + (NC * ((2.57 * 0.31) + (0.38 * 0.19))) +
                               (OC * (1.25 * 0.31)) + (FP * (5.25 * 0.31)) + (FO * (4.64 * 0.31)) +
                               (OF * (37.32 * 0.31)) + (RD * ((-0.22 * 0.31) + (-0.26 * 0.19))) +
                               (HR * ((0.73 * 0.31) + (0.55 * 0.5) + (0.57 * 0.19))))
      - Calving: wx = exp ((RD * ((-0.29 * 0.32) + (-0.42 * 0.3))) + (MF * (-1.18 * 0.3)) +
                           (W * (2.15 * 0.2)) + (HR * (0.12 * 0.18)))
      - Summer: wx = exp ((NC * (1.52 * 0.39)) + (FP * (4.37 * 0.39)) + (FO * (-1.87 * 0.39)) +
                          (RD * ((-0.44 * 0.39) + (-0.46 * 0.34) + (-0.6 * 0.27))) +
                          (MF * (-1.21 * 0.27)))
      - Fall: wx = exp ((CO * (15.13 * 0.64)) + (PI * (19.25 * 0.64)) + (D * (23.94 * 0.64)) +
                               (W * (5.41 * 0.64)) + (NC * (18.23 * 0.64)) +
                               (OC * (14.53 * 0.64)) + (FP * (26.02 * 0.64)) + (FO * (7.82 * 0.64)) +
                               (OF * (-4 * 0.64)) + (RD * ((-0.6 * 0.64) + (-0.73 * 0.36))) +
                               (HR * ((0.23 * 0.64))
      - Early Winter:  wx = exp ((D * 3.98) + (W * -15.19) + (NC * 5.43) + (OC * -3.06) +
                                 (FO * 4.78) + (OF * -630.91))                     
            
        - CO = Conifer = proportion of >50% leading non-pine conifer spp. in home range, from VRI
        - PI = Pine = proportion of >50% leading pine spp. in home range, from VRI
        - D = Deciduous = proportion of >50% leading deciduous or tall shrub spp. in home range, from 
          VRI
        - W = Water = proportion of water features and permanent wet areas (riparian areas, emergent 
          and submergent veg, open water) in home range, from fwa_wetlands_poly and fwa_lakes_poly
        - NC = New cutblock = proportion of logged =< 15 years in home range
        - OC = old cutblock = proportion oflogged > 15 years and <31 years in home range
        - FP = Pine Fire = proportion ofpine leading and burned =< 15 years in home range
        - FO = Other Fire = proportion ofnon-pine leading and burned =< 15 years in home range
        - OF = Old Fire = proportion of burned > 15 years and <31 years in home range
        - HR = habitat richness = number of distinct veg over classes except for road density and 
          mature forest in home range
        - RD = road density = km/km2 in home range
        - MF = mature forest = proportion of CO + PI + D in home range
     
     - would need to calculate covariate values at home range scale (km2):
         - Entiako 
            - Late Winter: 12
            - Calving: 20
            - Summer: 42
            - Fall: 37
            - Early Winter: 37
         - PG South
            - Late Winter: 13
            - Calving: 23
            - Summer: 27
            - Fall: 20
            - Early Winter: 18

  - third-order models (note for multi-models: I've added the model weigth as a multiplier to the 
    coefficient value):
     - Entiako 
      - Late Winter: wx = exp (((-4.48 * 0.52) + (-4.54 * 0.48)) +
                               (ELVkm * ((5.42 * 0.52) + (5.52 * 0.48))) + 
                               (ELVkm2 * ((-2.46 * 0.52) + (-2.50 * 0.48))) +
                               (east * ((-0.03 * 0.52) + (-0.03 * 0.48))) +
                               (north * ((-0.06 * 0.52) + (-0.06 * 0.48))) +
                               (conifer * ((0.11 * 0.52) + (0.11 * 0.48))) +
                               (decid * ((0.32 * 0.52) + (0.32 * 0.48))) + 
                               (fire_oth * ((0.26 * 0.52) + (0.26 * 0.48))) + 
                               (fire_pine * ((-0.41 * 0.52) + (-0.41 * 0.48))) + 
                               (herb * ((0.63 * 0.52) + (0.63 * 0.48))) + 
                               (new_cut * ((-0.06 * 0.52) + (-0.06 * 0.48))) +
                               (nonveg * ((0.47 * 0.52) + (0.47 * 0.48))) + 
                               (old_cut * ((0.01 * 0.52) + (0.01 * 0.48))) +
                               (old_fire * ((0.41 * 0.52) + (0.41 * 0.48))) +
                               (pine * ((-0.22 * 0.52) + (-0.22 * 0.48))) + 
                               (urban * ((-1.95 * 0.52) + (-1.95 * 0.48))) + 
                               (dist_rd * (0.00 * 0.48)) + (wet * (0.44 * 0.52)) +
                               (cover * ((0.02 * 0.52) + (0.02 * 0.48))))  
      
      - Calving: wx = exp (((-3.47 * 0.52) + (-3.50 * 0.48)) +
                               (ELVkm * ((3.90 * 0.52) + (3.75 * 0.48))) + 
                               (ELVkm2 * ((-1.80 * 0.52) + (-1.73 * 0.48))) +
                               (east * ((0.11 * 0.52) + (0.11 * 0.48))) +
                               (north * ((-0.11 * 0.52) + (-0.11 * 0.48))) +
                               (conifer * ((-0.07 * 0.52) + (-0.07 * 0.48))) +
                               (decid * ((0.59 * 0.52) + (0.60 * 0.48))) + 
                               (fire_oth * ((0.24 * 0.52) + (0.22 * 0.48))) + 
                               (fire_pine * ((-0.20 * 0.52) + (-0.24 * 0.48))) + 
                               (herb * ((0.97 * 0.52) + (0.98 * 0.48))) + 
                               (new_cut * ((-0.12 * 0.52) + (-0.12 * 0.48))) +
                               (old_cut * ((-0.65 * 0.52) + (-0.65 * 0.48))) +
                               (pine * ((-0.16 * 0.52) + (-0.16 * 0.48))) + 
                               (urban * ((-0.55 * 0.52) + (-0.55 * 0.48))) + 
                               (wet * ((-0.03 * 0.52) + (-0.03 * 0.48))) +
                               (dist_mature * (-0.02 * 0.52)))  

      - Summer: wx = exp (((-3.79 * 0.37) + (-3.83 * 0.36) + (-3.80 * 0.27)) +
                               (ELVkm * ((3.83 * 0.37) + (3.92 * 0.36) + (3.85 * 0.27))) + 
                               (ELVkm2 * ((-1.74 * 0.37) + (-1.78 * 0.36) + (-1.74 * 0.27))) +
                               (east * ((0.00 * 0.37) + (0.00 * 0.36) + (0.00 * 0.27))) +
                               (north * ((0.00 * 0.37) + (0.00 * 0.36) + (0.00 * 0.27))) +
                               (alpine * ((-0.65 * 0.37) + (-0.64 * 0.36) + (-0.65 * 0.27))) +
                               (conifer * ((0.29 * 0.37) + (0.28 * 0.36) + (0.29 * 0.27))) +
                               (decid * ((0.20 * 0.37) + (0.20 * 0.36) + (0.20 * 0.27))) +
                               (fire_oth * ((0.23 * 0.37) + (0.24 * 0.36) + (0.23 * 0.27))) +
                               (fire_pine * ((-0.06 * 0.37) + (-0.03 * 0.36) + (-0.06 * 0.27))) +
                               (herb * ((0.14 * 0.37) + (0.13 * 0.36) + (0.14 * 0.27))) +
                               (new_cut * ((-0.30 * 0.37) + (-0.31 * 0.36) + (-0.30 * 0.27))) +
                               (old_cut * ((-0.10 * 0.37) + (-0.11 * 0.36) + (-0.10 * 0.27))) +
                               (fire_old * ((0.17 * 0.37) + (0.16 * 0.36) + (0.17 * 0.27))) +
                               (pine * ((0.14 * 0.37) + (0.14 * 0.36) + (0.14 * 0.27))) +
                               (wet * ((-0.06 * 0.37) + (-0.06 * 0.36) + (-0.06 * 0.27))) +
                               (dist_mature * (0.01 * 0.37)) +
                               (escape * (0.01 * 0.37)))
      
    - Fall: wx = exp (((-1.77 * 0.71) + (-1.72 * 0.29)) +
                       (ELVkm * ((0.45 * 0.71) + (0.35 * 0.29))) + 
                       (ELVkm2 * ((-0.27 * 0.71) + (-0.23 * 0.29))) +        
                       (east * ((0.03 * 0.71) + (0.03 * 0.29))) +        
                       (north * ((0.04 * 0.71) + (0.04 * 0.29))) +         
                       (alpine * ((-0.16 * 0.71) + (-0.15 * 0.29))) +          
                       (conifer * ((0.18 * 0.71) + (0.19 * 0.29))) +         
                       (decid * ((0.28 * 0.71) + (0.28 * 0.29))) +        
                       (fire_oth * ((0.21 * 0.71) + (0.21 * 0.29))) +        
                       (fire_pine * ((-0.10 * 0.71) + (-0.10 * 0.29))) +         
                       (herb * ((0.39 * 0.71) + (0.39 * 0.29))) +        
                       (new_cut * ((0.01 * 0.71) + (0.00 * 0.29))) +  
                       (old_cut * ((-0.31 * 0.71) + (-0.32 * 0.29))) +  
                       (fire_old * ((-0.39 * 0.71) + (-0.40 * 0.29))) +  
                       (pine * ((-0.04 * 0.71) + (-0.04 * 0.29))) + 
                       (wet * -0.06) + 
                       (dist_roadkm * 0.00)) 

    - Early Winter: wx = exp (-3.97 +
                               (ELVkm * 4.30) + 
                               (ELVkm2 * -1.76) +        
                               (east * 0.01) +        
                               (north * 0.00) +         
                               (conifer * -0.40) +         
                               (decid * 0.18) +        
                               (fire_oth * 0.13) +        
                               (fire_pine * -0.76) +         
                               (herb * 0.79) +        
                               (new_cut * 0.08) +  
                               (old_cut * -0.20) +  
                               (fire_old * 0.33) +  
                               (pine * -0.71) + 
                               (wet * 0.56) + 
                               (dist_roadkm * 0.01) +
                               (dist_mature * 0.04)) 

  - PG South 
    -  Late Winter: wx = exp (((-2.54 * 0.47) + (-2.53 * 0.34) + (-2.53 * 0.19)) +
                                (ELVkm * ((1.76 * 0.47) + (1.76 * 0.34) + (1.75 * 0.19))) +
                                (ELVkm2 * ((-1.17 * 0.47) + (-1.16 * 0.34) + (-1.17 * 0.19))) +
                                (east * ((-0.03 * 0.47) + (-0.03 * 0.34) + (-0.03 * 0.19))) +
                                (north * ((0.11 * 0.47) + (0.11 * 0.34) + (0.11 * 0.19))) +
                                (conifer * ((0.16 * 0.47) + (0.17 * 0.34) + (0.17 * 0.19))) +
                                (decid * ((0.32 * 0.47) + (0.33 * 0.34) + (0.32 * 0.19))) +
                                (fire_oth * ((-0.07 * 0.47) + (-0.08 * 0.34) + (-0.06 * 0.19))) +
                                (fire_pine * ((0.11 * 0.47) + (0.11 * 0.34) + (0.11 * 0.19))) +
                                (herb * ((-0.72 * 0.47) + (-0.73 * 0.34) + (-0.73 * 0.19))) +
                                (new_cut * ((0.46 * 0.47) + (0.45 * 0.34) + (0.46 * 0.19))) +
                                (old_cut * ((0.18 * 0.47) + (0.17 * 0.34) + (0.17 * 0.19))) +
                                (fire_old * ((0.36 * 0.47) + (0.36 * 0.34) + (0.35 * 0.19))) +
                                (pine * ((0.22 * 0.47) + (0.22 * 0.34) + (0.22 * 0.19))) +
                                (urban * ((-1.40 * 0.47) + (-1.40 * 0.34) + (-1.41 * 0.19))) +
                                (wet * ((0.39 * 0.47) + (0.40 * 0.34) + (0.39 * 0.19))) +
                                (dist_roadkm * ((0.09 * 0.47) + (0.10 * 0.19))) +
                                (dist_mature * ((0.05 * 0.47) + (0.05 * 0.34))) +
                                (escape * 0.05)) 
                      
    - Calving: wx = exp (((-1.65 * 0.70) + (-1.73 * 0.30)) +           
                          (ELVkm * ((-0.34 * 0.70) + (-0.19 * 0.30))) +
                          (ELVkm2 * ((0.27 * 0.70) + (0.16 * 0.30))) +
                          (east * ((0.03 * 0.70) + (0.03 * 0.30))) +
                          (north * ((-0.06 * 0.70) + (-0.06 * 0.30))) +
                          (conifer * ((0.25 * 0.70) + (0.24 * 0.30))) +
                          (decid * ((0.28 * 0.70) + (0.27 * 0.30))) +
                          (fire_oth * ((-0.13 * 0.70) + (-0.11 * 0.30))) +
                          (fire_pine * ((0.13 * 0.70) + (0.12 * 0.30))) +
                          (herb * ((-0.35 * 0.70) + (-0.34 * 0.30))) +
                          (new_cut * ((0.05 * 0.70) + (0.07 * 0.30))) +
                          (old_cut * ((-0.03 * 0.70) + (-0.01 * 0.30))) +
                          (pine * ((0.07 * 0.70) + (0.05 * 0.30))) +
                          (urban * ((-1.39 * 0.70) + (-1.38 * 0.30))) +
                          (wet * ((1.12 * 0.70) + (1.09 * 0.30))) +
                          (dist_roadkm * -0.17)) 

      - Summer: wx = exp (((-2.57 * 0.61) + (-2.36 * 0.39)) +
                           (ELVkm * ((1.40 * 0.61) + (0.93 * 0.39))) +
                           (ELVkm2 * ((-0.84 * 0.61) + (-0.54 * 0.39))) +
                           (east * ((0.01 * 0.61) + (0.01 * 0.39))) +
                           (north * ((0.10 * 0.61) + (0.10 * 0.39))) +
                           (conifer * ((0.51 * 0.61) + (0.52 * 0.39))) +
                           (decid * ((0.39 * 0.61) + (0.39 * 0.39))) +
                           (fire_oth * ((0.24 * 0.61) + (0.24 * 0.39))) +
                           (fire_pine * ((0.22 * 0.61) + (0.23 * 0.39))) +
                           (herb * ((-0.65 * 0.61) + (-0.65 * 0.39))) +
                           (new_cut * ((-0.06 * 0.61) + (-0.08 * 0.39))) +
                           (old_cut * ((0.34 * 0.61) + (0.32 * 0.39))) +
                           (pine * ((0.38 * 0.61) + (0.39 * 0.39))) +
                           (urban * ((-2.29 * 0.61) + (-2.30 * 0.39))) +
                           (wet * ((0.92 * 0.61) + (0.93 * 0.39))) +
                           (dist_roadkm * 0.12)) 

    - Fall: wx = exp (((-1.41 * 0.65) + (-1.34 * 0.35)) +
                       (ELVkm * ((-1.00 * 0.65) + (-1.15 * 0.35))) +
                       (ELVkm2 * ((0.45 * 0.65) + (0.57 * 0.35))) +
                       (east * ((0.00 * 0.65) + (0.00 * 0.35))) +
                       (north * ((0.06 * 0.65) + (0.06 * 0.35))) +
                       (conifer * ((0.34 * 0.65) + (0.35 * 0.35))) +
                       (decid * ((0.24 * 0.65) + (0.25 * 0.35))) +
                       (fire_oth * ((0.19 * 0.65) + (0.18 * 0.35))) +
                       (fire_pine * ((0.84 * 0.65) + (0.85 * 0.35))) +
                       (herb * ((-0.84 * 0.65) + (-0.84 * 0.35))) +
                       (new_cut * ((0.51 * 0.65) + (0.49 * 0.35))) +
                       (old_cut * ((-0.04 * 0.65) + (-0.06 * 0.35))) +
                       (pine * ((0.28 * 0.65) + (0.30 * 0.35))) +
                       (urban * ((-1.73 * 0.65) + (-1.74 * 0.35))) +
                       (wet * ((0.21 * 0.65) + (0.23 * 0.35))) +
                       (dist_roadkm * 0.12) +
                       (dist_mature * ((-0.09 * 0.65) + (-0.09 * 0.35))))

- Early Winter: wx = exp (((-1.01 * 0.51) + (-1.04 * 0.28) + (-1.01 * 0.21)) +
                           (ELVkm * ((-2.21 * 0.51) + (-2.17 * 0.28) + (-2.26 * 0.21))) +
                           (ELVkm2 * ((1.30 * 0.51) + (1.25 * 0.28) + (1.33 * 0.21))) +
                           (east * ((0.03 * 0.51) + (0.03 * 0.28) + (0.03 * 0.21))) +
                           (north * ((0.06 * 0.51) + (0.06 * 0.28) + (0.06 * 0.21))) +
                           (conifer * ((-0.16 * 0.51) + (-0.17 * 0.28) + (-0.14 * 0.21))) +
                           (decid * ((0.18 * 0.51) + (0.17 * 0.28) + (0.20 * 0.21))) +
                           (fire_oth * ((0.40 * 0.51) + (0.41 * 0.28) + (0.33 * 0.21))) +
                           (fire_pine * ((0.26 * 0.51) + (0.24 * 0.28) + (0.19 * 0.21))) +
                           (herb * ((-0.33 * 0.51) + (-0.32 * 0.28) + (-0.31 * 0.21))) +
                           (new_cut * ((0.97 * 0.51) + (0.99 * 0.28) + (0.99 * 0.21))) +
                           (old_cut * ((-0.16 * 0.51) + (-0.13 * 0.28) + (-0.14 * 0.21))) +
                           (pine * ((-0.10 * 0.51) + (-0.12 * 0.28) + (-0.08 * 0.21))) +
                           (urban * ((-1.34 * 0.51) + (-1.33 * 0.28) + (-1.32 * 0.21))) +
                           (wet * ((0.29 * 0.51) + (0.27 * 0.28))) +
                           (dist_roadkm * ((-0.19 * 0.51) + (-0.19 * 0.28))) +
                           (dist_mature * 0.04))

CONTINUOUS:
- ELVkm = elevation in km, measured from provincial 25m DEM
- ELVkm2 = elevation in km, squared, measured from provincial 25m DEM
- east = eastness = sine of aspect, slopes <5 = 0, derived from provincial 25m DEM
- north = northness = cosine of aspect, slopes <5 = 0, derived from provincial 25m DEM
- dist_roadkm = distance to road in km; roads data from mutiple sources, including dra, trim, petrlm 
- dist_mature = distance to edge of mature conifer, pine or deciduous forest stands in km
- escape = distance to edge of mature conifer, pine or deciduous forest stands in km, from 'open' (new   cutblock, pine fire and wet) sites

CLASS:
- alpine = above treeline, dominated by shrubs, measured from VRI????
- conifer = non-pine conifer leading (>50%) stands, measured from VRI veg_comp_poly
- pine = pine leading (>50%) stands, measured from VRI veg_comp_poly
- decid = deciduous = deciduous and tall shrub leading (>50%) stands, 
  measured from VRI veg_comp_poly
- wet = permanent wet areas from fwa_wetlands_poly an fwa_lakes_poly
- new_cut = logged =< 15 years ago; cutblocks from 'results' data
- old_cut = logged > 15 years and <31 years ago; cutblocks from 'results' data
- fire_pine = wildfires burned =< 15 years ago in pine leading stand; fire from historical 
  fire polygons; pine type from VRI presumably?
- fire_oth = wildfires burned =< 15 years ago in non-pine leading stands; fire from historical 
  fire polygons
- fire_old = wildfires burned > 15 years and <31 years ago; fire from historical 
  fire polygons
- urban = agricultural areas; from VRI???
- herb = not clear for methods how this was measured; assume non-forest >50% herb cover from VRI???









- Mumma and Gillingham (2019) survival model (http://web.unbc.ca/~michael/Mumma_and_Gillingham_2019.pdf)
  - similar conceptually to an RSF, except models mortality risk or survival probabibility of cow 
    caribou (not resource selection probability) as a function of habitat
      - Cox proportional hazards model that estimates survival as a function of habitat covariates     
        using a hazard function
        - coefficients are hazard ratios
  - some study areas overlap/adjacent to caribou areas:
    - Entiako near Tweedsmuir/Itcha
    - PG South near Narrow Lake
    - West Parsnip near Wolverine, Chase
  - models fit for different mortality types:
    - wolf predation
    - hunting
    - starvation
    - other
    
  - Risk (wolf predation) = exp ((log (1.00) * RD200-1) + (log(0.56) * RD200-365) + 
                                 (log(1.34) * NC400-7) + (log(0.21) * NC400-180)) 
 
  - Risk (hunting) = exp ((log (1.62) * RD200-1) + (log(1.67) * RD200-365) + 
                          (log(49.06) * NC400-7) + (log(31.69) * NC400-180))                                 
  - Risk (starve) = exp ((log (0.97) * RD200-1) + (log(2.60) * RD200-365) + 
                         (log(1.14) * NC400-7) + (log(555.70) * NC400-180))                                 
  - Risk (other) = exp ((log (1.20) * RD200-1) + (log(1.60) * RD200-365) + 
                        (log(0.98) * NC400-7) + (log(0.27) * NC400-180))                                  
  - Surv (starve) = exp (-6.47 + (NC * 6.88))
  
    - RD = road density
    - 200-1 = within a 200 m radius from the location within the previous day
    - 200-365 = within a 200 m radius from the location within the previous year
    - NC = new cutblock, cutblocks 1-8 years old
    - 400-7 = within a 400 m radius from the location within the previous week
    - 400-180 = within a 400 m radius from the location within the previous half-year

  - RD is difficult to use in the framework of our model data, but we could do a work around where 
    we assume a roaded pixel has a some amount of road that traverses it , e.g., at a diagonal: 141m;      so, count pixels in 200m  radius, mutliply by 0.141km and divivde by 0.126km2 (for 200m radius 
    circle); that would only give you a max of ~21 pixels (I think, adn if we include partial pixels) 
    and thus max road density of ~24km/km2, which is very high; so, we could be more conservative here     and use 100m road in a roaded ha, which is 17km/km2; minimum is 1 pixel = .79km/km2, which is still     high, and equals survival of 0.62, which is quite low so we may need to be more conservative with 
    the road length assumption
  - temporal covariates also need a work around, because they measure the mean value over a 1 to 1 year
    period; 
      - for daily, we could calculate the mean density of values within the radius of a 'typical' daily         movement distance
      - for weekly, we could calculate the mean density of values within the radius of a 'typical'     
        weekly movement distance
      - for half year, we could calcuate the mean density of values within the radius of half a 
        'typical' home range
      - for annual, we could calcuate the mean density of values within the radius of a 'typical' home         range
      - movement and home range data on some of these moose in Schneidman (2018), pg. 35



