---
output: html_document
editor_options: 
  chunk_output_type: console
---
<!--
Copyright 2020 Province of British Columbia
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.-->

---
title: "Database creation for Wolverine Scenario Analysis"
author: "Kyle Lochhead"
date: "2 May 2024"
output: pdf_document
---

# Overview
-	Need timber supply impact analysis for the wolverine herd


# Usage
Set parameters for creating the database in the code chunk below.

```{r module_usage}
library (SpaDES)
library (SpaDES.core)
library (data.table)
library (keyring)
library (terra)

source (here::here("R/functions/R_Postgres.R"))

Sys.setenv(JAVA_HOME = 'C:\\Program Files\\Java\\jdk-14.0.1') #throws an error if pointing to different version of java (i.e., 32 vs 64 bit)

moduleDir <- file.path (paste0 (here::here (), "/R/SpaDES-modules"))
inputDir <- file.path (paste0 (here::here (), "/R/SpaDES-modules/fireCastor/inputs")) %>% reproducible::checkPath (create = TRUE)
outputDir <- file.path (paste0 (here::here (), "/R/SpaDES-modules/fireCastor/outputs")) %>% reproducible::checkPath (create = TRUE)


times <- list (start = 0, end = 1)
parameters <-  list (
        .progress = list (type = NA, interval = NA),
        .globals = list (),
        dataCastor = list(dbName = 'castor',
                          useCastorDB = "C:/Work/caribou/castor/R/SpaDES-modules/fireCastor/wolverine_castordb.sqlite",
                          sqlite_dbname = "wolverine", 
                          nameBoundaryFile = "public.wolverine_aoi", 
                          nameBoundaryColumn = "herd_name", 
                          nameBoundary = "Wolverine", 
                          nameBoundaryGeom = 'wkb_geometry',
                          nameCompartmentRaster = "rast.wolverine_boundary", 
                          nameCompartmentTable = "vat.wolverine_boundary", 
                          nameMaskHarvestLandbaseRaster = 'rast.bc_thlb2022', 
                          nameZoneRasters = c ("rast.zone_cond_beo", 
                                               "rast.zone_cond_vqo", 
                                               "rast.zone_wha_2021", 
                                               "rast.zone_uwr_2021",  
                                               "rast.zone_cond_nharv", 
                                               "rast.zone_cond_fsw", 
                                               "rast.zone_cond_cw",
                                               "rast.zone_cond_wolverine_crit",
                                               "rast.wolverine_he",
                                               "rast.wolverine_le",
                                               "rast.wolverine_bma_aoi",
                                               "rast.wolverine_bma_in_cpa",
                                               "rast.wolverine_cpa"
                                               # TAP proposed old growth deferral areas
                                               #"rast.zone_cond_pri_old_deferral"
                                               ),
                          nameZoneTable = "zone.constraints", 
                          # natural and managed stands yield curves are the same    
                          nameYieldsRaster = "rast.ycid_vdyp_2020", 
                          nameYieldTable = "yc_vdyp_2020", 
                          nameYieldsCurrentRaster = "rast.ycid_tipsy_current_2020",
                          nameYieldCurrentTable = "tipsy_prov_current_2020",
                          nameYieldsTransitionRaster = "rast.ycid_tipsy_prov_2020", 
                          nameYieldTransitionTable = "tipsy_prov_2020",  
                          nameForestInventoryRaster = "rast.vri2023_id", 
                          nameForestInventoryKey = "feature_id", 
                          nameForestInventoryTable = "vri.veg_comp_lyr_r1_poly2023",
                          nameForestInventoryAge = "proj_age_1",  
                          nameForestInventoryHeight = "proj_height_1",
                          nameForestInventoryCrownClosure = "crown_closure",                             
                          nameForestInventoryTreed = "bclcs_level_2",
                          nameForestInventoryBasalArea= "basal_area",
                          nameForestInventoryQMD = "quad_diam_125",
                          nameForestInventorySiteIndex = "site_index" 
                          ),
        growingStockCastor = list (periodLength = 1),
        blockingCastor = list(blockMethod = 'pre', 
                              patchZone = 'rast.zone_cond_beo',
                              patchVariation = 6,
                              nameCutblockRaster ="rast.cns_cutblk_2023",
                              useLandingsArea = FALSE),
        roadCastor = list (roadMethod = 'mst',
                           nameCostSurfaceRas = 'rast.rd_cost_surface',
                           nameRoads =  'rast.ce_road_2022'
                           ),
        forestryCastor = list(harvestBlockPriority = " dist, age DESC ", 
                              #adjacencyConstraint = 3,
                        reportHarvestConstraints = T,
                        activeZoneConstraint = c("rast.zone_cond_beo", 
                                                 "rast.zone_cond_vqo", 
                                                 "rast.zone_wha_2021", 
                                                 "rast.zone_uwr_2021",  
                                                 "rast.zone_cond_nharv", 
                                                 "rast.zone_cond_fsw", 
                                                 "rast.zone_cond_cw",
                                                 "rast.wolverine_he",
                                                 "rast.wolverine_le")
                           ),
        survivalCastor = list (caribou_herd_density = 0.05, 
                               nameRasCaribouHerd = "rast.caribou_herd_20220725", 
                               tableCaribouHerd = "vat.caribou_herd_20220725"),
        smcpopCastor = list (nameRasSMCHerd = "rast.smc_herd_habitat", 
                             tableSMCCoeffs = "vat.smc_coeffs"),
        disturbanceCastor = list(calculateInterval =  1, 
                                 criticalHabitatTable = "vat.zone_cond_wolverine_crit",
                                 criticalHabRaster = "rast.zone_cond_wolverine_crit",
                                 permDisturbanceRaster = "rast.mine_ag_wind_rail",
                                 recovery = 30), 
        climateCastor = list(calculateInterval = 1,
                    climateData = "observed", # only put this in if you want observed data
                    gcm = c("climatena"),
                    gcmname = "climatena",#c("MPI"), 
                    ssp = "none",#c("ssp370"),
                    run = "none",#c("r10i1p1f1"),
                    climateYears = 2021: 2023, # note the start year needs to be 2 yrs before your year of interest to calculate CMI3yr
                    maxRun = 3, 
                    nameClimateIdnoRast = "rast.climate_prism_base_layer",
                    nameClimateTable = "vat.climate_prism_lat_lon_lookup",
                    vars_aoi=c("PPT_03","PPT_04", "PPT_05","PPT_06","PPT_07", "PPT_08", "PPT_09","Tmax_04", "Tmax_05", "Tmax_06", "Tmax_07", "Tmax_08", "Tmax_09", "Tave_03","Tave_04", "Tave_05", "Tave_06", "Tave_07", "Tave_08", "Tave_09", "Tmin_03", "Tmin_04", "Tmin_05", "Tmin_06", "Tmin_07", "Tmin_08" ,"CMD_04", "CMD_05", "CMD_06", "CMD_07", "CMD_08", "CMI_03", "CMI_04", "CMI_05", "CMI_06", "CMI_07", "CMI_08", "CMI_09"),
                   nameProvCMITable = "public.prov_cmi_ave",
                   vars_prov = c("CMI05", "CMI06", "CMI07", "CMI08"),
                   nameProvCMITable = "public.prov_cmi_ave",
                   vars_prov = c("CMI05", "CMI06", "CMI07", "CMI08")),
                    
  fireCastor = list(calculateInterval =1,
                    ignitionMethod = 'poissonProcess', # options are poissonProcess, historicalDist, static
                    #calendarStartYear = 2020,
                    nameFrtRaster = "rast.frt",
                    nameAspectRaster = "rast.bc_ha_aspect",
                    nameSlopeRaster = "rast.bc_ha_slope",
                    nameDistInfrastructureRaster = "rast.dist_infrastructure",
                    nameRoadsRast = "rast.ce_road_2019",
                    #recovery = 300,
                    nameElevationRaster = "rast.dem",
                    nameClimateIdnoRast="rast.climate_prism_base_layer",
                    nameClimateTable = "vat.climate_prism_lat_lon_lookup",
                    simStartYear = 2022,
                    nameBecRast = "rast.bec_current",
                    nameBecTable = "vat.bec_zone_vat",
                    nameForestInventoryRaster = "rast.vri2023_id",
                    nameForestInventoryTable = "vri.veg_comp_lyr_r1_poly2023",
                    nameForestInventoryKey = "feature_id",
                    nameForestInventorybclcs_level_1 = "bclcs_level_1",
                    nameForestInventorybec_zone_code = '99999',
                    pixelid_10kmRast = "rast.pixelId10km",
                    nameFirepixel10km = "vat.spatially_varying_10km_vat",
                    numberFireReps = 1,
                    nameRoadsRast =  'rast.ce_road_2019'),
        volumebyareaReportCastor = list (calculateInterval = 1,
                                         AreaofInterestRaster = "rast.tsa_aac_boundary",
                                         AreaofInterestTable = "vat.tsa_aac_boundary"),
        uploadCastor = list(aoiName = 'wolverine_5scen',
                              dbInfo  = list(keyring::key_get ("vmdbhost", keyring="postgreSQL"),
                                             keyring::key_get ("vmdbuser", keyring="postgreSQL"),
                                             keyring::key_get ("vmdbpass", keyring="postgreSQL"), 
                                             keyring::key_get ("vmdbname", keyring="postgreSQL")))
        )

#scenario = data.table (name = "bau_og_def_road10", description = "Business as usual (BAU) sustainable. Adjacency = 3m. Priority queue = Closest to disturbance first, oldest second. Minimum volume: 125 m3/year. Even live harvest flow: 660,000 m3/year. Growing stock sustainable (flat) at year 100-200, or similar growing stock value at start and end of sim. road recovery (10 years).")

scenario = data.table (name = "le_no_harvesting",
                       description = "No harvesting in high or low elevation habitat. Priority queue = Closest to disturbance first, oldest second. Minimum volume: 125 m3/year. Even live harvest flow: 179,700 m3/year. Growing stock sustainable (flat) at year 100-200, or similar growing stock value at start and end of sim. Road recovery (30 years).")

modules <- list("dataCastor",
                "growingStockCastor",
                "blockingCastor", 
                "roadCastor",
                #"survivalCastor",
                "disturbanceCastor",
                #"volumebyareaReportCastor",
                "forestryCastor",
                "climateCastor",
                "fireCastor"
                #"uploadCastor"
                )

harvestFlow <- rbindlist(list(
                              data.table (compartment ="Wolverine",
                                          partition = ' vol > 125 AND age >= 80 ', 
                                          period = rep( seq (from = 1,
                                                           to = 20,
                                                           by = 1),
                                                     1),
                                          partition_type = 'live',
                                          flow = 179700 ) # 12497440 LRSY; 6185000 bau; 4930000 bma in cpa;   4099000cpa;  l3150000 bma aoi; 1797000 no harv le
                              #note I divided flow by 10 because period length was reduced from 10 to 1
                              ))

objects <- list(harvestFlow = harvestFlow, 
                scenario = scenario)

paths <- list(modulePath = moduleDir,
              inputPath = inputDir,
              outputPath = outputDir)

inputs <- list()
outputs <- list()

mySim <- simInit(times = times, 
                 params = parameters, 
                 modules = modules,
                 objects = objects,
                 paths = paths)

# outputs to keep; these are tables that get used in the uploader
outputs(mySim) <- data.frame (objectName = c("harvestReport",
                                             "growingStockReport",
                                             "tableSurvival",
                                             "disturbanceReport",
                                             "volumebyareaReport",
                                             "tableAbundanceReport",
                                             "firedisturbanceTable", 
                                             "fireReport"
                                             ))

system.time({
mysimout<-spades(mySim)
})

```
```{r}
saveRDS(mySim$fireReport,"C:/Work/caribou/castor/R/SpaDES-modules/fireCastor/outputs/fireReport_year1_rep21.rds")

saveRDS(mySim$firedisturbanceTable,"C:/Work/caribou/castor/R/SpaDES-modules/fireCastor/outputs/firedisturbanceTable_year1_rep21.rds")

```


```{r}

require(data.table)

df <- list.files(path="C:/Work/caribou/castor/R/SpaDES-modules/fireCastor/outputs/", pattern = "firedisturbanceTable",full.names=T) %>%
 map_dfc(readRDS)

df$summary<-
  df$numberTimesBurned...4+
  df$numberTimesBurned...8+
  df$numberTimesBurned...12+
  df$numberTimesBurned...16+
  df$numberTimesBurned...20+
  df$numberTimesBurned...24+
  df$numberTimesBurned...28+
  df$numberTimesBurned...32+
  df$numberTimesBurned...36+
  df$numberTimesBurned...40+
  df$numberTimesBurned...44+
  df$numberTimesBurned...48+
  df$numberTimesBurned...52+
  df$numberTimesBurned...56+
  df$numberTimesBurned...60+
  df$numberTimesBurned...64+
  df$numberTimesBurned...68+
  df$numberTimesBurned...72+
  df$numberTimesBurned...76+
  df$numberTimesBurned...80+
  df$numberTimesBurned...84+
  df$numberTimesBurned...88

df<-data.table(df)
df<-df[order(pixelid...3)]

library(RSQLite)

sqlite <- dbDriver("SQLite")


castordb <- dbConnect(sqlite,"C:/Work/caribou/castor/R/SpaDES-modules/fireCastor/wolverine_castordb.sqlite")
ras.info<-dbGetQuery(castordb, "Select * from raster_info limit 1;")
areaBurned<-raster(extent(ras.info$xmin, ras.info$xmax, ras.info$ymin, ras.info$ymax), nrow = ras.info$nrow, ncol = ras.info$ncell/ras.info$nrow, vals =0)
    
areaBurned[]<-df$summary

plot(areaBurned)
plot(st_geometry(study_area), add= TRUE,)
plot(study_area, add=TRUE)


```

```{r}
df <- list.files(path="C:/Work/caribou/castor/R/SpaDES-modules/fireCastor/outputs/", pattern = "fireReport",full.names=T) %>%
 map_dfr(readRDS)

plot(
  density(df$totalareaburned ), 
  main="Density Plot of Area burned",
  xlab="Area (ha)", ylab="Density",
  xlim=c(0, 4000)
  )


```

```{r, echo=TRUE}
# get latest data off BCGW
require (dplyr)
library(bcdata)

ignit<-try(
  bcdc_query_geodata("WHSE_LAND_AND_NATURAL_RESOURCE.PROT_CURRENT_FIRE_POLYS_SP") %>%
    filter(FIRE_YEAR > 2023) %>%
    collect()
)

ignit<-st_transform (ignit, 3005)

names(ignit)

ggplot() +
  geom_sf(data=study_area) + 
  geom_sf(data=ignit)


st_write(ignit, dsn = "C:/Work/caribou/castor/R/SpaDES-modules/fireCastor/outputs/ignit2023.shp", driver = "ESRI Shapefile")




# get study area
study_area<-getSpatialQuery("SELECT herd_name, wkb_geometry FROM public.wolverine_aoi where herd_name in ('Wolverine')")

ignit_subset <- ignit[study_area, ]
```


