---
title: "test2"
author: ""
date: "04 March 2020"
output: pdf_document
---

# Overview

Provide an overview of what the module does / how to use the module.

Module documentation should be written so that others can use your module.
This is a template for module documentation, and should be changed to reflect your module.

## R Markdown

R Markdown syntax allows R code, outputs, and figures to be rendered in the documentation.

For help writing in R Markdown, see http://rmarkdown.rstudio.com/.

# Usage

```{r module_usage}
library(SpaDES)

setPaths(modulePath = file.path(paste0(here::here(), "/R/SpaDES-modules")))
getPaths() # shows where the 4 relevant paths are

times <- list(start = 0, end = 2)

parameters <-  list(
  .progress = list(type = NA, interval = NA),
  .globals = list(),
  test2 = list(dbName='test',
              save_db= TRUE
                    ))

modules <- list("test2","test")
objects <- list()
inputs <- list()
outputs <- list()

mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects)

mySimOut <- spades(mySim)
```

# Events

Describe what happens for each event type.

## Plotting

Write what is plotted.

## Saving

Write what is saved.

# Data dependencies

## Input data

How to obtain input data, and a description of the data required by the module.
If `sourceURL` is specified, `downloadData("test2", "path/to/modules/dir")` may be sufficient.

## Output data

Description of the module outputs.

# Links to other modules

Describe any anticipated linkages to other modules.
