---
title: "Getting Started with CLUS"
author: "Tyler Muhly"
date: "04/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Introduction and Background
Here we document how to get started using the caribou and land use simulator (CLUS) model. This provides the basic instructions for implementing and running a scenario on CLUS.

Fundamentally, the CLUS model is a forest harvest simulator with the ability to flexibly "constrain" areas of the landscape to simulate alternative forest management regimes. These alternative regimes constitute specified areas ('zones') with defined forest targets (e.g., percentage area of a certain forest age). Thus, it can be used to test how alternative forest management zones influence the spatial distribution and rate (i.e., annual volume cut) of forest harvest. However, CLUS also includes various modules that provide caribou-specific indicators. Thus, the CLUS model can also be used to estimate the influence of alternative forest management regimes on caribou. Below we provide instructions for implementing a forest harvest scenario in CLUS. We provide the basic structure of the model, including data and parameter inputs needed to run the model.

## Model "Software" and Framework
CLUS is primarily built using the [R programming language](https://www.r-project.org/), supplemented with some JAVA in the module to create harvest blocks. An advantage of using R is that it is supported by many users that are actively creating 'packages' to do various analytical functions. There is a strong library of statistical packages, but also a diversity of data management and visualization packages. Working in R therefore provides a lot of flexibility. R packages are also typically well documented, so it is usually straighforward to learn how to use and apply the functions in a given package. 

### SpaDES R Package
The CLUS model is implemented using the [SpaDES package](https://spades.predictiveecology.org/). SpaDES provides a structure for implementing discrete-event, spatial simulation models, not unlike what a SELES model does. Importantly, SpaDES provides functions to manage 'events' in a model. Events are scheduled within 'modules' that represent independent processes within a model. Modules, and the 'events' within them, are scheduled and then actioned using SpaDES functions. SpaDES creates a 'sim' object that stores and tracks the events and modules    

SpaDES modules consist of two key files, a .R file and .Rmd file. The .R file contains the R script functions of the 'events' that occur within the module. It also defines the module parameters, expected inputs and ouputs. The .Rmd file provides the text description of the module, and importantly, contains the code chunk needed to run the .R functions. The .Rmd code chunk contains the standard elements needed to run a SpaDES module (e.g., parameters and objects in the sim). We don't provide a detailed description of SpaDES here, but more resources can be obtained using the SpaDES [getting started guide](https://github.com/PredictiveEcology/SpaDES/wiki/Getting-Started-Guide). We recommend spending some time familiarizing yourself with SpaDES, including reviiewing the [example model](https://github.com/PredictiveEcology/SpaDES-modules/blob/master/modules/LCC2005/LCC2005.Rmd). 

### Data Framework
At a minimum, CLUS needs an SQLite database to function. This database houses the data needed to run the forestry modules (e.g. forest inventory characteristics, yield curves and zone constaints). This database is created by running the "dataLoaderCLUS" module, however, previously created databases can be used to run scenarios, i.e., it's not necessary to run the "dataLoaderCLUS" module each time you want to run a scenario or set of scenarios. Existing databases are available at *\\spatialfiles2.bcgov\archive\FOR\VIC\HTS\ANA\PROJECTS\CLUS\Data\sql_tsa_tfl_databases*. 

## CLUS Model Structure and GitHub
All the programming code needed to run CLUS is available on [GitHub](https://github.com/bcgov/clus), an internet repository for developing software code. It is provided under the [Apache 2.0 software license](https://github.com/bcgov/clus/blob/master/LICENSE). To run the software on a local computer, you will need to [clone the repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository) code to that computer. We assume that you have an understanding of how to use program R, and R interfaces like [RStudio](https://rstudio.com/), and thus we do not go into detail on those here. 

The CLUS GitHub folder structure is complex, as it contains a lot of analysis code that are peripheral to running the CLUS model. However, much of this code can be ignored, unless you are interested in understading some of the more detailed analyses completed to parameterize the CLUS model. The key code for running the CLUS model is located in the R->SpaDES-modules, R->Params and R->functions folders.

### Functions
The R->functions folder contains a script and instructions for setting up password protection with the keyring function ("keyring_init.Rmd"). It also contains a script called "R_Postgres.R" with custom R functions for querying and manipulating data in the PostgreSQL database. These functions refer to some additional custom SQL functions created within the PostgreSQL database (these must be loaded into whichever PostgreSQL database you are using). For example, there are functions for clipping raster data to a polygon. These functions are referred to within the CLUS modules, and therefore it is important to preserve and maintain these functions within the folder structure.  

### Parameters
The R->Params folder contains various .Rmd scripts for creating data and parameters needed to run the CLUS model. Many of these populate the data into a network PostgreSQL database, and identify forest harvest constraints areas across the province. 

#### Simulation Area Boundaries
Forest harvest simulation areas are defined in the "study_area_boundaries.Rmd". Currently we use timber supply areas (TSAs) and tree farm license (TFL) areas to simulate forestry and maintain consistency with provincial timber supply modeling, but any area could be defined. The .Rmd creates a raster of integers representing each unique TSA or TFL boundary, and a look-up table to link the polygon names to the raster integers. 

#### Forest Harvest Constraints
The forest harvest constraint scripts load the source polygonal spatial data for each constraint area and rasterize them to the provincial standard, and create a table of constraints for each unique type of zone in the raster. For example, the "proposed_uwr_init.Rmd", "prov_manage_objs.Rmd", "uwr_cond_harvest.Rmd" and "wha_cond_harvest.Rmd" are scripts used to identify the location and type of forest harvest constraints to apply to those locations for each specified management area. These include 'typical' constraints used in timber supply models to support timber supply reviews. The "prov_manage_objs.Rmd" develops constraints related to biodiversity emphasis options (BEO), fisheries sensitive watershed areas (FSW), visual quality objectives (VQOs), old growth management areas (OGMAs), equivalent clearcut areas (ECAs) parks and protected areas and community watersheds across British Columbia. The "uwr_cond_harvest.Rmd" and "wha_cond_harvest.Rmd" files develop constraints around government action regulation (GAR) orders, including unglate winter ranges (UWRs) and wildlife habitat areas (WHAs), respectively. Forest harvest constraints in some of these GAR order area are complex, and are subject to interpretation (see [UWR](http://www.env.gov.bc.ca/wld/frpa/uwr/approved_uwr.html) and [WHA](http://www.env.gov.bc.ca/cgi-bin/apps/faw/wharesult.cgi?search=show_approved) orders), but these can be reviewed  and modified as requried using the script. 

There are also scripts for defining proposed or hypothetical areas to apply new forestry constraints, for example, within caribou management areas ("caribou_management_areas.Rmd"). Other scripts can be used to identify areas of interest ("areaofinterestRaster.Rmd") for summarizing volume and area of forest harvested, and forest harvest unit areas ("study_area_boundaries.Rmd"), e.g., timber supply areas.

The forest harvets constaint parameter outputs consist of a table and a raster. The raster is created from the input locations (polygonal data), and rasterized to a 1ha scale, following the provincial 1ha raster standard. Each zone gets a unique integer identifier corresponding to the table that identifies the constraint to be applied there. The table includes the zone ID integer (i.e., the zone identifier for the raster pixels), the name of the zone (i.e., the name of the corresponding raster in the PostgreSQL database), the "variable" to be constrained (i.e., age, height, crown closure, or whatever data is in, or can be created from the 'pixels' table in the SQLite database), the type of constraint (i.e., 'nh' = no harvest, 'ge' = greater than or equal to, or 'le' = less than or equal to), the threshold of the constraint (i.e., the value at which the variable will be constrained), and the "percentage" of the zone that must meet the constraint threshold. For example, if you want to apply a minimum 40% of an zone to be age 40 or more, then for that zone, variable = 'age', type = 'ge' and percentage = '40'. For each table created for each constraint area, there is a step to add it to a 'zone_constraints' table located in the PostgreSQL database. Thus, this table inherits all of the zone constraint tables identified in the Params folder. 

#### Growth and Yield Models
Data from [TASS/TIPSY](https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/forest-inventory/growth-and-yield-modelling/table-interpolation-program-for-stand-yields-tipsy) and [VDYP](https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/forest-inventory/growth-and-yield-modelling/variable-density-yield-projection-vdyp) growth and yeild models are incorporated into the model to estimate future parameters of 'managed' and 'natural origin' stands, respectively. Outputs form these stand models are obtained provincially, calculated by FAIB staff, for all stand in the inventory. 

The stand volume and height data from TIPSY is organized for CLUS via the tipsy_curves.Rmd. This .Rmd creates a raster of the forest inventory stand ID's that correspond to each TIPSY model stand. It also creates volume (tipsy_prov) and height (tipsy_ht_prov) tables in the network PostgreSQL database. 

Similarly, the stand volume and height data from VDYP is organized for the forestry simulator via the "vdyp_curves.Rmd". This .Rmd creates a raster of the forest inventory stand ID's that correspond to each VDYP model stand. Height, basal area and volume data for each stand is created in a table (vdyp_output)

- linkage between VDYP and TIPSY is made where?

#### Forest Inventory and the Timber Harvest Land Base
We use the provincial forest inventory to obtain forest stand characteristics. Other data could be substituted here if it's available and considered more useful, but the provincial forest inventory provides a standard for analyses across British Columbia, and is consistent with timber supply reviews.  
Forest inventory data is organized for CLUS via the "raster_data.Rmd". The input is the vegetation resources inventory (VRI) [layer 1 polygon data](https://catalogue.data.gov.bc.ca/dataset/vri-2019-forest-vegetation-composite-rank-1-layer-r1-), from which a raster of each polygon identifier (feature_id) is created for the province. The specifics of which data from the inventory get incorporated into CLUS are documented in the dataLoaderCLUS. A raster of the timber harvest land base (THLB) is also created in the "raster_data.Rmd".

#### Wildlife Habitat Models
The "rsf_model_coeff.Rmd" can be used to create habitat models for wildlife species, using the resource selection function (RSF) approach. The .Rmd creates a coefficient table for estimating habitat selection. The table includes the coeffcient values and spatial data to apply the coefficent.   

### SpaDES Modules
The R->SpaDES-modules folder contains the bulk of the scripts that run the model functions. Each folder within the directory contains a "module" of the model. Within each folder module, there is a .R and .Rmd file. The .R file contains the functions that process, analyze, summarize and output the data, whereas the .Rmd file is where you set and describe in text the model parameters and 'run' the model, i.e., by running the code chunk in the .Rmd file, you run the program functions in the .R file. Detailed information on the modules are provided in .Rmd files within each module folder, and these modules will be desribed in more detail below.

There are essentially two modules that run the bulk of the CLUS model functions and processes, i.e., the dataLoaderCLUS and the forestryCLUS. These modules can connect to other modules to run customized functions within them as needed. The dataLoaderCLUS module creates a SQLite database of the data needed to run a forest harvest simulation. Thus, you need to run the dataLoaderCLUS .Rmd for each unique area where you want to run simulations. The forestryCLUS module essentially runs the forest harvest functions and tracks the forest characteristics of interest throughout the simulation. 

Below is a description of each module, what parameters need you need to set for each module, and how it is connected to other modules (particularly the dataLoaderCLUS and forestryCLUS modules).

#### dataLoaderCLUS
The "dataLoaderCLUS" module compiles data on forest inventory and stand yields, the timber harvest land base, forest or other (e.g., caribou habitat) indicators, identifies harvest blocks and builds roads to those blocks, and defines management zones and their constraints for the area of interest. The area of interest could be any portion of British Columbia, but is typically a forest management unit, like a timber supply area or tree farm licence area. The dataLoaderCLUS module takes data from a network PostgreSQL database and compiles it into a SQLite database for the area of interest.

Many of the data in the PostgreSQL database were created as "parameters", using scripts in the R->Params folder. To run the "dataLoaderCLUS", you need to have created the following spatial files within the netwrok PostgreSQL database that you will be connecting to (parameter names as they are named in the "dataLoaderCLUS" module are indicated in parentheses):
- the analysis area boundary file, e.g., timber supply areas (nameBoundaryFile) 
- the column/field in the analysis area boundary file that contains the names of each unique area of interest  (nameBoundaryColumn)
- the name of the area of interest, as defined in the column (nameBoundary)
- the geometry type in the analysis area boundary file (nameBoundaryGeom)
- the rasterized version of the analysis area boundaries (nameCompartmentRaster)
- the value attribute table (VAT) that links the integer values in the analysis area raster to the name of the area of interest (nameCompartmentTable)
- the raster of the timber harvest land base (nameMaskHarvestLandbaseRaster)
- the rasters of each zone where a forest harvest constraint will be applied, including all zones in the 'business-as-usual' or alternative forest management scenarios (nameZoneRasters)
- the table where the constraints for each raster zone are defined (nameZoneTable)
- a raster with a unique integer id for each unique 'natural' forest stand yield curve, i.e., Variable Density Yield Projection (VDYP) curves, corresponding to the raster pixel where that curve applies (nameYieldsRaster)
- the VDYP yield table, which can be linked to each stand by the unique integer id (nameYieldTable)
- a raster with a unique integer id for each unique 'managed' forest stand yield curve, i.e., Table Interpolation Program for Stand Yields (TIPSY) curves, which can be linked to each stand by the unique id (nameYieldsTransitionRaster)
- the TIPSY table, which can be linked to each stand by the unique integer id (nameYieldTransitionTable)
- the forest inventory raster, with a unique integer id for each forest stand in the inventory (nameForestInventoryRaster)
- the inventory data table (nameForestInventoryTable)
- the column/field in the the forest inventory data that defines each unique forest stand (nameForestInventoryKey), that can be linked to the raster integer id
- the column/field in the the forest inventory data that defines the age of each unique forest stand (nameForestInventoryAge)
- the column/field in the the forest inventory data that defines the height of each unique forest stand (nameForestInventoryHeight)
- the column/field in the the forest inventory data that defines the crown closure of each unique forest stand (nameForestInventoryCrownClosure)
- the column/field in the the forest inventory data that defines the site index of each unique forest stand (nameForestInventorySiteIndex)

At a minimum, the SQLite database that is created by the "dataLoaderCLUS" includes four tables, called "pixels", "yields", "zone" and "zoneConstraints". The "pixels" table includes (but is not limited) to columns with the unique integer for each pixel in the area of interest (pixelid), each yield curve id (yieldid and yieldid_trans), THLB (thlb), stand age (age), volume (vol), height (height), crown closure (crownclosure), site index (siteindex), and percent deciduous (dec_pcnt) aassigned to that pixel, and columns for each relevant zone (e.g., zone1, zone2, zone3....) that identifies which forest harvest constraint zones the pixel occurs within. The "yields" table includes the volume (tvol) of each unique yield curve (yieldid) at each age and height. The "zone" table contains the identifier for each zone (e.g., zone1, zone2, zone3....) in the "pixels" table, and the unique zone constraint identifier in the raster (reference_zone). The "zoneConstraints" table also contains the zone identifier, and the related information on the constraint in each zone (e.g., type and threshold).  

The "dataLoaderCLUS" can be used with other modules. In this case, these modules need to be listed in the 'modules' list in the .Rmd code chunk. The "dataLoaderCLUS" can be used with the "blockingCLUS", "roadCLUS", "survivalCLUS", "disturbanceCalcCLUS" and "rsfCLUS" modules to create additional information and data for tracking caribou indicators, and to model forest harvest blocks and roads. 

The 'objects' list should include any additional objects in the code chunk. In the "dataLoaderCLUS" this includes the 'scenario' and 'patchSizeDist' scenarios. The "scenario" parameter identifies the name and description of the scenario. Since you aren't running a scenario in "dataLoaderCLUS", it's not critical to set this parameter, but you can set it to be consistent with the forestryCLUS module. Also, within the "dataLoaderCLUS" module you set the patchSizeDist parameter, which establishes the size of blocks and the frequency of each block size by each natural disturbance type (ndt). These are currently determined based on the provincial biodiversity guidebook(??). These pacth size distributions get used in the blockingCLUS module to pre-identify harvest blocks. 

#### blockingCLUS
The "blockingCLUS" module provides the option to pre-define cutblocks for harvest, by clustering or grouping similar forested pixels together into contiguous, unique blocks. When setting the blockMethod to "pre", it takes data on crown closure and height in each pixel and calculates distance statistics between neighbouring pixels, then groups those neighbouring pixels together where they are below a specified distance threshold, as defined by the "patchVariation" parameter (i.e., neighbouring pixels with similar charactersitics will have relatively small distance metrics and get grouped into 'blocks'). Thus, the module is used to identify spatially accurate cutblock boundaries, assuming a forestry company is likely to cut stands with uniform characteristics. 

To use the "blockingCLUS" module, include the module in the "dataLoaderCLUS" module list and set the parameters for blockMethod (set this to 'pre' to define the blocks as part of the "dataLoaderCLUS" process), patchZone (we use the rast.zone_cond_beo raster, as stored in our PostgreSQL database, which defines BEO areas), patchVariation (we recommend setting to 6???), nameCutblockRaster (the name of raster that defines existing cutblocks; we use rast.cns_cut_bl, as stored in our PostgreSQL database) and useLandingsArea (set to FALSE - why???). You will also need to set the patchSizeDist targets in "dataLoaderCLUS". We provide the distribution targets for BEO natural disturbance types (NDTs) as a 'default' value. The  "blockingCLUS" module adds a blockid column to the "pixels" table to identify each unique block. 

If you do not wish to pre-define cutblocks, and want harvest to occur randomly, set the blockMethod parameter to "dynamic". This harvests pixels based on a random probabiltiy of 'spreading' from one pixel to a neighbouring pixel.  

#### roadCLUS
The "roadCLUS" module can be used to simulate roads on the landscape. It simulates roads to each potential cutblock landing in the analysis area. Thus, it 'pre-solves' the road network and then if a cutblock is cut in a simulation, the road to the cutblock landing gets simulated. It can be presolved using two methods 'snap' or 'pre', where 'pre' creates roads from the exsiting road network to each landing following a least cost pathway while minimizing the amount of roads needed to reach multiple nearby landings, and where 'snap' creates direct, straight-line roads between landings and the network (see R->reports->roads->draft-CLUS-roads.Rmd for more details on these methods). The 'pre' method has a more complex algortihm that takes a computer longer to solve than the 'snap' method. However,the 'pre' method appears to be more accurate than the 'snap', as it creates much fewer roads. We recommend usign the 'pre' method unless computer processing power and time are a concern. 

To use the "roadCLUS" module, set the roadMethod ('snap' or 'pre'), nameCostSurfaceRas (the cost surface raster; called rast.rd_cost_surface in our PostgreSQL database) and nameRoads (the raster of the exsiting road network; called rast.crds_resource in our PostgreSQL database). The "roadCLUS" module adds a "roadyear" column to the "pixels" table, which gets updated with the time interval in the CLUS model that a road gets built. It also adds a "roadslist" table to the SQLite database that contains the landing that each potential road is attributed to and a character list of the pixel ID's that need to be converted into a road to reach the landing. Thus, if the landing gets selected for harvest as part of the forestry module, then the associated pixels get converted to roads.  

#### survivalCLUS
The "survivalCLUS" module is used to estimate adult female caribou survival rate in a caribou herd as a function of the amount of forest less than 40 years old in the herd range, using a model developed by [Wittmer et al. (2005)](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.1365-2656.2007.01220.x). Thus, it can be used to assess how forest harvest activities in a caribou herd range might influence surival of caribou there, where higher proportions of early seral forest results in lower survival rates. 

For the purpose of the "dataLoaderCLUS", the important parameters to set are the raster (nameRasCaribouHerd) and table (tableCaribouHerd) that define the caribou herd boundaries of interest, where survival will be estimated. Defining these in the dataLoaderCLUS adds a column to the pixels table called 'herd_bounds'. 

#### disturbanceCalcCLUS
The "disturbanceCalcCLUS" module is used to estimate disturbance metrics in caribou herd areas. The module calculates the area of forestry cutblocks and roads of a defined age, and 'permanent' disturbance features. In addition, it calculates the distance of each undisturbed pixel from the nearest disturbed pixel, so that buffered disturbance metrics can be estimated. For example, disturbance buffered by 500m is typically a metric of interest in caribou recovery. 

The module creates two new columns in the 'pixels' table, 'perm_dist' and 'dist', where 'perm_dist' identifies pixels that are permanenely disturbed (i.e., don't recover to forest in the simulation), and 'dist' identifies the distance of the pixel to the nearest disturbance. Disturbed pixels are identified as pixels where permanent disturbances occur, as identified by the 'permDisturbanceRaster' parameter, roads less than a certain age and forest cutblocks less than a certain age. The age is defined by the 'recovery' parameter. This allows some flexilibity in defining when a disturbance recovers, either by passive vegetation succession or active habitat restoration. Permanent disturance features are typically things like mines, agricutural areas and highways, that are unlikely to recover or be resotred over the long term. The other parameters in the module define how often disturbance metrics are calculated (calculateInterval) and the area within which to summarize the disturbance metrics (criticalHabRaster and criticalHabitatTable).

#### yieldUncertaintyCLUS
The "yieldUncertaintyCLUS" module calculates uncertainty metrics around the amount of volume harvested for a stand, using a yield uncertainty model. For the "dataLoaderCLUS", the module adds an elevation field (elv) to the 'pixels' table. Elevation is a parameter in the model to calculate uncertainty metrics around harvest yield. 

#### uploaderCLUS
The "uploaderCLUS" module defines the data (tables and rasters) that get output from the model and saved in a SQLite database. These data can then be summarized in the CLUS Explorer application. When running the module with "dataLoaderCLUS", the parameters for the name of the area of interest (aoiName) and the database where the data is uploaded (dbInfo) are populated to create a schema (aoiName) in a network PostgreSQL database (dbInfo) with some of the data used in the CLUS Explorer application. 

#### forestryCLUS
The "forestryCLUS" module is the primary module for running the forest harvest simulator, i.e., it contains many of the forest harvest event functions. There are a few parameter inputs exclusive to the forestryCLUS module. These include the the harvest priority queue logic ("harvestPriority"), the green-up, or adjacency requirement ("adjacencyConstraint"), a "scenario" object, a patch size distribution ("patchSizeDist") object and a harvest flow ("harvestFlow") object. 

The "harvestPriority" parameter is SQL code for ordering the landscape 'pixels' for harvest. It reads the 'pixels' table in the SQLite database and orders the pixels by each block and compartment, based on the desired harvest criteria. For example, an SQL statement of "age DESC, vol DESC" prioritizes oldest and then highest volume pixels in the harvest queue. 

The "adjacencyConstraint" parameter establishes the minimum height requirement (in metres) of adajacent stands before a block can be cut. 

The "patchSizeDist" object provides patch size distribution targets for BEO natural disturbance types (NDTs) as a 'default' value. These are currently determined based on the provincial biodiversity guidebook(??). These patch size distributions also used in the blockingCLUS module to pre-identify harvest blocks (??). 

The "harvestFlow" object is used to establish harvest flows (i.e., the 'flow' parameter, which is the target total cubic metres harvested per time period) for the simulation. A 'flow' can be partitioned to a location ("compartment"), e.g., a compartment of a TSA, time period ("year"), or stand type ("partition"). The "year" parameter in thsi object is also used to define the start ("from") and end ("to") period of the harvest flow, and the temporal interval ("by") of the simulation. The "partition" parameter can also be used to establish harvest crieria, such as minimum harvest volume, using an SQL query (e.g., ' vol > 150 '). Multiple criteria can be used for each unique 'compartment' by binding each of these criteria into a list.       

The "scenario" object is used to name each unique run of the model, for example, if adjusting parameters to compare alternate scenarios or run sensitivity analyses. It includes a 'name' and 'description' parameter for each scenario. The scenario name gets assigned to output tables from model runs, and should be something short but easy to understand (we typically use acronyms). A scenario table with both parameters is also uploaded to the schema in the network PostgreSQL database.  

All other parameters in "forestryCLUS" are related to, or dependent on other modules. Some of the key parameters in these modules include the database name and location, the 'study area', forest inventory data, blocking, harvest queue, caribou indicator, patch size distribution and scenario parameters.

Database parameters are listed within forestryCLUS as part of the dataLoaderCLUS module parameters, i.e., the forestryCLUS module needs to be consistent with dataLoaderCLUS for the area of interest. You need to specify the PostgreSQL database name (dbName), and the location fo the SQLite database that was created by the dataloaderCLUS module (useCLUSdb). Here you also specify the spatial area of the analysis (nameBoundaryFile, nameBoundaryColumn, nameBoundary, nameBoundaryGeom, nameCompartmentRaster and nameCompartmentTable), the timber harvest land base area (nameMaskHarvestLandbaseRaster), and importantly, the names of the rasters where forest harvest contraints will be applied (nameZoneRasters). Forest harvest constraints will include existing legal constraints as are typically defined for timber supply modeling in BC. They include biodiversity emphasis options (rast.zone_cond_beo), visual quality objectives (rast.zone_cond_vqo), wildlife habtiat areas (rast.zone_cond_wha), ungulate winter ranges (rast.zone_cond_uwr), fisheries sensitive watersheds (rast.zone_cond_fsw), community watersheds (rast.zone_cond_cw) and no harvest areas (rast.zone_cond_nharv), such as provincial parks. The forest harvest constraints to apply to these areas are defined in the nameZoneTable parameter. Refer to the "Params" section above for details. Also, within dataLoaderCLUS, the forest inventory parameters are defined, including the yield tables and rasters, and forest stand characteristics such as age, height, crown closure and site index.

Blocking parameters in the forestryCLUS module are referred to in blockingCLUS module. To use blocking in the forestryCLUS module you will have needed to define the blocking method as part of running the dataLoaderCLUS module. It will have created a "blocks" table in the SQLite database that will be used to define forest stands for harvest in forestryCLUS. 

You can periodically calculate growing stock as part of the forestryCLUS simulation by listing the growingStockCLUS module. You only need to set the periodLength parameter, and the forestry CLUS module will call the growingStockCLUS module at that interval and calculate the amount of volume available to be harvested.
 
The roadCLUS can be listed as a parameter to create roads within a forestry simulation. The roadCLUS model will need to have been run with the dataLoaderCLUS module to use the predefined roads (i.e., roadMethod = 'pre'). 

Similarly, the survivalCLUS, disturbanceCalcCLUS, and yieldUncertaintyCLUS modules can be run within forestryCLUS to calculate caribou survival rate and habitat disturbance and forest stand yield uncertainty estimates. The idea is that these, and potentially other yet to be developed modules can be added or removed to customize the information calculated by the forest harvest simulator.   

The uploaderCLUS is important to identify where outputs for th simuation are stored. The module consist of two parameters, "aoiName" and "dbInfo", which identify the name of the schema that the data will be uploaded to and the information needed to access the database. 

This module will upload the tables described in the 'outputs' object of the simulation. Within this object you can identify the outputs from the various modules (often referred to as 'reports').  

#### Other Modules
Other modules in the SpaDES-modules folder were developed to complete specific tasks. The "cutblockSeqPrepCLUS" module identifies the location of existing cutblocks and identifes their adjacent blocks. This module was developed to 

The "fisherCLUS" module can be used to define fisher (*Pekania pennanti*) territories and probbaility of fisher occupancy of those territories over a simulation period. 

The "volumebyareaReportCLUS" module can be used to create a report of the amount of volume harvested from a specified area during a simulation scenario. The area is defined by a raster (AreaofInterestRaster) with integers to identify the areas and a table (AreaofInterestTable) with the corresponding name for each area. These volumes can be calculated at specified intervals (calculateInterval). The output table includes the scenario name, forest harvest area name, time step, name of the specified area and the volume and area harvested from that area during the simulation.  

# Summary
This document provides an introduction to CLUS structure and how it functions. For more information, contact the CLUS team. We also recommend the CLUS quick-start tutorial for step-by-step instructions on how to use CLUS. 