SELECT * 
FROM all_tables
WHERE OWNER LIKE '%WILD%'
ORDER BY OWNER ASC, TABLE_NAME ASC

SELECT * FROM WHSE_WILDLIFE_MANAGEMENT.LEH_APPLICATIONS

SELECT * FROM WHSE_WILDLIFE_INVENTORY.GCPB_CARIBOU_POPULATION_SP


SELECT * 
FROM all_tables
WHERE TABLE_NAME LIKE '%FTEN%'
ORDER BY OWNER ASC, TABLE_NAME ASC

SELECT * FROM WHSE_FOREST_TENURE.FTEN_RECREATION_LINE
SELECT * FROM WHSE_FOREST_TENURE.FTEN_RCRTN_SUB_ACCESS_CODE

SELECT * 
FROM ALL_TAB_COLS
WHERE OWNER = 'WHSE_FOREST_VEGETATION' AND TABLE_NAME LIKE 'VEG%'
ORDER BY COLUMN_NAME ASC

SELECT A.NON_PRODUCTIVE_DESCRIPTOR_CD AS NPCD, B.SPECIES_CD_1 AS SPC1
FROM WHSE_FOREST_VEGETATION.VEG_COMP_POLY A LEFT JOIN WHSE_FOREST_VEGETATION.VEG_COMP_LAYER B ON A.FEATURE_ID = B.FEATURE_ID 
WHERE NON_PRODUCTIVE_DESCRIPTOR_CD = 'M' AND FOR_COVER_RANK_CD = '1'

SELECT * FROM WHSE_FOREST_VEGETATION.VEG_COMP_LAYER WHERE SPECIES_CD_1 = 'SB'

SELECT * FROM WHSE_FOREST_VEGETATION.VEG_COMP_LAYER WHERE FOR_COVER_RANK_CD <> LAYER_ID AND FOR_COVER_RANK_CD = 1 ORDER BY LAYER_ID DESC

SELECT SUM(TOT_NUM) FROM 
(
SELECT LAYER_ID, COUNT(*) AS TOT_NUM
FROM WHSE_FOREST_VEGETATION.VEG_COMP_LAYER
GROUP BY LAYER_ID
ORDER BY LAYER_ID ASC)

SELECT A.FEATURE_ID, A.LAYER_ID, B.BCLCS_LEVEL_1,B.BCLCS_LEVEL_2, B.BCLCS_LEVEL_3, B.BCLCS_LEVEL_4,B.BCLCS_LEVEL_5, B.FULL_LABEL
FROM WHSE_FOREST_VEGETATION.VEG_COMP_LAYER A LEFT JOIN WHSE_FOREST_VEGETATION.VEG_COMP_POLY B ON A.FEATURE_ID = B.FEATURE_ID
WHERE A.LAYER_ID = '0' 

SELECT A.FEATURE_ID, A.LAYER_ID, B.BCLCS_LEVEL_1,B.BCLCS_LEVEL_2, B.BCLCS_LEVEL_3, B.BCLCS_LEVEL_4,B.BCLCS_LEVEL_5, B.FULL_LABEL
FROM WHSE_FOREST_VEGETATION.VEG_COMP_LAYER A LEFT JOIN WHSE_FOREST_VEGETATION.VEG_COMP_POLY B ON A.FEATURE_ID = B.FEATURE_ID
WHERE A.LAYER_ID = '9' 

SELECT A.FEATURE_ID, A.LAYER_ID, B.BCLCS_LEVEL_1,B.BCLCS_LEVEL_2, B.BCLCS_LEVEL_3, B.BCLCS_LEVEL_4,B.BCLCS_LEVEL_5, B.FULL_LABEL
FROM WHSE_FOREST_VEGETATION.VEG_COMP_LAYER A LEFT JOIN WHSE_FOREST_VEGETATION.VEG_COMP_POLY B ON A.FEATURE_ID = B.FEATURE_ID
WHERE A.LAYER_ID = 'S' 


SELECT A.FEATURE_ID, A.LAYER_ID, B.BCLCS_LEVEL_1,B.BCLCS_LEVEL_2, B.BCLCS_LEVEL_3, B.BCLCS_LEVEL_4,B.BCLCS_LEVEL_5, B.FULL_LABEL
FROM WHSE_FOREST_VEGETATION.VEG_COMP_LAYER A LEFT JOIN WHSE_FOREST_VEGETATION.VEG_COMP_POLY B ON A.FEATURE_ID = B.FEATURE_ID
WHERE A.LAYER_ID = '5' 

SELECT A.FEATURE_ID, A.LAYER_ID, B.BCLCS_LEVEL_1,B.BCLCS_LEVEL_2, B.BCLCS_LEVEL_3, B.BCLCS_LEVEL_4,B.BCLCS_LEVEL_5, B.FULL_LABEL
FROM WHSE_FOREST_VEGETATION.VEG_COMP_LAYER A LEFT JOIN WHSE_FOREST_VEGETATION.VEG_COMP_POLY B ON A.FEATURE_ID = B.FEATURE_ID
WHERE CAST(A.LAYER_ID AS INT) <  = 9 AND A.LAYER_ID NOT IN ('D', 'S')


SELECT A.FEATURE_ID, B.FOR_COVER_RANK_CD, B.LAYER_ID
FROM WHSE_FOREST_VEGETATION.VEG_COMP_POLY A LEFT JOIN WHSE_FOREST_VEGETATION.VEG_COMP_LAYER B ON A.FEATURE_ID = B.FEATURE_ID
WHERE A.FEATURE_ID IN 
(SELECT FEATURE_ID FROM WHSE_FOREST_VEGETATION.VEG_COMP_LAYER WHERE LAYER_ID = 'S')
ORDER BY A.FEATURE_ID, LAYER_ID ASC

SELECT * FROM 
WHSE_FOREST_VEGETATION.VEG_COMP_LAYER
WHERE FEATURE_ID = 7635659

SELECT * FROM WHSE_FOREST_VEGETATION.VEG_COMP_LAYER WHERE FEATURE_ID = 8817233
