CREATE TABLE public.vdyp
(
  table_num integer,
  feature_id integer,
  district text,
  map_id text,
  polygon_id integer,
  layer_id text,
  projection_year integer,
  prj_total_age integer,
  species_1_code text,
  species_1_pcnt double precision,
  species_2_code text,
  species_2_pcnt double precision,
  species_3_code text,
  species_3_pcnt double precision,
  species_4_code text,
  species_4_pcnt double precision,
  species_5_code text,
  species_5_pcnt double precision,
  species_6_code text,
  species_6_pcnt double precision,
  prj_pcnt_stock double precision,
  prj_site_index double precision,
  prj_dom_ht double precision,
  prj_lorey_ht double precision,
  prj_diameter double precision,
  prj_tph double precision,
  prj_ba double precision,
  prj_vol_ws double precision,
  prj_vol_cu double precision,
  prj_vol_d double precision,
  prj_vol_dw double precision,
  prj_vol_dwb double precision,
  prj_sp1_vol_ws double precision,
  prj_sp1_vol_cu double precision,
  prj_sp1_vol_d double precision,
  prj_sp1_vol_dw double precision,
  prj_sp1_vol_dwb double precision,
  prj_sp2_vol_ws double precision,
  prj_sp2_vol_cu double precision,
  prj_sp2_vol_d double precision,
  prj_sp2_vol_dw double precision,
  prj_sp2_vol_dwb double precision,
  prj_sp3_vol_ws double precision,
  prj_sp3_vol_cu double precision,
  prj_sp3_vol_d double precision,
  prj_sp3_vol_dw double precision,
  prj_sp3_vol_dwb double precision,
  prj_sp4_vol_ws double precision,
  prj_sp4_vol_cu double precision,
  prj_sp4_vol_d double precision,
  prj_sp4_vol_dw double precision,
  prj_sp4_vol_dwb double precision,
  prj_sp5_vol_ws double precision,
  prj_sp5_vol_cu double precision,
  prj_sp5_vol_d double precision,
  prj_sp5_vol_dw double precision,
  prj_sp5_vol_dwb double precision,
  prj_sp6_vol_ws double precision,
  prj_sp6_vol_cu double precision,
  prj_sp6_vol_d double precision,
  prj_sp6_vol_dw double precision,
  prj_sp6_vol_dwb double precision,
  prj_mode text
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.vdyp
  OWNER TO clus_project;
